### ISSUE TITLE
Access to Mona Alta

### ISSUE THREAD

**Issue by Dscot401** [ForgottenGlory/Living-Skyrim-3#10]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
Put the version of the list you are on here.

**Describe the bug**
The stairway path that leads from the "Sale" sign up to Mona Alta does not go to the house.  It leads away from it and ends on top of another mountain.  I could not find a way to get to the house at all.  

**To Reproduce**
Start at the Sale sign and go up the stairs.  

**Expected behavior**
You should be able to walk up the stairs to the house. 

**Screenshots**
I didn't take a screenshot, but seriously, you wont need one.  

**Additional context**

**Comment by ForgottenGlory** [comment]
Not a bug, read the mod's description ;) https://www.nexusmods.com/skyrimspecialedition/mods/9883

**Comment by Dscot401** [comment]
Okay, BUT, there is still a problem.  I cant get from the stairs to the
"path of faith".  Others have had this problem too.  I will attach a
screenshot that someone had posted on the mod forum.
