### ISSUE TITLE
Ethereal Elven Overhaul issues with neck seams, Expressive Facegen Morphs, vampirism

### ISSUE THREAD

**Issue by celadoneiron** [ForgottenGlory/Living-Skyrim-3#100]
**LS Version**
LS3 Beta 2.

**Describe the bug**
- The player character's head will change shape dramatically if the player is an elf and becomes a vampire, because Ethereal Elven Overhaul's changes to vampire elf race records to make them use the same face part as non-vampire elves are overridden by Aetherius.
- Multiple visual issues with heads for elf races, including eye meshes that clip through the face with the default headpart.
- Beards do not fit to elf male heads (see  #23 ) because the EEO edits to beard trishapes are overwritten by Expressive Facegen Morphs. Marking the EFM beards folder as .mohidden resolves clipping for elven males with the default head part but creates clipping for all other races and headparts.
- Neck seams on elves occur when using head parts other than the default because EEO points the elf headparts to its own custom textures instead of replacements for vanilla textures.

**To Reproduce**
The fastest way to see a bunch of these at once is to start a new game and choose a High Elf male, keep the default preset, then pick the "I am a vampire in a secluded lair" start at the Mara statue. The beard clipping will be obvious before sleeping in the bed in the starting cell, then on waking up in the lair the face will be fitting to the beard properly.

**Expected behavior**
The player character's head shape while a vampire will be similar to their head shape prior to being a vampire. Beards will fit with the face. Eyes will not clip through the face. Neck and head textures will match.

**Screenshots**

![Screen Shot 02-10-21 at 12 46 AM](https://user-images.githubusercontent.com/73095714/107380483-a2965080-6b39-11eb-9d60-08b40987140e.PNG)
Ethereal Elven Overhaul (as part of NPC VO Merged) changes the elf vampire races to use regular elf headparts, but is overwritten by Aetherius.

![SkyrimSE 2021-02-10 01-22-45](https://user-images.githubusercontent.com/73095714/107387230-58649d80-6b40-11eb-9b08-dd83b00e38bb.png)
![SkyrimSE 2021-02-10 01-28-57](https://user-images.githubusercontent.com/73095714/107387409-83e78800-6b40-11eb-9b67-e14ee093ad7a.png)
High Elf male with the default preset and head part has beard clipping and a jagged and lumpy face (especially around the forehead, cheekbones and mouth).

![SkyrimSE 2021-02-10 01-03-19](https://user-images.githubusercontent.com/73095714/107386736-deccaf80-6b3f-11eb-8094-76cb9833c5d7.png)
![SkyrimSE 2021-02-10 01-30-01](https://user-images.githubusercontent.com/73095714/107387468-95c92b00-6b40-11eb-8298-1dbf526194d9.png)
High Elf male with the default preset and the non-High Poly Head vampire head part has dramatically better beard fit, but a very noticeable neck seam. Count Dorkula's transformation into a vampire included a facelift.

![SkyrimSE 2021-02-10 01-14-15](https://user-images.githubusercontent.com/73095714/107387582-b4c7bd00-6b40-11eb-94a6-4f079d826e09.png)
An example of eye clipping with the default head part.

![SkyrimSE 2021-02-10 01-51-32](https://user-images.githubusercontent.com/73095714/107389617-a8dcfa80-6b42-11eb-9855-66c3b2c8eb4c.png)
![SkyrimSE 2021-02-10 01-51-54](https://user-images.githubusercontent.com/73095714/107389643-b0040880-6b42-11eb-9de3-109e32d40b3e.png)
With EFM beards hidden, EEO beards fix elf beards on the default head part but create clipping issues for other races and head parts.

**Additional context**

The mod "Aesthetic Elves" makes changes to elf morphs in a similar way to EEO to try to make them look better, but is player-exclusive and (apparently) compatible with High Poly Head via an option in the HPH FOMOD. This patch seems to be mutually exclusive with the one for Expressive Facegen Morphs, but EFM also has an optional file that's a non-replacer and is supposed to be more compatible with other mods. Both of these may be worth exploring.

**Comment by TwistedModding** [comment]
Just get rid of ethereal elven overhaul, that mod does not work very well with cbbe and will be more trouble trying to fix it than its worth considering you can make a good looking elf with high poly head,

**Comment by ForgottenGlory** [comment]
Agree, done Beta 3
