### ISSUE TITLE
Sofia files install order incorrect, causing texture issues

### ISSUE THREAD

**Issue by celadoneiron** [ForgottenGlory/Living-Skyrim-3#101]
**LS Version**
Beta 2.

**Describe the bug**
Sofia's body textures have black patches and seams, particularly noticeable on the feet and when using QuickLight. This is because "Sofia - The Funny Fully-Voiced Follower" is overwriting "Sofia Re-Imagined SSE" in the left pane of MO2 instead of the other way around. Switching the priority of the two mods resolves the issue.

**To Reproduce**
Look at Sofia.

**Expected behavior**
Her textures are even without patches or seams.

**Screenshots**
If applicable, add screenshots to help explain your problem. Additionally, if your report applies to a specific object, make sure it is selected with the console open. Reports without this will be closed.

![SkyrimSE 2021-02-10 12-02-03](https://user-images.githubusercontent.com/73095714/107456845-b0c98880-6b9c-11eb-8461-3007c090d0d2.png)
![SkyrimSE 2021-02-10 12-02-07](https://user-images.githubusercontent.com/73095714/107456865-b8892d00-6b9c-11eb-8675-890aa90ff667.png)
^ LS3 default load order.

![SkyrimSE 2021-02-10 12-32-39](https://user-images.githubusercontent.com/73095714/107456901-cccd2a00-6b9c-11eb-9dd7-46a9a06bb8c0.png)
After switching the mods' priorities - no ankle seams, no blocky black shadows.

**Additional context**

**Comment by ForgottenGlory** [comment]
Fixed Beta 3
