### ISSUE TITLE
Decapitation , Mask stays on 

### ISSUE THREAD

**Issue by Cerberus610** [ForgottenGlory/Living-Skyrim-3#102]
It may be a minor bug but something i noticed. I was heading up to Bleak Falls Barrow and the bandits that swarm you from behind i noticed the (Executioner Mask) When i cut his head off , his mask stayed on while his head rolled away.  

Beta 

**Expected behavior**
A clear and concise description of what you expected to happen. I expected the head up to be cut off not his head inside the mask 

![LS3](https://user-images.githubusercontent.com/78388153/107486607-3d4f5900-6b53-11eb-9887-30a09c3d7f79.jpg)

**Comment by ForgottenGlory** [comment]
Decapitations have never played nice with mod-added armors... Not 100% sure how to fix this one.
