### ISSUE TITLE
Floating rocks above whiterun Giant Camp

### ISSUE THREAD

**Issue by seanpbelcher** [ForgottenGlory/Living-Skyrim-3#103]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
LS3 Beta 2

**Describe the bug**
A rock formation above the giant camp in Whiterun hold

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. Additionally, if your report applies to a specific object, make sure it is selected with the console open. Reports without this will be closed.
![enb2021_2_10_05_26_15](https://user-images.githubusercontent.com/67465410/107505011-b3f35300-6b61-11eb-849a-e57beb260b61.png)
![enb2021_2_10_05_26_28](https://user-images.githubusercontent.com/67465410/107505029-ba81ca80-6b61-11eb-8abc-4bb045c4ffc3.png)

**Additional context**

**Comment by TwistedModding** [comment]
Fixed, esp in patch channel

**Comment by ForgottenGlory** [comment]
Fixed Beta 4
