### ISSUE TITLE
Visable decal around words of power 

### ISSUE THREAD

**Issue by seanpbelcher** [ForgottenGlory/Living-Skyrim-3#104]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
LS3 Beta 2

**Describe the bug**
Minor cosmetic bug - decal and Decal Flags are misapplied in words of power when using an ENB

**To Reproduce**
Happens when using ENB and looking at a word of power

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. Additionally, if your report applies to a specific object, make sure it is selected with the console open. Reports without this will be closed.
![enb2021_2_8_06_38_33](https://user-images.githubusercontent.com/67465410/107512832-fe2e0180-6b6c-11eb-9bc4-8e5caeb0a5f0.png)

**Additional context**
There is a mod to fix this, but I'm not sure if it works for every user:
https://www.nexusmods.com/skyrimspecialedition/mods/41463

**Comment by TwistedModding** [comment]
I'm pretty sure that fix does work for everyone/all enbs.

**Comment by ForgottenGlory** [comment]
Fixed Beta 3
