### ISSUE TITLE
Riverfall Cottage Misaligned Wall

### ISSUE THREAD

**Issue by Orc12x** [ForgottenGlory/Living-Skyrim-3#105]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
Latest release

**Describe the bug**
A wall in the cottage is misaligned allowing the "abyss" to be viewable.

**To Reproduce**
Go into Riverfall Cottage, up the stairs to the second floor bar area, it's behind the bar.

**Expected behavior**
You shouldn't be able to see the abyss ;o

**Screenshots**
https://ibb.co/gvXJDkx

**Additional context**

**Comment by ForgottenGlory** [comment]
Fixed Beta 4
