### ISSUE TITLE
Misaligned Steps & Base @ Jorrvaskr.

### ISSUE THREAD

**Issue by Orc12x** [ForgottenGlory/Living-Skyrim-3#108]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
Latest version

**Describe the bug**
The stairs and base of Jorrvaskr are a bit misaligned. Because of it being misaligned, you'll see into the "nothing" This issue is *behind* the building.

**To Reproduce**
Go to Jorrvaskr's rear entrance and look at the stairs to the right. At the top of these stairs is also a bit misaligned.

**Expected behavior**
NO ABYSS >w<!!

**Screenshots**
https://ibb.co/c2VvxYL + https://ibb.co/0G4zp0v

**Additional context**

**Comment by ForgottenGlory** [comment]
Select the objects with the console open and post a screenshot of that please.
