### ISSUE TITLE
Black character head

### ISSUE THREAD

**Issue by Foxieboxy** [ForgottenGlory/Living-Skyrim-3#109]
If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
LS3, unsure where to find version
**Describe the bug**
Black head, white body

**To Reproduce**
No idea

**Expected behavior**
Body and head color to match up

![image](https://user-images.githubusercontent.com/78890748/107598045-a9c96700-6bea-11eb-921c-c6209da471da.png)

**Additional context**

**Comment by TwistedModding** [comment]
select the npc in the console and post the screenshot

**Comment by Foxieboxy** [comment]
[Uploading Autosave1_88BD3B50_0_42726F6F6B65_Tamriel_002230_20210211024711_13_1_2.zip…]()

**Comment by TwistedModding** [comment]
we dont need the save, just a screenshot of the npc selected in the console

**Comment by Foxieboxy** [comment]
![image](https://user-images.githubusercontent.com/78890748/107598408-9bc81600-6beb-11eb-9577-1c390c1befa1.png)

**Comment by TwistedModding** [comment]
https://www.nexusmods.com/skyrimspecialedition/mods/29090 this mod will probably fix it considering he doesnt have a head part in xedit

**Comment by ForgottenGlory** [comment]
Fixed Beta 4
