### ISSUE TITLE
Reaper bow has over 3000 Damage/ Also no in game loose model

### ISSUE THREAD

**Issue by Deathgamin596** [ForgottenGlory/Living-Skyrim-3#11]
**LS Version**
3.0.0

**Describe the bug**
Checking out the weapons added to LS3 was looking over the reaper gear and saw the bow has over 3000 Damage

Also if u drop it there is no model in game. Model is there if equipped though

**To Reproduce**
Search reaper in the additemmenu look at stats

Drop item

**Expected behavior**
A more balanced Damage amount

**Screenshots**
![reaperbow](https://user-images.githubusercontent.com/78379580/106506466-014b3280-6487-11eb-90bf-458c410d0f3f.png)

**Additional context**

**Comment by TwistedModding** [comment]
Can you drop it on the ground and select it in the console

**Comment by Deathgamin596** [comment]
It does not have a model to select. i was trying to do that when i discovered that.

**Comment by TwistedModding** [comment]
type in the console... help "reaper bow"

then send the screenshot

**Comment by Deathgamin596** [comment]
![image](https://user-images.githubusercontent.com/78379580/106507116-d4e3e600-6487-11eb-9d8d-850fccd3dd22.png)

**Comment by TwistedModding** [comment]
synthesis might fix this for the next beta, will look back at this then.

**Comment by seanpbelcher** [comment]
These need adjusting as well.
![enb2021_2_2_06_25_32](https://user-images.githubusercontent.com/67465410/106603729-4d988000-6524-11eb-9659-aa1f038eee0f.png)
![enb2021_2_2_06_26_29](https://user-images.githubusercontent.com/67465410/106603737-512c0700-6524-11eb-99ab-48b0e42b09b4.png)

**Comment by ForgottenGlory** [comment]
All fixed Beta 2
