### ISSUE TITLE
Game world will not load while walking

### ISSUE THREAD

**Issue by Horbath** [ForgottenGlory/Living-Skyrim-3#111]
**LS Version**
LS3 Beta 2

**Describe the bug**
While walking from dragons bridge to solitude game world will fail to load.

**To Reproduce**
Load attached save and start heading to dragons bridge. While traveling to dragons bridge you will fight Issildor (if I spelled it correct). Stop by and grab the statue of Meridia for the museum. Continue to Dragons bridge and finish the missives quest to deliver the potion. After that I would load into the inn (did not talk to anyone just looking for unique museum items) I would start walking back to solitude. About the time I get to where the carriage is the game world would fail to load. The near by farm was loaded and I tried to enter a house and that would lock my game. From there I had to restart my computer to get Skyrim to close (use CLT-ALT-DELETE). I did this three times in a row with the same results.

**Expected behavior**
Game world will fail to load.

**Screenshots**
N/A.

**Additional context**
Attached save game file
[Save3_3C5D8F0E_0_486F72626174682053746F726D626F726E_Tamriel_000329_20210209075627_6_1 (ESS).zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/5962986/Save3_3C5D8F0E_0_486F72626174682053746F726D626F726E_Tamriel_000329_20210209075627_6_1.ESS.zip)
[Save3_3C5D8F0E_0_486F72626174682053746F726D626F726E_Tamriel_000329_20210209075627_6_1 (SKSE).zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/5962988/Save3_3C5D8F0E_0_486F72626174682053746F726D626F726E_Tamriel_000329_20210209075627_6_1.SKSE.zip)

**Comment by ForgottenGlory** [comment]
Looking at your save, you seem to have some Creation Club content installed. This needs to be removed for the list to function properly.

**Comment by Horbath** [comment]
Ok my fault I will remove this. I didn't realize it was added.

**Comment by Horbath** [comment]
I will start a new save thank you.
