### ISSUE TITLE
Blanked map

### ISSUE THREAD

**Issue by vMichaelMyersv** [ForgottenGlory/Living-Skyrim-3#113]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
Beta 3

**Describe the bug**
map is completely white but locations still showing same as when Forgotten first streamed 

**To Reproduce**
unsure

**Expected behavior**
not a white map 

**Screenshots**

![skyrimmap](https://user-images.githubusercontent.com/78704848/107609331-862c0e00-6c36-11eb-8a0f-7237f48dff12.png)

**Additional context**
unable to locate save files do not appear to be stored in usual place?

**Comment by mooncowl** [comment]
I am experiencing this too.

**Comment by celadoneiron** [comment]
The meshes for the different maps (meshes\terrain\[worldspacename]\[filename].btr) don't seem to have the chunks required to display the paper world map. I've linked two sources for updated, functioning map meshes in the dev channels for checking.
