### ISSUE TITLE
Headless body spawned midfight during Bleakfall Burrows entrance encouter.

### ISSUE THREAD

**Issue by mordang7** [ForgottenGlory/Living-Skyrim-3#118]
![Skyrim Special Edition203](https://user-images.githubusercontent.com/21289127/107648687-f632a680-6cbf-11eb-9e91-7cac233ab2e2.png)
![Skyrim Special Edition204](https://user-images.githubusercontent.com/21289127/107648690-f7fc6a00-6cbf-11eb-86ad-7bc04ae4ed79.png)

**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
LS3 Beta 3

**Describe the bug**
During the first visit to Bleakfall Burrows and the first encounter with the enemies occupying the area, a headless body spawned midfight and just stood there doing nothing and only wearing underwear sitting in a stance like the 3D models in CBBE Bodyslide during creation. It had no enemy indicator, nameplate etc. and interaction was impossible. The Nirnroot sound effect was stuck all the way since exiting main gates of Whiterun.

**To Reproduce**

I reloaded the same savegame which starts outside the main entrance of Whiterun, the Nirnroot sound this time was gone but after reaching Bleakfall Burrows the 3D model was there with a head this time and I could interact with it like a regular dead body even though the model was never hit and now had breathing animations and idle standing animations, and a name.

**Expected behavior**
Normal interaction with NPCs, them being either friendly or not friendly.

**Screenshots**
If applicable, add screenshots to help explain your problem. Additionally, if your report applies to a specific object, make sure it is selected with the console open. Reports without this will be closed.

**Additional context**

[saves.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/5966094/saves.zip)

**Comment by ForgottenGlory** [comment]
I'm not able to replicate this
