### ISSUE TITLE
Floating Plants and Terrain near Blind Cliff Cave

### ISSUE THREAD

**Issue by Ermenher** [ForgottenGlory/Living-Skyrim-3#119]
Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
Beta 3

**Describe the bug**
Floating moss, bushes, and terrain features along the road just north of Blind Cliff Cave and just past the fallen tree that spans over the road. For more directions to them, they are south, down the road from Karthwasten.

**To Reproduce**
Go down the road south of Karthwasten, when you come to the tree that spans the gorge over the road, look to the right, they should be in a nock right there. They are just north along the road from Blind Cliff Cave. Should be some jagged ground, some floating hanging moss, and some floating bushes.

**Expected behavior**
No floating bushes, moss, rocks, or other terrain features.

**Screenshots**
![2021-02-11 (5)](https://user-images.githubusercontent.com/78520661/107660039-0f4a4180-6c45-11eb-9e9a-64cf3dc5bae2.png)
![2021-02-11 (4)](https://user-images.githubusercontent.com/78520661/107660060-14a78c00-6c45-11eb-85d9-86e55548ca51.png)
![2021-02-11 (3)](https://user-images.githubusercontent.com/78520661/107660078-18d3a980-6c45-11eb-8d9a-0e5b5af8415e.png)

**Additional context**
N/A

**Comment by ForgottenGlory** [comment]
Select the objects while the console is open and screenshot that please.

**Comment by ChunkeeMunkee** [comment]
Still present in Beta 5 (unsure if this was meant to be fixed for Beta 5 or Release?)

**Comment by ForgottenGlory** [comment]
It was closed because the requested information was not provided.
