### ISSUE TITLE
Discoloration face bug: Leonia Auria

### ISSUE THREAD

**Issue by weronika0805** [ForgottenGlory/Living-Skyrim-3#12]
**LS Version**
LS3 Beta 1

**Describe the bug**
Leonia Auria, a child added by Books of Skyrim in Solitude, has the discoloration face bug

**To Reproduce**
Look at Leonia Auria in Solitude

**Expected behavior**
How the child is supposed to look as per the mod page - https://staticdelivery.nexusmods.com/mods/1704/images/4115-8-1479062404.jpg

**Screenshots**
https://imgur.com/a/QppBgbH

**Additional context**
This is likely because the patch between RS Children and Books of Skyrim hasn't been installed - available on the RS Children Patch Compendium page https://www.nexusmods.com/skyrimspecialedition/mods/13409

**Comment by TwistedModding** [comment]
She doesn't have a headpart in xedit. I'll test the patch to see if it fixes the issue.

**Comment by ForgottenGlory** [comment]
Fixed beta 2
