### ISSUE TITLE
use this sse display tweaks ini instead

### ISSUE THREAD

**Issue by TwistedModding** [ForgottenGlory/Living-Skyrim-3#123]
It adds a framerate limit of 144 to all menus and gameplay (except loading screens, still capped at 60) providing a smoother experience for high refresh rate monitors, removes vsync(this should be enabled through gpu settings anyways) and enables borderlessupscaling for people who wish to run at lower resolutions

[SSEDisplayTweaks.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/5968203/SSEDisplayTweaks.zip)

**Comment by ForgottenGlory** [comment]
Done Beta 4
