### ISSUE TITLE
Lamp post in middle of ramp outside Whiterun

### ISSUE THREAD

**Issue by Trent223** [ForgottenGlory/Living-Skyrim-3#125]
**LS Version**
LS3 Beta 3

**Describe the bug**
In the small walled-in area in front of Whiterun, there is a lamp post clipping through the middle of a ramped staircase.

**Screenshots**
https://imgur.com/a/WSgIYW4

**Comment by weronika0805** [comment]
piggybacking off this, I also found a floating lantern (from Lanterns of Skyrim) in Falkreath:

![enb2021_2_13_20_53_36](https://user-images.githubusercontent.com/78365583/107861697-b3033f80-6e47-11eb-8ff3-072d98da34ff.png)

**Comment by ForgottenGlory** [comment]
Fixed Beta 4
