### ISSUE TITLE
Non-Aggressive/Attacking Bandit

### ISSUE THREAD

**Issue by Ermenher** [ForgottenGlory/Living-Skyrim-3#126]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
LS3 Beta 3, Map Update

**Describe the bug**
Outside of Bloated Man's Grotto I encountered a bandit archer who didn't attack my character. I approached and the bandit archer spoke generic non-aggressive dialogue. After a few minutes of running around the bandit, he still wasn't attacking. I entered and clear the grotto, then when I left the bandit was still their and non-aggressive, but he had his bow out. I ran around him but he didn't attack. So I left. Bandit ID 3D02298C

**To Reproduce**
Go to Bloated Man's Grotto and hope to encounter Bandit ID 3D02298C, or maybe encounter said bandit in another location.

**Expected behavior**
For Bandit ID 3D02298C to be hostile like other bandits.

**Screenshots**
![2021-02-11 (10)](https://user-images.githubusercontent.com/78520661/107730072-d2676480-6caf-11eb-9cf7-4a29d901f198.png)

**Additional context**
Sorry I can't seem to figure out how to share a save on this.

**Comment by ForgottenGlory** [comment]
Fixed Beta 5
