### ISSUE TITLE
Lingering EEO traces in LS3 Patches Merged affecting Wood Elves in RaceMenu

### ISSUE THREAD

**Issue by celadoneiron** [ForgottenGlory/Living-Skyrim-3#128]
**LS Version**
Beta 3 (map fix ver).

**Describe the bug**
Wood Elves show no difference when adjusting RaceMenu sliders for eyeliner/lips/eyeshadow/etc under the "Colors" tab, because the paths to those textures in LS3 Patches Merged still point to the Ethereal Elven Overhaul custom texture locations. Some hair colours and tint presets refer to unrelated records of the wrong type (a quest, an activator) or produce errors.

**To Reproduce**
Start a new game, choose Wood Elf as the race, and attempt to change the slider-based face colours.

**Expected behavior**
The slider changes should appear on the character's face.

**Screenshots**

![Screen Shot 02-12-21 at 05 21 PM](https://user-images.githubusercontent.com/73095714/107758956-559dbe80-6d73-11eb-93c3-f673ad2721a5.PNG)

**Additional context**
The WoodElf race is the only one still modified by Faces Merged, but seems to just revert changes made by Aetherius. It probably doesn't need to be in Faces Merged or LS3 Patches Merged at all, since none of the other player races are affected by either, so the merges might need to be rebuilt.

**Comment by ForgottenGlory** [comment]
Fixed Beta 4
