### ISSUE TITLE
Crafting recipes use wrong materials

### ISSUE THREAD

**Issue by celadoneiron** [ForgottenGlory/Living-Skyrim-3#129]
**LS Version**
Beta 3 (map fix).

**Describe the bug**
Many armours have material requirements that don't make sense.

- Armours named/described as being made of Netch Leather can be crafted using regular non-netch leather.
- The "Bandage" helmets require iron, leather strips, and leather, despite being visually made solely of cloth.

**To Reproduce**
Use the forge with 1 iron ingot, 5 leather strips, and 2 leather in inventory.

**Expected behavior**
Netch Leather armours should require netch leather to craft.
Bandages should be made of cloth.

**Screenshots**
If applicable, add screenshots to help explain your problem. Additionally, if your report applies to a specific object, make sure it is selected with the console open. Reports without this will be closed.
![Screen Shot 02-12-21 at 09 34 PM](https://user-images.githubusercontent.com/73095714/107763739-cc8a8580-6d7a-11eb-8cf3-804d2cf49e2a.PNG)
![Screen Shot 02-12-21 at 09 39 PM](https://user-images.githubusercontent.com/73095714/107763754-d01e0c80-6d7a-11eb-944a-df67f1e2c3fa.PNG)
(IDs for other netch leather armour pieces are shown in the bottom left.)
![Screen Shot 02-12-21 at 09 46 PM](https://user-images.githubusercontent.com/73095714/107764360-cfd24100-6d7b-11eb-94c4-998e7ec1bbb6.PNG)
![Screen Shot 02-12-21 at 09 46 PM 001](https://user-images.githubusercontent.com/73095714/107764369-d2cd3180-6d7b-11eb-84ea-5c1d6ffed5cd.PNG)

**Additional context**
Will add new items in comments from here out when/if I notice them.

**Comment by TwistedModding** [comment]
This and #70 i have mentioned a possible fix to this issue in the dev channel.

**Comment by ForgottenGlory** [comment]
Will be at least partially fixed for 3.0.0 Release
