### ISSUE TITLE
Interaction with NPC

### ISSUE THREAD

**Issue by Fjodik** [ForgottenGlory/Living-Skyrim-3#13]
**LS Version**
Beta 3.0.0

**Describe the bug**
Interaction with NPC Malexa (mercenary archer) does not work (pressing E does nothing)

**To Reproduce**
Press E in order to speak with her.

**Expected behavior**
Dialog with NPC with possibility to hire her.

**Screenshots**

![enb2021_2_1_21_09_33](https://user-images.githubusercontent.com/63248466/106513047-b35c1c00-64d2-11eb-876d-dc13eef86fab.jpg)
![enb2021_2_1_21_10_04](https://user-images.githubusercontent.com/63248466/106513051-b3f4b280-64d2-11eb-84e7-d29c1e177627.jpg)
![enb2021_2_1_21_09_32](https://user-images.githubusercontent.com/63248466/106513053-b525df80-64d2-11eb-98d1-c7217d874493.jpg)

**Comment by ForgottenGlory** [comment]
Expendable recruits isn't turned on by default, so you can't recruit her unless you turn that on in the Follower Framework MCM.
