### ISSUE TITLE
Fort Hraggstad doesn't show up as cleared after killing all bandits

### ISSUE THREAD

**Issue by PinguWick** [ForgottenGlory/Living-Skyrim-3#130]
**LS Version**
LS3 Beta 3 (map fix ver)

**Describe the bug**
All bandits in Fort Hraggstad have been killed, however the fort does not show up as clear. Due to this, Joining the Imperials quest cannot be completed.

**To Reproduce**
Start Joining the Imperials by talking to Legate Rikke at Castle Dour.

**Expected behavior**
Fort Hraggstad should count as cleared, and the quest should progress to report back to Legate Rikke.

**Screenshots**
If applicable, add screenshots to help explain your problem. Additionally, if your report applies to a specific object, make sure it is selected with the console open. Reports without this will be closed.

**Additional context**
[saves.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/5971865/saves.zip)
Save 6 - Castle Dour after accepting the quest to clear Fort Hraggstad
Save 8 - After killing all bandits, but quest hasn't progressed

**Comment by ForgottenGlory** [comment]
I imagine this is related to 3DNPC somehow, but am unsure how to fix it. Input welcome.

**Comment by ForgottenGlory** [comment]
After further investigation, Fort Hraggstad isn't "clearable" in the traditional sense like other dungeons. It may take a bit of running around to the quest marker and such to get the quest to progress, but it will progress eventually.
