### ISSUE TITLE
Visible alpha/decal - TG Shadowmark on Carlotta Valentia's house

### ISSUE THREAD

**Issue by ChunkeeMunkee** [ForgottenGlory/Living-Skyrim-3#131]
**LS Version**
Beta 3.0.0.3

**Describe the bug**
The Thieves' Guild shadowmark etched onto the wall to the right of Carlotta's House in Whiterun has a noticeably dark box around it, suggesting the alpha for that particular decal is playing up.

Oddly, the same marker is found in several other places in Whiterun, and as far as I can tell these are not affected.

**To Reproduce**
Travel to Whiterun - Go to Carlotta's House - Observe with eyeball(s)

**Expected behavior**
Darkened square should not be present around marker.

**Screenshots**
https://imgur.com/a/flzLfOX
(Could not select marker itself in console, selected wall asset if that helps?

**Additional context**
Other identical markers seem unaffected - issue persists after restarting game.

**Comment by TwistedModding** [comment]
That might be a side effect of an enb (not 100% sure), but if it is, it's unfixable by us unless im pretty sure unless there is a mod out there to specifically fix it.

**Comment by ChunkeeMunkee** [comment]
I'll test with a different ENB and also with ENB removed later today and report back!

**Comment by ChunkeeMunkee** [comment]
Tested with Silent Horizons and Amon Reborn, both show the issue. Then tested with no ENB at all, issue resolved.

Definitely ENB-related.

**Comment by TwistedModding** [comment]
In that case, there is nothing we can do as far as i know so im closing the issue.
