### ISSUE TITLE
Cash to Desktop in Mine of Darkwater crossing

### ISSUE THREAD

**Issue by Cat656** [ForgottenGlory/Living-Skyrim-3#132]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.
[Crash_2021_2_12_21-0-36.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/5975193/Crash_2021_2_12_21-0-36.txt)

**LS Version**
2/12/2021 3.0.0.3 Beta 3

**Describe the bug**
A crash to desktop after entering the mine in Darkwater cossing, waiting 6 hours, then waiting for npcs to leave.

**To Reproduce**
Enter the mine and have every ore deposit taken up by an npc.  Wait long enough that they want to leave and go home. 

**Expected behavior**
Not crash when npcs try to leave.

**Screenshots**
If applicable, add screenshots to help explain your problem. Additionally, if your report applies to a specific object, make sure it is selected with the console open. Reports without this will be closed.

**Additional context**

**Comment by TwistedModding** [comment]
Is this repeatable?

**Comment by Cat656** [comment]
Attempted to repeat, didn't crash.
