### ISSUE TITLE
Chest clipping in Sleeping Giant Inn Basement

### ISSUE THREAD

**Issue by weronika0805** [ForgottenGlory/Living-Skyrim-3#133]
**LS Version**
LS3 beta 3

**Describe the bug**
Populated Skyrim adds a merchant chest below Sleeping Giant Inn in Riverwood, but it's in the same place where JK's Sleeping Giant basement is located, so the chest is visible and clips through a bench there.

**To Reproduce**
Visit Sleeping Giant Inn in Riverwood

**Expected behavior**
Merchant chest is located somewhere not visible, no clipping with a bench.

**Screenshots**
![enb2021_2_13_14_45_04](https://user-images.githubusercontent.com/78365583/107851500-c5ab5380-6e0a-11eb-8c24-6f3c7ae327f6.png)
![enb2021_2_13_14_45_07](https://user-images.githubusercontent.com/78365583/107851504-c8a64400-6e0a-11eb-9c88-f57093feab88.png)
![enb2021_2_13_14_45_11](https://user-images.githubusercontent.com/78365583/107851505-c93eda80-6e0a-11eb-817d-c0b075bf5eb0.png)

**Comment by ForgottenGlory** [comment]
Fixed Beta 4
