### ISSUE TITLE
Blue Palace transparent bath

### ISSUE THREAD

**Issue by weronika0805** [ForgottenGlory/Living-Skyrim-3#134]
**LS Version**
LS3 Beta 3

**Describe the bug**
The bath added to Elisif's room by JK's Blue Palace has a transparent flooring that you can see through; however, the flooring is still there so you can't fall through it.

**To Reproduce**
Visit the bath in Jarl Elisif's room (it's behind a door)

**Expected behavior**
The flooring shouldn't be see-through

**Screenshots**
![enb2021_2_13_01_23_04](https://user-images.githubusercontent.com/78365583/107851582-64d04b00-6e0b-11eb-87c0-bc3fdbdbc11e.png)
![enb2021_2_13_01_23_07](https://user-images.githubusercontent.com/78365583/107851585-67cb3b80-6e0b-11eb-84b9-3432e8ba7bab.png)
![enb2021_2_13_01_23_15](https://user-images.githubusercontent.com/78365583/107851587-6a2d9580-6e0b-11eb-9f66-a62bfb8d2cec.png)

**Additional context**
I'm not sure if this is an issue with LS3 or something with the mod itself, but I haven't seen anything about this bug on the mod page comments section

**Comment by ForgottenGlory** [comment]
Fixed Beta 4

**Comment by ForgottenGlory** [comment]
Not fixed Beta 4, something weird is going on with this particular area - maybe something to do with Occlusion? More investigation needed

**Comment by ForgottenGlory** [comment]
Related to 185 - still uncertain of cause

**Comment by TwistedModding** [comment]
fixed - patch in patch channel

**Comment by ForgottenGlory** [comment]
Fixed for full release
