### ISSUE TITLE
Add Gamepad++ to the Configuration Specific

### ISSUE THREAD

**Issue by JaxomofRuatha** [ForgottenGlory/Living-Skyrim-3#135]
https://www.nexusmods.com/skyrimspecialedition/mods/27007

Since we're already considering adding this mod to be within acceptable unmodified guidelines, it makes more sense to specifically add it into the list as "configuration specific" instead of having players go off and try to install it themselves.

I can provide some recommended custom mappings (and instructions for how to revert to K+M) if that's helpful for the README/MCM as well.

**Comment by TwistedModding** [comment]
+1 to adding it, but keeping it disabled by default.

**Comment by ForgottenGlory** [comment]
Done Beta 4
