### ISSUE TITLE
Messed up door alignments in weird unnamed settlement between South Windcaller pass and Alechmist Shack

### ISSUE THREAD

**Issue by Cat656** [ForgottenGlory/Living-Skyrim-3#136]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
2/12/2021 3.0.0.3 Beta 3

**Describe the bug**
Odd floating door that leads to an empty room floating in the air. 

**To Reproduce**
Travel from SWP along the road till you reach a Stormcloak encampment. Check the "worker's house"

**Expected behavior**
No weird doors in the middle of the air.

**Screenshots**
If applicable, add screenshots to help explain your problem. Additionally, if your report applies to a specific object, make sure it is selected with the console open. Reports without this will be closed.
![enb2021_2_13_02_02_22](https://user-images.githubusercontent.com/57968713/107865091-09f12080-6e18-11eb-986f-3c215eaa70b8.jpg)

![enb2021_2_13_02_02_38](https://user-images.githubusercontent.com/57968713/107865137-74a25c00-6e18-11eb-835d-254cb3dea088.jpg)

**Additional context**

**Comment by Cat656** [comment]
On reloading the game, I cannot find proof this building ever existed.

**Comment by celadoneiron** [comment]
I recognise this location. Leeks, random floating Worker's House door, those map markers on the compass, that's gotta be Mixwater Mill.

![Screen Shot 02-17-21 at 07 39 PM](https://user-images.githubusercontent.com/73095714/108188225-0f71a200-715b-11eb-8b4c-e1bdad18bc13.PNG)

**Comment by ForgottenGlory** [comment]
Fixed Beta 4
