### ISSUE TITLE
Some elemental staff and weapon enchantments are not applying their effects. 

### ISSUE THREAD

**Issue by FlawedKing** [ForgottenGlory/Living-Skyrim-3#137]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
2/12/2021 3.0.0.3 Beta 3

**Describe the bug**
Fire enchantments on melee weapons are not applying their enchantment effects. Fire and Lightning enchantments on staffs and wands are not applying their effects and thus not doing damage at all. 

**To Reproduce**
Use the console to spawn in a staff and melee weapon of each broken elemental enchantment type.
Staff of Flames: player.additem 0004dee0 1
Staff of Sparks: player.additem 0004dee2 1
Iron Dagger of Embers: player.additem 000896ae 1
Use a companion or spawn an enemy to test them on.
Generic One-Handed Bandit: player.placeatme 0003DECB 1
Test each weapon on the companion/bandit.

The below weapon/elemental enchantment combinations seem to work fine, but for testing purposes:
Staff of Frostbite: player.additem 0004dee1 1
Iron Dagger of Chills: player.additem 000896bd 1
Iron Dagger of Sparks: player.additem 000896c9 1

**Expected behavior**
Staff of Flames should deal fire damage.
Iron Dagger of Embers should deal added fire damage.
Staff of Sparks should deal lightning damage to health and magicka. 

**Screenshots**
N/A

**Additional context**
I've done some further testing with other enchanted weapons than iron daggers, and have also enchanted my own to test, and the issue persists for all melee weapons as far as I can tell.

**Comment by TwistedModding** [comment]
I mean can we give this bug report a round of applause. Everyone take notes :)

Looking at this right now.

**Comment by AronaxAE** [comment]
I am in awe at the absolute cojones this guy is packing. Now THAT is a bug report!

**Comment by TwistedModding** [comment]
So after a bit of testing and looking in xedit, I don't really see anything wrong. The enchantments being used (fire damage and shock) are completely vanilla. So I'm really not sure what's going on here. I want to say its intended but after testing, it doesn't feel right (especially with the dagger literally not dealing any fire damage at all even though it states it should do 5 overtime.)

Handing this over to more smarter people than me :p

**Comment by ForgottenGlory** [comment]
Staves should be fixed Beta 4, unsure on the daggers and such though.
