### ISSUE TITLE
Non-stacking steel arrows

### ISSUE THREAD

**Issue by celadoneiron** [ForgottenGlory/Living-Skyrim-3#139]
**LS Version**
Beta 3 (map fix).

**Describe the bug**
The steel arrows that the player can pick up from some dead Imperial soldiers ("dunCGImperialSoldierArcherA04" 00105ee2, "MQ101ImperialArcherFemale" 00106b83, "MQ101ImperialArcherMale" 00106b84) will not stack with other steel arrows, because they are a different item ("MQ101SteelArrow" 00105ee7, instead of "SteelArrow" 0001397f).

**To Reproduce**
Go to the bridge on the path between Redoran's Retreat and Fort Greymoor, and loot arrows from the dead soldiers.

**Expected behavior**
All steel arrows should stack.

**Screenshots**
![Screen Shot 02-15-21 at 01 44 PM 002](https://user-images.githubusercontent.com/73095714/107903196-4cd80300-6f94-11eb-948e-ed63928a4096.PNG)
![Screen Shot 02-15-21 at 01 44 PM](https://user-images.githubusercontent.com/73095714/107903202-519cb700-6f94-11eb-92c5-a1056571f398.PNG)
![Screen Shot 02-15-21 at 01 45 PM](https://user-images.githubusercontent.com/73095714/107903210-582b2e80-6f94-11eb-852c-4a1e548115b5.PNG)
![Screen Shot 02-14-21 at 07 06 PM 002](https://user-images.githubusercontent.com/73095714/107903476-18187b80-6f95-11eb-910c-2e52545dc1a5.PNG)
![Screen Shot 02-14-21 at 07 06 PM 001](https://user-images.githubusercontent.com/73095714/107903483-1c449900-6f95-11eb-8f26-7fd6e6b9c68a.PNG)

**Additional context**

**Comment by ForgottenGlory** [comment]
Fixed Beta 4
