### ISSUE TITLE
Floating Wall of Water in Entry of Old Ruins by Stonehills

### ISSUE THREAD

**Issue by Ermenher** [ForgottenGlory/Living-Skyrim-3#140]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
LS3 Beta 3

**Describe the bug**
In the entry to Old Ruins that are just beside the town of Stonehills, their is a sheet of water filling a third the entry, the rest of the entry is clear. If you enter the water you'll have to swim to the entry, but if you jump or fall into the two-thirds without the sheet of water, you can walk into the entry. But if you walk up into the two-thirds with the sheet of water, you'll began to swim and can't leave swimming unless you raise to the surface of the third with the sheet of water, if you raise to the surface where the sheet of water isn't, you won't stop swimming. I know this makes little sense but I can't figure out how to describe it any better.

**To Reproduce**
Go to the burial mound, Old Ruins beside the town of Stonehills. Walk down into the burial mound of Old Ruins, you can't miss it.

**Expected behavior**
For the entry of Old Ruins to be either clear of water, or filled with water, which ever it's supposed to be. (I think clear because the ruin isn't flooded inside." But none of this floating wall of water filling only a third of the entry.

**Screenshots**
![2021-02-16](https://user-images.githubusercontent.com/78520661/108045111-51d29c00-7000-11eb-9edb-f08dde949101.png)
![2021-02-16 (2)](https://user-images.githubusercontent.com/78520661/108045120-54cd8c80-7000-11eb-9a05-45d0f694692e.png)
![2021-02-16 (1)](https://user-images.githubusercontent.com/78520661/108045145-59924080-7000-11eb-94eb-de4cc88c8550.png)

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**
I think a field or section of water from another area overlapped into the entry of the ruin.

**Comment by ForgottenGlory** [comment]
Fixed Beta 4
