### ISSUE TITLE
Audio bug

### ISSUE THREAD

**Issue by FowHoe** [ForgottenGlory/Living-Skyrim-3#141]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
Put the version of the list you are on here.
Beta 3?
**Describe the bug**
I start a new character and I wait for all the mods to do their thing and after that, I select my spawn and whatever, but I load in and my arms are missing in 1st person (my hands are there holding a sword but my arms are missing) and the audio is really wonky, my sword swings don't make noise and neither does my walking
**To Reproduce**
I make a character and load in
**Expected behavior**

**Screenshots**

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**

**Comment by TwistedModding** [comment]
I can't replicate this.. Can you post a screenshot of your MO2?

**Comment by FowHoe** [comment]
Actually another issue just popped up, my MO2 just reset itself  Sent from Mail for Windows 10 From: TwistedModdingSent: Wednesday, February 17, 2021 12:33 PMTo: ForgottenGlory/Living-Skyrim-3Cc: FowHoe; AuthorSubject: Re: [ForgottenGlory/Living-Skyrim-3] Audio bug (#141) I can't replicate this.. Can you post a screenshot of your MO2? and upload a save with this happening?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by TwistedModding** [comment]
If your mo2 reset itself, reinstall through wabbajack.

**Comment by FowHoe** [comment]
Okay this may be stupid to ask but I’m not very bright, how do I do that? Sent from Mail for Windows 10 From: TwistedModdingSent: Wednesday, February 17, 2021 2:10 PMTo: ForgottenGlory/Living-Skyrim-3Cc: FowHoe; AuthorSubject: Re: [ForgottenGlory/Living-Skyrim-3] Audio bug (#141) If your mo2 reset itself, reinstall through wabbajack.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by KNGLogan** [comment]
for the save go to your LS3 install folder, than profiles and than select your newest save. The ESS file and SKSE

**Comment by KNGLogan** [comment]
and for the screenshot just open up MO2 and take a screenshot
