### ISSUE TITLE
NPC Missing Response and conversation 

### ISSUE THREAD

**Issue by Cerberus610** [ForgottenGlory/Living-Skyrim-3#142]
2 Different times I've experienced conversation's that are missing response's and questions. No choices other than "Another time perhaps", This may of been reported, if so i apologize. Something I just ran into just now.

**Newest LS3 Beta*

**Describe the bug**
I believe there may be a load order issue or something is over written where the script is changed. 

**To Reproduce**
Speak to wondering NPC in Towns and Villages 

**Expected behavior**
Not sure what mod this may be but some sort of followers

**Screenshots**

![enb2021_2_17_01_15_45](https://user-images.githubusercontent.com/78388153/108168064-af302100-70c4-11eb-8832-b6c439c6beb4.jpg)
![enb2021_2_16_21_43_05 (2)](https://user-images.githubusercontent.com/78388153/108168072-b22b1180-70c4-11eb-873c-791b09c3e400.jpg)
![enb2021_2_16_21_42_51](https://user-images.githubusercontent.com/78388153/108168099-b8b98900-70c4-11eb-8949-d183ffe391b5.jpg)

**Comment by ForgottenGlory** [comment]
Did you already have 3 or 4 followers? If you're at the limit this will happen instead of allowing you to offer to recruit them.

**Comment by Cerberus610** [comment]
> Did you already have 3 or 4 followers? If you're at the limit this will happen instead of allowing you to offer to recruit them.
Yes i did actually.  Sorry for the late reply. Makes sense!
