### ISSUE TITLE
Swimming without Water in White River Watch

### ISSUE THREAD

**Issue by Ermenher** [ForgottenGlory/Living-Skyrim-3#144]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
LS3 Beta 3

**Describe the bug**
Against one of the back walls of White River Watch, the character will begin to swim in the air without any water near. It is only right against the wall. Once you swim a short distance away from the wall the character begins to walk again.

**To Reproduce**
Go to White River Watch, go to the room by the exit from the trap door tunnel (gate), its the right tunnel leading down from the first main room. Go to the back wall and walk right. Remaining against the wall one's character will began to swim.

**Expected behavior**
For my character to walk when on dry land and only swim when in water. The character shouldn't swim there in the air.

**Screenshots**
![2021-02-17 (8)](https://user-images.githubusercontent.com/78520661/108223038-9c364480-70f6-11eb-8f58-4b473b229eb3.png)
![2021-02-17 (11)](https://user-images.githubusercontent.com/78520661/108223056-a0faf880-70f6-11eb-96ea-9dd1181aa1a3.png)
![2021-02-17 (9)](https://user-images.githubusercontent.com/78520661/108223074-a5bfac80-70f6-11eb-8e9d-fe52873baee0.png)
![2021-02-17 (10)](https://user-images.githubusercontent.com/78520661/108223088-a9533380-70f6-11eb-9001-6ee53ffbc9fb.png)

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**
In the tunnel from the trap door their is some water, that tunnel wraps around and behind that section, I wonder if that could be affecting it.

**Comment by ForgottenGlory** [comment]
I'm not able to replicate this, unsure what's going on here
