### ISSUE TITLE
Wabbajack installation still opens the "/ls3/" readme - 404 error

### ISSUE THREAD

**Issue by ChunkeeMunkee** [ForgottenGlory/Living-Skyrim-3#145]
**Section**
The Wabbajack Beta 3 installer opens the defunct "/ls3/" ReadMe URL, leading to a 404 page.

**Description**
Wabbajack should trigger a link to the "/ls/" ReadMe URL.

**Comment by ForgottenGlory** [comment]
Will be fixed Beta 4

**Comment by ForgottenGlory** [comment]
Fixed Beta 4
