### ISSUE TITLE
MCM Config - SmoothCam - Specify "Load"

### ISSUE THREAD

**Issue by ChunkeeMunkee** [ForgottenGlory/Living-Skyrim-3#146]
**Section**
In the MCM setup guide - SmoothCam

**Description**
Could you add a specific mention to clicking the _Load_ section of the menu please, as the MCM menu's first "Slot4: Modern Preset" is actually under the Save section. This would help dum-dums like myself to avoid accidentally overwriting your SmoothCam preset with the default one.

The guide currently has:

- SmoothCam
-     Presets
-         Click Slot4: Modern Preset

Could this be amended to:

- SmoothCam
-     Presets
-         **Load**
-             Click Slot4: Modern Preset

**Comment by ForgottenGlory** [comment]
Done
