### ISSUE TITLE
Blackface Child in Mixwater Mill

### ISSUE THREAD

**Issue by Ermenher** [ForgottenGlory/Living-Skyrim-3#147]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
LS3 Beta 3

**Describe the bug**
In Mixwater Mill, the male child named Haukr, ID 4E038841 from The Greater Village of Mixwater Mill Mod has the blackface bug.

**To Reproduce**
Go to Mixwater Mill and find the male child Haukr, he will have a blacked out face while his body is not so.

**Expected behavior**
For Haukr's face to match his body.

**Screenshots**
![2021-02-17 (15)](https://user-images.githubusercontent.com/78520661/108251771-14136780-7115-11eb-9ac6-4fec1e3d94ca.png)
![2021-02-17 (19)](https://user-images.githubusercontent.com/78520661/108251777-15dd2b00-7115-11eb-9548-dce29e1ef92b.png)
![2021-02-17 (17)](https://user-images.githubusercontent.com/78520661/108251782-17a6ee80-7115-11eb-8048-1f2c5ec9cccd.png)

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**

**Comment by ForgottenGlory** [comment]
Fixed Beta 4
