### ISSUE TITLE
Invisible wall blocking path, plus tree clipping - Valtheim Towers

### ISSUE THREAD

**Issue by ChunkeeMunkee** [ForgottenGlory/Living-Skyrim-3#148]
**LS Version**
Beta 3.0.0.3

**Describe the bug**
An invisible wall blocks the player's path at the Northern bend of the Western elevated walkway of Valtheim Towers.

There is a large tree clipping through this bend in the path which may have something to do with it, though the invisible wall doesn't appear to align with the actual tree itself.

The walls are pictured in the screens linked below - whilst the bend in the walkway is blocked, the player can easily take a diversion across the adjacent forge platform.

**To Reproduce**
Travel to Valtheim Towers, East of Whiterun
Ascend to the Westernmost elevated walkway (it crosses the roadway)
Walk to the Northern end, near the forge, and try to walk around the bend in the walkway

**Expected behavior**
Path should not be blocked, and tree should not clip through the walkway.

**Screenshots**
https://imgur.com/a/xdnHp40

**Comment by ForgottenGlory** [comment]
Fixed Beta 4
