### ISSUE TITLE
Landscape tears and floating or clipping objects outside Routa

### ISSUE THREAD

**Issue by celadoneiron** [ForgottenGlory/Living-Skyrim-3#149]
**LS Version**
Beta 3 (map fix).

**Describe the bug**
The exterior of the Routa player home doesn't align with the landscape changes made by the Windhelm Bridge Overhaul, so things like the house and the rocks are floating above the landscape while other objects like the smithing storage are partially under the ground.

**To Reproduce**
Travel to the Windhelm Stables and look around the exterior of Routa.

**Expected behavior**
Objects align with landscape.

**Screenshots**
![Screen Shot 02-17-21 at 09 54 AM 001](https://user-images.githubusercontent.com/73095714/108305919-c7a05880-71f6-11eb-9319-1cca1581bace.PNG)
![Screen Shot 02-17-21 at 09 54 AM](https://user-images.githubusercontent.com/73095714/108305925-cb33df80-71f6-11eb-9b36-56f3fdb1c9f9.PNG)
![Screen Shot 02-18-21 at 02 41 PM](https://user-images.githubusercontent.com/73095714/108306297-983e1b80-71f7-11eb-918a-36d6173f484a.PNG)
![Screen Shot 02-18-21 at 02 42 PM 001](https://user-images.githubusercontent.com/73095714/108306308-9bd1a280-71f7-11eb-90c1-9e9a36f2d88a.PNG)
![Screen Shot 02-18-21 at 02 42 PM 005](https://user-images.githubusercontent.com/73095714/108306347-a7bd6480-71f7-11eb-89fc-38e63faaa280.PNG)
![Screen Shot 02-18-21 at 02 42 PM 006](https://user-images.githubusercontent.com/73095714/108306355-ac821880-71f7-11eb-9915-c1e4361e2141.PNG)

**Additional context**
This will probably require landscape editing as well as moving individual objects.

**Comment by ForgottenGlory** [comment]
After digging into this a bit more, Routa has more issues than just this. Routa removed Beta 4
