### ISSUE TITLE
Similar potions aren't group together

### ISSUE THREAD

**Issue by Quietbeat** [ForgottenGlory/Living-Skyrim-3#15]
**LS Version**
3

**Describe the bug**
In v2 when I viewed my potions, similar potions were grouped together, i.e., "Weak poison (3)" instead of each individual potion being displayed. I asked on the forum if this was due to a mod but no one replied.

**To Reproduce**
Buy/craft a potion then open in the inventory.

**Expected behavior**
All similar potions are grouped together.

**Screenshots**
![Similar potions are not grouped together](https://user-images.githubusercontent.com/57841662/106516006-525d2580-648b-11eb-9a02-20003e7055d2.png)

**Comment by ForgottenGlory** [comment]
This is from CACO and the way it handles potions. It's possible to have multiple "unique" versions of a single kind of potion, so they don't stack.

**Comment by sirwanace** [comment]
Potions don't stack AT ALL. If this is intended I'd suggest taking it out as it makes inventory management a real hassle.
