### ISSUE TITLE
Helgen Reborn/Helgen Keep

### ISSUE THREAD

**Issue by jwildy** [ForgottenGlory/Living-Skyrim-3#150]
**LS Version**
3.0.0.3

**Describe the bug**
Freeze on load screen into Helgen Keep.

**To Reproduce**
On quest "Desperate Times"
On objective "Escort Marcus to Valerius in Helgen Keep"
Level 4, Walked from Falkenreath and also Fast Traveled to Helgen.
Open the door to Helgen Keep.

**Expected behavior**
To end up in Helgen keep to progress to the next step of the quest "desperate times"

** in addition to Marcus Jannus I also have Lucien Flavius and Locatta following me.

**Comment by ForgottenGlory** [comment]
This contains no actionable information.
