### ISSUE TITLE
Missing textures on rock in Helgen

### ISSUE THREAD

**Issue by Weedy2503** [ForgottenGlory/Living-Skyrim-3#156]
**LS Version**
LS3 Beta 3

**Describe the bug**
There is a rock in Helgen where the textures are missing 

**Screenshots**
![image](https://user-images.githubusercontent.com/79363318/108623955-23aaed00-7442-11eb-8bcc-963e6bdab792.jpeg)

![image](https://user-images.githubusercontent.com/79363318/108623970-2c9bbe80-7442-11eb-8a43-851289493790.jpeg)

**Comment by ForgottenGlory** [comment]
Does this persist after restarting the game? As far as I was aware the DynDOLOD issues should be fixed
