### ISSUE TITLE
CTD in Bleakfalls Barrow

### ISSUE THREAD

**Issue by Lodreyon** [ForgottenGlory/Living-Skyrim-3#157]
**LS Version**
LS3

**Describe the bug**
Game keeps crashing to Desktop in Bleakfalls Barrow, mainly at the Wall where I learn the FUS-Shout.
[Crash_2021_2_21_15-45-12.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6017892/Crash_2021_2_21_15-45-12.txt)

**Expected behavior**
The crash just happens. The first crash happened by just walking through Bleak Falls Barrow. Later on (at the FUS-Wall) it crashed after learning the shout and now it crashes shortly after I load the game (the "effect waves" of the wall are approaching my character and then it crashes).

**Comment by ForgottenGlory** [comment]
Rule 11
