### ISSUE TITLE
NPC Detection and Fury Spell

### ISSUE THREAD

**Issue by ZaryGodMan** [ForgottenGlory/Living-Skyrim-3#158]
Describe the bug

Illusionist Builds don't efficiently work on LS3. I've Furyd groups of people and, commonly, they just keep looking for me while staring at each other. I think npcs are blind in the dark, like really blind that they can't see each other. This causes a unique issue were npcs who are under the effect of Fury may only attack another if they bump into them or step into a bright area. My issue is less prominent in daylight or lit areas. 

To Reproduce

I walked to the cliff above Valtheim Towers at night. Am vampire using pred vision and was casting fury on various NPCs on the bridge and towers. They did not react as I was expecting and found difficulty persuading npcs to kill each other. 

Expected behavior

They did not react as I was expecting and found difficulty persuading npcs to kill each other.

**Comment by celadoneiron** [comment]
Based on the observation that light seems to have an impact, this may be related to Realistic AI Detection SE. It looks like we're using the Lite version, and the mod page suggests that if NPCs are slow to detect you or each other (it seems like here they may be continuing to search for the already-detected player without noticing that other NPCs are around?) it may be necessary to use a version of RAID with stronger effects. Lite is recommended for Obsidian Weathers, but Medium for ELFX, so switching up might help mitigate this.

If it really is a light issue, and changing the version of RAID makes little difference or makes player sneak builds less manageable, it may end up being that the most effective way of handling it is to make Magelight a part of an Illusionist build. Casting Fury on one enemy and then lighting up the area (or another enemy directly) with Magelight could be the way to go, and would be a neat in-game solution.

**Comment by ForgottenGlory** [comment]
Fixed for full release
