### ISSUE TITLE
Crouching nearly all the time

### ISSUE THREAD

**Issue by Quietbeat** [ForgottenGlory/Living-Skyrim-3#16]
**LS Version**
3

**Describe the bug**
After I started my new life in my home in Riverwood, I noticed that I was crouching nearly all the time. Pressing L-CTRL didn't resolve the issue. I didn't assign L-CTRL to any other key and I checked the other mods. Sometimes it'll resolve itself but always go back to crouching. 

**To Reproduce**
Create a new character in Breezewood.

**Expected behavior**
Characters only crouch when told to.

**Screenshots**
[saves.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/5906699/saves.zip)

**Additional context**
I went to the Ultimate Dodge mod to verify that no bindings were set and when I left MCM, I was un-crouched for a while. Another user had the same issue. I've been wondering if it is a key bind issue, what's the best way to reset all of the mods to the original value?

I continued playing and I'm finding that even when I don't have L-CTRL assigned to dodge that somehow it's being used to Dodge. I tried changing the assignment to G and \ to no avail.

**Comment by ForgottenGlory** [comment]
The crouch/sneak key is Shift, not CTRL. Refer to Keymap for details: http://www.keyboard-layout-editor.com/#/gists/0469bf568cf28f1ea8e9e78dba13c169
