### ISSUE TITLE
Better Container Controls, Yes I'm Sure, and EZ2C Dialogue Menu

### ISSUE THREAD

**Issue by celadoneiron** [ForgottenGlory/Living-Skyrim-3#160]
You mentioned wanting to check/add these.

**Comment by ForgottenGlory** [comment]
Done

**Comment by celadoneiron** [comment]
Better Container Controls not included in Beta 5.

**Comment by ForgottenGlory** [comment]
I seem to recall BCC causing issues with... something. QuickLoot maybe? I forget exactly what. Will look into it though.
