### ISSUE TITLE
Footsteps, Combat sounds

### ISSUE THREAD

**Issue by Deepockent** [ForgottenGlory/Living-Skyrim-3#161]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
LS3 B4

**Describe the bug**
At this time, none of my characters have footsteps outside of 1 in 6 steps. Combat sounds don't work, either, when they work in other ML's.

**To Reproduce**
I'm not sure what the reproduction case is - For me it is literally constant.

**Expected behavior**
I should hear a footstep every time my character .. steps. When I smack somebody with a warhammer, it should make noise. 

**Screenshots**
N/A

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**
N/A

**Comment by TwistedModding** [comment]
Never have been able to replicate sound issues, someone else will have to look at this.

**Comment by ForgottenGlory** [comment]
Fixed for full release
