### ISSUE TITLE
Just a Matter of Time Widget & Less Intrusive HUD Compass go out of Synch on Reload

### ISSUE THREAD

**Issue by Eurafrica** [ForgottenGlory/Living-Skyrim-3#162]
**LS Version**
2/12/2021 3.0.0.3 Beta 3

**Describe the bug**
Upon reloading a save, the compass and clock/time widget will become out of synch. Since they share the same toggle key <X>, you have to hold X and press escape, and let go to fix, or just spam x really quickly. A minor issue, but can get irritating over time since the clock and compass are so useful.

**To Reproduce**
Just reload a save, your compass and SkyUI buffs will be showing, but the clock will not. Press X and the clock will appear and compass will fade.

**Expected behavior**
All UI elements should remain in synch upon reload. Unless I'm misunderstanding the intended behavior.

**Comment by ForgottenGlory** [comment]
This happens occasionally. Can be fixed by disabling the toggle option for iHUD then toggling it back on. AFAIK there isn't a way to fix it.
