### ISSUE TITLE
Incorrect interaction between ELSA and Custom Classes & Birthsigns SSE

### ISSUE THREAD

**Issue by Eurafrica** [ForgottenGlory/Living-Skyrim-3#163]
**LS Version**
LS3 Beta 4

**Describe the bug**
Odd interaction between ELSA and Custom Classes & Birthsigns SSE. If you use ELSA first, then Custom Classes, your ending skills and bonuses will be correct. If you use Custom Classes first, and then apply ELSA +10 bonus to an ability you chose +20 to, you will get an extra amount. 

Pasted from Discord:

"Ex.
-New character, Nord, select Alchemist +20 bonus from Classic Classes, then pick +10 Apothecary bonus from Reflect ELSA, end result is 60 Alchemy (which is incorrect)

-New character, Nord, use Reflect ELSA, select Apothecary +10, then choose +20 from Classic Classes, end result is 40 Alchemy, which is correct.

The other downside to this...bug, is that it skips over getting an Attribute assigned from AVA if the skill goes over 50."

**To Reproduce**
Just create a new character and test it both ways. Was bugged in Beta 3, confirmed still bugged in Beta 4.

**Expected behavior**
Should be able to pick in either order; Reflecting or Custom Class setup shouldn't be providing different bonuses based on order of use.

**Comment by ForgottenGlory** [comment]
This is why it's listed the way it is in the MCM document.
