### ISSUE TITLE
NPCs stalking but not attacking when bounty is high

### ISSUE THREAD

**Issue by celadoneiron** [ForgottenGlory/Living-Skyrim-3#164]
**LS Version**
LS3 beta 4.

**Describe the bug**
Some NPCs will draw their weapons and closely follow the PC when they have a bounty, but not attack or forcegreet/arrest. They will constantly (every second or so) say their default greeting, e.g. "Huh?" "Aye?" "Need something?". They cannot be entered into conversation with. They will follow for long distances and through load doors.

Paying off the bounty through the console results in them sheathing their weapons and walking away, presumably back towards their normal routine.

**To Reproduce**
- Acquire bounty.
- Find a Militia NPC for the hold the bounty is in. (Spawning them in seems to just summon a generic bandit instead, maybe because that's the template they're based on?)

**Expected behavior**
They should either attack or ignore, but not just follow.

**Screenshots**
![Screen Shot 02-22-21 at 05 58 PM](https://user-images.githubusercontent.com/73095714/108680669-e1fd6d80-7539-11eb-9144-f4a2e3168f89.PNG)
![Screen Shot 02-22-21 at 05 58 PM 001](https://user-images.githubusercontent.com/73095714/108680682-e45fc780-7539-11eb-8c59-f5b45edfc51f.PNG)
![Screen Shot 02-22-21 at 05 58 PM 002](https://user-images.githubusercontent.com/73095714/108680689-e6298b00-7539-11eb-91e7-c730a09f4899.PNG)
![Screen Shot 02-22-21 at 05 58 PM 003](https://user-images.githubusercontent.com/73095714/108680695-e75ab800-7539-11eb-98f4-d4835863fd6f.PNG)

**Additional context**
These ones are Populated Skyrim NPCs. I think it may be happening because they're in GuardFaction[Hold] and IsGuardFaction but they've been set to unaggressive, so they're angry at the player for doing crimes but don't have the dialogue to arrest you and also can't attack.

**Comment by ForgottenGlory** [comment]
Fixed Beta 5
