### ISSUE TITLE
Sofia Follower Bug

### ISSUE THREAD

**Issue by jwildy** [ForgottenGlory/Living-Skyrim-3#165]
**LS Version**
3.0.0.4 (Beta 4)

**Describe the bug**
CTD when changing Sofia Follower Combat Class in the MCM settings.

**To Reproduce**
Allow Sofia to follow you, open MCM and change her combat class. ( i was trying to do heavy one handed ) then close MCM, and ctd. 

**Expected behavior**
Make Sofia into my teams tank by forcing her to use taunt from NFF and change her combat style using MCM settings to heavy one handed.

**Additional context**
CTD occured both with Sofia not imported into NFF and with her imported.

**Comment by jwildy** [comment]
[Crash_2021_2_22_13-19-6.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6024281/Crash_2021_2_22_13-19-6.txt)

**Comment by jwildy** [comment]
If you stop Sofia from following you, and remove from NFF. The crash doesn't happen when changing her Combat Class in the MCM

**Comment by ForgottenGlory** [comment]
Fixed Beta 5
