### ISSUE TITLE
Large tree LODs shrink noticeably on approach

### ISSUE THREAD

**Issue by ChunkeeMunkee** [ForgottenGlory/Living-Skyrim-3#167]
**LS Version**
Beta 3.0.0.4

**Describe the bug**
The very large tree LOD models shrink noticeably when approaching them from ~1/4 mile away (see images)

**To Reproduce**
For the trees in the screenshots, follow the path from the entrance to Dushnikh Mine North (back down the hill to Dushnikh Orc Stronghold - the "Orc Stronghold" Alternate Start point).

Trees are on the hilltop directly North of the mine entrance.

**Expected behavior**
No clear difference in LOD model sizes

**Screenshots**
https://imgur.com/a/HDZI9Fx

If your report pertains to a specific NPC, object, or item.... [Issue pertains to multiple items of this same type, namely the very large tree pictured]

**Additional context**
Cannot get onto game right now to grab specific IDs, but if you need me to take the IDs of the trees pictured - or test other such trees across Skyrim - I'd be happy to help)

**Comment by ForgottenGlory** [comment]
Fixed Beta 5
