### ISSUE TITLE
All Forsworn in Markarth have the black face bug.

### ISSUE THREAD

**Issue by mordang7** [ForgottenGlory/Living-Skyrim-3#169]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
LS 3 Beta 4

**Describe the bug**
Upon the first Forsworn attack outside of Markarth, all the Forsworn appear to have the black face bug.

**To Reproduce**
I reloaded several times and the Forsworn NPC's always appeared with a black face bug.

**Expected behavior**
Models to follow correct skin/body texture and for face textures to load properly.

**Screenshots**
![ScreenShot209](https://user-images.githubusercontent.com/21289127/108801685-b92cb500-75d9-11eb-9070-03df089a7850.png)
![ScreenShot210](https://user-images.githubusercontent.com/21289127/108801690-bb8f0f00-75d9-11eb-90b8-2459fe5b2441.png)
![ScreenShot211](https://user-images.githubusercontent.com/21289127/108801704-c184f000-75d9-11eb-8e6b-54afe5cacb04.png)
[BlackFaceBugSaves.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6026789/BlackFaceBugSaves.zip)

![ScreenShot206](https://user-images.githubusercontent.com/21289127/108801588-81be0880-75d9-11eb-9b24-deb0fd4ec511.png)
![ScreenShot207](https://user-images.githubusercontent.com/21289127/108801602-87b3e980-75d9-11eb-9c7c-a7749d97d159.png)
![ScreenShot208](https://user-images.githubusercontent.com/21289127/108801608-8a164380-75d9-11eb-91fb-23a0d8aa62ae.png)

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**

**Comment by ForgottenGlory** [comment]
Fixed Beta 5
