### ISSUE TITLE
Oneway wall in Embersharde Mine treasure room.

### ISSUE THREAD

**Issue by xelphos** [ForgottenGlory/Living-Skyrim-3#17]
**LS Version**
LS3 Open Beta 1

**Describe the bug**
Inside Embershard Mine in the treasure room there is a one way rock wall only visible from inside the treasure room. Going through it traps you inside the trasure room.

**To Reproduce**
Enter Embershard Mine, cross the drawbridge and head to the treaser room on the right.

**Expected behavior**
Shouldn't be a wall there.

**Screenshots**
https://www.youtube.com/watch?v=PrcFF5RPfZk
Console can bee seen at 0:36.

**Comment by ForgottenGlory** [comment]
Fixed Beta 2

**Comment by TwistedModding** [comment]
Probably can just place embarshardmine revisited somewhere at the bottom of the esp list (along with the other revisted mods if any issues pop up.)

**Comment by ForgottenGlory** [comment]
Fixed Beta 4
