### ISSUE TITLE
Raylof won't trigger conversing with Gertrud (his sister) in Riverwood.

### ISSUE THREAD

**Issue by mordang7** [ForgottenGlory/Living-Skyrim-3#170]
[RaylofNoEventTrigger_saves.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6026902/RaylofNoEventTrigger_saves.zip)
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
LS3 Beta 4

**Describe the bug**

After the attack in Helgen, if I follow Raylof to Riverwood he will stop a few meters away from Gertrud (his sister who he's supposed to speak to) but the event of conversation will never trigger. 
**To Reproduce**

**Expected behavior**

Raylof should trigger the conversation with his sister as soon as we arrive in Riverwood, behind the mill without stopping before doing so.

**Screenshots**

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**

**Comment by celadoneiron** [comment]
After trying quite a few different routes, I'm unable to replicate this in a new save, and can't identify a cause for it in the ones you've uploaded. It's possible that reloading an earlier save, maybe from before entering the cave to find Ralof, would allow the scene to progress as normal. But if not, you can still advance the main quest - talking to Gerdur works as normal, and you can also just ignore Riverwood altogether and go directly to the Jarl.
