### ISSUE TITLE
Falkreath Tomb

### ISSUE THREAD

**Issue by jwildy** [ForgottenGlory/Living-Skyrim-3#171]
**LS Version**
3.0.0.4 (Beta 4)

**Describe the bug**
Giant Rock spawns above the floor right at the doorway in Falkreath Tomb

**To Reproduce**
Go into Falkreath Tomb.

**Expected behavior**
No stone should exist.

![ScreenShot210](https://user-images.githubusercontent.com/79277356/108857632-49a6cd80-75b9-11eb-9efa-8f9148e1d48c.png)
![ScreenShot211](https://user-images.githubusercontent.com/79277356/108857642-4ad7fa80-75b9-11eb-94e9-14739d031c04.png)
![ScreenShot212](https://user-images.githubusercontent.com/79277356/108857650-4c092780-75b9-11eb-9c33-203f47028d7c.png)
![ScreenShot213](https://user-images.githubusercontent.com/79277356/108857655-4dd2eb00-75b9-11eb-8275-a0e6d5a005bf.png)

**Comment by ForgottenGlory** [comment]
Fixed Beta 5
