### ISSUE TITLE
Cerri Steelfist can't be interacted with after having her as a follower for awhile.

### ISSUE THREAD

**Issue by jwildy** [ForgottenGlory/Living-Skyrim-3#172]
**LS Version**
3.0.0.4 (Beta 4)

**Describe the bug**
the activate button is gone, and i cant talk to or interact with the follower.

**To Reproduce**
just have her as a follower and eventually it went away. i also have toccata and sofia as followers all in NFF

**Expected behavior**
able to talk to the follower to change armor
![ScreenShot214](https://user-images.githubusercontent.com/79277356/108860476-3812f500-75bc-11eb-899b-c3e279612671.png)
![ScreenShot215](https://user-images.githubusercontent.com/79277356/108860487-3b0de580-75bc-11eb-9c7e-5062096cfa97.png)

**Comment by ForgottenGlory** [comment]
@Day7-J Let me know if you find a fix

**Comment by ForgottenGlory** [comment]
Should be fixable by resetting Cerri's name using the Real Names MCM.
