### ISSUE TITLE
Lantern at whiterun gate 

### ISSUE THREAD

**Issue by KNGLogan** [ForgottenGlory/Living-Skyrim-3#173]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
Beta 4

**Describe the bug**
random lantern 

**To Reproduce**
go in front of whiterun gate

**Expected behavior**
it not be there

**Screenshots**
![SkyrimSE 2021-02-23 18-42-23](https://user-images.githubusercontent.com/66355096/108933524-e8124d80-7610-11eb-9458-b358e2c290eb.png)

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**
reloaded saves and still is there 
[Saves.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6032818/Saves.zip)

**Comment by ForgottenGlory** [comment]
Fixed Beta 5
