### ISSUE TITLE
Game freeze at around 12:10 game clock consistantly.

### ISSUE THREAD

**Issue by rohlin1** [ForgottenGlory/Living-Skyrim-3#174]
[Save file](https://drive.google.com/drive/folders/1EpFuTfteXnU1343LthCZg6LM2ndtFye4?usp=sharing)

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
LS3

**Describe the bug**
Every time I sleep, wait, or let the time pass in-game past about 12:10am on the 1st of Hearthfire, the game freezes for me.

**To Reproduce**
Use the wait menu, sleep, or wait in-game for the in-game clock to roll over to ~12:10am, 1st of Hearthfire.

**Expected behavior**
Screen freezes and program stops responding.

**Additional context**
I changed some settings with the dodge roll mod for controller usage and changed Spelltutor to make learning magic incremental instead of having a chance to fail. Otherwise I followed the changes listed in the modlist.

**Comment by ForgottenGlory** [comment]
Update to the latest version of the list
