### ISSUE TITLE
Cannot change from 1st person to 3rd person view 

### ISSUE THREAD

**Issue by jawjadawg** [ForgottenGlory/Living-Skyrim-3#175]
**LS Version**
3.0.0.4

**Describe the bug**
Can't change from first-person to third-person view. 

**To Reproduce**
Created three characters with different races and attributes.  Same behavior with each.

**Expected behavior**
Using the scroll mouse button to change view.

**Additional context**
Also can,t move in sneak position.

ENB Rudy 
ENB version 0.452
Nvidia GeForce RTX 2070 Driver 461.40
16 GB RAM
Resolution 3840x2160
Also, have DnD installed

**Comment by TwistedModding** [comment]
Intentional, click f to go to third person.
