### ISSUE TITLE
Skill Leveling with Passive Bonuses

### ISSUE THREAD

**Issue by Deepockent** [ForgottenGlory/Living-Skyrim-3#177]
[save.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6039141/save.zip)

**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
3.0.0.4 (B4)

**Describe the bug**
I've got the smithing skill fortification from class creation major skill focus - It would appear that due to the lack of an uncapper, that means that my character won't receive experience to get to 100 smithing in order to take full advantage of the perks available. A likely fix is the inclusion of an uncapper.

**To Reproduce**
Steps to reproduce the behavior: Start game. Focus in a skill. Try to that level that skill to 100.

**Expected behavior**
Start game. Focus in a skill. Level that skill. Have skill + bonus(es).

**Screenshots**

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**

**Comment by ForgottenGlory** [comment]
The amount of console commands used on this save make it impossible for us to diagnose or fix any issues related to your save.
