### ISSUE TITLE
Falskaar Map

### ISSUE THREAD

**Issue by jwildy** [ForgottenGlory/Living-Skyrim-3#179]
**LS Version**
3.0.0.4 Beta 4

**Describe the bug**
Falskaar map is messed up

**To Reproduce**
go to falskaar open the map and mouse towards the bottom

**Expected behavior**
a normal map

![ScreenShot216](https://user-images.githubusercontent.com/79277356/109093885-1cf0d400-76e7-11eb-8f86-bcd7acd6f6e3.png)

**Comment by celadoneiron** [comment]
Link to fixed map version in dev patch channel.

**Comment by ForgottenGlory** [comment]
Fixed for full release
