### ISSUE TITLE
Faendal doesn't work well with the dodge ability

### ISSUE THREAD

**Issue by Ashensakar** [ForgottenGlory/Living-Skyrim-3#18]
If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
2.3.2

**Describe the bug**
Faendal doesn't work with the dodge mod
**To Reproduce**
obtain Faendal as a follower do some general playthrough

**Expected behavior**
not bent over when dodges

**Screenshots**
![Screenshot 2021-02-01 205404](https://user-images.githubusercontent.com/68168803/106517160-04b6dc00-64d0-11eb-8032-152e530d978d.png)

**Additional context**

**Comment by weronika0805** [comment]
I just had the same thing happen with Gorr, I think it's an occassional issue with The Ultimate Dodge Mod when NPCs are allowed to dodge too:

![enb2021_2_1_22_42_43](https://user-images.githubusercontent.com/78365583/106521805-1b186400-64df-11eb-8a68-2c0fed086d7e.png)

**Comment by Ashensakar** [comment]
> I just had the same thing happen with Gorr, I think it's an occassional issue with The Ultimate Dodge Mod when NPCs are allowed to dodge too:
> 
> ![enb2021_2_1_22_42_43](https://user-images.githubusercontent.com/78365583/106521805-1b186400-64df-11eb-8a68-2c0fed086d7e.png)

looks like you just perfectly timed Gorr just tripping up lol

**Comment by VyktoryJaye** [comment]
Disallowing NPCs to dodge in TUDM works to fix this... but I'm not sure if the list is balanced for that. This can happen to the player if they don't press G to set dodge style. Seems like a bug in TUDM itself.

**Comment by TwistedModding** [comment]
In the mcm for tudm, either do what @VyktoryJaye suggested, or change the dodge to side step OR roll, not both. It's a known issue with the mod and nothing we can do to fix it.
