### ISSUE TITLE
Cursor hotspot misaligned

### ISSUE THREAD

**Issue by celadoneiron** [ForgottenGlory/Living-Skyrim-3#181]
**LS Version**
Beta 5.

**Describe the bug**
The cursor hotspot (activation point) is above the actual visible cursor pointer. I think it's slightly to the left as well, but the height offset is more noticeable. In menus where precise clicking is required, like sliders, this makes it difficult to accurately select things.

**To Reproduce**
Start a new game and try to adjust sliders in RaceMenu using a mouse and the marker in the middle of the slider.

**Expected behavior**
The cursor hotspot should be on the point of the cursor.

**Screenshots**
If the cursor is positioned with its _height_ relative to the slider as below, the slider will not move when clicking or dragging. (I moved it sideways so it's more visible, but it doesn't matter whether it's horizontally-aligned with the slider marker or not, if the height's like this it won't work.)
![Screen Shot 02-26-21 at 11 01 AM](https://user-images.githubusercontent.com/73095714/109240093-90e3c700-7822-11eb-8d11-b4bc4663c31b.PNG)
If the cursor is positioned with its _height_ relative to the slider as below, both clicking and dragging will work.
![Screen Shot 02-26-21 at 11 02 AM](https://user-images.githubusercontent.com/73095714/109240174-c4265600-7822-11eb-8208-2b7264fa144e.PNG)

**Additional context**
The cause is within the cursormenu.swf file included as part of the Paper World Map mod. Hiding that file resolves the issue (but makes the cursor much larger, to a point where it seems very unwieldy). I tested the mod "[Smaller Vanilla Cursors](https://www.nexusmods.com/skyrimspecialedition/mods/20617)" and the issue appears not to exist with that cursormenu.swf, so if reducing the cursor size is something you'd like to include then I would recommend testing that out at the 50% setting. I did not experience any issues with the map's appearance or functionality when hiding or replacing the Paper World Map cursor.

**Comment by ForgottenGlory** [comment]
Fixed for full release
