### ISSUE TITLE
Aetherius racial traits overwritten for Wood Elves

### ISSUE THREAD

**Issue by celadoneiron** [ForgottenGlory/Living-Skyrim-3#183]
**LS Version**
Beta 5.

**Describe the bug**
Wood Elves have Resist Disease and Resist Poison from a racial trait called "Resist Disease and Poison," but Aetherius's Wood Elves are meant to have "Green Pact: You have 50% Poison Resistance. You also deal 25% extra damage with sneak attacks and spells." 

**To Reproduce**
Make a Wood Elf character.

**Expected behavior**
Wood Elves should use Aetherius racials.

**Additional context**
Aetherius is being overwritten by a copy of the WoodElfRace record in Faces Merged that seems to be doing nothing except reverting Aetherius changes. No other race records are hit by this. Faces Merged may need to be re-built in case this is a leftover from a removed mod, or the record could be removed by hand, or a patch created to carry forward the Aetherius changes.

**Comment by TwistedModding** [comment]
Just make a hand patch for the merge. Make sure it's flagged as an esl. Or I can do it later today if needed.

**Comment by celadoneiron** [comment]
> 
> 
> Just make a hand patch for the merge @celadoneiron . Make sure it's flagged as an esl. Or I can do it later today if needed.

Uploaded in the patches channel. :)

**Comment by ForgottenGlory** [comment]
Fixed for full release
