### ISSUE TITLE
Candlehearth Hall no floors in the basement and missing furniture like beds and tables.

### ISSUE THREAD

**Issue by TheCadinal** [ForgottenGlory/Living-Skyrim-3#185]
**LS Version**
Beta 5

**Describe the bug**
I started in Candlehearth Hall with Alternate start and the basement floor and other furniture like tables are missing. I reloaded but the problem persisted. I use no ENB.

**To Reproduce**
Enter Candlehearth Hall.

**Expected behavior**
The floor should be visible

**Screenshots**

![Candle](https://user-images.githubusercontent.com/79724122/109356675-53faed00-7881-11eb-82f3-7f43c5e0cdfe.jpg)

**Comment by ForgottenGlory** [comment]
Related to #134, uncertain of cause

**Comment by TwistedModding** [comment]
Fixed, patch in patch channel.

**Comment by ForgottenGlory** [comment]
Fixed for full release
