### ISSUE TITLE
Candlehearth Hall basement floors/furniture not loading

### ISSUE THREAD

**Issue by solitudebliss** [ForgottenGlory/Living-Skyrim-3#186]
**LS Version**
Beta 5

**Describe the bug**
Candlehearth Hall has no basement floors/tables upon loading. Tried on multiple characters with multiple saves and the issue persists.

**To Reproduce**
Load into Candlehearth Hall

**Screenshots**
See Attached
![20210226150749_1](https://user-images.githubusercontent.com/79724689/109356700-b4206d80-7846-11eb-90a3-1e6d321b3c3d.jpg)
![20210226150802_1](https://user-images.githubusercontent.com/79724689/109356711-b5ea3100-7846-11eb-997e-32887f520ff7.jpg)

**Comment by ForgottenGlory** [comment]
Duplicate of #185
