### ISSUE TITLE
Broken papermap

### ISSUE THREAD

**Issue by periwinklerene** [ForgottenGlory/Living-Skyrim-3#187]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
Put the version of the list you are on here.
LS3 beta 5

**Describe the bug**
The map is. Thoroughly confused

**To Reproduce**
open the map screen

**Expected behavior**
expected to see paper map, instead got a very confused map

**Screenshots**
![20210226170328_1](https://user-images.githubusercontent.com/36176511/109360137-ad005c00-7854-11eb-841c-5c99ce233b9c.jpg)

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**
n/a

**Comment by TwistedModding** [comment]
make sure paperworldmap.esp (and all of friends) are at the very bottom of mo2 in the right pane.

**Comment by periwinklerene** [comment]
that resolved it. thank you for your time!
