### ISSUE TITLE
Player Bard songs do not have sound

### ISSUE THREAD

**Issue by periwinklerene** [ForgottenGlory/Living-Skyrim-3#188]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
Put the version of the list you are on here.
Living Skyrim 3 Beta 5
**Describe the bug**
When playing the any of the songs of the imperials with a loot, no sound is made even with the player music at its highest volume.
**To Reproduce**
own lute
use songbook of the imperials
choose any song
**Expected behavior**
A short tune once the animation begins.
**Screenshots**

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**
I'm assuming it is a problem with all the songbooks, but I haven't had the chance to test them.

**Comment by celadoneiron** [comment]
I can't replicate this. There's no "of the Imperials" songbook, but every song from Songbook: Songs of Cyrodiil had audio, and after trying at least one song from all of the other Songs of X Location songbooks, I didn't encounter any without audio. It may be an install issue.
