### ISSUE TITLE
Floating NPC - Hisygg

### ISSUE THREAD

**Issue by Fraktyl** [ForgottenGlory/Living-Skyrim-3#189]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
Beta 5

**Describe the bug**
NPC Hisygg is floating in midair at the Half-Moon Mill

**To Reproduce**
Go to Half Moon Mill.. find the NPC

**Expected behavior**
Him to not have magic powers of levitation
![enb2021_2_26_22_36_26](https://user-images.githubusercontent.com/478132/109374407-16975f00-7883-11eb-9e15-74dc4413ae83.png)

**Screenshots**

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**

**Comment by celadoneiron** [comment]
Fix shared in patches channel in Discord.

**Comment by ForgottenGlory** [comment]
Fixed for full release
