### ISSUE TITLE
staff enchant table inside bookcase in Dragonreach

### ISSUE THREAD

**Issue by Ashensakar** [ForgottenGlory/Living-Skyrim-3#19]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
2.3.2

**Describe the bug**
staff enchant table inside bookcase in Dragonreach
**To Reproduce**

Look inside dragonreach 

**Expected behavior**
just the staff enchanting table
**Screenshots**
![Screenshot 2021-02-01 211447](https://user-images.githubusercontent.com/68168803/106519247-ea323200-64d2-11eb-8374-90d0da855399.png)
![Screenshot 2021-02-01 211529](https://user-images.githubusercontent.com/68168803/106519259-eef6e600-64d2-11eb-8233-3fb789a7ba48.png)

**Additional context**

**Comment by ForgottenGlory** [comment]
Fixed Beta 2
