### ISSUE TITLE
Karthwasten - Misaligned steps, NPCs and player cannot walk into buildings

### ISSUE THREAD

**Issue by ChunkeeMunkee** [ForgottenGlory/Living-Skyrim-3#190]
**LS Version**
Beta 3.0.0.5

**Describe the bug**
Three buildings in Karthwasten - Karthwasten Hall, the Miners' Barracks, and the Sleepy Hag Inn - have a large, visible gap between the doorstep and the main steps leading down to ground level.

This is blocking the player from getting all the way to the door (though they are still within interaction distance), and NPCs have difficulty entering buildings.

**To Reproduce**
Travel to Karthwasten and look towards the tops of the steps leading to the three buildings mentioned.

**Expected behavior**
No gap, entering buildings to be snag-free for player and NPCs.

**Screenshots**
https://imgur.com/a/UqHDzl5

**Additional context**
I've also included a final shot of the animal skulls on the wall outside the Sleepy Hag. These appear to be floating, which suggests that the walls and stone steps may be too low, as opposed to the buildings themselves being placed too high.

**Comment by ForgottenGlory** [comment]
Fixed for full release
