### ISSUE TITLE
CTD near Reachwind Eyrie

### ISSUE THREAD

**Issue by jawjadawg** [ForgottenGlory/Living-Skyrim-3#192]
[Crash_2021_3_1_17-57-55.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6065038/Crash_2021_3_1_17-57-55.txt)

**LS Version**
3.0.0.5

[ReachCrashSaveFiles.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6065051/ReachCrashSaveFiles.zip)
**Additional context**

**Comment by TwistedModding** [comment]
are you able to replicate it?

**Comment by jawjadawg** [comment]
Yes, Each time I walk up the hill it crashes.  I've tried sneak in 1st person view and Regular walking in 3rd person view.  I'm using ENB with Rudy.

**Comment by TwistedModding** [comment]
What about on a new save?

**Comment by jawjadawg** [comment]
Two crashes with a new save.  The character at a lower level and with different followers. Crashes still near Reachwind. 
[Crash_2021_3_1_23-1-45.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6066148/Crash_2021_3_1_23-1-45.txt)
[Crash_2021_3_1_23-17-50.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6066149/Crash_2021_3_1_23-17-50.txt)

**Comment by ForgottenGlory** [comment]
Fixed for full release
