### ISSUE TITLE
Jarl Stiddgeir dialogue/quest issue

### ISSUE THREAD

**Issue by Dscot401** [ForgottenGlory/Living-Skyrim-3#194]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
Beta 5

**Describe the bug**
The courier brings me the letter from Jarl Stiddgeir of Falkreath.  I go to him, but he dialogue (it should say something like "I am Sandy, you sent me a letter.." does not advance.   I read the letter, which did put the quest in my journal and he has a quest marker.  I don't know why I am not getting the dialogue. 

**To Reproduce**

**Expected behavior**
He should acknowledge who I am and send me on a quest to kill bandits then make me a Thane
![2021 03 02-03 22](https://user-images.githubusercontent.com/57390279/109620846-5458e980-7b08-11eb-97f7-6015c51f183f.png)
![2021 03 02-03 22_01](https://user-images.githubusercontent.com/57390279/109620867-5ae76100-7b08-11eb-9f90-4f5f513886b3.png)
![2021 03 02-03 22_02](https://user-images.githubusercontent.com/57390279/109620891-620e6f00-7b08-11eb-9cf7-5b455bb500bf.png)
![2021 03 02-03 23](https://user-images.githubusercontent.com/57390279/109620915-689ce680-7b08-11eb-8d34-88a81694f921.png)

 

**Screenshots**

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**

**Comment by ForgottenGlory** [comment]
This seems to be a vanilla bug that can happen very rarely, a known fix is to accept a bounty quest from either the innkeeper or steward in Falkreath and then try again.

**Comment by Dscot401** [comment]
Okay.  Thank you
