### ISSUE TITLE
Floating Hanging Moss, terrain, and Juniper Bush

### ISSUE THREAD

**Issue by ChunkeeMunkee** [ForgottenGlory/Living-Skyrim-3#196]
**LS Version**
Beta 3.0.0.5

**Describe the bug**
2 floating Hanging Moss, a Juniper bush, and 2 terrain assets on the left hand side of the path to Karthwasten approaching from Blind Cliff Cave

**To Reproduce**
Walk the path heading North from Blind Cliff Cave, and look to the left immediately after passing under the dead tree bridge

**Expected behavior**
No floaties :)

**Screenshots**
https://imgur.com/a/Nz96ncS

**Additional context**
Likely a large terrain piece was removed that formerly held all these assets up?

**Comment by ForgottenGlory** [comment]
Fixed for full release
