### ISSUE TITLE
Name mis-spelled on RaceMenu preset

### ISSUE THREAD

**Issue by ChunkeeMunkee** [ForgottenGlory/Living-Skyrim-3#197]
**LS Version**
Beta 3.0.0.5

**Describe the bug**
So, a ridiculously minor one...

Any chance you could correct the spelling of my name on the Ari preset please? 😆 

**To Reproduce**
Check Presets in RaceMenu

**Expected behavior**
Correct spelling is **ChunkeeMunkee**

**Screenshots**
![image](https://user-images.githubusercontent.com/2692881/109732409-077f1c80-7bb5-11eb-8887-69074e6e4c97.png)

**Additional context**
I've also added another preset, a female Orc named Rulga. Not sure if she was added to the Release candidate yet, but if so could you check the spelling there too please? Thanks!

**Comment by celadoneiron** [comment]
There've been a few new presets shared in the channel that could be added along with Rulga. I'm definitely not just saying this because some of them are mine. (I'm only _mostly_ saying this because some of them are mine, lmao.)

**Comment by ForgottenGlory** [comment]
As tempted as I am to leave it just to annoy you, fixed for whatever update is next. ;)
