### ISSUE TITLE
Incorrect Kings Tree LOD.

### ISSUE THREAD

**Issue by xelphos** [ForgottenGlory/Living-Skyrim-3#2]
**LS Version**
LS3 Open Beta 1

**Describe the bug**
Kings Tree gets smaller as you get closer to it.

**To Reproduce**
Walk towards any Kings Tree from a fair distance away.

**Expected behavior**
Should probably remain the same size.

**Screenshots**
https://www.youtube.com/watch?v=gf7FxqUnX5Q
https://i.imgur.com/XryJbF8.png

**Comment by seanpbelcher** [comment]
![enb2021_2_1_07_47_40](https://user-images.githubusercontent.com/67465410/106473571-8889ad80-6469-11eb-856c-2a75682381b2.jpg)

Kings Tree also is depositing a large tree in the middle of the farm storage shack in Rorikstead.

![enb2021_2_1_07_48_05](https://user-images.githubusercontent.com/67465410/106473733-bf5fc380-6469-11eb-8eb0-3d9f6dc55268.jpg)

**Comment by TwistedModding** [comment]
@ForgottenGlory downloading this: https://www.nexusmods.com/Core/Libs/Common/Widgets/DownloadPopUp?id=174287&nmm=1&game_id=1704 should fix the issue. I dont think the lods need to be redone, but it might be the case.

**Comment by TwistedModding** [comment]
Fixed

**Comment by ForgottenGlory** [comment]
Fixed Beta 2
