### ISSUE TITLE
Hedge Armor Set Invisible.

### ISSUE THREAD

**Issue by shiraisenpai** [ForgottenGlory/Living-Skyrim-3#20]
**LS Version**
Open Beta 3.0.0

**Describe the bug**
Missing textures/invisible armor - Hedge Mage Set

**To Reproduce**
Equip the set

**Expected behavior**
Visible Armour

Screenshot
![bug1](https://user-images.githubusercontent.com/62576612/106526766-ee575300-64c4-11eb-8feb-7009d7cc5e98.png)

**Comment by Quietbeat** [comment]
I'm having the same issue; I wrote up a bug recently about invisible body parts w/pictures...can I link my post to this post?

**Comment by ForgottenGlory** [comment]
Duplicate of #6
