### ISSUE TITLE
Examine Dragon Stalking Fix Loose files release

### ISSUE THREAD

**Issue by inire** [ForgottenGlory/Living-Skyrim-3#201]
Examine
Dragon Stalking Fix (Loose Files Update)
https://www.nexusmods.com/skyrimspecialedition/mods/46472?tab=description
as a possible replacement for
Dragon Stalking Fix
https://www.nexusmods.com/skyrimspecialedition/mods/14060

**Comment by TwistedModding** [comment]
+1, i dont see why not.

**Comment by ForgottenGlory** [comment]
I also don't see any reason why to use it, the Dragon Stalking Fix in the list is already ESL flagged so it doesn't take up a load order slot anyway. Unless I'm missing something?

**Comment by TwistedModding** [comment]
Didnt realize it was esld already no need for it then :p
