### ISSUE TITLE
CTD when trying to order certain crafting gear in Whiterun

### ISSUE THREAD

**Issue by Flergin** [ForgottenGlory/Living-Skyrim-3#202]
I was trying to order items through the Whiterun master crafter and it would CTD on certain items. The ones that I tried leading me to CTD were Blackened and Blademaster gear. I tried some standard vanilla armor like banded and that DID NOT lead to crash. I am assuming it has to deal specifically with added modded gear.

[Save13_5505A316_0_5A6872656B_WhiterunWorld_000129_20210303223907_4_1.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6079655/Save13_5505A316_0_5A6872656B_WhiterunWorld_000129_20210303223907_4_1.zip)

**Comment by celadoneiron** [comment]
Unable to replicate, with new saves or the saves provided. People do report experiencing CTDs with Honed Metal on the mod page, but I don't know if the crashes when ordering items are ever consistent rather than occasional and random.

**Comment by Flergin** [comment]
Thanks for looking into it.

Odd you can’t replicate, I just started playing again after this report and it happened again, same items.

I was however able to console command and wear the items, so it seems to be with ordering.

Best,
Christian
