### ISSUE TITLE
Unable to download file during instal

### ISSUE THREAD

**Issue by sofeestar** [ForgottenGlory/Living-Skyrim-3#205]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
3.0

**Describe the bug**
Wabbajack fails to download the Odin - Vokrii Compatibility Patch as there is a new version of the patch as of  3-3-21 and its trying to download an older version, causing the installation to fail.

**To Reproduce**
Attempt to download and install the modlist

**Expected behavior**
The modlist to install

**Screenshots**

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**

**Comment by celadoneiron** [comment]
We know.
