### ISSUE TITLE
Odin - Vokrii compatibility Patch-26176-4-3-0-1614625597

### ISSUE THREAD

**Issue by CrookNoah** [ForgottenGlory/Living-Skyrim-3#206]
**LS Version**
Latest Version 

**Describe the bug**
unable to download Odin - Vokrii compatibility Patch-26176-4-3-0-1614625597 using WABBAJACK Installation Failed

**Screenshots**
https://imgur.com/a/S7kqafY

**Additional context**
Couldn't find the right version to download on nexus.
This is the only error occurring 
Date 03/03/21
11pm est

**Comment by ForgottenGlory** [comment]
We know. I'm going to ban the next person that reports this.

**Comment by CrookNoah** [comment]
My apologies haven't touched skyrim in years sorry
