### ISSUE TITLE
Nudity in LS3 (beta 5)

### ISSUE THREAD

**Issue by Dscot401** [ForgottenGlory/Living-Skyrim-3#207]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
Beta 5

**Describe the bug**
If you advance the Dawngaurd quest line and Serana "marries" you (I think that's Serana Dialogue" mod), you get the dialogue option something like "Are you ready to turn in for the night?" (don't remember the exact wording).  She will strip naked before she lays in the bed.  Just thought I would mention it.  Sorry I didn't catch it before the beta 5 bug reports closed.

**To Reproduce**

**Expected behavior**

**Screenshots**

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**

**Comment by TwistedModding** [comment]
github has a no nudity rule. i removed your picture.

**Comment by Dscot401** [comment]
Oh, sorry

**Comment by lukefly2** [comment]
this is also present for cerri steelfist if that matters

**Comment by ForgottenGlory** [comment]
Should be fixed 3.1.0
