### ISSUE TITLE
Lantern at whiterun gate 

### ISSUE THREAD

**Issue by foxylica** [ForgottenGlory/Living-Skyrim-3#208]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
3.0.0

**Describe the bug**
random lantern
exactly the same problem https://github.com/ForgottenGlory/Living-Skyrim-3/issues/173 

**To Reproduce**
go in front of whiterun gate 

**Save the game --> load the game -->the lantern disappear ,  load the game again --> the lantern appears**

**Expected behavior**

**Screenshots**

![enb2021_3_4_14_08_43](https://user-images.githubusercontent.com/80045161/109966494-00f9bd80-7cf9-11eb-96c1-f51514bad57f.png)

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**
Sorry for the bad english :(

[saves1.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6083852/saves1.zip)

**Comment by BryanBoru** [comment]
same experience for me

**Comment by TwistedModding** [comment]
Fixed, patch in patch channel

**Comment by tjbassoon** [comment]
hmm... this didn't show in my game. Might have been an artifact that was fixed by rerunning dyndolod for the performance guide? Or I just didn't notice LOL

**Comment by ForgottenGlory** [comment]
Fixed 3.1.0
