### ISSUE TITLE
FLoating grass in Darkwater Crossing.

### ISSUE THREAD

**Issue by xelphos** [ForgottenGlory/Living-Skyrim-3#21]
**LS Version**
LS3 Open Beta 1

**Describe the bug**
There is a large patch of grass floating and clipping through things in Darkwater Crossing.

**To Reproduce**
Head over to Darkwater Crossing, cross the bridge and observe.

**Expected behavior**
Shouldn't be floating or even there for the most part.

**Screenshots**
https://www.youtube.com/watch?v=CbGcirL1PgA

**Comment by ForgottenGlory** [comment]
Partially fixed Beta 2, the landscape is correct but there is still floating grass - will be fixed for Beta 3

**Comment by ForgottenGlory** [comment]
Fixed Beta 3
