### ISSUE TITLE
HUD Overlap

### ISSUE THREAD

**Issue by BabehKittehs** [ForgottenGlory/Living-Skyrim-3#210]
**LS Version**
LS 3.0.1

**Describe the bug**
When pressing X to open the Hud for the compass, etc. there is overlap between the compass, date, and time HUD elements.

**To Reproduce**
Press X

**Expected behavior**
No overlap

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**

**Comment by BabehKittehs** [comment]
Somehow the HUD in regards to the compass and the date/time has resolved. X now switches between the two. However, there is also overlap involving the bars during combat and the NPC name.

**Comment by TwistedModding** [comment]
screenshots would be nice

**Comment by JaxomofRuatha** [comment]
I'm going to guess that either the automatic MCM for A Matter of Time didn't run or the README didn't get followed in loading the Less Intrusive HUD menu (the load portion is on the RIGHT of the MCM).

I just did a new save with the MCM instructions followed and looks fine:

![489830_20210313162220_1](https://user-images.githubusercontent.com/69613908/111051428-8deaf800-8418-11eb-9c69-11c0a16da2af.png)

**Comment by JaxomofRuatha** [comment]
![489830_20210313163149_1](https://user-images.githubusercontent.com/69613908/111051585-c5a66f80-8419-11eb-9574-43c05384fb0c.png)

Yep, looks like LIH settings need to have the subtitles moved up a bit, possibly the ammunition element moved further right as well (that seemed pretty far to the left, not sure if it's default but it will probably overlap with dialogue)

**Comment by ForgottenGlory** [comment]
Seems fine for me, this may be somewhat dependent on the resolution of the game. LIH2 lets you tweak the location of HUD Elements, I'd suggest using that if it bothers you.
