### ISSUE TITLE
FOV Bug making Triumvirate spell unusable

### ISSUE THREAD

**Issue by Bossaruuu** [ForgottenGlory/Living-Skyrim-3#212]
**LS Version**
3.0.0

**Describe the bug**
When using the Wildshape spell from Triumvirate, the FOV goes to an absolutely insane value, making the spell nearly unusable.

**To Reproduce**
Cast Wildshape from Triumvirate and start running

**Expected behavior**

**Screenshots**
https://i.gyazo.com/b2e4cc44a64d7d03d0f9b82edfe9a0a6.jpg

**Additional context**
In the screenshot: The little green thing on my crosshair is me in the deer form while running with Wildshape

**Comment by ForgottenGlory** [comment]
I'm open to suggestions on how to fix this

**Comment by ForgottenGlory** [comment]
Will fix when a fix is found

**Comment by celadoneiron** [comment]
This is from the SmoothCam "Modern" preset. My brief testing suggests:

- EasyEaze, Octavian's Preset, Octavian Alt: No jank FOV. The camera starts pretty close to the deer's butt, in varying degrees of proximity. Zooming out works to get to a viewpoint not filled with deer ass.
- Waxx's Preset, Modern Preset: This FOV issue.

I don't know which settings are actually causing it, though.
