### ISSUE TITLE
Two overlapping wooden bar stool in Riverwood Inn

### ISSUE THREAD

**Issue by sebastianmaute** [ForgottenGlory/Living-Skyrim-3#213]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
3.0.1

**Describe the bug**
Two overlapping wooden bar stool in Riverwood Inn right infront of the bar.

**To Reproduce**
Enter the Riverwood Inn.

**Expected behavior**
Only one stool present.

**Screenshots**
[https://imgur.com/a/XKjvP2P](https://imgur.com/a/XKjvP2P)
[https://i.imgur.com/auoFfoW.jpg](https://i.imgur.com/auoFfoW.jpg)

**Additional context**
None

**Comment by TwistedModding** [comment]
Fixed patch in patch channel

**Comment by ForgottenGlory** [comment]
Fixed 3.1.0
