### ISSUE TITLE
Duplicate hide armor recipes at the forge

### ISSUE THREAD

**Issue by sebastianmaute** [ForgottenGlory/Living-Skyrim-3#214]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
3.0.1

**Describe the bug**
Using the blacksmith forge in Whiterun there are duplicate recipes for hide armor (bracers and helmet). One is working and showing up in the inventory. The other can be crafted but will not show up in the inventory. Both can be improved at the workbench. Improving the faulty one does not make it appear in the inventory. They are different as the broken one takes iron ingots in addition and is missing the icon in the workbench as well as having a broken info panel in the forge.

**To Reproduce**
Use the blacksmith forge in Whiterun or possibly any other.

**Expected behavior**
Only one hide armor recipe is available for crafting.

**Screenshots**
Working helmet workbench [https://imgur.com/9yWpg5f](https://imgur.com/9yWpg5f)
Broken helmet workbench [https://imgur.com/LqYZmbD](https://imgur.com/LqYZmbD)
Broken bracers forge [https://imgur.com/qMLLXea](https://imgur.com/qMLLXea)
Broken helmet forge [https://imgur.com/zDCi7O6](https://imgur.com/zDCi7O6)

**Additional context**
None

**Comment by sebastianmaute** [comment]
Gonna add that following armors show up with a broken info panel in the forge as well

- Hunter's Boots
- Hunter's Furs
- Hidden Hood
- All of the Half-Giant armor
- Duplicate of Chronographer Boots
- Athir's Armor

[saves.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6095723/saves.zip)

**Comment by TwistedModding** [comment]
Might be remnants of tmopatcher as well. Redoing with my instructions might help out a bit.

**Comment by ForgottenGlory** [comment]
Will be fixed as part of #200
