### ISSUE TITLE
Unable to pick up Argonian Ale in Bannered Mare Whiterun

### ISSUE THREAD

**Issue by sebastianmaute** [ForgottenGlory/Living-Skyrim-3#215]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
3.0.1

**Describe the bug**
The Argonian Ale is blocked and cannot be interacted with thus making the beggar remain thirsty. Quest category Miscellanous - Steal the Argonian Ale from the Bannered Mare. Using tcl in console to reach will not solve as instead of picking up it works as ACTI to order a meal.

**To Reproduce**
Open the sliding door of the cupboard.

**Expected behavior**
Being able to pick up the ale.

**Screenshots**
[https://imgur.com/WMCIvAN](https://imgur.com/WMCIvAN)

**Additional context**
None

**Comment by lukefly2** [comment]
I was able to pick up the ale by jumping on top of the table next to the cupboard. However, I would agree that it is very difficult and finicky.

**Comment by sebastianmaute** [comment]
Tested again with fresh save to the same effect. Spawns inside the cupboard.

**Comment by celadoneiron** [comment]
The version of JK's Bannered Mare used by the list needs to be updated to version 1.0.2. I tested this version and it resolved the issue for me.

**Comment by ForgottenGlory** [comment]
Fixed 3.1.0
