### ISSUE TITLE
Unlimited power bug?

### ISSUE THREAD

**Issue by ganshunter** [ForgottenGlory/Living-Skyrim-3#216]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
3.0.1

**Describe the bug**
Novice Lighting spell can be used even when magic runs out.

**To Reproduce**
Use the spell in combat? 

**Expected behavior**
When magic runs out not being able to use the spell. Tried a novice calm spell and it worked as intending meaning when not enough magic I was not able to use the spell.

**Screenshots**

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**
Is this a bug, or what?

**Comment by TwistedModding** [comment]
Uhhh this kinda reminds me of a similar issue in ls2. I'm 90% sure that you are regenerating magic fast enough, so the moment you run out, you just keep getting more giving you a seemingly endless amount of magicka. Leaving this open just incase.
