### ISSUE TITLE
Bags of Gold Using Multicolored Texture

### ISSUE THREAD

**Issue by solitudebliss** [ForgottenGlory/Living-Skyrim-3#217]
**LS Version**
3.0.1

**Describe the bug**
Gold sacks that are used as props for a ledger have an odd multicolored texture.

**To Reproduce**
Check the ledger on the table in the Ragged Flagon for reference. Also appears in any loading screen using these.

**Expected behavior**
A texture that is abnormal should appear.

**Screenshots**
![20210306131842_1](https://user-images.githubusercontent.com/79724689/110218551-f3227480-7e7f-11eb-8953-3642ba7a4ba4.jpg)

**Comment by TwistedModding** [comment]
Had this in ls2, and the fix was adding js purses and septims, but that mod is already in the list so im unsure.

**Comment by ForgottenGlory** [comment]
Fixed 3.1.0
