### ISSUE TITLE
Floating white bolt in Winterhold

### ISSUE THREAD

**Issue by epierrej** [ForgottenGlory/Living-Skyrim-3#22]
**LS Version**
3.0.0.1

**Describe the bug**
A floating white bolt near the Winterhold college stairs

**Screenshots**
![image](https://user-images.githubusercontent.com/23179930/106534366-8b13f380-64b9-11eb-8cbd-f6718a5dd184.png)

Savegame:
[Save4_2647F9CE_0_456772696D6D_Tamriel_000102_20210202001629_1_1.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/5907670/Save4_2647F9CE_0_456772696D6D_Tamriel_000102_20210202001629_1_1.zip)

**Comment by seanpbelcher** [comment]
FYI - I wanna say that's from Wheels of Lull. There's a device in that exact spot that the player interacts with in that quest.

**Comment by ForgottenGlory** [comment]
Fixed Beta 2
