### ISSUE TITLE
Hadvar pathfinding broken in Riverwood

### ISSUE THREAD

**Issue by echilda** [ForgottenGlory/Living-Skyrim-3#220]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
3.0.0

**Describe the bug**
When travelling from Helgen cave to Riverwood, Hadvars pathfinding seems to break and he runs through town to the tavern, turns around, runs out of town and repeats, missing the triggered conversation with the Blacksmith. Sometimes he runs out of the town completely.
[saves.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6096225/saves.zip)

**To Reproduce**
Follow Hadvar into Riverwood from Helgen Cave

**Expected behavior**
The scripted conversation where you enter the Blacksmiths home should trigger

**Screenshots**

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**
Seems non game breaking, as you can just manually speak to the Blacksmith and get the next portion of the quest to go to Whiterun

**Comment by ForgottenGlory** [comment]
Considering you can progress the quest by speaking to Sven or the blacksmith, I'm not sure this is worth the time it would take to fix
