### ISSUE TITLE
Wayfarer's coat companion clipping issue

### ISSUE THREAD

**Issue by sebastianmaute** [ForgottenGlory/Living-Skyrim-3#222]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
3.0.1

**Describe the bug**
Equipping the Wayfarer's Coat on NPC companion, tested Inigo and Lucien, makes the upper body disappear.

**To Reproduce**
Equip them with the armor.

**Expected behavior**
Armor is shown.

**Screenshots**
Example Inigo [https://imgur.com/XAcLxYO](https://imgur.com/XAcLxYO)
Example Inigo [https://imgur.com/7FXTQ7j](https://imgur.com/7FXTQ7j)
Console item IDs [https://imgur.com/Bq6sBt5](https://imgur.com/Bq6sBt5)

**Additional context**
[https://www.nexusmods.com/skyrimspecialedition/mods/10194?tab=description](https://www.nexusmods.com/skyrimspecialedition/mods/10194?tab=description)

**Comment by MiloBaj** [comment]
I think that's not a bug but it's only a female armor, if you are a male player character, your body will disappear as well. Happened to me.

**Comment by TwistedModding** [comment]
cool
