### ISSUE TITLE
Missing Safebox underneath Anise's cabin. Unable to obtain ROTW. (LOTD)

### ISSUE THREAD

**Issue by PulsefireEzreal** [ForgottenGlory/Living-Skyrim-3#224]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
3.0.1

**Describe the bug**
Safebox underneath Anise's cabin near riverwood is not there. Therefore unable to obtain Ring Of The Wind for LOTD.

**To Reproduce**
1. go to anise's cabin and go into the cellar underneath.
**Expected behavior**
A safebox. 
**Screenshots**
![image](https://user-images.githubusercontent.com/80222523/110253872-22a1b180-7f52-11eb-95bd-3e970232f694.png)

What it's supposed to look like.
![image](https://user-images.githubusercontent.com/80222523/110254196-bc1d9300-7f53-11eb-862b-d17e1d0e85e1.png)

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**
I have attempted to load an earlier save, but still no safebox.

Save file:

[Anise cabin troubles.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6097931/Anise.cabin.troubles.zip)

**Comment by PulsefireEzreal** [comment]
It does exist as I have just added it to my inventory by console commands, but the safebox its supposed to spawn in does not. At least for me.

**Comment by tjbassoon** [comment]
It seems like there are probably multiple LOTD artifacts that are positioned incorrectly inside certain locations that have been altered. Not sure if this is an LS3 bug or an LOTD bug, but I submitted a similar issue.

**Comment by LTYNS** [comment]
The Tools of Kagrenac has the same ring, and is integrated into LOTD,can you find it in The Arcaneum (College of Wintherhold library)?

**Comment by ForgottenGlory** [comment]
As mentioned, this is now obtained via Tools of Kagrenac in The Arcaneum.
