### ISSUE TITLE
LOTD Item "Golden Knife" inaccessible without tcl

### ISSUE THREAD

**Issue by tjbassoon** [ForgottenGlory/Living-Skyrim-3#226]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
Put the version of the list you are on here. 3.01

**Describe the bug**
Item is outside of normal bounds of the house where I was sent to recover artifact.

**To Reproduce**
Hard to reproduce as you have to get the fetch quest from Auryen, but the object is simply there if you don't have the quest. It's in one of the houses in Shor's Stone

**Expected behavior**
For the knife to be on the table inside the building, within normal bounds.

**Screenshots**

![Screenshot (15)](https://user-images.githubusercontent.com/19911571/110264303-aa051a00-7f7e-11eb-95fb-ef060a5b4040.png)

![Screenshot (16)](https://user-images.githubusercontent.com/19911571/110264309-ac677400-7f7e-11eb-84b6-cf3ee4d964f8.png)
![Screenshot (17)](https://user-images.githubusercontent.com/19911571/110264311-ae313780-7f7e-11eb-8aa7-819cedccd1a0.png)

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**

**Comment by ForgottenGlory** [comment]
Fixed 3.1.0
