### ISSUE TITLE
Add more SmoothCam presets?

### ISSUE THREAD

**Issue by lukefly2** [ForgottenGlory/Living-Skyrim-3#227]
Right now the only SmoothCam preset available is Modern Camera Preset.

Maybe consider adding some of the more popular alternative presets:
EasyEase - https://www.nexusmods.com/skyrimspecialedition/mods/41395
Octavian - https://www.nexusmods.com/skyrimspecialedition/mods/43927
Sepia - https://www.nexusmods.com/skyrimspecialedition/mods/46614
GuitarthVader's Cinematic - https://www.nexusmods.com/skyrimspecialedition/mods/45800
etc

**Comment by TwistedModding** [comment]
I agree, might as well provide more options to users for something that doesn't cause any compatibility issues.

**Comment by ForgottenGlory** [comment]
Added some 3.1.0
