### ISSUE TITLE
Mirai neck gap/seam

### ISSUE THREAD

**Issue by Ivoryspells** [ForgottenGlory/Living-Skyrim-3#228]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
3.0.1

**Describe the bug**
Mirai has a noticeable gap on her neck

**To Reproduce**
Steps to reproduce the behavior: Appears to always be there

**Expected behavior**

**Screenshots**
![Screenshot (2)](https://user-images.githubusercontent.com/80289516/110383278-aa0a2600-8021-11eb-8697-d7dac18dc067.png)

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**

**Comment by ForgottenGlory** [comment]
Should be fixed 3.1.0
