### ISSUE TITLE
Organic Factions Extension Dirty Edits

### ISSUE THREAD

**Issue by shittyusername** [ForgottenGlory/Living-Skyrim-3#229]
**LS Version**
3.0

**Describe the bug**
It seems that there are a number of dirty edits in Organic Factions Extension. I first noticed this from a floating distant cloud static object in the sky that's usually not there. I looked into it in xEdit and notice a very large number of useless edits that add random cliffs and other static objects. Other dirty edits include messing with landscape or doing nothing at all.

**To Reproduce**
Just loading the game with vanilla Living Skyrim.

**Expected behavior**
A life free from dirty edits...

**Screenshots**
![unknown](https://user-images.githubusercontent.com/9057052/110423760-430f6000-8067-11eb-8c4f-044339231dcf.png)
![Screenshot 2021-03-08 233856](https://user-images.githubusercontent.com/9057052/110423863-781bb280-8067-11eb-9715-82fa442971f2.jpg)

**Additional context**

**Comment by shittyusername** [comment]
Might be a good idea to let the mod author know about this as well.

**Comment by TwistedModding** [comment]
Good find! Should be fixed, patch in patch channel for glory.

**Comment by ForgottenGlory** [comment]
Fixed 3.1.0
