### ISSUE TITLE
Altmer/Bosmer beard patchy In character creation.

### ISSUE THREAD

**Issue by itzrabiid** [ForgottenGlory/Living-Skyrim-3#23]
LS Version
LS3 Open Beta 1

Describe the bug
When creating character and choosing the beard it looks patchy/incomplete for both Altmer and Bosmer characters.

To Reproduce
Choose Altmer/Bosmer character and scroll through the beards

Expected behavior
Beard should be complete and not appearing patchy.

Screenshots
![Patchy Beard 1](https://user-images.githubusercontent.com/70617000/106535267-be5a8f00-655a-11eb-8821-8dd9fbe5cac3.png)
![Patchy beard 2](https://user-images.githubusercontent.com/70617000/106535270-c0bce900-655a-11eb-9782-03313c2cc0cb.png)

**Comment by ForgottenGlory** [comment]
Not a bug, known issue with High Poly Head. You'll have to sculpt the head using Racemenu to reduce/remove clipping.
