### ISSUE TITLE
skyrim falskaar weird map bug?

### ISSUE THREAD

**Issue by ganshunter** [ForgottenGlory/Living-Skyrim-3#230]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
3.0.1 I think(latest version)

**Describe the bug**
 falskaar weird map bug? I'll put a picture.

**To Reproduce**
Open the map normally.

**Expected behavior**
A clear and normal map.

**Screenshots**
![image](https://user-images.githubusercontent.com/41804541/110508450-e9f00c80-80f8-11eb-9950-9819f4a71f1a.png)

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**

**Comment by ForgottenGlory** [comment]
Should be fixed by #256
