### ISSUE TITLE
Night/Predator Vision Not Working as Vampire

### ISSUE THREAD

**Issue by Crimthann** [ForgottenGlory/Living-Skyrim-3#231]
**LS Version**
3.0.0

**Describe the bug**
Night Vision and Predator Vision not working as a volkihar vampire. Tried using the power, the spells, and the hotkeys, nothing seems to work. 

**To Reproduce**
Removed the enb I was using (Silent Horizons) to see if that was causing the issue, no change. Ran wabbajack again just to make sure everything as it should be, no change. 

**Expected behavior**
Expected to have night vision or predator vision after pressing the respective hotkeys as a vampire.

[save.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6110858/save.zip)

**Comment by Crimthann** [comment]
I made a khajit, and the night vision worked using the hotkey and the power.

**Comment by TwistedModding** [comment]
Since there isnt an issue anymore im closing this
