### ISSUE TITLE
Falkreath Buildings Clipping

### ISSUE THREAD

**Issue by scotscottscottt** [ForgottenGlory/Living-Skyrim-3#232]
**LS Version**
3.0.1

**Describe the bug**
Falkreath longhouse clipping outside of alchemy shop

**Screenshots**

![enb2021_3_9_21_32_58](https://user-images.githubusercontent.com/72586509/110581614-becce380-811f-11eb-84ee-1bc7f26f7317.jpg)
![enb2021_3_9_21_52_56](https://user-images.githubusercontent.com/72586509/110583080-fe94ca80-8121-11eb-9f29-17eaa1a4af34.jpg)

Happened on three new games when loading into Dead Man's Drink from Abandoned Prison. All readme instructions followed including MCM. No additional options changed. Third attempt after transferring SSE/LS3 to new SSD and running Wabbajack successfully. Widescreen fix and Gamepad ++ enabled in MO2 but quickloot left disabled.

**Comment by lukefly2** [comment]
This does not occur on my install (3.0.0, performance guide)

**Comment by lukedewolf** [comment]
This occurred on my install.

**Comment by Day7-J** [comment]
Updated LS3 as of 20 minutes ago, or so, and this is in fact happening to me now as well

**Comment by ChunkeeMunkee** [comment]
Tested several characters in 3.0.0, both travelling to Falkreath and starting in Dead Man's Drink - no issue.

Tested with two caharcters in 3.0.1 (updated today) in same circumstances - one entering Falkreath, one starting in Dead Man's Drink - issues pictured above were found.

**Comment by lukefly2** [comment]
so I just realized that this issue was already opened 4 days ago https://github.com/ForgottenGlory/Living-Skyrim-3/issues/221

**Comment by ChunkeeMunkee** [comment]
Dagnammit...

Copied my notes over to that ticket

**Comment by TwistedModding** [comment]
Working on this rn

**Comment by TwistedModding** [comment]
Possible fix in patch channel

**Comment by ForgottenGlory** [comment]
Fixed 3.1.0
