### ISSUE TITLE
Hedge Mage Armor missing

### ISSUE THREAD

**Issue by ghost** [ForgottenGlory/Living-Skyrim-3#233]
If possible, please also attach a copy of your most recent save before the issue occurred.**
[save.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6117448/save.zip)

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
3.0.1

**Describe the bug**
When starting a new Game the Hedge Mage Armor is not added to the inventory and the Quest does not start.

**Expected behavior**
Adding of the Armor to Inventory and starting of the quest.

**Screenshots**
![Screenshot (15)](https://user-images.githubusercontent.com/80405893/110663011-5dac1b00-81c6-11eb-8b66-c36da5c66b1f.png)

**Additional context**
The Fortify Hedge Mage Armor Spell and the Journal are added as expected.

**Comment by lukefly2** [comment]
You're meant to add it with console commands. I think you might also be able to craft it.

**Comment by tjbassoon** [comment]
Yes, this is not a bug. Check the pins in the discord channel.

**Comment by Fraktyl** [comment]
The pins disappeared in the Discord channel.  They used to be in #living-skyrim-chatter but are gone.

Recommend adding the instructions to the readme or setting the bot up to spit them out when asked.

**Comment by goli537** [comment]
Thank you for your help.

**Comment by TwistedModding** [comment]
In my opinion, I dont even think we should have this mod if we cant find a way to have it work properly without the use of console commands. Its not very "user friendly" for lack of a better term. I dont really know how to do this, but we might be able to tie the craftable hedge mage armor to a script that activates the hedge mage armor quest.

**Comment by celadoneiron** [comment]
> 
> 
> In my opinion, I dont even think we should have this mod if we cant find a way to have it work properly without the use of console commands. Its not very "user friendly" for lack of a better term. I dont really know how to do this, but we might be able to tie the craftable hedge mage armor to a script that activates the hedge mage armor quest.

I agree. It's also one of the only - if not the actual single only - armour mods that we have that doesn't use CBBE, so there's a body mismatch there, and the male version looks a bit strange because it was definitely designed as female-only. It's a shame because I actually really liked the mod when we used the placed-in-the-world version, I thought it was a nice design and the upgrading was a unique mechanic that I quite enjoyed, but with the body-shape mismatch and the difficulty getting the no-camp version to work I'm not sure it's worth keeping.

**Comment by ForgottenGlory** [comment]
Yeeted 3.1.0
