### ISSUE TITLE
Falkreath Missives Board Empty

### ISSUE THREAD

**Issue by lukedewolf** [ForgottenGlory/Living-Skyrim-3#234]
**LS Version**
3.0.1

**Describe the bug**
The Falkreath Missives board is an empty container. It does not appear to be affected by the usual Missives scripts. 

**To Reproduce**
Go to Falkreath, select the Missives board. 

**Expected behavior**
Expected the board to open with Missives quests after waiting for its script to run and clicking again. 

**Screenshots**
![image](https://user-images.githubusercontent.com/24323272/110670218-641ca180-818a-11eb-964a-afe8112ab466.png)

**Additional context**
Tested this with a running character (new, first time getting to Falkreath and multiple times since), then with a new character on the patron at an inn start in Falkreath.

**Comment by lukefly2** [comment]
are you using quickloot? if i recall correctly, quickloot can break it

**Comment by lukedewolf** [comment]
No, quickloot is off. Never turned on.

**Comment by ForgottenGlory** [comment]
If this is on a relatively new save, it can take a few in-game days to populate the missives boards. Reopen this if they don't.

**Comment by lukedewolf** [comment]
It wasn't on a new save only. I visited multiple times and waited several days at a time in another cell. The board still acted like an empty container and didn't even attempt scripting. Maybe the other fixes for Falkreath will work.

**Comment by lukedewolf** [comment]
Please reopen, this is still not working in 3.1.0. I've tested other boards and they work fine.

**Comment by Fraktyl** [comment]
Just to add to the comment.  I did the following:
- Turned off Quickloot (just in case)
- Turned Novice Mission change to 100%
- Waited for 5 days in game.
- Nothing on Missive board
- coc to Riften - nothing on board there
- Waited one day and missives spawned
- coc back to Falkreath
- No missives, waited another 5 days in game
- Still nothing

Haven't dug into any of the other tools to see if there was a weird conflict, but wanted to add some troubleshooting steps I did

**Comment by tjbassoon** [comment]
Missives boards can take a while to load with things. You sometimes just have to stand in front of it for a while, move your mouse away from it, click on it again, move away, etc. Several times. This happened to me in Solitude on 3.01, and it took quite a while for the board to populate but it eventually did.

**Comment by lukedewolf** [comment]
> 
> 
> Missives boards can take a while to load with things. You sometimes just have to stand in front of it for a while, move your mouse away from it, click on it again, move away, etc. Several times. This happened to me in Solitude on 3.01, and it took quite a while for the board to populate but it eventually did.

That's not what's happening here. The other boards are functioning as you describe, the Falkreath board opens immediately and is empty. It appears to be a regular container and the script to populate the missives doesn't appear to be running. This only affects the Falkreath board as far as I'm aware. This was tested on both 3.0.1 and 3.1.0
