### ISSUE TITLE
CDC in the Reach

### ISSUE THREAD

**Issue by codelbue** [ForgottenGlory/Living-Skyrim-3#235]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
LS v3.0.1.
**Describe the bug**
Trying to do the Legacy of the Dragonborn Quest to get the Jade Warrior. Walking from Markarth towards the Camp and 
always getting a CDC after The bridge. If I run around the longway (I tried it with "player.setav speedmult 500" and "tgm") it doesn´t crash

**To Reproduce**
Walk from Markarth towards the camp where the Jade Warrior is and it crashes.

**Expected behavior**
Game should not crash

**Screenshots**
"Map"
![enb2021_3_10_23_08_57](https://user-images.githubusercontent.com/79068642/110706089-97e1e080-81f7-11eb-866c-752396dd525e.jpg)
"Starting Point"
![enb2021_3_10_23_08_44](https://user-images.githubusercontent.com/79068642/110706123-a62ffc80-81f7-11eb-8fa9-b83faa6cfce8.jpg)
"Crash Point"
![enb2021_3_10_23_09_34](https://user-images.githubusercontent.com/79068642/110706191-c495f800-81f7-11eb-90a4-04eeb178b134.jpg)

**Additional context**
Crashlog:
[Crash_2021_3_10_22-46-6.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6119093/Crash_2021_3_10_22-46-6.txt)

**Comment by TwistedModding** [comment]
can you post more crashlogs?

**Comment by codelbue** [comment]
Sure 
[Crash_2021_3_10_0-10-2.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6119243/Crash_2021_3_10_0-10-2.txt)
[Crash_2021_3_10_0-13-36.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6119245/Crash_2021_3_10_0-13-36.txt)
[Crash_2021_3_10_23-9-38.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6119247/Crash_2021_3_10_23-9-38.txt)
thats all of them if you want more I can crash there a few more times

**Comment by TwistedModding** [comment]
Seems to be related to the forsworn in the area, ill look at this later.

**Comment by TwistedModding** [comment]
Yeah just looked in xedit, nothing seems to be wrong with the forsworn mentioned in the log. I think we can assume updating the extension as cela mentioned would fix this crash.

**Comment by ForgottenGlory** [comment]
I’m more curious what mod adds a Center for Disease Control in the Reach.

**Comment by ForgottenGlory** [comment]
Should be fixed 3.1.0 by #237
