### ISSUE TITLE
Update Organic Factions Extension to v1.05

### ISSUE THREAD

**Issue by celadoneiron** [ForgottenGlory/Living-Skyrim-3#237]
The crashes people have been mentioning in the Discord (occurring when traveling west from Cradle Stone Tower) are due to a fatal navmesh conflict that's been fixed for v1.05. We're currently using 1.043, which makes references to navmeshes that are deleted in Update.esm, causing consistently-replicable CTDs.

I don't know whether it will also help with the crashes from #235.

**Comment by ForgottenGlory** [comment]
Done 3.1.0
