### ISSUE TITLE
Clipping with Morskom Estate's boat to Solitude

### ISSUE THREAD

**Issue by LunaticLooter** [ForgottenGlory/Living-Skyrim-3#239]
**LS Version**
301

**Describe the bug**
Heavy clipping with the land area around Haafinheim, when taking the boat from Morskom to Solitude

**To Reproduce**
Sail to Solitude

**Expected behavior**
Not being on dry land :P

**Screenshots**
![enb2021_3_11_15_44_04](https://user-images.githubusercontent.com/80470810/110805612-8c3afc00-8281-11eb-99fb-f57c0a084b9d.jpg)

**Comment by ForgottenGlory** [comment]
Haafinheim removed 3.1.0, should resolve this
