### ISSUE TITLE
Sven in Riverwood mentions Master Neloth when recruited as a follower.

### ISSUE THREAD

**Issue by xelphos** [ForgottenGlory/Living-Skyrim-3#24]
**LS Version**
LS3 Open Beta 1

**Describe the bug**
When recruiting Sven in riverwood as a follower, he talks about Master Neloth from the Dragonborn DLC.

**To Reproduce**
Head to Riverwood, talk to Sven and do the quest "A Lovely letter", side with Sven. Return to Sven and ask him to follow you.

**Expected behavior**
Shouldn't mention Master Neloth.

**Screenshots**
https://www.youtube.com/watch?v=_YbsnLk4DlI

**Comment by TwistedModding** [comment]
Can you select sven in the console and post the screenshot

**Comment by xelphos** [comment]
> Can you select sven in the console and post the screenshot

Yeah will do after doing a while reinstall again.

**Comment by celadoneiron** [comment]
This is a vanilla bug, and affects many follower NPCs with the voice type MaleYoungEager. If I remember right, the subtitle will usually be for the normal follower lines. But the audio for Talvas Fathryon's recruitment response (FormID 0403A47E, "I suppose Master Neloth won't mind. He's always telling me to get out of his way.") will play instead.

The Unofficial Patch is supposed to fix it; that change may be being overwritten somewhere. (From the patch changelog for UDBP v1.0.2 - (2013-03-18): "A line of generic dialogue used by several followers in the vanilla game (MaleYoungEager voice type) has been restored from the vanilla game after Dragonborn overwrote it with dialogue for Talvas.")

**Comment by ForgottenGlory** [comment]
Looking at this in xEdit, the conditions for that dialogue line are correct (it specifically checks to make sure the speaking NPC is Talvas), so I have no idea how this happened. Definitely open to suggestions for fixes.

**Comment by ForgottenGlory** [comment]
As mentioned before, the conditions are correct in xEdit and this appears to be a vanilla bug with the voices so if someone knows a fix I'm open to including it but until then, can't fix
