### ISSUE TITLE
Download Failed in Wabbajack

### ISSUE THREAD

**Issue by FawnFlower** [ForgottenGlory/Living-Skyrim-3#240]
Download failed twice now in the 9/22 section of the Wabbajack download. 
Unable to download:
LS3 DynDOLOD Output 3.0.0.7z 
LS3 Grass Cache.7z
LS3 SSELODGen Output 3.0.0.7z
Cannot continue was unable to download 1 or more archives. 
I am saving to a Living Skyrim folder located directly in the C drive with 1.48T open memory.
![Screenshot (1)](https://user-images.githubusercontent.com/80484528/110844212-fd68b800-825d-11eb-9e43-aa7f1e098384.png)

**Comment by TwistedModding** [comment]
go to readme common questions. and dont post wabbajack related issues on github, join the discord for help.
