### ISSUE TITLE
Bow blur when aiming and holding right click

### ISSUE THREAD

**Issue by se7enex** [ForgottenGlory/Living-Skyrim-3#241]
https://i.imgur.com/tm4ATIDh.jpg (Normal)
https://i.imgur.com/AYhvVbh.jpg (Right click held down)

Im thinking maybe this is an effect to supplement the zoom perk? Very confusing for it to happen without having the perk, though.

**Comment by lukefly2** [comment]
are you using an enb that would affect this?
