### ISSUE TITLE
Complete Widescreen Fix shows strings for CC Survival Mod stats on equipment

### ISSUE THREAD

**Issue by celadoneiron** [ForgottenGlory/Living-Skyrim-3#242]
**LS Version**
3.0.1.

**Describe the bug**
If using the Complete Widescreen Fix for Vanilla and SkyUI 2.2 and 5.2 SE, equippable clothing items will show $EXPROTLOV and $RAINPROTLC next to the Armor Rating and Carry Weight information in the inventory screen.

**To Reproduce**
Enable the widescreen UI mod and hover over a piece of armour/clothing in the armour section of the inventory screen.

**Expected behavior**
No mention of unsupported survival stats.

**Screenshots**
![Screen Shot 03-12-21 at 03 48 PM](https://user-images.githubusercontent.com/73095714/110898611-464a6a80-834b-11eb-808b-48d465224a9c.PNG)

**Comment by ForgottenGlory** [comment]
Fixed 3.1.0
