### ISSUE TITLE
Out of place bench in Windhelm Inn

### ISSUE THREAD

**Issue by MiloBaj** [ForgottenGlory/Living-Skyrim-3#243]
![Bench-00021374-2D014D07](https://user-images.githubusercontent.com/80553137/111009264-73bb0680-8393-11eb-9644-73362795e954.PNG)

Hi there,

I've entered the Windhelm Inn and to my surprise I saw some NPC's sitting in a rather weird position.
Looking closer at it, I realized it's an out of place bench, right underneath the counter and infront of the regular chairs.

I went ahead and disabled it, but I was adviced to report it here too.

So there it is, thanks for all the hard work!

Kind regards,
Milo

**Comment by TwistedModding** [comment]
Fixed patch in patch channel

**Comment by MiloBaj** [comment]
Awesome, thanks a lot for your hard work people!

**Comment by TwistedModding** [comment]
Leave this open so glory knows about it

**Comment by ForgottenGlory** [comment]
Fixed 3.1.0
