### ISSUE TITLE
Progressing past the wedding mission in Dark Brotherhood quest line causes saves to crash

### ISSUE THREAD

**Issue by Bellmerser** [ForgottenGlory/Living-Skyrim-3#245]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
3.0.1

**Describe the bug**
Any savegame after progressing past the kill the bride mission in the dark brotherhood questline crashes to desktop when trying to load.

**To Reproduce**
Complete the quest and then create a new save after turning in the quest and the saves will crash when loaded. The game continues to run fine as long as any new saves are not loaded.
[crashingsaves.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6134893/crashingsaves.zip)

**Expected behavior**
The save file to load properly.

**Screenshots**

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**
[Crash_2021_3_13_8-37-39.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6134883/Crash_2021_3_13_8-37-39.txt)

[saves.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6134887/saves.zip)

**Comment by Bellmerser** [comment]
I was able to narrow down a more specific point when the crashing begins with some more testing. The saves are stable up until "Breaching security".  If I attempted to fast-travel to Whiterun ahead of the target any save made after that point would crash on loading. If I fast-travel to a location outside Whiterun and then enter the saves are stable unless I enter one of the two interior cells that the target can go to- Dragonsreach or Bannered mare. If I kill the target inside the city itself the next save also becomes unstable and will not load. I have attached a stable quicksave inside Whiterun and the save right after killing the target inside the city that crashes for me.

I also tested waiting a day or two in game and attacking the target at another city which so far has not caused the saves to become unstable.
[Second set of saves.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6135299/Second.set.of.saves.zip)

**Comment by TwistedModding** [comment]
Can you upload more crashlogs? I might have a fix for you.

**Comment by Bellmerser** [comment]
[Crash.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6136000/Crash.zip)
Here are all of the crashes from various related attempts of narrowing this down today. If you need additional please let me know and I can generate more.

**Comment by TwistedModding** [comment]
Yeah so all of these logs are pointing to vc runtime. Disable the mod .NET Script Framework and see if that fixes the issue.

**Comment by Bellmerser** [comment]
No luck disabling .Net script framework. Added the living skyrim folder to windows defender exclusion list and no change either. Still crashing, also checked the folder and confirmed its not generating crashes indicating that the .net script framework doesn't appear to be running.

**Comment by TwistedModding** [comment]
You can reenable .net script framework then. Do you have inigo as a follower?

**Comment by Bellmerser** [comment]
I do not. Followers are currently Taccota, Froa and Dagri'Lon.

**Comment by ForgottenGlory** [comment]
Should be resolved per info in #250 for 3.1.0
