### ISSUE TITLE
Floating bedroll inside door of Ivarstead building

### ISSUE THREAD

**Issue by JaxomofRuatha** [ForgottenGlory/Living-Skyrim-3#248]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
Put the version of the list you are on here.

3.0.1

**Describe the bug**

A bedroll (BaseForm 0003B3C3) is floating and clipped through the door of a building across the river northwest of Ivarstead's main area.

**To Reproduce**

Go to Ivarstead, walk northwest across the bridge, find a building with a bedroll in the door.

**Expected behavior**

No more bedroll

**Screenshots**

![489830_20210313142308_1](https://user-images.githubusercontent.com/69613908/111050831-8d506280-8414-11eb-8b3e-1425af53fb79.png)

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**

The Reference FormID doesn't show up for me in SSEEdit, and the player character is the owner of the bedroll.

**Comment by JaxomofRuatha** [comment]
Tested the new 3DNPC Patch from https://www.nexusmods.com/skyrimspecialedition/mods/36380 (The Great Town of Ivarstead - 3DNPC Patch), issue is fixed! I loaded it after "LS3 Patches Merged", but I think anywhere before Paper Map plugins should work fine.

**Comment by ForgottenGlory** [comment]
Fixed 3.1.0
