### ISSUE TITLE
Pendulum for LOTD unobtainable.

### ISSUE THREAD

**Issue by TwistedModding** [ForgottenGlory/Living-Skyrim-3#249]
Pendulum (for LOTD) from Royal Armory can't be acquired due to LS leveling system. It requires level 70 pickpocket perk and Keeper Carcette is killed at 10 when Dawnguard starts. 
Unless we are intended to kill everyone at the Hall of Vigilant sub-level 10? (from Spagett in the discord) 

This is fixed by the mod in mods fg forgot.

**Comment by ForgottenGlory** [comment]
Fixed 3.1.0
