### ISSUE TITLE
Paper World Map mod isn't showing Whiterun when I have own the Breezeway home

### ISSUE THREAD

**Issue by Quietbeat** [ForgottenGlory/Living-Skyrim-3#25]
**LS Version**
3

**Describe the bug**
I've visited Whiterun but when I view it on the map, there's no marker

**To Reproduce**
Visit WhiteRun then open the map.

**Expected behavior**
The marker for Whiterun is shown.

**Screenshots**
![No Whiterun marker](https://user-images.githubusercontent.com/57841662/106550179-7cccd400-64c7-11eb-9dab-e2f66e64a2c4.png)

**Additional context**
[saves.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/5908504/saves.zip)

**Comment by ForgottenGlory** [comment]
If you start in Whiterun, then leave and start the main quest of the game, the Whiterun marker gets removed until you return to Whiterun. This is how the game handles forcing you to have the interaction with the guard at the gate.
