### ISSUE TITLE
Vampire dark vision does not work

### ISSUE THREAD

**Issue by Lampades** [ForgottenGlory/Living-Skyrim-3#251]
**LS Version**
LS3

**Describe the bug**
While playing as a vampire in a new game, the vampire vision does not work. Also the Predator vision mod which gives you night vision does not work. Buying the Dark Vision spell from this mod does also not work. It will only show a animation with no effect. 

**To Reproduce**
Start new game 
Fix all MCM
Start as vampire
Try and use the vampire night vision ability
Does not work
Run to White Run and buy Dark Vision
Does not work.

**Expected behavior**
That night vision would work. Who would play vampire without it?

**Comment by TwistedModding** [comment]
sounds like an issue with your enb, google how to tweak if for night vision.
