### ISSUE TITLE
Falskaar map icons/locations are floating

### ISSUE THREAD

**Issue by DarkSoulitude** [ForgottenGlory/Living-Skyrim-3#252]
**LS Version**
3.0.1

**Describe the bug**
In Falskaar, the world map is bugged. The location icons on the map (including the player's current location) float above the map as opposed to being stuck in their correct places. This makes navigating Falskaar incredibly difficult.

**To Reproduce**
Go to Falskaar and check the world map. I have tested this on completely fresh runs as well. Have seen other folks in the community having the issue as well.

**Expected behavior**
One would expect the icons to stay in place in their proper locations on the map.

**Screenshots**
I can dig around for a screenshot if requested.

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**
Nothing else to be said as far as I can tell.

**Comment by ForgottenGlory** [comment]
Fixed by #256 for 3.1.0
