### ISSUE TITLE
Left hand casting constantly breaking

### ISSUE THREAD

**Issue by omgitskae** [ForgottenGlory/Living-Skyrim-3#254]
**LS Version**
3.0.1

**Describe the bug**
I am unsure what it causing it, but left hand casting breaks seemingly randomly, may be related to zoning in/out of interiors. When it breaks, my left hand still shows the casting animation and plays the sounds without issue, also temporarily depletes my mana while holding mouse button down. Upon releasing the mouse button, no mana is consumed (goes back to 100%) and no spell is cast.

**To Reproduce**
Unsure

**Expected behavior**
Expect the spell to be cast upon release of mouse button.

**Additional context**
This can be temporarily fixed by reloading the save file (even if the save was after the bug happened), but it comes back within 30 minutes of playing. This is on a completely clean/fresh installation of skyrim (used skyrim shredder to remove every trace of skyrim) and installed via wabbajack. I have seen a couple others having the same issue but it seems to have been dismissed in the past due to not being able to reproduce it. This started within 10 minutes of me starting a brand new character, setting up the MCM, and zoning out of the cave I started in (chose vampire start).

**Comment by ForgottenGlory** [comment]
Do you have enough mana to actually cast the spell? It will deplete as much as it can while holding the spell then refund and cancel casting it if you don't have enough. Reopen this if it persists after checking.

**Comment by omgitskae** [comment]
> Do you have enough mana to actually cast the spell? It will deplete as much as it can while holding the spell then refund and cancel casting it if you don't have enough. Reopen this if it persists after checking.

Yes, this was tested on a new character, choosing magw class and all attributes into mage stats. I could not cast any spell with left hand or dual casted, but the same spells worked fine when cast with right hand.

**Comment by Ajajane** [comment]
I also have this problem randomly as well, I don't always notice it since I'm primarily melee and it isn't until I whip out Gonar's Greed that I realize the issue is happening which fixes on doing a save and load.  I do have enough mana to cast the spell and it will work just like with OP when I swap to the right hand instead, please don't close it yet, what other info do you need from us?

**Comment by omgitskae** [comment]
I'm unsure how to reopen this ticket, but I uninstalled LS3 after being unable to find a solution myself and since it's under maintenance I can't redownload it, but that is my next step. I would love to help you guys track this issue down if you can give me some guidance. Once the modlist is back up I plan to redownload it and see if the issue persists.

**Comment by Ajajane** [comment]
Maybe we'll get lucky and the update will fix it, here's hoping.

**Comment by Kramer42** [comment]
Just had this occur as well (using sparks in the offhand, flame in the main hand, full mana, could both spells in main hand, neither in offhand) save/reload fixed it. I'm something like 10 hours into the game, first time it happened, and thankfully very easy to fix, but figured I'd add that this occurred anyhow.
