### ISSUE TITLE
Toccatta NPC - Mismatched body/hand sizes

### ISSUE THREAD

**Issue by ChunkeeMunkee** [ForgottenGlory/Living-Skyrim-3#255]
**LS Version**
3.0.1

**Describe the bug**
Toccatta appears to have incorrectly scaled hands, leading to visible seams at the wrist and transparency at the break point.

**To Reproduce**
Find Toccatta and check her wrists.

**Expected behavior**
No noticeable size difference or noticeable seam.

**Screenshots**

![enb2021_3_12_22_18_17](https://user-images.githubusercontent.com/2692881/111128923-62c5ed00-856d-11eb-8d07-3f954f6b4d3e.png)
![enb2021_3_12_22_18_25](https://user-images.githubusercontent.com/2692881/111128929-65284700-856d-11eb-8ab9-6efee1cf55c5.png)

**Additional context**
My best guess is that she is using a custom body sizing as she's a unique NPC, but the hands are reverting back to the standard female NPC Bodyslide settings? Is there a .nif that hasn't been included somewhere?

**Comment by ForgottenGlory** [comment]
Should be fixed 3.1.0
