### ISSUE TITLE
Auto-MCM: I'm a Customer "Use Label" option prevents "Eating locations" from working correctly

### ISSUE THREAD

**Issue by celadoneiron** [ForgottenGlory/Living-Skyrim-3#258]
**LS Version**
3.0.1

**Describe the bug**
The "I'm a Customer" MCM is preconfigured so that it should only activate the take/eat menu popup when "At Home," but this setting does not actually apply, and the popup menu will appear in other locations (including dungeons) as well. Disabling the "Use Label" option in the MCM makes the settings apply properly. Trying to update the settings in other ways without disabling "Use Label," such as by changing the Eating Locations setting from "At Home Only" to "Anywhere" and then back to "At Home Only," will not work. The only way to remove the popup is by disabling "Use Label."

**To Reproduce**
The fastest way is to start a new game, and without entering the "I'm a Customer" MCM, choose the "I was shipwrecked off the coast!" start and activate one of the food items in the ship.

**Expected behavior**
The menu should not appear outside of player homes.

**Additional context**
Changing the method to "With Fork Equipped" or "Only When Not Sneaking" also works, but that's because it disables the option to use "Use Label" at all.

**Comment by ForgottenGlory** [comment]
MCMs will be updated 3.1.0 to fix this.
