### ISSUE TITLE
Ebony Knight Armor - First Person Gloves mismatch

### ISSUE THREAD

**Issue by MiloBaj** [ForgottenGlory/Living-Skyrim-3#259]
**LS Version**
3.0.1

**Describe the bug**
The gloves of the armor set Ebony Knight have different textures in first-person.

**To Reproduce**
Equp Gloves, go in first-person mode

**Expected behavior**
Expected to look like in third-person. 

**Screenshots**

![ThirdPerson_Ebony_Knight](https://user-images.githubusercontent.com/80553137/111285837-da654c00-8641-11eb-8cd4-e53c29f12a38.PNG)
![FirstPerson_Ebony_Knight](https://user-images.githubusercontent.com/80553137/111285842-dc2f0f80-8641-11eb-8e39-4d5da4af4c51.PNG)

**Additional context**
This bug was also reported on the nexusmods of NordWarUA's armor mod and someone (Omolad) came up with a fix:
https://imgur.com/a/58XnfGd
It would be nice to include the fix in the next update?

Also, the beards clip horribly through the helmet of this armor, but I don't know if there's a fix for that.

Thanks a lot for your hard work and kind regards!
Milo

**Comment by ForgottenGlory** [comment]
Drop the gloves on the ground, open console, click on the gloves (they'll highlight white), then take a screenshot of that and upload it please

**Comment by MiloBaj** [comment]
Here you go!

![image](https://user-images.githubusercontent.com/80553137/111543015-bf462980-8772-11eb-8620-d2f915d1d86c.png)

**Comment by ForgottenGlory** [comment]
Fixed 3.1.0
