### ISSUE TITLE
Range crosshair shown must of the time

### ISSUE THREAD

**Issue by Quietbeat** [ForgottenGlory/Living-Skyrim-3#26]
**LS Version**
3

**Describe the bug**
Not sure when this happened but I believe when I started using a bow & arrow, the crosshair would show the  '4-point crosshair' all to most of the time (see screenshot). Switching to melee weapons or spells doesn't change the crosshair; Turning Crosshair on or off from the game menu doesn't always have the desired effect..

**To Reproduce**
Unsure but best guess is to equip a bow and arrow.

**Expected behavior**
When the game menu (Settings - Display - Crosshair) is disable then there shouldn't be a crosshair. When enabled then the 'normal' crosshair (a dot) should be displayed.

**Screenshots**
![With Crosshair on or off](https://user-images.githubusercontent.com/57841662/106550401-ec42c380-64c7-11eb-964a-a56dd4459d37.png)
![With Crosshair on or off - Spells](https://user-images.githubusercontent.com/57841662/106550626-552a3b80-64c8-11eb-86e9-1a9832241cdd.png)

**Additional context**
[saves.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/5908528/saves.zip)

**Comment by VyktoryJaye** [comment]
I've also noticed this, but it tends to go underneath my notice half the time. heh

**Comment by ForgottenGlory** [comment]
The crosshair is set to be enabled when you have weapons/spells readied so you can aim.
