### ISSUE TITLE
I can craft Savior's Hide with almost no skills

### ISSUE THREAD

**Issue by tjbassoon** [ForgottenGlory/Living-Skyrim-3#260]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
Put the version of the list you are on here.
3.01

**Describe the bug**
Probably shouldn't be able to craft a unique daedric artifact with 20 smithing and no perks and just leather and iron.

**To Reproduce**

**Expected behavior**

**Screenshots**

![enb2021_3_13_20_11_40](https://user-images.githubusercontent.com/19911571/111378933-87ef5400-8670-11eb-9552-afc3489ed6c8.png)

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**

**Comment by ForgottenGlory** [comment]
Part of #200
