### ISSUE TITLE
"Mead with Juniper Berries" UI tip alignment

### ISSUE THREAD

**Issue by ChunkeeMunkee** [ForgottenGlory/Living-Skyrim-3#261]
**LS Version**
3.0.0 and 3.0.1

**Describe the bug**
The Mead with Juniper Berries bottles in the loft of the Helgen tavern have interaction tips that are bunched together and out of alignment, and the LotD icon has dropped to the bottom of the UI element

**To Reproduce**
Leap from the tower into the roof of the tavern, and look at the items

**Expected behavior**
Spacing between key tip and prompt, corrected alignment

**Screenshots**
![Inkedenb2021_3_17_20_52_47_LI](https://user-images.githubusercontent.com/2692881/111537679-a2eec080-8763-11eb-817e-16dceff5cf8b.jpg)
![enb2021_3_17_20_52_58](https://user-images.githubusercontent.com/2692881/111537707-af731900-8763-11eb-8f06-09de16c3b6df.png)
![enb2021_3_17_20_53_06](https://user-images.githubusercontent.com/2692881/111537732-b6019080-8763-11eb-9320-1f5b3418b050.png)

**Additional context**
A minor one overall, but it's been pointed out to me by a couple of people now

**Comment by ForgottenGlory** [comment]
Uhhh.... no idea on this one. Open to suggestions.

**Comment by celadoneiron** [comment]
![Screen Shot 03-20-21 at 16 22](https://user-images.githubusercontent.com/73095714/111861256-87203000-8998-11eb-9c81-247cfaff7829.PNG)

It's normal in mine. It looks like you're using a controller - what happens if you disable Gamepad++, or use keyboard and mouse exclusively?

**Comment by ChunkeeMunkee** [comment]
A bit more digging later: It appears that this occurs when using gamepad _or_ keyboard and mouse, and also with the Complete Widescreen Fix mod enabled and disabled (Gamepad++ was not active in this attempt nor the original bug report attempt):

![enb2021_3_20_16_08_20](https://user-images.githubusercontent.com/2692881/111876702-d6b22c00-8997-11eb-97c3-b9318d960baf.png)

I can, however, get the interaction label to appear exactly as yours by disabling the "Use Label" option in I'm a Customer, so it looks like that mod is incorrectly formatting the Eat label when applying to this item.

**Comment by ForgottenGlory** [comment]
MCMs will be updated for 3.1.0 to fix this
