### ISSUE TITLE
Cooking pot in JK's Riverside Cottage gives away free meat.

### ISSUE THREAD

**Issue by mysteryblock** [ForgottenGlory/Living-Skyrim-3#264]
The cooking pot in the basement of the building will only allow you to cook the items you have in your inventory, which seems correct. However, none of these items are ever consumed and you can craft all the cooked meat you want for years to come. This also causes the UI to become very laggy and sometimes freezes the game for awhile.

**Comment by ForgottenGlory** [comment]
Use the bug report template
