### ISSUE TITLE
JK's Riverfall Cottage Food Duplication

### ISSUE THREAD

**Issue by mysteryblock** [ForgottenGlory/Living-Skyrim-3#265]
**LS Version**
x3.0.1

**Describe the bug**
Using the cooking pot in the basement of the house, you can craft an unlimited number of foodstuffs if you have the base materials in your inventory. The inventory items are not consumed, but you get the cooked version. I have tried this with many meats, but not with every single recipe. Also, when crafting these foods the UI gets rather laggy, and if you make several at a time the game will often freeze for a bit. 

**To Reproduce**
1. Put items needed for say, cooked beef, in your inventory.
2. Open the cooking pot interface.
3. Select the recepie from the list of ones you can make.
4. Select it for all eternity, as you can have as much meat as you would like.
5. fin.

**Expected behavior**
Ingredients would be consumed when making a recipe using them.

**Comment by ForgottenGlory** [comment]
I believe this is related to the "infinite food at home" part of I'm a Customer, can someone check if turning that option off in the MCM makes this not happen?

**Comment by celadoneiron** [comment]
I am unable to replicate this issue. Cooking at the cooking pot in Riverfall Cottage consumes component items as expected, including specifically raw -> cooked beef, both with the default I'm a Customer MCM settings and even with "Infinite Food" set to "Everywhere" in case the location wasn't being recognised as a home for some reason.
