### ISSUE TITLE
SkyUI Error code on ITEMS menu

### ISSUE THREAD

**Issue by Bellmerser** [ForgottenGlory/Living-Skyrim-3#267]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
3.1.0

**Describe the bug**
Widescreen option enabled
Opening any loot container or the items menu prompts for SKYUI error code and the menu does not display properly.

**To Reproduce**
Open any container or the Items menu.

**Expected behavior**
No SKYUI error message and the menu to display properly on the screen.

**Screenshots**
![enb2021_3_21_17_48_39](https://user-images.githubusercontent.com/80585445/111922119-85c13700-8a6e-11eb-953b-6e20b05d6210.jpg)

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**
All other menus and the map work as expected.

**Comment by ChunkeeMunkee** [comment]
Also just had the same, and also using the Widesreen Fix.

I'll test a new character in case of an MCM setup mistake, and will also try the same with Widesreen Fix disabled.

**Comment by ChunkeeMunkee** [comment]
Addition to the above: I also had QuickLootRE and QuickLoot Retexture installed, but I do not believe this is related.

Tried new save and again had the above problem, saved and restarted the game with Widescreen Fix disabled and the error box did not appear (though inventory interface is of course oversized for the screen as in Bellmerser's image).

Exited and tried re-enabling Widescreen Fix and disabling QuickLoot and QuickLoot Retexture and the error box returned. Also tried creating another new character in this state and again the SkyUI error box appeared.

Issue presents itself on the first instance of opening player inventory and container inventory after a load screen cell change. Problem appears to be between Complete Widescreen Fix and SkyUI - possibly an updated file missing from the former?

**Comment by Raecaug** [comment]
In addition, the Sculpt menu within RaceMenu also exhibits improper scaling in 21:9 with the Widescreen fix enabled, however no error message appears there.

**Comment by ForgottenGlory** [comment]
This can be worked around by turning off SWF Version checking in the SkyUI MCM under Advanced. Will be fixed for the next update.

**Comment by se7enex** [comment]
I also noticed it says "PlayerName" and "PlayerRace" at the bottom of the menu, even the magic menu that is scaled (sort of) properly. These values do not appear with the mod disabled. 
![The Elder Scrolls V  Skyrim Special Edition Screenshot 2021 03 21 - 22 17 47 40](https://user-images.githubusercontent.com/59957381/111933581-2414c300-8a96-11eb-86de-f77306bededc.png)

**Comment by se7enex** [comment]
For the record I found the fix, it would seem the included mod is just out of date, easy enough fix!

"Complete Widescreen Fix for SkyUI 5.2 SE Alpha - 2560x1080" from https://www.nexusmods.com/skyrimspecialedition/mods/1778 resolves the issue entirely. (For me at least, 3440x1440)

**Comment by se7enex** [comment]
As an addendum using that mod in a rule 11 build still has the savegame flicker issue, everything else works perfectly though. May need an additional fix. EDIT: Installing the savegame flicker mod directly under the above mod fixes that issue, as well.

**Comment by StormCloak4Ever** [comment]
> For the record I found the fix, it would seem the included mod is just out of date, easy enough fix!
> 
> "Complete Widescreen Fix for SkyUI 5.2 SE Alpha - 2560x1080" from https://www.nexusmods.com/skyrimspecialedition/mods/1778 resolves the issue entirely. (For me at least, 3440x1440)

How did you apply the updated widescreen fix to the load order to get it working correctly?

**Comment by TwistedModding** [comment]
go to community additions in he discord @StormCloak4Ever

**Comment by StormCloak4Ever** [comment]
I fixed the problem. Literally did exactly what you suggested: downloaded the mod you linked, opened it with MO2,  applied it to the Living Skyrim 3 mod list, and it solved the problem. SKYUI and the rest of the game is working 100% in beautiful 3440x1440.

**Comment by ForgottenGlory** [comment]
Fixed 3.1.1
