### ISSUE TITLE
Patch files: Some races reverted to previous version of Aetherius, including unresolvable reference errors

### ISSUE THREAD

**Issue by celadoneiron** [ForgottenGlory/Living-Skyrim-3#268]
**LS Version**
3.1.0.

**Describe the bug**
LS3 Patches Merged.esp's versions of RaceArgonian, RaceArgonianVampire, and RaceKhajiit are referencing records that no longer exist in the list. They look like records from the old version of Aetherius that are no longer used and have been deleted. The file within the merge that makes these changes looks to be LS3 Faces Merged Patch.esp.

The in-game consequence of this is that Argonians don't seem to have an actual Resist Disease effect active when looking through the list of active effects in console, although the written description of the effect that appears in the active effects tab of the magic menu says they should. Something similar would be happening with Khajiit not getting the effects they should have.

Additonally, the total number of skill points that races get from their skill boosts is unequal, as some races are having their updated records from the new Aetherius overwritten by patches for older versions too.

Bretons, Nords, Imperials, Redguards, Dark Elves, and High Elves get more points from skill boosts than Argonians, Khajiit, Orcs, and Wood Elves. The former get 4 x +10 and 1 x +15 bonus points from skill boosts, whereas the latter get 4 x +5 and 1 x +10.

**To Reproduce**
1. Start a new game as an Argonian.
2. Open the console and select the player character, and navigate through the "Effects" list to see that no Resist Disease effect is applied.

**Expected behavior**
The changes from the current version of Aetherius should be applied. The total number of additional skill points provided by racial skill bonuses should be equal across races.

**Screenshots**

![Screen Shot 03-22-21 at 15 18](https://user-images.githubusercontent.com/73095714/111945328-4144a280-8b25-11eb-8d59-97c619aca368.PNG)

**Additional context**
Trying to copy the race records that contain no-longer-extant references into a new file as overrides to simply make another patch that can be layered on top doesn't work - all the fields are empty. They'll have to be edited directly/rebuilt as appropriate.

**Comment by celadoneiron** [comment]
I've shared a patch in the dev patch channel that should resolve this and also the vampire face explosion issue (by removing the "overlay head part list" flag on vampire races so that characters with HPH sculpts don't get deformed faces when becoming vampires).

**Comment by ForgottenGlory** [comment]
Fixed 3.1.1
