### ISSUE TITLE
Sparks has no casting sound effect

### ISSUE THREAD

**Issue by Zurg12345** [ForgottenGlory/Living-Skyrim-3#269]
**LS Version**
3.1.0

**Describe the bug**
The spell "sparks" only has the passive crackling sound effect when i have it equipped but it doesn't have any sound effect when casting.

**To Reproduce**
Create a new high elf character, choose the mage class and birthsign which give magicka and then cast the sparks spell.
**Expected behavior**
The spell doesn't have any casting sound effects.

**Comment by celadoneiron** [comment]
I'm unable to replicate this issue. Is it only with Sparks and no other spells? Does it persist across different new characters?

**Comment by Zurg12345** [comment]
It happened with the spell flames too but i tried with healing, candlelight and lightning rune spells and they all worked. It happened with my first character then i created a new character and still no casting sound effect. i just did a fresh install of skyrim and living skyrim and it stil happened. only thing that that comes to mind that could cause it is if my download somehow broke some mod because i first tried to download the mod right before it went under maintenance before the newest update and wabbajack couldn't complete the download and then when the new update came out i just continued the download. i'll try to do a completely fresh download of living skyrim tonight to see if it fixes it.

**Comment by Zurg12345** [comment]
I did a completely fresh install of skyrim (used skyrim shredder) and living skyrim, created a new character and still no sound. I don't know if this can affect the issue but during the download wabbajack got an error downloding RUSTIC RELIEF, Soul Cairn 4K, Embers XD and Sovngarde HD but after restarting wabbajack it downloaded them.

**Comment by ForgottenGlory** [comment]
This issue stems from a failed install, it sounds like. Visit the FG's Modlists Discord server for assistance with installing the list.
