### ISSUE TITLE
Clipping and floating objects in Ivarstead

### ISSUE THREAD

**Issue by Schnipserle** [ForgottenGlory/Living-Skyrim-3#271]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
3.1.0

**Describe the bug**
Overlapping structures and buildings, floating objects, trees going through houses in Ivarstead caused by a conlict between JK's Skyrim and The Great Town of Ivarstead.

**To Reproduce**
Go to Ivarstead 

**Expected behavior**

**Screenshots**

![SkyrimSE 2021-03-23 19-48-28](https://user-images.githubusercontent.com/67802820/112202784-12f0c100-8c12-11eb-810e-a093b8c77e62.png)
![SkyrimSE 2021-03-23 19-45-59](https://user-images.githubusercontent.com/67802820/112202800-171cde80-8c12-11eb-92a2-0e8238a5506f.png)
![SkyrimSE 2021-03-23 19-46-06](https://user-images.githubusercontent.com/67802820/112202815-1be19280-8c12-11eb-8e6c-975a266d0e26.png)
![SkyrimSE 2021-03-23 19-46-15](https://user-images.githubusercontent.com/67802820/112202832-213edd00-8c12-11eb-9a5f-646d16aeed8b.png)
![SkyrimSE 2021-03-23 19-47-16](https://user-images.githubusercontent.com/67802820/112202853-256afa80-8c12-11eb-90f6-00e8eba3ba2a.png)
![SkyrimSE 2021-03-23 19-47-29](https://user-images.githubusercontent.com/67802820/112202866-29971800-8c12-11eb-8faa-d07ec33e376a.png)

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**

Try "The Great Town of Ivarstead Patch Collection" with JK's module https://www.nexusmods.com/skyrimspecialedition/mods/36380
Haven't tested it yet.

**Comment by Schnipserle** [comment]
Looks much better with The Great Town of Ivarstead Patch Collection and these 2 patches

![grafik](https://user-images.githubusercontent.com/67802820/112204486-00778700-8c14-11eb-924c-939937dd3319.png)

![SkyrimSE 2021-03-23 20-12-13](https://user-images.githubusercontent.com/67802820/112204545-1422ed80-8c14-11eb-991e-d9fce09e7949.png)

**Comment by se7enex** [comment]
For what it's worth there is also clipping vegetation under Solstheim, it's literally floating in the air by about 5 or so feet and really stands out, unfortunately.

**Comment by ForgottenGlory** [comment]
Fixed 3.2.0
