### ISSUE TITLE
Children with smooth glowing hair

### ISSUE THREAD

**Issue by celadoneiron** [ForgottenGlory/Living-Skyrim-3#272]
**LS Version**
3.1.0.

**Describe the bug**
Children who use one specific hair mesh have perfectly smooth, very shiny hair that reflects light, because of a problem with the mesh/textures. Affected NPCs include Leonia Auria and Henrietta Entius, though I think it's used by some others as well that I haven't seen in-game yet.

**To Reproduce**
Use the console to spawn Leonia Auria with
player.placeatme b2002e7

**Expected behavior**
Hair should look like hair.

**Screenshots**
![Screen Shot 03-24-21 at 21 34](https://user-images.githubusercontent.com/73095714/112402064-90721980-8d57-11eb-9736-bfb1d8510827.PNG)
![Screen Shot 03-24-21 at 21 34 001](https://user-images.githubusercontent.com/73095714/112402085-95cf6400-8d57-11eb-9384-bed22e3b7ac5.PNG)
(The console highlight effect makes the problem invisible, but it's still there.)

**Additional context**
The mod [RS Children Overhaul Patch Compendium - Shiny hair texture fix](https://www.nexusmods.com/skyrimspecialedition/mods/38091?tab=description) will fix the shiny hair texture (as one might guess).

**Comment by ChunkeeMunkee** [comment]
Apologies if this is one of the two mentioned NPCs, but I believe the young girl resident in Left Hand Mine outside Markarth may also have this issue

**Comment by ForgottenGlory** [comment]
Fixed 3.1.1
