### ISSUE TITLE
LoTD icon no longer showing on gear/special items.

### ISSUE THREAD

**Issue by Ashensakar** [ForgottenGlory/Living-Skyrim-3#273]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
3.1.0

**Describe the bug**
LoTD icon no longer appearing on gear.
**To Reproduce**
no idea
**Expected behavior**
LOTD icons to appear on gear/special items
**Screenshots**
![Screenshot 2021-03-25 164954](https://user-images.githubusercontent.com/68168803/112511246-27f06000-8d8a-11eb-838b-d43881cb408a.png)

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**
[skyrim save.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6206419/skyrim.save.zip)

**Comment by ForgottenGlory** [comment]
Fixed 3.2.0
