### ISSUE TITLE
Black Face bug in LS3.

### ISSUE THREAD

**Issue by JJGWhite** [ForgottenGlory/Living-Skyrim-3#274]
**LS Version**
Living Skyrim 3

**Describe the bug**
A black face bug on several NPCs around Skyrim. The ones I've found so far are Commander Caius, Uthgerd the Unbroken, Addvar, Idolaf Battle-Born and Sinmir (the guy who always complains about Whiterun's security). I also think maybe Balgruuf's housecarl, but she's a Dunmer so I can't be sure. Screenshots included only show Addvar, as I've just started a new character after a fresh install and this is as far as I've gotten.

**To Reproduce**
Steps to reproduce the behavior: Start a new game and go to Solitude. Addvar has a black face. Go to Whiterun. The NPCs mentioned that live there also have black faces.

**Expected behavior**
For there to be no black face bug.

**Screenshots**

![20210325224113_1](https://user-images.githubusercontent.com/81240023/112552820-55a1cd00-8dbb-11eb-8a8f-4309c7bf8e62.jpg)

![20210325224123_1](https://user-images.githubusercontent.com/81240023/112552840-5cc8db00-8dbb-11eb-8405-64c5b02f3bdd.jpg)

**Additional context**
Apparently this isn't supposed to happen in LS3. I don't really know what else to say beyond I haven't modified the modlist in any way whatsoever. No additions, no moving files around. Nothing.

**Comment by ForgottenGlory** [comment]
Something is wrong with your load order, re-run the Wabbajack installer to reset it to defaults.

![ScreenShot213](https://user-images.githubusercontent.com/25124348/112553646-4448c880-8d9b-11eb-877a-2f8b78b66391.png)
![ScreenShot214](https://user-images.githubusercontent.com/25124348/112553652-47dc4f80-8d9b-11eb-952e-892c1f66c8b1.png)

**Comment by JJGWhite** [comment]
Cheers.
