### ISSUE TITLE
Crouching freezes character in place

### ISSUE THREAD

**Issue by TheShadyFlame** [ForgottenGlory/Living-Skyrim-3#275]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
3.1.0

**Describe the bug**
From new character creation, crouching freezes char in place

**To Reproduce**
Crouching after loading past life another life

**Expected behavior**
Be able to sneak instead

**Screenshots**

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**

**Comment by TwistedModding** [comment]
read the common issues section of the readme
