### ISSUE TITLE
Winterhold Return to Ship and Entrance to The Scarlett without obtaining The Scarlett

### ISSUE THREAD

**Issue by TheCadinal** [ForgottenGlory/Living-Skyrim-3#276]
**LS Version**
v3.1.0

**Describe the bug**
Near the Winterhold Docks, the is an entrance to "Return to Ship" but I have not unlocked the Scarlett. When returning to the Ship I am warped in the Ocean, Near this location, there is another entrance to The Scarlett which warps me to the original Location of the Scarlett. 

**To Reproduce**
Go to the Winterhold Docks and activate the Entrance "Return to Ship" without unlocking the Scarlett.

**Expected behavior**
There should be no Entrance to the Scarlett.

**Screenshots**

![Return to Ship](https://user-images.githubusercontent.com/79724122/112714330-2df55680-8eda-11eb-9167-e5b54f89214c.jpg)

![Warp Location](https://user-images.githubusercontent.com/79724122/112714331-3188dd80-8eda-11eb-9f34-92ebe4376b5d.jpg)

![Open The Scarlett](https://user-images.githubusercontent.com/79724122/112714332-3483ce00-8eda-11eb-80e6-5b21b4eafffb.jpg)

**Additional context**

**Comment by ForgottenGlory** [comment]
Please take a screenshot with the objects in question selected in console so I can identify them and look into a fix.

**Comment by TheCadinal** [comment]
![enb2021_5_1_16_56_12](https://user-images.githubusercontent.com/79724122/116786438-e21c6b00-aa9e-11eb-8014-333e364922ce.jpg)

I have since unlocked the Scarlett and the boat is clipping with new additions in Solstein and Dawnstar. Do I have to open another Issue?

![enb2021_4_17_14_26_09](https://user-images.githubusercontent.com/79724122/116786451-ecd70000-aa9e-11eb-8943-9cf013a35996.jpg)

![enb2021_4_17_14_26_05](https://user-images.githubusercontent.com/79724122/116786453-ef395a00-aa9e-11eb-8d8a-0655b47dbac0.jpg)
