### ISSUE TITLE
Skyrim's Unique Treasures MCM automation not working

### ISSUE THREAD

**Issue by celadoneiron** [ForgottenGlory/Living-Skyrim-3#277]
**LS Version**
3.1.0.

**Describe the bug**
Skyrim's Unique Treasures is set to enable "Lore-friendly items only" by default, but this setting does not actually apply unless you deselect and reselect it.

**To Reproduce**
1. Start a new game and choose to spawn in the Dead Man's Drink in Falkreath.
2. Go behind the bar to see an "Elder Scrolls Plate : Oblivion" plate.
3. Go into the MCM for Skyrim's Unique Treasures, disable "Lore-friendly items only," re-enable it, and exit the MCM.
4. The plate has disappeared.

**Expected behavior**
The "Lore-friendly items only" setting should apply from the jump.

**Screenshots**
![Screen Shot 03-27-21 at 21 16](https://user-images.githubusercontent.com/73095714/112718909-b1965e00-8f41-11eb-8496-303581883b9b.PNG)

**Comment by ForgottenGlory** [comment]
Should be fixed 3.2.0
