### ISSUE TITLE
Able to freely take half of the shop items in Warmaiden

### ISSUE THREAD

**Issue by Toverrijst** [ForgottenGlory/Living-Skyrim-3#278]
**LS Version**
downloaded 25-03-2021

**Describe the bug**
I can freely take half of the shop items in the Warmaiden's in Whiterun. I tested this with the female owner's relationship at both 0 and 1. These appear to be items added by the mod "JK's Warmaiden's", located on stands, in front of the clerk's desk, and on the first floor. Items that have a base defined in Skyrim.esm show the 'Barter' prompt. Other non-shop items such as the mead on the back table show the 'Steal' prompt.

**To Reproduce**
Nothing but I delivered the Jarl's sword for the owner.

**Expected behavior**
Show 'Barter' prompt, or show 'Steal' prompt.

**Screenshots**
https://i.imgur.com/i59Ko9U.jpg
https://i.imgur.com/KKmLqb2.jpg
https://i.imgur.com/mghE3Wx.jpg
https://i.imgur.com/ekPEdId.jpg

**Comment by ForgottenGlory** [comment]
Fixed 3.2.0
