### ISSUE TITLE
Moving Ship with clipping items. North from Septimus Sigmus Outpost.

### ISSUE THREAD

**Issue by TheCadinal** [ForgottenGlory/Living-Skyrim-3#279]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
v3.1.0

**Describe the bug**
The Ship is moving and the miscellaneous Items are static. 

**To Reproduce**
Go to the Ship near the Lunar Passage north from Septimus Signus Outpost.

**Expected behavior**
Static Items should not be clipping with the moving Ship

**Screenshots**

![enb2021_3_27_16_36_44](https://user-images.githubusercontent.com/79724122/112726159-4b4b1480-8f1c-11eb-86b5-ebc933e2aecd.jpg)

![enb2021_3_27_16_36_50](https://user-images.githubusercontent.com/79724122/112726166-4dad6e80-8f1c-11eb-90f4-a149f976a23d.jpg)

![enb2021_3_27_16_36_58](https://user-images.githubusercontent.com/79724122/112726169-4f773200-8f1c-11eb-9bdf-0df9921b47ad.jpg)

**Additional context**

**Comment by ForgottenGlory** [comment]
Fixed 3.2.0
