### ISSUE TITLE
Unable able to cast using my left hand

### ISSUE THREAD

**Issue by Quietbeat** [ForgottenGlory/Living-Skyrim-3#28]
**LS Version**
3

**Describe the bug**
I was able to use my left hand to cast several 'hours' ago but now I can't. I haven't configured any 'magic' mods. For skills I have Destruction Mastery and Destruction Dual Casting. 

[UPDATE on 2/2/21] What's interesting is that for some time since the initial post, I could use the left hand but now when I tried to dual cast, I'm back to not being able to use it.

[UPDATE 2/3/21] since I had many issue with the current save game, I loaded an earlier save and now I can cast with my left hand. I'm attaching the save file.

**To Reproduce**
With my left hand extended, when I press the Left mouse button (to use the avatar's left hand), he flinches for a second. The right hand works fine.

**Expected behavior**
I can cast with my left hand.

**Screenshots**
N/A

**Additional context**
The first save is when I initially created the post and the second is more recent.

[saves.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/5908740/saves.zip)
[saves.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/5916409/saves.zip)
[saves.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/5923097/saves.zip)

**Comment by daffodilian** [comment]
I can't replicate this. Have you tried with another mouse if possible? I'd say it's possible that the mouse click is not holding

**Comment by ForgottenGlory** [comment]
I too am unable to replicate this - you need to click both mouse buttons simultaneously to dualcast.
