### ISSUE TITLE
Two flowers on the same spot

### ISSUE THREAD

**Issue by Toverrijst** [ForgottenGlory/Living-Skyrim-3#280]
**LS Version**
downloaded 25-03-2021

**Describe the bug**
Gleamblossom and Nightshade are growing on the exact same spot in Whiterun next to the Talos shrine on both sides. Same problem with Dragon's Tongue and Nightshade in front of Arcadia's in Whiterun.

**Expected behavior**
Should be only one flower at that spot.

**Screenshots**
_I already picked the flowers before, so the Nightshade model is not completely white when selected:_
https://i.imgur.com/mcoIFCB.jpg
https://i.imgur.com/OU85pUf.jpg

**Comment by ForgottenGlory** [comment]
No
