### ISSUE TITLE
Companions get stuck on their "horses"

### ISSUE THREAD

**Issue by se7enex** [ForgottenGlory/Living-Skyrim-3#281]
Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
3.1

**Describe the bug**
When you get on your horse NFF spawns a horse for your companion/s, sometimes when you dismount (whether its quick or slow) the horse companion dissapears as intended however the companion is still "on" the horse and doesn't get off. It is a repeatable, sporadic issue. Usually getting back on your own horse and jumping off a few times gets the companion to right themselves.

**To Reproduce**
Get on your horse with a companion in tow that has a horse spawn for them, ride for a bit then get off your horse. The issue is sporadic in nature but repeatable. 

**Expected behavior**
Companion gets off their horse

**Screenshots**
![The Elder Scrolls V  Skyrim Special Edition Screenshot 2021 03 27 - 13 27 03 73](https://user-images.githubusercontent.com/59957381/112729032-84758b80-8f00-11eb-9bbf-fc656ce97e90.png)

**Comment by OverarchUpwardNullify** [comment]
In regards to this shouldn't NFF horses be disabled in the mcm and let  Convenient Horses handle this. Wouldn't this create a race condition between NFF and Convenient Horses for which package to use for follower horses, i'm assuming NFF would surpass other mods packages, but this should probably be disabled in the mcm.
