### ISSUE TITLE
Vegetation between Solitude Docks and Sawmill is floating

### ISSUE THREAD

**Issue by se7enex** [ForgottenGlory/Living-Skyrim-3#282]
Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
3.1

**Describe the bug**
Vegetation between the Solitude Docks and Sawmill near the coast is floating several feet into the ground then continues to "float" through the water

**To Reproduce**
Steps to reproduce the behavior: go there and look at it

**Expected behavior**
vegetation to be removed or not floating

**Screenshots**

![The Elder Scrolls V  Skyrim Special Edition Screenshot 2021 03 27 - 13 40 11 43](https://user-images.githubusercontent.com/59957381/112729402-48dbc100-8f02-11eb-9deb-83cc603250ab.png)

**Comment by se7enex** [comment]
https://imgur.com/a/bFjrdDD

**Comment by ForgottenGlory** [comment]
Fixed 3.2.0
