### ISSUE TITLE
Occasional headless, naked bandit

### ISSUE THREAD

**Issue by se7enex** [ForgottenGlory/Living-Skyrim-3#283]
Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
3.1

**Describe the bug**
Occasionally a headless, naked bandit will spawn with other (working) bandit groups. 

**To Reproduce**
Go bandit hunting, I suppose. (Happens in interiors more often it would seem)

**Expected behavior**
For all bandits to be clothed and have their heads

**Screenshots**

https://imgur.com/a/gYUaauC

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

https://imgur.com/a/WxO2gzL

**Comment by ChunkeeMunkee** [comment]
I have also witnessed this in a previous LS version inside Embershard Mine, and it's also in one of Squelchy's Let's Play videos outside Silent Moons Camp, timestamped below (I believe is using 3.1.0):

https://youtu.be/YdrUhiZz14I?t=754

**Comment by chkmcngt** [comment]
![ScreenShot220](https://user-images.githubusercontent.com/73603652/113026285-dd287b00-91c3-11eb-8f9d-43673ddea04d.png)
![ScreenShot221](https://user-images.githubusercontent.com/73603652/113026293-def23e80-91c3-11eb-908a-6f188505146c.png)

**Comment by chkmcngt** [comment]
hope this helps narrowing down the issue

**Comment by ForgottenGlory** [comment]
Unsure of cause or fix, open to suggestions

**Comment by DustyLeon** [comment]
![SkyrimSE 2021-05-17 06-21-13](https://user-images.githubusercontent.com/83781072/118475493-516a9f80-b6da-11eb-8857-a115d21779fe.png)
![SkyrimSE 2021-05-17 06-31-30](https://user-images.githubusercontent.com/83781072/118475518-59c2da80-b6da-11eb-8063-0ff612767cb5.png)
[Headless Save.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6493226/Headless.Save.zip)

**Comment by ForgottenGlory** [comment]
Possibly fixed 3.2.1
