### ISSUE TITLE
Floating Grass near Solitude Sawmill

### ISSUE THREAD

**Issue by TheCadinal** [ForgottenGlory/Living-Skyrim-3#284]
**LS Version**
v3.1.0

**Describe the bug**
Floating Grass between Solitude Docks and Solitude Sawmill.

**To Reproduce**
Go to the Solitude Docks and walk to the Sawmill.

**Expected behavior**
There should be no Floating Grass.

**Screenshots**

![enb2021_3_28_15_55_29](https://user-images.githubusercontent.com/79724122/112754921-ae04e480-8fde-11eb-9a4c-e39d11099341.jpg)

![enb2021_3_28_15_55_49](https://user-images.githubusercontent.com/79724122/112754924-b0673e80-8fde-11eb-968b-5e84e8495c76.jpg)

**Additional context**

**Comment by se7enex** [comment]
Already posted here https://github.com/ForgottenGlory/Living-Skyrim-3/issues/282

Please review the issues section before posting, thank you!

(Corrected title because of this post so, thanks for that lol)
