### ISSUE TITLE
Weird mesh issues with "Wanderer's Coat"

### ISSUE THREAD

**Issue by Barachiel2285** [ForgottenGlory/Living-Skyrim-3#285]
**LS Version**
3.1.0

**Describe the bug**
The crafted armor "Wayfarer's Coat" has some weird mesh issues on both male and female.  On the male, it renders the main body invisible (head, hands and feet are fine), as though it doesn't have a male mesh.  It should, as I've used this coat before.  On the female, it has a pair of panties sticking noticably out the back.  To make it funnier, the panties are empty (ie no body inside them).  

**To Reproduce**
Just craft the armor and put it on.  

**Expected behavior**
For the coat to appear on males, and to be no clipping floating panties on the females.  

**Screenshots**
https://imgur.com/a/iArcdwP

**Comment by ForgottenGlory** [comment]
This part of issue #270
