### ISSUE TITLE
Vokrii Incompatibility with Spell Tutor; +30% Chances for Apprentice+ Perks Not Counting

### ISSUE THREAD

**Issue by Eurafrica** [ForgottenGlory/Living-Skyrim-3#287]
**LS Version**
3.1.0

**Describe the bug**
Based on my personal experience and a wealth of feedback from LS3 Discord, Spell Tutor doesn't appear to be getting the proper +30% chance from perk bonuses for Apprentice-and-above-difficulty spells. Even when playing a high magic affinity race and start, spells of that difficulty and above are difficult to learn and result in loss of many tomes on standard MCM settings. **Celadoneiron*** did mention they were going to look into which spell ID's corresponded with the old version of Apprentice -> Adept, etc. perks, but it doesn't appear to work that way in Vokrii sadly. 

I opened xEdit to look, and it appears that Vokrii has moved the Apprentice, Adept, Expert, Master <Spell School> perks into the <Spell School> Mastery perk at the beginning of Vokrii's perk trees. That perk reduces the cost of spells of those difficulty each time you hit the 25, 50, 75, 100 breakpoints, but because they are all the perks Spell Tutor previously checked for separately, I don't believe they are being counted for +30% each difficulty respectively. 

**To Reproduce**
Play the game, fill out your magic perk trees and skill up to 25+ and try learning Apprentice+ tomes. The chance should be around 50-60% with perk bonuses and Magicka bonuses. Feels closer to the base amount of 5-10% (depending on Magicka pool).

**Expected behavior**
Ideally, hitting skill-level 25 while having Destruction Mastery should "activate" the check that Spell Tutor does, and satisfy the +30% bonus for having the Apprentice Destruction Magic perk, who's ID and effect is now contained within Destruction Mastery.

**Screenshots**
![Vokrii Magic Perks](https://user-images.githubusercontent.com/79347243/112901226-78313000-90b2-11eb-90fd-38db50002add.png)

Is an example of the perk structure from Vokrii and how all of the old vanilla "mastery" perks are tied into the one starter perk now.

**Additional context**
Potential solutions would either include getting Spell Tutor to check the one perk and your level of progress in it, and apply the appropriate bonus according to level, or move the perk ID's that Spell Tutor checks and assign them to a different perk in each tree. I think getting the former to work would be a good solution, as when the mod is working properly, it really balances magic well (when trying to learn Novice spells for example, properly punishes you for having low Magicka or no perks). Conversely, forcing you to spend more points in the tree to learn higher difficulty spells feels more "difficulty appropriate", and better simulates progressing as a mage. Dropping one point in each tree and moving on isn't very aspiring mage'ish...

I.e. change:
Mercy Perk: Restoration spells are up to 50% more effective if the recipient's remaining Health is low." 
to
Restoration spells are up to 50% more effective if the recipient's remaining Health is low. Apprentice level spells are easier to learn"

**Comment by celadoneiron** [comment]
Spell Tutor now has a patch for Vokrii included in its Optional Files section, "Perk condition for Vokrii," which should resolve this issue if included in the next release. In the meantime, you can adjust the difficulty values and other settings in the Spell Tutor MCM to compensate.

(It was me who was looking at the perk associations, not Twisted.)

**Comment by Eurafrica** [comment]
From Spell Tutor page Optional Tab for those that want to see how it will work:

"Use this addon if you want Perk condition from Spell Tutor with Vokri mastery perks.

Requires mastery perk + skill (since it uses only one mastery perk)
Skill 0/25/50/75/100 - novice/apprentice/adept/expert/mastery spells."

Perfect solution, thanks Celadoneiron!

**Comment by celadoneiron** [comment]
> 
> 
> From Spell Tutor page Optional Tab:
> 
> "Use this addon if you want Perk condition from Spell Tutor with Vokri mastery perks.
> 
> Requires mastery perk + skill (since it uses only one mastery perk)
> Skill 0/25/50/75/100 - novice/apprentice/adept/expert/mastery spells."
> 
> Perfect solution, thanks Celadoneiron!

Just to make sure this is clear, in case someone is wondering - no support will be available for any issues (even ones that seem unrelated) if you add this to the current version of the list. If you decide to add it, you'll need to direct any support requests to the #community-additions channel in the Discord, as per Rule 11.

**Comment by ForgottenGlory** [comment]
Fixed 3.2.0
