### ISSUE TITLE
Small "annoyance" in Whiterun

### ISSUE THREAD

**Issue by SexyThighs** [ForgottenGlory/Living-Skyrim-3#289]
Just a couple of trees blocking the missives board in Whiterun.

**Comment by TwistedModding** [comment]
select the tree(s) in the console and take a screenshot then post it here.

**Comment by SexyThighs** [comment]
![The Elder Scrolls V  Skyrim Special Edition Screenshot 2021 04 02 - 21 45 26 86](https://user-images.githubusercontent.com/81831662/113464720-f2d4b500-93fc-11eb-8305-3d49cd9f2f27.png)

**Comment by ForgottenGlory** [comment]
Fixed 3.1.1
