### ISSUE TITLE
Can't interact with the Shrine of Jephre in Whiterun

### ISSUE THREAD

**Issue by TheCadinal** [ForgottenGlory/Living-Skyrim-3#290]
**LS Version**
v3.1.0

**Describe the bug**
Can't interact with the Shrine of Jephre in Whiterun. I have tried to disable and enable the Shrine but I still couldn't interact with it.

**To Reproduce**
Go to the Shrine of Jephre near Bloated Man's Grotto and try to interact with it.

**Expected behavior**
Activate the Shrine to get the Shrine blessing - Fortify Carry Weight.

**Screenshots**

![enb2021_4_3_17_07_31](https://user-images.githubusercontent.com/79724122/113482708-2c123100-94a0-11eb-9f22-c370d1345e36.jpg)

![enb2021_4_3_17_07_17](https://user-images.githubusercontent.com/79724122/113482709-2ddbf480-94a0-11eb-8569-50d79b2a2802.jpg)

**Additional context**

**Comment by ForgottenGlory** [comment]
Fixed 3.2.0

**Comment by ForgottenGlory** [comment]
Well, I thought I could fix this, but I haven't been able to. Will fix when a fix is found
