### ISSUE TITLE
CTD around Markarth Military Camp

### ISSUE THREAD

**Issue by GravenImages** [ForgottenGlory/Living-Skyrim-3#291]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
3.1.0

**Describe the bug**
When going to the first step of Mirai's first quest (finding the item at her camp), travelling to the location from Markarth consistently CTDs just after the fork in the road past Markarth Military Camp.

**To Reproduce**
Go to the area.

**Expected behavior**
No crash

**Screenshots**

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**
[Crash_2021_4_3_11-44-14.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6253163/Crash_2021_4_3_11-44-14.txt)

**Comment by celadoneiron** [comment]
If you still have saves from when this happened, can you find them (both the .ess and .skse save files), put them into a .zip file, and upload it here?

**Comment by ForgottenGlory** [comment]
This crash was caused by Civil War Checkpoints which was removed in v3.1.1 of the list.
