### ISSUE TITLE
Follwer Collision seems Disabled

### ISSUE THREAD

**Issue by SHIIIZA117** [ForgottenGlory/Living-Skyrim-3#292]
hello,  whenever i add a Follower the Collision between me (Player) and Followers seems to get disabled.

is that a Bug, How can i fix this.

Best Regards

in the file i attached you can see how i am standing in the Follower because there is no collision.

![SkyrimSE 2021-04-04 22-52-21](https://user-images.githubusercontent.com/81931352/113521274-bccc3800-9598-11eb-9066-7044d6823245.png)

**Comment by JaxomofRuatha** [comment]
This is intentional, part of the functionality for https://www.nexusmods.com/skyrimspecialedition/mods/27742. It can result in some weird clipping, but way better than being blocked from doorways and such!
