### ISSUE TITLE
Not all bound weapon perks apply to arcane weapon from Forgotten Magic Redone

### ISSUE THREAD

**Issue by mnatler** [ForgottenGlory/Living-Skyrim-3#295]
**LS Version**
3.1.0

**Describe the bug**
Not all of the bound weapon perks from Vokrii apply to the Arcane Weapon spell from Forgotten Magic Redone. Soul stealer does apply, Oblivion Binding and Void Brand don't. Didn't test the other perks.

**To Reproduce**
Easily done with the console. Cast arcane weapon with the relevant perks and hit someone. Then cast bound whatever from Odin, hit someone, and see the difference.

**Expected behavior**
All Bound weapon perks will apply to the Arcane Weapon spell, not just certain ones.

**Additional context**
"Expected" compatibility issue requiring patch -  According to Vokrii's compatibility notes on Nexus:
"Mods that add bound weapons will not be affected by several bound weapon perks without a patch."
https://www.nexusmods.com/skyrimspecialedition/articles/1174

Asked on Enai's discord, was told
"best bet is to check the spell effect in Xedit and see if it uses the vanilla keywords"
No idea what that means so do what you will with it.

**Comment by mnatler** [comment]
Did some further checking - Blessed Weapon and and Hammer of Justice have the same issue and also need to be fixed.

**Comment by ForgottenGlory** [comment]
Fixed 3.2.0
