### ISSUE TITLE
Sneak Bug - Locked in position, then locked in Sneak mode

### ISSUE THREAD

**Issue by Chaps-Fantastic** [ForgottenGlory/Living-Skyrim-3#296]
**Describe the bug**
When I try to sneak, I get stuck in a position that looks like I am beginning a Dodge roll. To move at all I need to sheathe/unsheathe (whether I have weapons drawn or not) and then I am in Sneak mode. However, I cannot leave Sneak mode now.

**To Reproduce**
Every time I try to Sneak this occurs.

**Comment by TwistedModding** [comment]
read the readme
