### ISSUE TITLE
Silent Horizons ENB and True Storms not compatible

### ISSUE THREAD

**Issue by Doverling321** [ForgottenGlory/Living-Skyrim-3#297]
**LS Version**
3.1.0.

**Describe the bug**
I am using the Silent Horizon ENB as suggested in the ReadMe. However, everytime a storm/heavy-rain would appear the game would become desaturated and hold almost no colour (essentially turning the game black and white)

**To Reproduce**
Install the Silent Horizon ENB and vanilla LS3.

**Expected behavior**
No desaturation of the game during rain/storms.

**Additional context**
Using LS3's ModOrganiser I have disabled True Storms, this has actually corrected the problem. Proving that the ENB and True Storms aren't compatible (which is confusing seeing as the ReadMe reccomends the ENB). So far the game is stable and has not CTD.

I know removing mods is mid-game is a death sentence so I have made back ups in case there is a solution found by the dev team.

Kind Regards,

Doverling

**Comment by TwistedModding** [comment]
you could just use a different enb in the mean time

**Comment by Doverling321** [comment]
> you could just use a different enb in the mean time

Yeah I’m currently using a different ENB, however Silent Horizons is the preferred ENB so hopefully this can be rectified fairly easily.

As I mentioned previously it states in the readme that SH goes well with Living Skyrim yet it’s not currently compatible with True Storms due to the desaturation.

**Comment by H-Finch-404** [comment]
I am experiencing this as well.

Upon further reading though, the fix is to install a sound only patch for True Storms/Obsidian. Silent Horizons presets are not tweaked for True Storms weathers. Although you can probably up some setting in the ENB to get some more colour!

Edit: specifically - the author mentioned upping minimum saturation in ImageSpace under enbeffect

**Comment by Doverling321** [comment]
> I am experiencing this as well.
> 
> Upon further reading though, the fix is to install a sound only patch for True Storms/Obsidian. Silent Horizons presets are not tweaked for True Storms weathers. Although you can probably up some setting in the ENB to get some more colour!
> 
> Edit: specifically - the author mentioned upping minimum saturation in ImageSpace under enbeffect

It's ok I've gone with a different ENB now, the ENB author mentioned that it wasn't compatible with True Storms and other Obsidian patches which LS contains.
