### ISSUE TITLE
CTD North East of Whiterun

### ISSUE THREAD

**Issue by Neeksman** [ForgottenGlory/Living-Skyrim-3#298]
[Crash_2021_4_7_18-36-26.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6275478/Crash_2021_4_7_18-36-26.txt)

**LS Version**
Living Skyrim 3.1.1

**Describe the bug**
I was running down hill past the dragon burial mound you discover North East of skyrim when the game instantly crashed to desktop

**To Reproduce**
Go northeast of white-run
Find the Dragon Burial site
go down the hill (go striaght)

**Expected behavior**
Every time I go down hill the game CTD's. The expected behavior is that it does not crash

**Screenshots**

![IMG_4514](https://user-images.githubusercontent.com/77408460/113957187-a1993c80-97d3-11eb-89d8-6568bdf5d294.jpg)

this is the area

**Additional context**
Thank you for your help :)

**Comment by ForgottenGlory** [comment]
Duplicate of #300
