### ISSUE TITLE
Incorrect foot step sound while sprinting in heavy armor.

### ISSUE THREAD

**Issue by xelphos** [ForgottenGlory/Living-Skyrim-3#3]
**LS Version**
LS3 Open beta 1

**Describe the bug**
While sprinting in heavy armor it only plays sound for every other foot step. It almost sounds like you are hopping on one leg or limping.

**To Reproduce**
Simply sprint while wearing heavy armor.

**Expected behavior**
Should sound normal and play a sound for both feet.

**Screenshots**
https://youtu.be/QOCseNUotmk

**Comment by TwistedModding** [comment]
Can you post a screenshot of the armor you are using selected in the console?

**Comment by xelphos** [comment]
> Can you post a screenshot of the armor you are using selected in the console?

https://www.youtube.com/watch?v=4iKpqlU0d1E

https://i.imgur.com/R1i2Yl3.png

**Comment by TwistedModding** [comment]
There doesn't seem to be an issue on my end. See if the issue persists on a new game.

**Comment by xelphos** [comment]
> There doesn't seem to be an issue on my end. See if the issue persists on a new game.

Still happens on a new save.

**Comment by seanpbelcher** [comment]
It's in the LS3 Patches Merged, I think. FSTSprintArmorHeavyLFootstep is missing from the patch. 
![SprintHvyArmr](https://user-images.githubusercontent.com/67465410/106578945-b6bccb00-6505-11eb-8955-2ede4a10fb79.jpg)

**Comment by TwistedModding** [comment]
I dont have this issue on my end still. I can post a fix in the discord for someone to test. Preferably @xelphos.

**Comment by ForgottenGlory** [comment]
Fixed Beta 2
