### ISSUE TITLE
Attacked by many random civilian NPCs, most from Populated Skyrim.

### ISSUE THREAD

**Issue by VyktoryJaye** [ForgottenGlory/Living-Skyrim-3#30]
Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
3.0.0 Beta 1

**Describe the bug**
For some reason I'm getting attacked by many random NPCs. Many from the hunter faction. I have not killed any innocents, however I have been playing a thief stealing a few things. I've also killed some wolves, and I killed a deer from afar as well.

**To Reproduce**
Steps to reproduce the behavior: I tried, it seems random, and it seems solved by a re-load.

**Expected behavior**
No random attacks from civilians.

**Screenshots**
![enb2021_2_2_18_50_32](https://user-images.githubusercontent.com/77305453/106569954-5b342100-6589-11eb-91e9-b3f7258a5d61.jpg)
![enb2021_2_2_18_55_37](https://user-images.githubusercontent.com/77305453/106569958-5c654e00-6589-11eb-97ab-9aee50b37549.jpg)
![enb2021_2_2_18_56_41](https://user-images.githubusercontent.com/77305453/106569963-5d967b00-6589-11eb-982a-6f5a6ae16f5b.jpg)

**Additional context**
Some saves are attached, one post-massacre, two before at BleakFalls, (one testing a theory), and one reproduction test.
[save11-preattack-BFB.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/5909697/save11-preattack-BFB.zip)
[save12-postmassacre.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/5909701/save12-postmassacre.zip)
[save13-preattack-lvluptest.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/5909703/save13-preattack-lvluptest.zip)
[save14-reprotest.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/5909704/save14-reprotest.zip)

Also some discord chatter has been happening in our dev channels.

Signed - VyktoryJaye (aka NexxusDrako)

**Comment by VyktoryJaye** [comment]
![image](https://user-images.githubusercontent.com/77305453/106573787-2f676a00-658e-11eb-8795-d865db6b17ea.png)
And here's a console shot of the guy who started it all.

**Comment by ForgottenGlory** [comment]
Unlikely fixed but definitely mitigated in Beta 2. Continue to report this if it happens again please.
