### ISSUE TITLE
Tree LOD issues after doing Performance Guide

### ISSUE THREAD

**Issue by smarshallsay** [ForgottenGlory/Living-Skyrim-3#301]
**LS Version**
3.11

**Describe the bug**
Tree lods show as billboard / low qual texture when at mid distance for ScotsPine and Bentpine

**To Reproduce**
Follow performance guide, select 'Medium' for dyndolodx64

**Expected behavior**
Some trees look ugly, at closer ranges than expected. 

**Screenshots**
![image](https://user-images.githubusercontent.com/5755133/114271132-c970e600-9a07-11eb-8ece-ac70ba3aa18e.png)
![image](https://user-images.githubusercontent.com/5755133/114271137-d097f400-9a07-11eb-828a-c96b502f296f.png)
![image](https://user-images.githubusercontent.com/5755133/114271130-c118ab00-9a07-11eb-9896-93e9a0264bff.png)

**Additional context**
Running Dyndolodx64 with 'High' preset seems to solve this issue.

**Comment by ForgottenGlory** [comment]
If you thought the game would look the same or better after doing the performance guide, sorry, but I’m gonna burst that bubble now. It won’t.
