### ISSUE TITLE
Castle Volkihar Crash 

### ISSUE THREAD

**Issue by Bluelite5** [ForgottenGlory/Living-Skyrim-3#302]
**LS Version**
3.01
**Describe the bug**
Game freezes on loading screen when entering the Castle.

**To Reproduce**
Enter Castle Volkihar, retuning to Garan Marethi after filling the Blood Chalice 
**Expected behavior**
When entering the Castle to return to Garan Marethi after finishing the quest the game would black screen freeze but still can hear the wind sounds from the game.

**Comment by mc93-archi** [comment]
yep I was also getting this infinite black loading screen when entering the castle a lot

**Comment by ForgottenGlory** [comment]
This bug report is missing necessary information. Create a new bug report and fill out the entire form, attaching crashlogs and such as needed.

**Comment by boyooo** [comment]
This is happening to me today. I've done this quest a couple of times already but on different saves and have had no problem until now....
