### ISSUE TITLE
Candlehearth Hall

### ISSUE THREAD

**Issue by scraunch** [ForgottenGlory/Living-Skyrim-3#304]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
3.1.1

**Describe the bug**
Table go through wall

**To Reproduce**
Close eyes, then reopen.

**Expected behavior**
Table not go through wall

**Screenshots**
![image](https://user-images.githubusercontent.com/82478190/114627977-025cc500-9c6b-11eb-9b15-6eb9bc4aa7a3.png)

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**
REF ID I typed out in console is for the Door itself. Don't know if you need that or not.

**Comment by ForgottenGlory** [comment]
Fixed 3.2.0
