### ISSUE TITLE
Henrik's House in Ivarstead has an erection.

### ISSUE THREAD

**Issue by scraunch** [ForgottenGlory/Living-Skyrim-3#307]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
3.1

**Describe the bug**
Bedroll sticks out of house.

**To Reproduce**

**Expected behavior**
Bedroll inside house, next to Henrik's Teddy Ruxpin.

**Screenshots**
![enb2021_4_15_20_25_13](https://user-images.githubusercontent.com/82478190/114967294-09c9cd00-9e29-11eb-84b6-94470352bf53.jpg)

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**
I'm sorry.

**Comment by JaxomofRuatha** [comment]
Just to note here too, this is almost certainly because the 3DNPC patch from https://www.nexusmods.com/skyrimspecialedition/mods/36380 seems to have not been included, unsure if it was in prior LS versions.

**Comment by ForgottenGlory** [comment]
Fixed for 3.2.0
