### ISSUE TITLE
CTD on save load. Reversed to earlier save, played for three hours, then CTD on loading save(s) again. 

### ISSUE THREAD

**Issue by LunaticLooter** [ForgottenGlory/Living-Skyrim-3#308]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
3.1.0
Didn't update, due to ongoing save. 

**Describe the bug**
CTD on loading savegames. Not just a singular save, but several. It began after playing Wyrmstooth a while. After the initial quests, I played for maybe 30 minutes. Got stuck in an animation (couldn't put down my hands, after combat), tried to reload an earlier save, but hands were still up. Made a new save, and used the kill command on myself (as that has previously solved some animation related stuff) and CTD'd. Suddenly,  I ccouldn't load ANY save  (not just the one) after I flew the Aveza there. Saves before that work just fine. 
Reverted to an earlier save, chose not to call in the Aveza to check if things worked out, finished most of Wyrmstooth, and now there's at least eleven more savefiles that CTD on load. Basically, any savefile related to Wyrmstooth does not work anymore. 

**To Reproduce**
I couldn't honestly say. I'd say test out if others have the same problem with Wyrmstooth, but some user on the ls-gameplay-help mentioned he's had this issue outside of WT. 

**Expected behavior**
Save loads and everyone's happy. 
[Crash_2021_4_16_11-55-14.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6325322/Crash_2021_4_16_11-55-14.txt)

**Additional context**
[Crash_2021_4_16_11-55-14.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6325327/Crash_2021_4_16_11-55-14.txt)

**Comment by JartanFTW** [comment]
I've been getting a similar CTD on savegame loading for every save past one I have in the LoTD safehouse. I haven't touched Wyrmstooth. I can't seem to load any later saves, even if I make a new one after loading the safehouse one.
I've completely reinstalled skyrim and the modlist via Wabbajack. No dice.
Edit: Unfortunately, I for me, no crash dumps are created on CTD.

**Comment by ForgottenGlory** [comment]
Seems related to the Visual C++ runtime, see if disabling your antivirus resolves the issue.
