### ISSUE TITLE
Honed Metal crash when ordering items

### ISSUE THREAD

**Issue by Cerberus610** [ForgottenGlory/Living-Skyrim-3#31]
I Have tried this multiple times when i ask Eorlund Gray-Mane to make me the resplendent armor i get a immediate crash. Haven't tried it with anyone else unfortunately. 
[Crash_2020_10_28_14-17-16.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/5910257/Crash_2020_10_28_14-17-16.txt)

**Comment by ForgottenGlory** [comment]
Possibly fixed Beta 2, followup on this

**Comment by ForgottenGlory** [comment]
Tested it again while working on Beta 3, seems to be resolved.
