### ISSUE TITLE
Weird Flickering Effect

### ISSUE THREAD

**Issue by Jzenner615** [ForgottenGlory/Living-Skyrim-3#312]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
I am on the newest version of the list (3.1.1)

**Describe the bug**
I have this weird sort of flickering effect, I believe it is due to the ENB but I am not entirely sure.

**To Reproduce**
I installed Amon ENB and had made no changes to the list.

**Expected behavior**
I just expected there to be no flickering of sorts while using an enb.
**Screenshots**
Since screenshots wouldn't really work I have a video I uploaded to youtube using Geforce Experience. In the description it lists my PC specs as well, here is the link:
https://www.youtube.com/watch?v=1YxXP0X-Tvs

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**

**Comment by JartanFTW** [comment]
Does this happen elsewhere, or just near Solitude?

**Comment by Jzenner615** [comment]
So I did some testing and it seems to only have a lot of flickering near
whiterun and solitude during the daytime, in other areas such as Windhelm,
Morthal and Markarth it seemed to not really be there other than the shadow
flickering. I uploaded another video on it so you can can see what's
happening: https://www.youtube.com/watch?v=4erwfPUsCH8

**Comment by TwistedModding** [comment]
anti aliasing issue on your end.

**Comment by Jzenner615** [comment]
How can I fix this? I tried disabling Anti Aliasing in the launcher and it
keeps persisting.
