### ISSUE TITLE
Merc Follower Bug

### ISSUE THREAD

**Issue by scraunch** [ForgottenGlory/Living-Skyrim-3#313]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
3.1

**Describe the bug**
Upon entering and exiting a battle with a Mercenary as a Follower of the player character, the Follower becomes untargetable, meaning when I move my crosshair over the NPC, there is no prompt to use Action button to speak to the NPC. I also have Ashe as another follower, and she I was able to speak to upon leaving combat. 

**To Reproduce**
Steps to reproduce the behavior: Hire Mercenary, they auto-import into NFF. Get into battle. Leave battle. Attempt to speak with Mercenary Follower. Can't speak with Mercenary Follower.

**Expected behavior**
Place Crosshair over NPC model, and see 'Press E to Talk'

**Screenshots**
![enb2021_4_22_14_13_02](https://user-images.githubusercontent.com/82478190/115786750-1644ad00-a376-11eb-9e00-116dfe80d9f2.jpg)
![enb2021_4_22_14_12_45](https://user-images.githubusercontent.com/82478190/115786789-22306f00-a376-11eb-91f9-edf11404c463.jpg)
![enb2021_4_22_14_27_41](https://user-images.githubusercontent.com/82478190/115787373-f497f580-a376-11eb-8bef-ac085f571cb7.jpg)
![enb2021_4_22_14_30_27](https://user-images.githubusercontent.com/82478190/115787630-5f493100-a377-11eb-925e-45713c2058fd.jpg)
![enb2021_4_22_14_30_49](https://user-images.githubusercontent.com/82478190/115787638-61ab8b00-a377-11eb-9fd6-38f7edee2348.jpg)

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**
I reloaded, same problem. Only with Mercenaries and only after you get into combat with them. If you hire and never fight, you can always Talk to them. Looking at NFF, it appears that even though I am looking at the NPC with my crosshair on them, that it appears at least to NFF that I dont have my crosshairs set on anyone. I added a side by side of me with Crosshair over Ashe, and NFF clearly shows that is exactly what is up. No dice for the Orc Merc. Cheers.

**Comment by ForgottenGlory** [comment]
There is sometimes a weird interaction between Real Names and NFF where NFF "loses track" of an NPC that's been renamed. See if resetting the NPC's name using the Real Names MCM and adding an exclusion for that NPC in the real names MCM fixes it.
