### ISSUE TITLE
LOTD bugged texture in quest

### ISSUE THREAD

**Issue by RetroBoy99** [ForgottenGlory/Living-Skyrim-3#314]
If possible, please also attach a copy of your most recent save before the issue occurred.**![bugged texture](https://user-images.githubusercontent.com/82152970/115921212-db309f80-a483-11eb-88c4-262fce163f27.png)

**LS Version**
3.1.0

**Describe the bug**
in the Legacy of the dragonborn quest Shattered Legacy, you get teleported into location called Sancre Tor using an amulet and some of the building in there are orange and there are other bugged textures

**To Reproduce**
arrive at Sancre Tor

**Screenshots*
![bugged texture](https://user-images.githubusercontent.com/82152970/115921287-f56a7d80-a483-11eb-9212-eae358b497ab.png)

[Save2600_0DACFBC0_0_537072697465_SancreTorWorld_030654_20210423192512_27_1.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6367682/Save2600_0DACFBC0_0_537072697465_SancreTorWorld_030654_20210423192512_27_1.zip)

**Comment by ForgottenGlory** [comment]
Should be fixed 3.2.0
