### ISSUE TITLE
Dev Aveza Windhelm Location Wooden plank leads to  nowhere

### ISSUE THREAD

**Issue by TheCadinal** [ForgottenGlory/Living-Skyrim-3#315]
**LS Version**
v3.0.1

**Describe the bug**
The Exit of the Dev Aveza near Windhelm doesn't work with Windhelm Entrance Overhaul. The Wooden Plank floats in the Air.

**To Reproduce**
Unlock the Dev Aveza and fly to Windhelm. 

**Expected behavior**
The Plank should connect to the Windhelm Bridge. 

**Screenshots**

![enb2021_4_24_17_57_43](https://user-images.githubusercontent.com/79724122/115966402-b264e480-a52d-11eb-8e73-b80ba44fdf35.png)

![enb2021_4_24_17_57_47](https://user-images.githubusercontent.com/79724122/115966405-b42ea800-a52d-11eb-89f2-9497239993e0.png)

**Additional context**

**Comment by ForgottenGlory** [comment]
Open to suggestions on how to fix
