### ISSUE TITLE
Missing crosshair with bows

### ISSUE THREAD

**Issue by wswank13** [ForgottenGlory/Living-Skyrim-3#317]
**LS Version**
3

**Describe the bug**
Crosshair not displaying when bow is equipped.  iHUD settings were checked and the crosshair is set to display with ranged weapons.

**To Reproduce**
- New character
- Pick "camping in woods" start
- Equip hunting bow
- Ready hunting bow.  Observe missing crosshair.

**Expected behavior**
From using iHUD in the past, readying the bow should display the crosshair on a slight delay, and unequipping/lowering the bow should hide it.

**Screenshots**
![ScreenShot230](https://user-images.githubusercontent.com/83145819/115976464-9b24f780-a52b-11eb-927e-10032ee9c748.png)
![ScreenShot231](https://user-images.githubusercontent.com/83145819/115976466-9ceebb00-a52b-11eb-92b5-1e325fdfffcc.png)

**Additional context**
Added another bow at random via console and checked - no crosshair.  (Hallowed Stalhrim bow)

**Comment by ForgottenGlory** [comment]
See solution in #73
