### ISSUE TITLE
CTD when near Korvanjund

### ISSUE THREAD

**Issue by Jzenner615** [ForgottenGlory/Living-Skyrim-3#320]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
Newest Version (3.1.1)

**Describe the bug**
As I begin to approach Korvanjund I get a CTD. I am currently on the Jagged Crown quest but it seems to happen on earlier saves as well. I have tried using the command "coc Korvanjund01" as i've seen for similar issues but it has not worked.

**To Reproduce**
Approach Korvanjund.

**Expected behavior**
To not crash as I approach Korvanjund.
[Crash_2021_4_25_18-2-18.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6373625/Crash_2021_4_25_18-2-18.txt)

**Screenshots**

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**

**Comment by scraunch** [comment]
https://discord.gg/Agb4CVR7

Please join this, the FG's Modlist Discord Server, and check #ls-announcements for the fix to your issue.

**Comment by Jzenner615** [comment]
Sorry I didn't even think of checking the discord, thank you!
