### ISSUE TITLE
Crash Near Markarth Bridge

### ISSUE THREAD

**Issue by Jzenner615** [ForgottenGlory/Living-Skyrim-3#323]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
3.1.1 (Newest Version)

**Describe the bug**
I CTD when I begin to approach Markarth, (The farm in front of Markarth to be specific).

**To Reproduce**
Walk past the bridge to Markarth, shortly after I get a CTD.

**Expected behavior**
To not crash.

**Screenshots**

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**
I believe it is the same issue as these posts:
https://github.com/ForgottenGlory/Living-Skyrim-3/issues/237
https://github.com/ForgottenGlory/Living-Skyrim-3/issues/235
My crash log says it is because of Organic Faction Extensions
[Crash_2021_4_29_19-24-21.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6402760/Crash_2021_4_29_19-24-21.txt)

**Comment by Jzenner615** [comment]
Also, today I went back to the beginning of my save game typed tmm 01 and fast traveled there with no issues. I'm going to see if it's because of the civil war quest or if fast traveling there before hand solves the crashing.

**Comment by Jzenner615** [comment]
Alright by fast traveling to Salvius Farm(I would crash before I made it to the fence) it fixed my issue and I can freely walk across the bridge and up to Markarth without any issues.

**Comment by ForgottenGlory** [comment]
Should be fixed 3.2.0
