### ISSUE TITLE
CTD in Dragonborn Gallery, Save CTD's upon loading in.

### ISSUE THREAD

**Issue by scraunch** [ForgottenGlory/Living-Skyrim-3#329]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**
Apparently my most recent save is from March 9th, so.... I don't know, doubt it would be helpful. Feels weird I don't have any saves from the last 7 weeks of gaming... any help finding the save in question for this Crash would be appreciated. I don't have any other folders where game saves would go. Weird.
![image](https://user-images.githubusercontent.com/82478190/116834828-afdd3d00-ab74-11eb-9563-eded8e7531e7.png)

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
3.2

**Describe the bug**
Inside Dragonborn Gallery
[Crash_2021_5_2_15-18-35.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6412612/Crash_2021_5_2_15-18-35.txt)
[Crash_2021_5_2_18-26-41.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6412613/Crash_2021_5_2_18-26-41.txt)

**To Reproduce**
Can't load back in to game. CTD on load

**Expected behavior**

**Screenshots**

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**

**Comment by ZhamelSeh** [comment]
I was on 3.1.1, upgraded to 3.2.0, I am also having CTD when trying to load my saves, I was in the Hall of Heros. Tried two different saves, a manual and an autosave.

[Crash_2021_5_3_12-33-5.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6418905/Crash_2021_5_3_12-33-5.txt)
[Crash_2021_5_3_12-37-49.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6418907/Crash_2021_5_3_12-37-49.txt)

If a copy of a save is needed please let me know.

**Comment by celadoneiron** [comment]
Scraunch, your saves will be located in [Your LS3 install folder]\profiles\Living Skyrim 3\saves\.

ZhamalSeh, saves from previous versions are incompatible with LS3.2.0. You will need to start a new game.

**Comment by ForgottenGlory** [comment]
@scraunch In `[install folder]\mods\SSE Fixes\DLLPlugins` there's a `FPSFixPlugin.ini` file, try switching `UseOSAllocators=1` to `UseOSAllocators=0` in that and try again. Let me know results, thanks!

**Comment by ForgottenGlory** [comment]
Should be fixed 3.2.1 by #343
