### ISSUE TITLE
Great City of Falkreath conflicts

### ISSUE THREAD

**Issue by seanpbelcher** [ForgottenGlory/Living-Skyrim-3#33]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
LS3 beta

**Describe the bug**
The Great City mods are awesome looking expansions, but they need a lot of TLC, and Falkreath is no exception. Using it with JK's can be tricky I've discovered. 
GCoF has some navmesh issues that are really apparent when coupled with population mods. People getting stuck between the wall GCoF adds and Lod's tanning rack, just for one example. 
![enb2021_2_2_04_12_05](https://user-images.githubusercontent.com/67465410/106595878-d3fb9480-6519-11eb-8f9b-fbcec1fbec93.png)
![enb2021_2_2_04_12_30](https://user-images.githubusercontent.com/67465410/106595889-da8a0c00-6519-11eb-87e7-8588f4c44280.png)
![enb2021_2_2_04_12_40](https://user-images.githubusercontent.com/67465410/106595897-deb62980-6519-11eb-9ff9-1928c825b5be.png)

Missives needs a patch for it as well. 

![enb2021_2_2_04_11_22](https://user-images.githubusercontent.com/67465410/106595963-fe4d5200-6519-11eb-8a69-383313cb6676.png)

And, finally, LoSII needs some patching. The patch to make it play nice with JK's isn't catching the floating lantern in the shot attached. 
![enb2021_2_2_04_13_58](https://user-images.githubusercontent.com/67465410/106596000-09a07d80-651a-11eb-9421-cf50c0fd0676.png)

**To Reproduce**
N/A

**Expected behavior**
N/A

**Screenshots**
If applicable, add screenshots to help explain your problem. Additionally, if your report applies to a specific object, make sure it is selected with the console open. Reports without this will be closed.

**Additional context**

**Comment by TwistedModding** [comment]
Could just remove this mod, the city is covered by jk's skyrim. If not, idk how to fix it.

**Comment by seanpbelcher** [comment]
For what its worth, I ditched in on my own load order and just went with JK's + Arthmoor's + Sepolcri. I was just in love with making the cemetery bigger and that sweet interior for the Jarl's chamber, but not so much I was willing to keep messing with it. A lot of the Great Cities series have issues, unfortunately, because I love their design.

**Comment by ForgottenGlory** [comment]
Fixed Beta 2
