### ISSUE TITLE
Textures Not Existing

### ISSUE THREAD

**Issue by TheDTubbs** [ForgottenGlory/Living-Skyrim-3#334]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
Living Skyrim 3.2.0

**Describe the bug**
I Started a new game and started to play. I selected the left for dead option and spawned in solsthiem. When i got to solsthiem the texture for the ship that takes you to skyrim wasnt appearing. So i decided to ignore because i was only going to use it the one time but when i got to windhelm and got in to the inn the basement floor had the same texture issue, I could walk on it but it isnt there

**To Reproduce**
Steps to reproduce the behavior: Unsure

**Expected behavior**
Textures to be there

**Screenshots**

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**

**Comment by foxylica** [comment]
candlehearth hall - windhelm _ ![enb2021_5_7_17_50_44](https://user-images.githubusercontent.com/80045161/117474198-5d7c9180-af63-11eb-8ecb-2e7c2db6cd0b.png)
![enb2021_5_7_17_51_01](https://user-images.githubusercontent.com/80045161/117474203-5e152800-af63-11eb-891f-39827d5c234f.png)
![enb2021_5_7_17_51_23](https://user-images.githubusercontent.com/80045161/117474207-5eadbe80-af63-11eb-8f5d-c4cca066bb47.png)

**Comment by ForgottenGlory** [comment]
Fixed 3.2.1
