### ISSUE TITLE
Dark Face Bug - Torolf (with patch)

### ISSUE THREAD

**Issue by celadoneiron** [ForgottenGlory/Living-Skyrim-3#336]
**LS Version**
LS3.2.0

**Describe the bug**
Torolf (00013641) has the BFB.

**To Reproduce**
Look at him.

**Expected behavior**
Torolf is not pulling a Trudeau.

**Screenshots**
![Screen Shot 05-07-21 at 09 37](https://user-images.githubusercontent.com/73095714/117379026-ec64bc00-af19-11eb-82d4-d554d5ae903d.PNG)

**Additional context**
Known issue with Northbourne NPCs of Falkreath Hold - the facegen files for Torolf are not included in the most recent version of the mod.

Patch provided in developer patches channel.

**Comment by ForgottenGlory** [comment]
Fixed 3.2.1
