### ISSUE TITLE
Whiterun Windows Show Through Brazier Smoke

### ISSUE THREAD

**Issue by CMYKMatter** [ForgottenGlory/Living-Skyrim-3#337]
**LS Version**
v3.2.0

**Describe the bug**
When in Whiterun (possibly other locations as well), if you look through brazier smoke towards some of the windows, the windows themselves will appear in front of the brazier smoke. 

**To Reproduce**
Go to Whiterun's front gate, stand by the brazier and look above the front door of the Drunken Huntsman through the smoke of the brazier at the 3 small windows there. 

**Expected behavior**
The windows should appear behind the brazier smoke ideally. 

**Screenshots**
https://i.imgur.com/hr8yW5g.jpg

I have tried to select the window type that seems to be causing this, but have been unable to do so.  The item itself seems unselectable. 

**Additional Context**
There seems to be so distance where this issue resolves itself. There is some manner of z-fighting when you get close enough and move around while looking at it.

**Comment by CMYKMatter** [comment]
I was actually able to trace this back to Enhanced Lights & FX.  I had remembered running into this previously.  The problem occurs with the ELFX Exteriors house meshes.  There is a patch by Wizkid to fix this here: 

https://www.nexusmods.com/skyrimspecialedition/mods/26327?tab=description

You can just use the meshes/textures and delete the ESP. Fixed the issue completely for me.

**Comment by ForgottenGlory** [comment]
Fixed 3.2.1
