### ISSUE TITLE
Ursine Cuirass equip slots assigned incorrectly (patch provided)

### ISSUE THREAD

**Issue by celadoneiron** [ForgottenGlory/Living-Skyrim-3#338]
**LS Version**
LS3.2.0.

**Describe the bug**
The Ursine Light and Heavy Cuirasses will unequip certain Bandoliers items and vice versa, because the cuirasses have been marked as using Slot 48 in their ARMO record despite that slot being referenced by neither the .nif file nor the armor addon record.

**To Reproduce**
Craft and equip an Ursine cuirass.
Craft and equip a Bandoliers item marked as "Back Left."

**Expected behavior**
Putting on a satchel should not make the character strip.

**Additional context**
See dev patches channel for fix.

**Comment by ForgottenGlory** [comment]
Fixed 3.2.1
