### ISSUE TITLE
Thief guild Raggen flagon fire bug 

### ISSUE THREAD

**Issue by ganshunter** [ForgottenGlory/Living-Skyrim-3#339]
**LS Version**
LS3.2.0.

**Describe the bug**
Fire bug thing-picture below.

**To Reproduce**
Nothing?

**Expected behavior**

**Screenshots**
![dsds](https://user-images.githubusercontent.com/41804541/117546002-2324fa00-b020-11eb-821b-b729d225cf9e.png)

**Comment by ForgottenGlory** [comment]
This bug report is missing required information, create a new bug report with all requested information from the bug report template.
