### ISSUE TITLE
Hair clipping 

### ISSUE THREAD

**Issue by seanpbelcher** [ForgottenGlory/Living-Skyrim-3#34]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
LS3 Beta

**Describe the bug**
Some of the modded hairstyles clip very badly with NPCs when they wear head coverings.
![enb2021_2_2_04_24_35](https://user-images.githubusercontent.com/67465410/106596741-0f4a9300-651b-11eb-9ec2-20aa5ee0ae0b.png)
![enb2021_2_2_03_47_37](https://user-images.githubusercontent.com/67465410/106596946-546ec500-651b-11eb-8418-7db76da96139.png)

**To Reproduce**
It only affects certain NPCs and only when they are wearing head coverings - it's dependent on the hairstyle they have been assigned. For minor NPCs just milling around it's obnoxious but not a big deal, but for named important NPCs like Astrid, it can be very distracting since you are in conversation with her a fair amount. 

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. Additionally, if your report applies to a specific object, make sure it is selected with the console open. Reports without this will be closed.

**Additional context**

**Comment by ForgottenGlory** [comment]
I'm open to suggestions on this one

**Comment by TwistedModding** [comment]
Although ive never seen this before, it could be a flag or something in xedit letting the hair show, i can look at it a bit later

**Comment by ForgottenGlory** [comment]
Possibly fixed Beta 4
