### ISSUE TITLE
Helgen rock is giving me skinwalker ranch vibes

### ISSUE THREAD

**Issue by scraunch** [ForgottenGlory/Living-Skyrim-3#340]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
3.2

**Describe the bug**
Blood red and screen tear lookin rock.

**To Reproduce**
I'm a virgin, don't ask me.

**Expected behavior**
Look like a normal rock.

**Screenshots**
![SkyrimSE 2021-05-08 12-56-46](https://user-images.githubusercontent.com/82478190/117551879-2e1a6300-affd-11eb-9e32-317e6fb75dfb.png)
![SkyrimSE 2021-05-08 12-56-11](https://user-images.githubusercontent.com/82478190/117551882-32468080-affd-11eb-8e55-33028e2e4be4.png)

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**

**Comment by ForgottenGlory** [comment]
Looks fine to me, unable to replicate
