### ISSUE TITLE
Distant LOD bug in coldharbour

### ISSUE THREAD

**Issue by PocketPhoenix** [ForgottenGlory/Living-Skyrim-3#341]
**LS Version 3.2.0**

**Describe the bug**
While going through the Vigilant faction quest mod, I ended up in the worldspace of coldharbour. For some reason the game decides to load the distance LOD versions of some buildings ontop of the actual ones. Causes extreme flickering etc.

**To Reproduce**
Steps to reproduce the behavior: Has not happened in any other worldspace.

**Expected behavior**
None

**Screenshots**

![enb2021_5_9_10_44_10](https://user-images.githubusercontent.com/83901495/117566053-b6a80a80-b0b4-11eb-9a1d-981d60b72416.jpg)

[Distant LOD Bug Coldharbour.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6447190/Distant.LOD.Bug.Coldharbour.zip)

**Additional context**
None

**Comment by ForgottenGlory** [comment]
Will fix the next time I regenerate LODs

**Comment by JulesMarz** [comment]
Not sure if related, but many of the building textures are flickering between detailed and blurry.

Can create separate issue if unrelated

**Comment by william7733** [comment]
Having this problem too, made an account here to post this. I read somewhere it could be warburg paper map mod causing the issue but i refuse to get rid of my paper maps, maybe the info might help somebody here
