### ISSUE TITLE
Save issue with "CLOCKWORK (CLOCKWORK CASTLE)"

### ISSUE THREAD

**Issue by HillyBilly48** [ForgottenGlory/Living-Skyrim-3#343]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
Living Skyrim 3.2

**Describe the bug**
I have started the mod that adds the clock-tower mansion. I have been doing the quest too get back to Skyrim. My game crashes every time I try to save while in and outside mansion. Re-loading a save before I started the mod back in Skyrim seems to work fine. added multiple crash logs. All crash logs while playing the quest mod are attached. Also had 2 random crashes inside the mansion while looking around.

**To Reproduce**
Steps to reproduce the behavior: Load save game within the mod, save game, crashes when clicking save.

**Expected [behavior**]
For the game too save.

**Screenshots**

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**
Crash Logs:
[Crash_2021_5_10_20-4-51.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6455813/Crash_2021_5_10_20-4-51.txt)
[Crash_2021_5_10_20-8-6.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6455814/Crash_2021_5_10_20-8-6.txt)
[Crash_2021_5_10_20-22-37.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6455815/Crash_2021_5_10_20-22-37.txt)
[Crash_2021_5_10_20-32-44.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6455816/Crash_2021_5_10_20-32-44.txt)
[Crash_2021_5_10_20-42-55.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6455817/Crash_2021_5_10_20-42-55.txt)
[Crash_2021_5_10_20-46-31.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6455818/Crash_2021_5_10_20-46-31.txt)
[Crash_2021_5_10_20-58-39.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6455819/Crash_2021_5_10_20-58-39.txt)

Saves:

[save before starting clockwork.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6455878/save.before.starting.clockwork.zip)

[saves after starting clockwork.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6455885/saves.after.starting.clockwork.zip)

**Comment by ForgottenGlory** [comment]
I'm able to replicate this but am unsure what's causing it, the crash logs don't give me enough information to go from. I don't see anything wrong with the save file itself... Might just be an instance of reloading an earlier save and going from there.

**Comment by ForgottenGlory** [comment]
Fixed 3.2.1
