### ISSUE TITLE
Stealing from containers is not a crime

### ISSUE THREAD

**Issue by celadoneiron** [ForgottenGlory/Living-Skyrim-3#344]
**LS Version**
LS3.2.0.

**Describe the bug**
Stealing from containers is not a crime. Even if the interact prompt says "Steal from [container]" and the items you take have the red-hand "stolen" icon, your Items Stolen stat will not increase, you will not gain a bounty, and NPCs will not react even if you do it right in front of them. Stealing items that exist in the world, either as loose items or harvesting owned harvestables, works as expected.

**To Reproduce**
1. Start a new game.
2. Choose a start with owned items and NPCs around (e.g. an inn).
3. Go directly in front of NPCs and steal something from a container.

**Expected behavior**
Stealing is stealing.

**Additional context**
Occurs in a totally default LS3 setup (no QuickLoot, etc).

**Comment by ForgottenGlory** [comment]
Unsure on this one, help wanted.

**Comment by ChunkeeMunkee** [comment]
LS version 3.1.0:

General Store in Riverwood, Bannered Mare in Whiterun, middle of Riften market, and in the Four Shields Inn in Dragonbridge - all four triggered a 1 Septim bounty for the respective holds when looting from owned containers.
