### ISSUE TITLE
CTD on my way to Nightgate Inn 

### ISSUE THREAD

**Issue by Delta-06** [ForgottenGlory/Living-Skyrim-3#345]
**LS Version**
5/2/2021 3.2.0

**Describe the bug**
Early in the game. Trying to approach Nightgate Inn. Attempted from multiple directions and both sides of the river. Once I get a certain distance away (its not close) I get CTD. I tried to attach the recent save but I get "We don't support that file type" message

**To Reproduce**
Tried loading different load files prior to the CTD. Same outcome.

**Expected behavior**
No CTD

**Screenshots**
N/A

**Additional context**
[Crash_2021_5_11_19-39-48.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6477972/Crash_2021_5_11_19-39-48.txt)

**Comment by ForgottenGlory** [comment]
You're not on version 3.2.0 if you're getting this crash. Your crash log also indicates you're not on 3.2.0 with the ESP count. Download the latest installer through Wabbajack and follow the updating instructions in the Readme.

**Comment by Delta-06** [comment]
Just wanted to say Thankyou.

Getting a fix to my problem so quickly is greatly appreciated!

Your effort is appreciated.
