### ISSUE TITLE
Fireball does 0 damage

### ISSUE THREAD

**Issue by KingCollege** [ForgottenGlory/Living-Skyrim-3#347]
**LS Version**
LS Version 3.2.0

**Describe the bug**
Fireball does 0 damage, not even burning damage.

**To Reproduce**
Not sure if this is why but I have most of the requirements setting in spell tutor off - only magica requirement is on. 
Left or right-hand cast

**Expected behavior**
Do damage

**Additional context**
Some other destruction spells do 0 damage as well: Chain Lighting and firebolt

**Comment by ForgottenGlory** [comment]
I'm not able to replicate this, open to suggestions on how to fix.

**Comment by Etrux** [comment]
[bugged save.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6488639/bugged.save.zip)
ive had the same issue with firebolt, fireball, chainlightning, and lightening bolt

**Comment by KingCollege** [comment]
> I'm not able to replicate this, open to suggestions on how to fix.

not really a fix, but it works after creating a new character - so it might be something that happened during gameplay with my old character.

**Comment by Etrux** [comment]
My guy if you hit “resurrect” on your character, it’ll fix it. Problem being now your active effects are gone.. it must be a hidden one at least it was in my case. Though I have no idea how to fix it

**Comment by ForgottenGlory** [comment]
Seems to be an issue with AVA, which I've reported to the mod author. Will fix when it's fixed.
