### ISSUE TITLE
Fixed body collision acting weird 

### ISSUE THREAD

**Issue by CappedPluto** [ForgottenGlory/Living-Skyrim-3#348]
**LS Version**
Current version: 5/2/2021 3.2.0

**Describe the bug**
when you walk over a dead body, it will sometimes behave in a weird way, i have had time where it move me a bit to the side and timed where it throws me a across a room, its very annoying during combat

**To Reproduce**
walk over a dead body a lot 

**Expected behavior**
sometimes it wont trigger, sometimes you will be moved a bit and sometimes it will move you alot

**Additional context**
i recorded a video of the bug in action, unfortunately i couldn't get footage of it throwing across a room but you can still see my player being moved weirdly in the video: https://youtu.be/SAr5cTr71TA

**Comment**
i believe that the mod that is causing this i "Fixed body collision", however i could not test to see if this would fix it because a bunch of error messages came up when i tried to disable it and load the game.

**Comment by ForgottenGlory** [comment]
From what I can tell this is working as intended. Throwing things across the room is just par for the course for Skyrim at this point, the physics engine is far from perfect but shouldn't be happening often enough for it to be an issue.
