### ISSUE TITLE
Candlehearth Hall Bottom Floor

### ISSUE THREAD

**Issue by cmm093** [ForgottenGlory/Living-Skyrim-3#349]
The bottom floor of Candlehearth Hall in Windhelm is blank. I've attached a screenshot.
![Candlehearth Hall Bottom Floor](https://user-images.githubusercontent.com/13308288/118377763-f0857f00-b594-11eb-8e7d-1aa8eedcacc0.png)

**Comment by ForgottenGlory** [comment]
Duplicate of #334
