### ISSUE TITLE
UI font size is too large and has text overlapping other UI elements

### ISSUE THREAD

**Issue by Quietbeat** [ForgottenGlory/Living-Skyrim-3#35]
**LS Version**
3

**Describe the bug**
When I started the game, all of the UI elements were larger than in v2. I looked at all of the mods that had to do with the UI but none of the changes I made had any effect. In the Read.me section, there's no mention of how to adjust the font size.

**To Reproduce**
Start a new game then open any of the menus. Try changing SkyUI and the newer UI mods.

**Expected behavior**
The font size is adjustable and no text (subtitles for example) overlap other UI elements.

**Screenshots**
![Stamina progress bar overlaps subtitles](https://user-images.githubusercontent.com/57841662/106624716-d0243e00-652a-11eb-8cea-10f048ed2158.png)

**Additional context**
[saves.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/5912431/saves.zip)

**Comment by VyktoryJaye** [comment]
Just out of curiosity, what resolution are you running at? I'm having no issues at 1080p, and this could either be an Ultrawide issue or a scaling issue.

On the topic of scaling, maybe check that your Windows scaling settings are set to 100% and not zoomed in or out. Many games react weirdly if scaling is set to anything else as it essentially resizes everything.

**Comment by belkyrnn** [comment]
I'm having the same issue as Quietbeat, and I'm running in 1080p and Windows scaling is at 100%.

**Comment by VyktoryJaye** [comment]
> I'm having the same issue as Quietbeat, and I'm running in 1080p and Windows scaling is at 100%.

Fair enough, maybe I just haven't noticed it happening on my end. I'll try doing some testing then. I have noticed the UI is quite sized more than usual.

**Comment by Quietbeat** [comment]
My monitor info:
- ASUS ROG Swift PG348Q
- Panel Size : Ultra-wideScreen 34” 21:9
- True Resolution : 3440x1440

**Comment by ForgottenGlory** [comment]
Use Less Intrusive HUD to adjust it then? That's why it's in the list - so you can set up the HUD how you like it. Controls for LIH2 are in the keymap from the readme.
