### ISSUE TITLE
Main Quest Broken, the quest "The Fallen" can't be finished

### ISSUE THREAD

**Issue by GaetanDeAlmeida** [ForgottenGlory/Living-Skyrim-3#351]
[SSE Save for bug report.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6489555/SSE.Save.for.bug.report.zip)

LS Version
LS Version 3.2.0

Describe the bug
Odahviing flies over Dragonreach and doesn't stop

To Reproduce
https://www.youtube.com/watch?v=HpTwbOj-kJA
I recorded the process only once, but you can repeat it indefinitly

Expected behavior
Odhaviing stop and fight

**Comment by TwistedModding** [comment]
On a side note... are you using Ari?

**Comment by TwistedModding** [comment]
Also, try leaving that cell and going back in and see if that fixes it.

**Comment by GaetanDeAlmeida** [comment]
> On a side note... are you using Ari?

Who is Ari? A follower? If the answer is yes, then, no, I don't use Ari

**Comment by GaetanDeAlmeida** [comment]
> Also, try leaving that cell and going back in and see if that fixes it.

I just tried it out, it doesn't solve the issue

**Comment by ChunkeeMunkee** [comment]
> On a side note... are you using Ari?

Hair, skintone, and tattoos all check out :)

Gaetan - Ari is a RaceMenu preset that Twisted made, think you're using it?

**Comment by ChunkeeMunkee** [comment]
Dekjo on the Discord suggests heading back into Dragonsreach and waiting a day (they quoted 20hrs which is rather specific!) and going back outside - this fixed it for them

**Comment by GaetanDeAlmeida** [comment]
> > On a side note... are you using Ari?
> 
> Hair, skintone, and tattoos all check out :)
> 
> Gaetan - Ari is a RaceMenu preset that Twisted made, think you're using it?

OH yes, It's the Bosmer Female preset available in LS, she looks great :) 

ty Twisted for that

**Comment by GaetanDeAlmeida** [comment]
> Dekjo on the Discord suggests heading back into Dragonsreach and waiting a day (they quoted 20hrs which is rather specific!) and going back outside - this fixed it for them

Just tried it, it doesn't work either

but...

I find a work around. What I did exactly:

1 - As soon as he appears, I open the console command
2 - I select him

In the console I type the following commands
3 - disable
4 - moveto player
5 - enable

And voilà

I was not the only one with this issue, and this method is the most consistent way to get rid of it until it's fixed.

Thanks for your time Chunkee and Twisted

**Comment by ForgottenGlory** [comment]
There are quite a few vanilla-game bugs relating to this part of the quest. I've seen a number of fixes, ranging from the "wait 20 hours" thing to reloading an earlier save. You do also need to use Dragonrend to force Odahviing to land (which apparently also doesn't always work. Great job Bethesda.). Will fix if a fix is found, but until then, there's plenty of workarounds.
