### ISSUE TITLE
Crash near Markarth

### ISSUE THREAD

**Issue by nicobonada** [ForgottenGlory/Living-Skyrim-3#357]
[Crash_2021_5_18_10-43-41.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6502469/Crash_2021_5_18_10-43-41.txt)
[Crash_2021_5_18_10-48-18.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6502470/Crash_2021_5_18_10-48-18.txt)
[Crash_2021_5_18_11-5-46.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6502471/Crash_2021_5_18_11-5-46.txt)
[Crash_2021_5_18_11-28-2.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6502472/Crash_2021_5_18_11-28-2.txt)

**LS Version**
3.2.1

**Describe the bug**
The game crashes when heading from Markarth towards the spot with the Jade Warrior 2

**To Reproduce**
Travel to Markarth by carriage
Walk past the bridge, towards the mountain

**Expected behavior**
The game doesn't crash

**Additional context**
This happens in the exact same spot as #235 but the game also crashes when taking the long way around.

**Comment by CocoBunHun** [comment]
I think I got this crash in a previous version. Have you went inside of Markarth yet? 
What fixed it for me was to travel to Markarth, go inside (I let the scene that happens when you first enter play out), and then head towards that area.

**Comment by nicobonada** [comment]
I hadn't gone inside Markarth when the crash happened. I'll try doing that when I start a new character.

**Comment by fantacinni** [comment]
Having the same issue. Solved by:
1. Open Cathedral Asset Optimizer, go to "Meshes" tab, check "Process meshes" and "Medium optimization" to optimize "SSE Organic Factions Extension" folder.
2. Enter Markarth before doing anything in the reach as CocoBunHun mentioned.
![Capture](https://user-images.githubusercontent.com/10670532/120539379-1bd3ef00-c41a-11eb-9150-16a545ba258b.PNG)

**Comment by ForgottenGlory** [comment]
Fixed 3.3.0
