### ISSUE TITLE
Invisible arms with the Hammerfell Garb in first person

### ISSUE THREAD

**Issue by PocketPhoenix** [ForgottenGlory/Living-Skyrim-3#358]
**LS Version**
3.2.1

**Describe the bug**
Started as an Alak'r member with the "Hammerfell Garb". The arms in first person seem to be invisible. Can only see floating hands.

**To Reproduce**
Steps to reproduce the behavior: Put on Hammerfell garb and check first person

**Expected behavior**
Visible arm textures in first person

**Screenshots**
![enb2021_5_18_19_38_51](https://user-images.githubusercontent.com/83901495/118699527-ecb26080-b811-11eb-9c03-8c4539e30df0.jpg)

Fresh savegame with the outfit on:

[Hammerfell garb bug savefile.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6503285/Hammerfell.garb.bug.savefile.zip)

**Comment by celadoneiron** [comment]
Patch in dev patches channel.

**Comment by ForgottenGlory** [comment]
Fixed 3.3.1
