### ISSUE TITLE
Trading Iron Arrows to Auri Crashes to Desktop

### ISSUE THREAD

**Issue by Sederien** [ForgottenGlory/Living-Skyrim-3#359]
[Crash_2021_5_22_22-52-33.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6526531/Crash_2021_5_22_22-52-33.txt)
[Crash_2021_5_22_22-49-53.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6526532/Crash_2021_5_22_22-49-53.txt)
[saves.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6526536/saves.zip)

**LS Version**
3.2.1

**Describe the bug**
Talk w/ Auri. Select "I'd like to trade with you" (or the dialogue choice resembling that). Select player inventory, Iron Arrows, and I was attempting about 120 out of 150-odd. Immediate crash upon hitting enter or clicking enter.

**Expected behavior**
Arrows go into Auri's inventory as with any container. Save and both crash logs (same event, tries 1 and 2) attached.

**Comment by Sederien** [comment]
SPECIFICALLY:

Bug only occurs when trading a partial amount of arrows. Just clicking okay is fine, apparently.

**Comment by ForgottenGlory** [comment]
Will fix when fix is found
