### ISSUE TITLE
Issues with giving spell tomes to Auri 

### ISSUE THREAD

**Issue by DustyLeon** [ForgottenGlory/Living-Skyrim-3#360]
**LS Version**
3.2.1

**Describe the bug**
Giving Auri a spell tome removes that spell from the character with a message "Can't learn from a container." 

Secondarily, reloading an earlier save then leaves you with a tome with a double learned %'s (see screenshot), though restarting fixes this. 

**To Reproduce**
Trading either the flames or healing tome to her will cause this. 

**Expected behavior**
In 3.2.0, Auri learned and used new spells without issue. 

![ScreenShot296](https://user-images.githubusercontent.com/83781072/119230109-ce39b700-bae8-11eb-9a36-ce7f263c1a0d.png)
[saves.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6526585/saves.zip)

**Comment by ForgottenGlory** [comment]
Will fix when fix is found
