### ISSUE TITLE
Crash to desktop on trying to save

### ISSUE THREAD

**Issue by lorenzom** [ForgottenGlory/Living-Skyrim-3#361]
[Crash_2021_5_23_13-25-47.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6527973/Crash_2021_5_23_13-25-47.txt)
[Saves.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6527985/Saves.zip)

**LS Version**
3.2.1

**Describe the bug**
On trying to save the game crashes, whether using f5 or manual save.

**To Reproduce**
Try f5 save or manual saving

**Expected behavior**
Game saves and continues playing

**Comment by OverarchUpwardNullify** [comment]
Try running mo2 as administrator and just to confirm can you check the read\write permissions on your save location. 
The saves are usually in a location like D:\Living Skyrim\profiles\Living Skyrim 3\saves

**Comment by lorenzom** [comment]
Thanks for commenting.
The damage was also retroactive where even saves made before this now suddenly couldn't save, all the way back to the the first save. 
Ran as admin without any change.
Read and write permissions are full, no restrictions in place. 
Eventually came up with a solution. Seemed to be script related. 
Loaded a save before this, then in console ran player.kill command, then load this save, run player.kill, then load this save again. After this was able to save again.
