### ISSUE TITLE
Trees (specifically ELOS Oaks Mixed Greens) outside Solitude Sawmill missing distant textures

### ISSUE THREAD

**Issue by mnatler** [ForgottenGlory/Living-Skyrim-3#362]
**LS Version**
3.2.0

**Describe the bug**
The trees are purple when viewed from a distance. They go back to normal once you get closer. According to the console all the trees with missing textures are from ELOS Oaks Mixed Greens.

**To Reproduce**
Go to Solitude Sawmill

**Expected behavior**
Non-purple trees

**Screenshots**
![screenshot_8806](https://user-images.githubusercontent.com/82017800/119272342-1acae280-bc0e-11eb-9fad-54183b809a7c.png)

**Comment by LunarDelta** [comment]
![ScreenShot271](https://user-images.githubusercontent.com/29786040/120069612-d2b81f80-c054-11eb-9029-468cd69f046f.png)
Can confirm this happens, and it looks really jarring when there's a lot of them.

**Comment by ForgottenGlory** [comment]
Fixed 3.3.0
