### ISSUE TITLE
A possibly very easy solution to the dual flurry "extreme weaponspeedmult" problem

### ISSUE THREAD

**Issue by AstridCone** [ForgottenGlory/Living-Skyrim-3#363]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
v3.2.1

**Describe the bug**
The dual flurry perks adds 1.20 and 1.35 onto your left and normal weaponspeedmult. The first isn't a problem (0 weaponspeed is equivalent to 1, and 1.20 is correctly 20% faster), the second interacts poorly with the fact that without the perks you already have more than 0 weaponspeedmult depending on your agility attribute.

I don't know if we have or what fix we have to the general weaponspeedmult problem, which is stuff like dual flurry, the shout elemental fury and etc add 1.XX onto your 0 weaponspeedmult and make it go haywire. But it seems to me that AVA, as the nexus page for the mod says, has a fix like that incorporated, which is why I think the root of the problem is that AVA and the Vokrii perks are not interacting as intended.

So to me the fix would simply be this: change the values of the dual flurry perks to 0.20 and 0.35 for the weaponspeedmult, and leave leftweaponspeedmult alone. Though preferrably I would have liked it if agility affected both weaponspeedmults and the proposed dual flurry values also affected both, so that the attack speed portion of agility would actually benefit a dual wield character.

**To Reproduce**
Be dual wielding, it doesn't matter the weapon type or if it is a vanilla, expansion or modded weapon. If you then have either ranks of the perk, what I've described will take effect. The perks only apply when you have a 1 handed melee weapon in either hand, and "player.getav weaponspeedmult" & "player.getav leftweaponspeedmult" reflect what I have described

**Expected behavior**
N/A, descriped alongside the bug

**Screenshots**
Below are screenshots of me going down the rabbit hole on the Discord, set in motion by tjbassoon, which may or may not provide additional context
![Weaponspeedmult 1](https://user-images.githubusercontent.com/69372766/119280637-8fb01380-bc32-11eb-97c3-5509cc8206fe.PNG)
![Weaponspeedmult 2](https://user-images.githubusercontent.com/69372766/119280639-92ab0400-bc32-11eb-89ac-283094c49277.PNG)

**Additional context**
I just really hope this is an alright report, not really fucking annoying to read and/or interpret. I'll probably take the initiative to report whatever other bugs I come across, because it feels nice I managed to get this funky bug down with words

**Comment by AstridCone** [comment]
I'd say its moderate, since It stinks on dual wielding characters in general. I get it though, who the hell plays dual wield characters anyway

**Comment by AstridCone** [comment]
Ok here is a result I had to check. This bug does **not** occur if you don't set up AVA, because then your weaponspeedmult will be 0. Because we don't have another weaponspeed fix in this list I guess? So I guess my fix would also require that a base weaponspeeldmult av be 1 with or without AVA, because if not my fix would actually make non-ava characters dual flurry perk make their dual wield strikes 80% slower (0+0.20)

I don't know anymore

**Comment by AstridCone** [comment]
I honestly don't know what could possibly be done here besides making some custom modded script that changes the perk effect to 1.20 or 0.20 based on whetever or not you've set up your attributes or not

**Comment by celadoneiron** [comment]
I've shared a fix in the dev patches channel. It should prevent weaponspeedmult from breaking, and also apply Agility attack speed bonuses to the left hand as well.

**Comment by ForgottenGlory** [comment]
Fixed 3.3.1
