### ISSUE TITLE
Atronach standing stone zeros magika regeneration.

### ISSUE THREAD

**Issue by catapsis** [ForgottenGlory/Living-Skyrim-3#365]
**LS Version**
v3.2.1

**Describe the bug**
According to the Mundustar mod page, the Atronach standing stone is supposed to come with a 75% lower magika regeneration rate in combat. In game, the regeneration rate seems to be 100% lower such that magika doesn't regenerate in combat.

**To Reproduce**
Acquire the Atronach standing stone, use some magika in combat, and observe that the bar does not refill.

**Expected behavior**
Magika should refill at 25% the normal rate during combat rather than not at all.

**Additional context**
Switching standing stones restores in-combat magika regeneration. Tested on the off chance that it was a weird, unrelated bug.

**Comment by ForgottenGlory** [comment]
Fixed 3.3.0
