### ISSUE TITLE
Buggy Female Vigilant clothes

### ISSUE THREAD

**Issue by GravenImages** [ForgottenGlory/Living-Skyrim-3#366]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
3.2.1

**Describe the bug**
The female version of the Vigilant armor in Stuhn Ravine seem bugged. Looks like they have physics applied to them, and it causes an NPC to look quite odd when sitting.

**To Reproduce**
Go to Stuhn Ravine and look at female NPCs.

**Expected behavior**
No physics.

**Screenshots**

![Stendarr bug](https://user-images.githubusercontent.com/81875512/119575733-b5453600-bd74-11eb-91bf-a0a93f6e02bc.png)

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**

[saves.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6542655/saves.zip)

**Comment by celadoneiron** [comment]
This looks like the bodies are built for a physics preset but are freaking out because XPMSSE isn't installed. According to the comments on [the Vigilant CBBE patch page](https://www.nexusmods.com/skyrimspecialedition/mods/43676?tab=posts), all the outfits with optional 3BBB versions are messed up in the current release, even if you build the non-3BBB version.

**Comment by ForgottenGlory** [comment]
Will fix when mod is fixed

**Comment by celadoneiron** [comment]
I think it may be possible to fix this by overriding with the BodySlide files from version 1.2.0 for the BodySlide files and keeping the .esp and male outfits and so on from 1.4.2. Version 1.3.0 was when 3BBB support was added, and that's what broke things (the supposedly non-3BBB versions of outfits with 3BBB versions are still using 3BBB bones, so they break), so rolling back to the release before that should sort it out.

**Comment by ForgottenGlory** [comment]
Testing fix in 3.3.1
