### ISSUE TITLE
Freeze then CTD in LS 3.2.1

### ISSUE THREAD

**Issue by chirpingbird** [ForgottenGlory/Living-Skyrim-3#368]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

Sadly, no crash reports are generating with this issue.

If possible, please also attach a copy of your most recent save before the issue occurred.**

[saves.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6543494/saves.zip)

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
Put the version of the list you are on here.

3.2.1

**Describe the bug**

I've been playing 3.2.1 for a few days now and it seems way more stable than 3.2.0 for me. I was having lots of crashes to desktop on the earlier version. That said, I'm a few days in now, at level 12 and started to have crashes to desktop again. They seem a little different though - instead of immediately crashing, the screen freezes for a few seconds first, then crashes to desktop. And there are no crash logs when it does that. I'm not sure if it's something I'm doing wrong like saving at wrong times or if it's just a bug. I've been very conscious of saving before load screens and not after, but I also save after combat or after a large inventory organizing etc. I don't know how to tell if scripts are running or not to avoid saving while scripts are running. Sorry if this is the wrong place to report, still just learning.

**To Reproduce**

Honestly have no idea. This may be a coincidence but all of the CTDs I've experienced in both 3.2.0 and 3.2.1 have all been inside Nordic ruins.

**Expected behavior**

**Screenshots**

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**

**Comment by chirpingbird** [comment]
Tried going back a few saves and trying again. Once I get into Dead Man's Respite it happened again (after a little while, not immediately, but still while in the first room.) Here are the other two saves I tried:

[earlier saves.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6543570/earlier.saves.zip)

**Comment by chirpingbird** [comment]
I think this is something with my saves, so far after reverting to a previous save, I haven't been able to repeat it. I wish I knew what I'm doing wrong with saving.

**Comment by TwistedModding** [comment]
wait 30-60 seconds after a loading screen, and dont save more than once in the same cell(unless you're in the Skyrim worldspace)

**Comment by ForgottenGlory** [comment]
Can't be fixed without a crash log
