### ISSUE TITLE
Game will not start

### ISSUE THREAD

**Issue by wolfeagle123** [ForgottenGlory/Living-Skyrim-3#369]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
Put the version of the list you are on here.
_Version 3_
**Describe the bug**

After installing the mod list and opening mod organizer through the Living Skyrim folder I have a notification that says "You have one or more script extender plugins which failed to load!" clicking on the notification it says specifically "  • Couldn't load EngineFixes.dll (SSE Engine Fixes (skse64 plugin)). A dependency DLL could not be found (code 126). 
Ignoring that notification I clicked play on living skyrim and was stuck on a loading screen that wouldn't end before the start menu even arrived. All I could see was the Living Skyrim menu but nothing else

**To Reproduce**

I have reset my computer and tried opening the program several times, even reinstalling SKSE but nothing works

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/84893038/119769732-fe86aa00-be88-11eb-86f0-bf709dcd7562.png)

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**

**Comment by celadoneiron** [comment]
Did you follow the instructions in the readme about copying over the Game Folder Files contents?

**Comment by wolfeagle123** [comment]
Where is the readme file? I cannot seem to find it

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by celadoneiron** [comment]
https://www.fgsmodlists.com/living-skyrim

It would have opened in your browser when you first downloaded the list and again when WJ finished installing. Follow all the instructions there, including the instructions regarding the MCM settings. The game should start properly after that.
