### ISSUE TITLE
LotD Craftloot does not work in Museum Safehouse

### ISSUE THREAD

**Issue by VyktoryJaye** [ForgottenGlory/Living-Skyrim-3#37]
**LS Version**
3.0.0 Beta 1

**Describe the bug**
Craftloot set to Prompt and Restricted should still allow Craftloot to work in LotD added locations, such as the Museum Safehouse. This doesn't work at any of the stations.

**To Reproduce**
Steps to reproduce the behavior: Attempt to craft at any station in the Museum Safehouse, and note the lack of Craftloot.

**Expected behavior**
Craftloot to ask if you wish to stow items within itself.

**Screenshots**
Not Applicable, but I will give them if neccessary.

**Comment by ForgottenGlory** [comment]
I'm wondering if this is related to the Legacy Safehouse Plus mod not being updated to account for v5.4.x of LOTD. Could also be related to the MCM for LOTD being automated and setting craftloot to prompt. Maybe try manually setting that option in the MCM and see if it works afterwards?

**Comment by Horbath** [comment]
I also have this happen on all new LS3 beta 2 game starts. I know what fixed it for me was go into the MCM and disable the craftloot option then reenable it.

**Comment by ForgottenGlory** [comment]
Temporarily turned off MCM Automation for LOTD Craftloot until we can fix it for Beta 3
