### ISSUE TITLE
Black Fix Glitch

### ISSUE THREAD

**Issue by wolfeagle123** [ForgottenGlory/Living-Skyrim-3#370]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
LS3

**Describe the bug**
Several NPC's have the annoying black face glitch and I can't figure out how to fix it. The characters so far I've noticed are Idolaf Battle-Born, the Priest of Arkay guy in Whiterun, I think Balgruuf's housecarl and one of the merchants in Solitude, I believe it's Advaar. 

**To Reproduce**

**Expected behavior**
An explanation of how to fix the black face. I am new to modding and never used the creation kit so if that's needed I will need a lot of instructions

**Screenshots**

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**

**Comment by ForgottenGlory** [comment]
Invalid, include screenshots of affected NPCs selected in console
