### ISSUE TITLE
Hang when entering Red Eagle Redoubt - Save attached

### ISSUE THREAD

**Issue by jolietrob** [ForgottenGlory/Living-Skyrim-3#372]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
3.0.1

**Describe the bug**
When I click the door to open the area Red Eagle Redoubt from Red Eagle Ascent the door animation plays, the screen goes dark with only the character level showing in the upper right corner as if the new area is loading but around the time I would expect the new area to load the screen goes completely black. Checking task manager shows Skkyrim not responding and the only way to get out is to use taskkill /f /fi "status eq not responding"

**To Reproduce**
Click to open door to Red Eagle Redoubt

**Expected behavior**
The next area Red Eagle Redoubt should load

**Screenshots**

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**
I have worked backwards through several saves inside Red Eagle Ascent but all will hang as described above when trying to enter Red Eagle Redoubt. I can turn around and exit Red Eagle Ascent no problem and re-enter as well but then when I try to enter Red Eagle Redoubt I experience
[Save892_EEA79C78_0_4479736F6E_RedEagleRedoubtWorld_062239_20210529035110_17_1.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6565749/Save892_EEA79C78_0_4479736F6E_RedEagleRedoubtWorld_062239_20210529035110_17_1.zip)
 the same hang.

**Comment by ForgottenGlory** [comment]
Unable to replicate, let me know if this persists after the 3.3.0 update
