### ISSUE TITLE
Horses randomly spawn rugs when ridden

### ISSUE THREAD

**Issue by violet-forest** [ForgottenGlory/Living-Skyrim-3#375]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**
[RecentSave.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6620131/RecentSave.zip)

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
LS v3.2.1

**Describe the bug**
While riding horses, rugs will randomly spawn in the air.

**To Reproduce**
Finish Convenient Horses quest and ride horse. It will happen randomly.

**Expected behavior**
Riding a horse with no rugs spawning.

**Screenshots**
![20210608191353_1](https://user-images.githubusercontent.com/85591718/121270170-2fa2a980-c88f-11eb-8ba8-1d8d6f1e7eab.jpg)

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**

**Comment by ForgottenGlory** [comment]
So this happens when you give a Campfire backpack to a follower (or maybe horse, in this instance). I'm not aware of a fix for it - best option is to make sure they don't have a backpack and instead give them Bandoliers. Will fix if a fix is found.
