### ISSUE TITLE
3DNPC quest path blocked by CACO ingredient changes (third-party patch available)

### ISSUE THREAD

**Issue by celadoneiron** [ForgottenGlory/Living-Skyrim-3#376]
**LS Version**
3.2.2.

**Describe the bug**
The Interesting NPCs quest "Birds of a Feather" has an optional route allowing the player to use a Charred Skeever Hide in the place of another ritual ingredient, but this path is not available because CACO replaces all instances of Charred Skeever Hide with Charred Skeever Meat.

**To Reproduce**
Attempt to play through the Birds of a Feather quest and collect ingredients for the non-murdery option. Charred Skeever Hide cannot be found and will be swapped to Charred Skeever Meat if you add it to your inventory using the console.

**Expected behavior**
Completing the quest both ways should be possible.

**Additional context**
A fix for this issue is included in the CACO-3DNPC patch from [QUASIPC](https://www.nexusmods.com/skyrimspecialedition/mods/18369). This patch also integrates CACO changes to other parts of 3DNPC, so if there are other cases like this the patch should take care of them as well.

**Comment by ForgottenGlory** [comment]
Fixed 3.3.0
