### ISSUE TITLE
Enchant Arrow spell's description is gibberish

### ISSUE THREAD

**Issue by mnatler** [ForgottenGlory/Living-Skyrim-3#378]
**LS Version**
3.2.2

**Describe the bug**
Screenshot is fairly self-explanatory. All of the "enchant arrow" spells have the bug. The spell tomes vendors sell for them have an identical description.

**To Reproduce**
Obtain spell

**Expected behavior**
A normal spell description

**Screenshots**
![screenshot_15062021_18333](https://user-images.githubusercontent.com/82017800/122112749-d821b200-ce29-11eb-8081-a6af3a0d2761.png)

**Additional context**

**Comment by ForgottenGlory** [comment]
Fixed 3.3.0
