### ISSUE TITLE
Some craftable items are insanely overvalued.

### ISSUE THREAD

**Issue by VyktoryJaye** [ForgottenGlory/Living-Skyrim-3#38]
**LS Version**
3.0.0 Beta 1

**Describe the bug**
Some craftable items are insanely overvalued, both to buy and to sell. For example, there are a variety of material cheap items that give massive amount of gold.

**To Reproduce**
Steps to reproduce the behavior: Sort craftable items by value, and see that some are way over-valued for their material cost.

**Expected behavior**
Balanced values.

**Screenshots**
![SkyrimSE 2021-02-03 03-37-23](https://user-images.githubusercontent.com/77305453/106632128-86426300-65d1-11eb-838f-59c94b501b97.png)

**Additional context**
The attached screenshot is just one of the issues here. The duplication of this "Ranger Outfit Groin" is also intriguing.

**Comment by TwistedModding** [comment]
Reminder for Glory while he is updating next so he doesnt forget again. Synthesis' tmopatcher will fix A LOT of recipes. Any recipes it doesn't fix, we can either just wait for reports, or go in xedit and fix them after tmopatcher is ran

**Comment by ForgottenGlory** [comment]
Should be mostly fixed Beta 2, feel free to keep reporting specific items with issues after that comes out
