### ISSUE TITLE
CTD upon loading any sav e

### ISSUE THREAD

**Issue by GromitJr** [ForgottenGlory/Living-Skyrim-3#380]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`
[Crash_2021_6_18_17-33-37.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6678316/Crash_2021_6_18_17-33-37.txt)

If possible, please also attach a copy of your most recent save before the issue occurred.**
[Most recent save.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6678330/Most.recent.save.txt)

Sorry, brand new to this, so unsure if this is best way of adding save file ^^^

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
Put the version of the list you are on here.
3.0

**Describe the bug**

CTD upon loading save - short period of time on loading screen, then CTD

**To Reproduce**

Load save file

**Expected behavior**

The game to load as normal

**Screenshots**

N/A

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**

Game was working perfectly as of 08/06/21, have changed nothing since then.

**Comment by ForgottenGlory** [comment]
Your crashlog indicates a botched install. Reinstall the list through WJ.
