### ISSUE TITLE
Floating tree - Hillgrund's Tomb

### ISSUE THREAD

**Issue by Zyquis** [ForgottenGlory/Living-Skyrim-3#381]
**LS Version**
V3.2.2

**Describe the bug**
I have encountered a floating tree next to Hillgrund's Tomb in the Whiterun Hold.

**To Reproduce**
Approach the tomb and you will find a floating pine a short distance to the left of it.

**Expected behavior**
For the tree not to float.

**Screenshots**
![enb2021_6_19_11_45_58](https://user-images.githubusercontent.com/83829459/122639854-2b2e8a00-d0f4-11eb-9f8c-76d456b94b0b.png)

**Additional context**
N/a

**Comment by ForgottenGlory** [comment]
Fixed 3.3.0
