### ISSUE TITLE
Silent Moons Camp Overhaul installed multiple times

### ISSUE THREAD

**Issue by celadoneiron** [ForgottenGlory/Living-Skyrim-3#382]
**LS Version**
3.2.2(.1)

**Describe the problem**
Multiple versions of the mod [Serenity - A Silent Moons Camp Overhaul](https://www.nexusmods.com/skyrimspecialedition/mods/30019) are installed.

Serenity.esp, SailorMoonClub,esp, and LunarWeapons.esp are all installed and enabled, but you're only supposed to have either the Prefab or the Ikea version of the mod, not both. The Prefab version (Serenity.esp) comes with new versions of the vanilla weapons with the Lunar Forge enchantments merged into the one file. The Ikea version comes with one plugin for a minor edit to the camp, without all the features of the major camp overhaul (SailorMoonClub.esp), and another plugin, LunarWeapons.esp, which is only supposed to be used if you are using the Ikea version without running the patcher to generate Lunar-enchantment versions of all your non-vanilla weapons.

Right now we have two different Lunar Enchantment versions of every vanilla weapon, one from Serenity.esp and one from LunarWeapons.esp. There are also multiple overlapping statics in the Silent Moons Camp area, two versions of the same quest running at the same time, and so on.

I think the setup that would work best is with the Prefab version installed, then using the patcher from the Ikea version to generate enchanted versions of modded weapons (if desired) and removing any duplicate enchanted versions of vanilla weapons from the patch plugin if present. The patcher should generate new weapons with Serenity.esp as the master if that's the one that's enabled. But whether we patch the modded weapons or not, SailorMoonClub.esp and LunarWeapons.esp shouldn't be enabled.

**Comment by ForgottenGlory** [comment]
Will fix when LOTD patch is fixed to not require both as master
