### ISSUE TITLE
EZ2C Dialogue Menu not on Nexus anymore

### ISSUE THREAD

**Issue by danistahl** [ForgottenGlory/Living-Skyrim-3#385]
**LS Version**
6/6/2021 3.2.2

**Describe the bug**
File not found on Nexus
EZ2C Dialogue Menu-2246-3-1.rar (NexusDownloader+State|SkyrimSpecialEdition|2246|2926)

**To Reproduce**
Go to Nexus and try to get the file #2246

**Comment by ForgottenGlory** [comment]
lol
