### ISSUE TITLE
Shield of Valtheim bugged

### ISSUE THREAD

**Issue by Soullassar** [ForgottenGlory/Living-Skyrim-3#386]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`
[Crash_2021_6_26_20-24-43.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6720607/Crash_2021_6_26_20-24-43.txt)

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
Put the version of the list you are on here.
3.2.2.1
**Describe the bug**
So The Valtheim shield (found at fort valtheim) causes ctds and also cannot be equipped by the player character
**To Reproduce**
(Just to be clear the only follower I've tested this on is Bikhai from the Khajiit will follow mod)
#1- Place the shield inside follower bag and fast travel to a different location. The location I tested (because they were the only locations I had discovered), were from Whiterun, Riverwood, Helgen, Solitude
#2- Place the shield inside follower inventory. Exit out of the inventory. Talk to the follower and go back into follower inventory, and put the shield back into your inventory.
**Expected behavior**
#1 Should result in a crash after loading screen, though it also has resulted in permanent black screens too.
#2 Should result in an immediate crash to desktop
**Screenshots**
![image](https://user-images.githubusercontent.com/86534369/123524147-41be7d80-d6c0-11eb-912d-a6bffa45099d.png)
![image](https://user-images.githubusercontent.com/86534369/123524271-0a9c9c00-d6c1-11eb-9f9f-d518ece35fcd.png)

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**

**Comment by ForgottenGlory** [comment]
Trying to replicate this, can you post a screenshot of where the shield is obtained from in-game?
