### ISSUE TITLE
Arena - An Encounter Zone Overhaul links to wrong modpage

### ISSUE THREAD

**Issue by WitchGirlTamara** [ForgottenGlory/Living-Skyrim-3#387]
**Section**
Important Mods You Need to Know About
The Combat Mods
![image](https://user-images.githubusercontent.com/84421445/123846819-20ef6580-d916-11eb-9b4c-e2222a0d8f14.png)

**Description**
the link saying Arena - An Encounter Zone Overhaul actually leads to [Encounter Zones Unlocked SE
](https://www.nexusmods.com/skyrimspecialedition/mods/19608)

the link in the [modlist ](https://www.fgsmodlists.com/living-skyrim/living-skyrim-modlist) is correct.

**Comment by TwistedModding** [comment]
Fixed.
