### ISSUE TITLE
Freezing Entering Castle Volkihar Not Fixed (#302)

### ISSUE THREAD

**Issue by boyooo** [ForgottenGlory/Living-Skyrim-3#388]
**LS Version**
3.2.2.1

**Describe the bug**
Game freezes up and audio still plays. Screen is black.

**To Reproduce**
Fill the bloodstone chalice and return to castle volkihar.  Freezes upon loading.

**Expected behavior**
Screen goes black, audio present. 

**Screenshots**

**Additional context**
I found that this was an issue that was "fixed" in 3.2.0 but obviously it has not been fixed... 
I'm more than happy to upload my save but I need to be told how. Old #Bug report: #302

**Comment by ForgottenGlory** [comment]
Same as #302 , this bug report is missing necessary information - crash log, etc. Cannot fix until the bug report is filled out properly.

**Comment by boyooo** [comment]
There is no crash log since its just a black screen......
