### ISSUE TITLE
Save The Icerunner broken, Hargar's Journal not persistent

### ISSUE THREAD

**Issue by celadoneiron** [ForgottenGlory/Living-Skyrim-3#389]
**LS Version**
LS3.2.2.

**Describe the bug**
The required item to complete the saving-the-Icerunner path of Save The Icerunner does not spawn.

**To Reproduce**
(from Diode Diabolus in Discord)
- Conversed with the headsman and got directed to the Grotto in quest to kill Hargar. 
- Went to the Winking Skeever. Asked if there are rumours. And got directed to Ja-Ree. 
- Talked to Ja-Ree. Chose dialogue option "Should report you to the guards." 
- Conversed with Aldis, but no proof. 
- Returned to the Grotto. Couldn't find the journal on Hargar or around. 
- Went to Modpage and found the command "set STIHandHoldingEnabled 1."
- Followed the quest marker to the table on the top of the converted ship. But no journal to be seen.

**Expected behavior**
Journal should appear and allow quest to progress.

**Additional context**
This occurs because SkyRem - Iris sets the journal to "Initially Disabled" instead of "Persistent," for some reason, overwriting the changes made by Save the Icerunner and preventing the journal from ever appearing. I'm uploading a patch to the dev channel that should fix it.

**Comment by ForgottenGlory** [comment]
Fixed 3.3.0
