### ISSUE TITLE
Toccata Outfit

### ISSUE THREAD

**Issue by belkyrnn** [ForgottenGlory/Living-Skyrim-3#39]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
Living Skyrim 3 Beta 1

**Describe the bug**
Toccata is nude, not nevernude. So, may cause an issue for streamer or players that not expecting to see nude with everyone else is nevernude.

**To Reproduce**
1) Gain Toccata as a follower
2) Talk to Toccata
3) Select "I'd like to change an outfit of yours."
4) Select "I'd like to change your standard outfit."

At this point, Toccata will be completely nude.

Even if you give clothes to her and when changes her outfit, she will go nude briefly then put clothes on. Or if you don't give her any clothes, she'll stay completely nude.

**Expected behavior**
She should have a bra and underwear on like everyone else (nevernude setting).

**Screenshots**
Since nudity is involved, I'll not post screenshots, as it's easy to reproduce as steps outlined above.

**Comment by ForgottenGlory** [comment]
Fixed Beta 2
