### ISSUE TITLE
Breezehome One-Way Wall

### ISSUE THREAD

**Issue by Tychi101** [ForgottenGlory/Living-Skyrim-3#391]
**LS Version**
v3.3.0

**Describe the bug**
Breezehome has a one-way wall in the middle of the home.  You can pass through it when not visible, but can't pass through it when it is visible.

**To Reproduce**
Created a new game and selected Breezehome as the starting location.  

**Expected behavior**
No wall in the middle of Breezehome.

**Screenshots**
![image](https://user-images.githubusercontent.com/87244234/125174112-fc568180-e190-11eb-9e00-1b5231232b03.png)
![image](https://user-images.githubusercontent.com/87244234/125174192-974f5b80-e191-11eb-86d9-991fbdedf951.png)

**Additional context**

**Comment by celadoneiron** [comment]
Looks like we need the no-Breezehome option for Lux.

**Comment by ForgottenGlory** [comment]
Fixed 3.3.1
