### ISSUE TITLE
Bandits above Riverrun cause game freeze.

### ISSUE THREAD

**Issue by Tychi101** [ForgottenGlory/Living-Skyrim-3#392]
**LS Version**
v3.3.0

**Describe the bug**
Looking at the bandit camp above Riverrun with a bow drawn and bandits aggro'd causes a screen freeze.

**To Reproduce**
Go up the mountain behind Riverrun towards the bandits.  Shoot an arrow above their camp to get them to search for you.  Watch the camp until it freezes.

**Expected behavior**
No freeze.

**Additional context**

[Riverrun Crash.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6795970/Riverrun.Crash.zip)

**Comment by ForgottenGlory** [comment]
Invalid without crashlog
