### ISSUE TITLE
1 Handed weapons appear on the ground when equipped in left hand

### ISSUE THREAD

**Issue by roguesins** [ForgottenGlory/Living-Skyrim-3#394]
**LS Version**
3.3.0

**Describe the bug**
One handed Weapons equipped in left hand appear on the ground both when drawn and sheathed in 3rd person. Weapon stays static between player characters feet when attacking and moving. Shields are unaffected. 

**To Reproduce**
Equipped one handed weapon to left hand.

**Expected behavior**
Weapon should appear in left hand and move appropriately when player attacks or moves. 

**Screenshots**
![image](https://user-images.githubusercontent.com/81392570/125179844-05fbdb80-e1c9-11eb-94bd-65a282cd52c4.png)

**Comment by ForgottenGlory** [comment]
Testing fix for 3.3.1

**Comment by ForgottenGlory** [comment]
Fixed 3.3.1
