### ISSUE TITLE
Random door in a field outside of Whiterun.

### ISSUE THREAD

**Issue by xelphos** [ForgottenGlory/Living-Skyrim-3#4]
**LS Version**
LS3 Open Beta 1

**Describe the bug**
There is a random door all on it's own in a field just South West of the Whiterun stables. Doesn't lead anywhere, just plays the open and close animation.

**To Reproduce**
Go to Whiterun Stables, head south west just right of the Kings Trees.

**Expected behavior**
Shouldn't be there unless a building is missing.

**Screenshots**
https://i.imgur.com/5oo66fq.jpg
https://i.imgur.com/ANU2mhq.png
https://i.imgur.com/k07sroy.png
https://i.imgur.com/1jfOjwB.png
**Album Link:** https://imgur.com/a/4OM8Law

**Comment by TwistedModding** [comment]
Fixed

**Comment by ForgottenGlory** [comment]
Fixed Beta 2
