### ISSUE TITLE
Reading is Good does not boost skill gain nor give skill.

### ISSUE THREAD

**Issue by VyktoryJaye** [ForgottenGlory/Living-Skyrim-3#40]
**LS Version**
3.0.0 Beta 1

**Describe the bug**
Reading is Good should give a 4% boost per skill book read instead of providing a skill point; however, it does neither. This bug may be related to the books' renaming to have the skill in the beginning within parentheses.

**To Reproduce**
Steps to reproduce the behaviour: Read a skill book, then check the MCM for Reading is Good and see that there has been no change. Also, note that options enabled by default should notify you of the gain in skill boost.

**Expected behaviour**
MCM reports that there is some form of skill boost, and mod to tell you of such, as intended.

**Screenshots**
Shouldn't be needed, but can supply if so.

**Additional context**
As I mentioned, could be a book renaming issue, load order, or even just a missing patch.

**Comment by celadoneiron** [comment]
According to comments on the Reading is Good Nexus page, the official LOTD compatibility patch stops Reading is Good from working, because it's made for a different version of Reading is Good, and no patch is necessary for the current version.

https://forums.nexusmods.com/index.php?showtopic=9271763/#entry86834483

> I can confirm that if you use the DBM_ReadingisGood_Patch.esp from the Legacy of the Dragonborn Patches FOMOD installer, it will change the BOOK records to NOT provide a skill point, and therefore prevent this new version from working properly.
> 
> The current LotD patch is not designed for this version (SKSE) of Reading is Good, it's designed for the original (Legacy) version.
> 
> Simply remove it or disable the patch from your load order and Reading is Good (SKSE) should work fine.
> 
> Unless you did a Bash Patch, then the modified BOOK records would have been copied in to it also, and therefore you will also need rebuild your Bash Patch again, after disabling the RiG LotD patch.
> 
> Hope this is clear enough...

**Comment by ForgottenGlory** [comment]
Fixed Beta 2
