### ISSUE TITLE
Embershard mine ore vein blocking path previously unblocked in previous versions

### ISSUE THREAD

**Issue by PulsefireEzreal** [ForgottenGlory/Living-Skyrim-3#400]
![image](https://user-images.githubusercontent.com/80222523/125252432-fb6f3e00-e2bd-11eb-84e1-b72dc5deb2b8.png)

Should not be blocked by this ore vein. Embershard mine.
As well as this path.
![image](https://user-images.githubusercontent.com/80222523/125252744-543ed680-e2be-11eb-9a7d-c00a12eda4bd.png)

I also noticed that there are incredibly less bandits than before in there. Could be something changed after switching from the individual dungeons revisited to the full mod?

**Comment by ForgottenGlory** [comment]
Fixed 3.3.1
