### ISSUE TITLE
Possible Missing Textures in Bleak Falls Barrow

### ISSUE THREAD

**Issue by cmm093** [ForgottenGlory/Living-Skyrim-3#401]
![Screenshot 2021-07-12 034726](https://user-images.githubusercontent.com/13308288/125260601-1cd42800-e2c6-11eb-9a3b-70a2fae3ab21.png)
![Screenshot 2021-07-12 034639](https://user-images.githubusercontent.com/13308288/125260612-1fcf1880-e2c6-11eb-927e-33b4428200c5.png)
**LS Version**
3.3.0

**Describe the bug**
Possible missing textures on the crypts in Bleak Falls Barrow (they appear purple)

**To Reproduce**
Go to Bleak Falls Barrow in the opening room inside

**Expected behavior**
The crypts will be purple

**Screenshots**

**Comment by Exoticusgaming** [comment]
I have the same thing happening. I think the textures are missing for those parts of the column. 

<img width="430" alt="SMIM_Column01" src="https://user-images.githubusercontent.com/62580057/126717776-e545d8e7-8f56-4f99-afda-73b7f93d8c66.PNG">
<img width="433" alt="Mod Organizer_ SMIMFolder" src="https://user-images.githubusercontent.com/62580057/126717772-4d322ff3-74e0-4df0-9b91-d5734c606783.PNG">
<img width="836" alt="NifSkope Bone Dirt" src="https://user-images.githubusercontent.com/62580057/126717774-3ca67064-e5ae-4b01-817f-396f29d0f114.PNG">
<img width="836" alt="NifSkope Nordic Skeleton" src="https://user-images.githubusercontent.com/62580057/126717775-f1e9f4e2-fddb-42be-86e3-fed23ca9cc3c.PNG">

I extracted the missing textures files from SMIM into **"mods\Static Mesh Improvement Mod\textures\smim\dungeons"** and I am testing to see if that fixed the issue.

![image](https://user-images.githubusercontent.com/62580057/126719144-12683c13-5179-4d23-923a-fdc1efd26e33.png)

Edit: That seems to have fixed the issue.

![The Elder Scrolls V  Skyrim Special Edition Screenshot 2021 07 22 - 17 47 26 65](https://user-images.githubusercontent.com/62580057/126719215-c0706843-b899-4236-9d79-777d896d5154.jpg)

**Comment by TwistedModding** [comment]
thank you for the fix boss man @Exoticusgaming

**Comment by Exoticusgaming** [comment]
No problem.

**Comment by ForgottenGlory** [comment]
Fixed 3.3.1
