### ISSUE TITLE
Light Armour "Iron Fist" perk unequips Pugilist fists

### ISSUE THREAD

**Issue by celadoneiron** [ForgottenGlory/Living-Skyrim-3#402]
**LS Version**
LS3.3.0.

**Describe the bug**
Having the Light Armour perk "Iron Fist" will forcibly unequip hand-to-hand weapons from Pugilist due to a script from Vokrii. See the bug report ["game automatically de-equip hand-to-hand weapons"](https://www.nexusmods.com/skyrimspecialedition/mods/46425?tab=bugs) on the Hand-to-Hand mod page.

**To Reproduce**
Take the "Iron Fist" perk in the Light Armour tree and try to equip the Fists of the Pugilist.

**Expected behavior**
Fists remain fisted.

**Comment by ForgottenGlory** [comment]
Testing fix for 3.3.1

**Comment by ForgottenGlory** [comment]
Fixed 3.3.1
