### ISSUE TITLE
Floating grass at brightwood

### ISSUE THREAD

**Issue by WitchGirlTamara** [ForgottenGlory/Living-Skyrim-3#403]
**LS Version**
3.3.0

**Describe the bug**
floating grass at brightwood (the skyrim grandma mod)

**To Reproduce**
travel to brightwood and look to the side of the house.

**Expected behavior**
not floating grass

**Screenshots**
![image](https://user-images.githubusercontent.com/84421445/125285475-f8ef0180-e31a-11eb-8838-1ef4738e51cb.png)

**Additional context**
not sure if this is intended but there is also a hunter's camp at the same location. grandma has hunters hanging around her house because of that
![image](https://user-images.githubusercontent.com/84421445/125285742-423f5100-e31b-11eb-8bfe-0d121450aa0a.png)

**Comment by ForgottenGlory** [comment]
Fixed 3.3.1
