### ISSUE TITLE
cloaks mod graphics bug in ratway

### ISSUE THREAD

**Issue by WitchGirlTamara** [ForgottenGlory/Living-Skyrim-3#404]
**LS Version**
3.3.0

**Describe the bug**
ashlander's tribal wrap cloak from cloaks mod is invisible or almost invisible depending on angle 

**To Reproduce**
go to this location in the ratway warrens (beyond the ragged flagon) and look at the table. 
![image](https://user-images.githubusercontent.com/84421445/125298047-1a0a1f00-e328-11eb-8b8e-cba445bba72b.png)

**Expected behavior**
cloak not being visually bugged

**Screenshots**
![image](https://user-images.githubusercontent.com/84421445/125297177-4d987980-e327-11eb-8c42-ac5485896c70.png)

**Additional context**
other cloaks from the mod may have these visual bugs aswell.

**Comment by celadoneiron** [comment]
Glory, try running the assets for Cloaks of Skyrim Retextured through SSE Nif Optimizer - a bug report on the mod's nexus page suggests that may resolve the issue.

**Comment by ForgottenGlory** [comment]
Should be fixed 3.3.1
