### ISSUE TITLE
Double Door

### ISSUE THREAD

**Issue by TheCaptain91** [ForgottenGlory/Living-Skyrim-3#405]
Location: Soljund's Sinkhole
Bug: Miner's House door

![P_20210712_160839](https://user-images.githubusercontent.com/87318482/125301672-7d498080-e32b-11eb-8d1c-25e633b9cd62.jpg)

![P_20210712_160844](https://user-images.githubusercontent.com/87318482/125301642-77539f80-e32b-11eb-8612-62e96eecd870.jpg)

**Comment by ForgottenGlory** [comment]
Fixed 3.3.1
