### ISSUE TITLE
Installation Instructions contain bad, broken, and invalid link(s).

### ISSUE THREAD

**Issue by ghost** [ForgottenGlory/Living-Skyrim-3#406]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
3.3.0

**Describe the bug**

Sections like this either send you in circles, provide invalid information, or just generally confuse people. 

 "Also make sure you have followed the **Game Folder Files** step of this readme." which then links you to an invalid URL which then circles you back to where you were before.

**To Reproduce**

Go to https://www.fgsmodlists.com/living-skyrim and control F the above.

**Expected behavior**

Not dead links.

**Comment by ForgottenGlory** [comment]
Fixed.
