### ISSUE TITLE
Bounty targets for bounty notes not completing the bounty

### ISSUE THREAD

**Issue by Dace617** [ForgottenGlory/Living-Skyrim-3#407]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
3.3.0

**Describe the bug**
taking a bounty quest to kill a bandit via a bounty note marks the bandit as a quest target, however killing the bandit does not complete the quest and no trophy/proof of bounty item is placed on the bandit corpse to complete the quest leaving you with an incompletable bounty quest

**To Reproduce**
Steps to reproduce the behavior: Take a bounty quest from an inn keeper via the bounty note, try to complete the quest by killing the marked bandit

**Expected behavior**
According to the Headhunter mod page the bandit targeted for the bounty should have a trophy item to loot which is not present.

**Additional context**
This may also affect missive bounties, I have not tested that yet.

**Comment by Rahmiel** [comment]
This seems to be happening more than just from Inn Keepers. I have had issues, and GreatPadinski has had this issue on stream, both from Inn Keepers and from Stewards. The Bounty Quests can still be completed using the vanilla console commands setstage bq01 100, but you don't get any rewards from it.

**Comment by Rahmiel** [comment]
Another update, it seems this quest also bugs if you get it from ANY NPC, but not from the missives board. The quest not only bugs out by not producing the "trophy" it also does not allow for the capture part of the quest either. I tried a bounty from Hoth, from Inn Keepers, Directly from the Steward, none of those worked. The bounty from the Missives Board worked fine though and allowed for both options of completing the quest. To me, it seems that the Headhunter mod is not properly overwriting the vanilla version (which explains why the vanilla console command is working partially), but I'm no modder or anything and am only guessing based on past experiences with modding other games.

**Comment by ForgottenGlory** [comment]
Fixed 3.3.1
