### ISSUE TITLE
Nilheim increased enemy spawns fight the bandits there.

### ISSUE THREAD

**Issue by WitchGirlTamara** [ForgottenGlory/Living-Skyrim-3#409]
**LS Version**
3.3.0

**Describe the bug**
In nilheim the bandits fight each other. The increased enemy spawn bandits fight the normal ones. After the normal bandits are dead they are non hostile to the player

**To Reproduce**
1. talk to telrav across the bridge from nilheim and agree to help him
2. walk to nilheim with him
3. when he tells you he'll give you your reward after a few seconds he should attack you with his friends but instead the bandits start fighting among themselves.

**Expected behavior**
the bandits not fighting among themselves properly

**Screenshots**
![image](https://user-images.githubusercontent.com/84421445/125551668-d863e905-a758-4a8b-bfed-b25a51d87a88.png)
![image](https://user-images.githubusercontent.com/84421445/125552167-48a98fa2-bbab-4279-91fc-84a894b37dec.png)

**Additional context**
all the bandits seem to be part of the same player ally faction (see the screenshots) both the normal amd extra enemy spawn bandits.

**Comment by celadoneiron** [comment]
Fix in dev patches channel.

**Comment by ForgottenGlory** [comment]
Fixed 3.3.1
