### ISSUE TITLE
Visual bugs in Windhelm with Embers HD/XD

### ISSUE THREAD

**Issue by weronika0805** [ForgottenGlory/Living-Skyrim-3#41]
**LS Version**
LS3 Beta 1

**Describe the bug**
1. The fire brazier added by Embers XD in front of the Statue of Ysgramor at the Windhelm entrance does not have any fire attached to it, and in addition it seems despite the Embers/JK's Skyrim patch it is not properly navmeshed, as NPCs walk in the middle of the brazier and the statue of Ysgramor.
2. Right behind the statue and before Candlehearth Inn Entrance there's an ember just floating around, this one added by EmbersHD.

**To Reproduce**
Visit Windhelm, preferably at night.

**Expected behavior**
The brazier has a fire on, NPCs walk around it instead of inside it.

**Screenshots**
![enb2021_2_2_19_06_51](https://user-images.githubusercontent.com/78365583/106644772-d1d21e00-658b-11eb-86d4-bbc0112716d0.png)
![enb2021_2_2_19_06_58](https://user-images.githubusercontent.com/78365583/106644779-d4cd0e80-658b-11eb-875a-054e52369ada.png)
![enb2021_2_2_19_08_57](https://user-images.githubusercontent.com/78365583/106644782-d696d200-658b-11eb-8da3-624858df1d34.png)

**Comment by TwistedModding** [comment]
Fixed, esp in patch channel

**Comment by ForgottenGlory** [comment]
Fixed Beta 2
