### ISSUE TITLE
Forgotten Magic Redone SE spell Veil of Nature destroys current raised undead minions when cast

### ISSUE THREAD

**Issue by DrTedNelson** [ForgottenGlory/Living-Skyrim-3#413]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
3.3.0

**Describe the bug**
Casting the Forgotten Magic Redone SE druid spell Veil of Nature instantly kills any undead minions the player created using the "Reanimate Corpse" spell line.

**To Reproduce**
Use any "Reanimate Corpse" spell on an appropriate corpse to raise it as a minion. Cast Forgotten Magic Redone SE druid spell Veil of Nature. 

**Expected behavior**
To cast Veil of Nature and not have my reanimated undead minions die.

**Screenshots**
N/A

**Additional context**
Raising an undead minion AFTER Veil of Nature is active works correctly. It is only when an active undead minion is near when Veil of Nature is cast that the bug happens. I also tested this with the "Conjure Familiar" spell and casting Veil of Nature did *not* kill that summon.

After doing some Googling, this is apparently a variation of a bug that appears in other mods/vanilla Skyrim involving the interaction of cloak spells, Conjuration summon spells and the "WISpellDangerous" tag the magic effect uses - Veil of Nature is apparently a cloak spell. Saw other reports online of people able to fix this by changing keyword tags in spells.

**Comment by DrTedNelson** [comment]
[VeilofNaturebug.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6832702/VeilofNaturebug.zip)
save file with corpses nearby to test with. character has Reanimate Lesser Corpse and Veil of Nature spells.

**Comment by ForgottenGlory** [comment]
Fixed 3.3.1
