### ISSUE TITLE
Imagespace transitions from predatorvision.esp sometimes stop functioning, and create save file issues

### ISSUE THREAD

**Issue by tjbassoon** [ForgottenGlory/Living-Skyrim-3#416]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
3.x seems to be affected. Bug appeared in two users on 3.3.0

**Describe the bug**
On some sames the predator vision spells (hunter's night vision and predator vision) stop working. The hotkeys stop doing anything at all, and the spells only create sound, but do not change the image space in any way. I don't know why this begins happening, and is likely not totally due to the modlist, as I've read of this happening on totally different load orders.

**To Reproduce**
Unsure

**Expected behavior**
Hotkeys function like on a new character.

**Screenshots**

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**
It looks like a script in the save file starts to go haywire, and multiple stacks and frames with huntersvisionmaintainancescript being the primary issue, when the save is opened in the latest version of Fallrim Tools ReSaver. I took the following steps on two user's save files that resulted in the hotkeys and spells working properly, as well as all errors from ReSaver going away, and no suspended stacks in the save file.

OK, for anyone having issues with Predator Vision and Hunter's Vision (nightvision spells, lesser powers, and hotkeys) there is probably a problem in your save file. I have no idea what the cause is, because I use the nightvision hotkey power All the time in my game and haven't had issues, but here's how I've fixed it for two people here:

It's best to do this from a save in a relatively low-key environment. Inside an inn, qasmoke, player home, something like that. Make the save after standing still for about 30 seconds.

Open the save with Fallrim tools Resaver. It will probably give a warning about stacks and frames which may indicate a problem. If so, this fix might work for you.
(use the filter to find them easily by typing "hunters" in the filter field)

Expand "Script Definitions" and delete the following:
huntersvisionmaintainancescript
huntersvisionkeypressscript
huntersvisionscript

Expand "Active Scripts"
Highlight all huntersvision*
right click and select "terminate"

Load save in game and test the hotkeys (with ENB on). If it works, yay! Disable night vision before saving.

Save again, and open that save in Resaver and it should open clean with no errors. You should have no "huntersvision" related active scripts, and your Suspended Stacks trees should be empty.

It may be worth further exploring this issue when other users show similar behavior.
https://discord.com/channels/690583538210308106/690616522032545812/865601117881761792

https://discord.com/channels/690583538210308106/734283215044345927/865636843415404554

**Comment by ForgottenGlory** [comment]
Fixed 3.3.1
