### ISSUE TITLE
Infinitely scaling health from interaction between Forgotten Magic and Smart Cast

### ISSUE THREAD

**Issue by Quijiin** [ForgottenGlory/Living-Skyrim-3#417]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
3.3.0

**Describe the bug**
If you place Earthbound Weapon with the health increasing perk on two separate combo spells, then cast them both simultaneously the spell will function normally. When it runs out, however, your health will not reset to the normal. Using this you can infinitely scale your health up 25% at a time. 

**To Reproduce**
Place Earthbound Weapon on two separate combo spells from the Smart Cast mod. Cast both simultaneously, then wait an hour or two for EW to run out. You will notice your health does not return to the amount it was beforehand. 

Refreshing EW will not reproduce this behavior, and as long as you maintain EW this bug will not occur. It is only upon fading that your health will be locked permanently to its increased value.  

**Expected behavior**
Earthbound Weapon would increase health for the duration of the spell then health would return to its original value afterward

**Screenshots**

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**

**Comment by ForgottenGlory** [comment]
I'll allow it.
