### ISSUE TITLE
Stuck in npc conversation 

### ISSUE THREAD

**Issue by SeaSpongeXD** [ForgottenGlory/Living-Skyrim-3#418]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
3.3

**Describe the bug**
Once you enter an npc quest conversation you will be stuck as if the npc is talking even though they are not. The only buttons that do anything are k and b opening the follower menu and journal.

**To Reproduce**
Steps to reproduce the behavior: To reproduce behavior after completing the quest "The boy who cried wolf" start a conversation with Falk Firebeard.

**Expected behavior**
You will be completely stuck in conversation only able to look around.

**Screenshots**

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**
I successfully left the conversation by pressing k and ordering my followers to attack falk firebeard. This successfully stopped the conversation however every conversation after would lead to the same incident of being stuck in conversation.

**Comment by ForgottenGlory** [comment]
I'm unable to replicate this.
