### ISSUE TITLE
Krahvalok and Apotheosis will not go on display in Gallery

### ISSUE THREAD

**Issue by Leonineus** [ForgottenGlory/Living-Skyrim-3#419]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
3.3.0

**Describe the bug**
Krahvalok and Apotheosis from the Ice Blade of the Monarch Mod will not be placed in their displays. Attempting to place them manually has no effect, and if placed in the display drop off then they do not get placed on display - they just stay in the box until manually removed.

**To Reproduce**
Attempt to place Krahvalok and Apotheosis in their displays using the save attached (both are in the display drop-off box in front of you), either manually or by telling the display drop off box to place artefacts.

**Expected behavior**
For Krahvalok and Apotheosis to go where they're supposed to go.

**Screenshots**
n/a

**Additional context**
[saves.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6840704/saves.zip)

**Comment by ForgottenGlory** [comment]
Fixed 3.3.1
