### ISSUE TITLE
"Exhume Wolf" spell wolf textures messed up.

### ISSUE THREAD

**Issue by roguesins** [ForgottenGlory/Living-Skyrim-3#420]
**LS Version**
3.3.0

**Describe the bug**
Spell "Exhume Wolf" summons wolf body that has its textures misaligned and I think incomplete.

**To Reproduce**
Use spell "Exhume Wolf" to spawn the wolves body.

**Expected behavior**
Texture in proper alignment with wolves body.

**Screenshots**
![image](https://user-images.githubusercontent.com/81392570/126231902-04f89739-17a1-48cf-beaa-47d7972babc6.png)
![image](https://user-images.githubusercontent.com/81392570/126231942-94125bbd-7078-4c2f-abd7-72c3fe776c17.png)
![image](https://user-images.githubusercontent.com/81392570/126231974-f2b2a286-98d6-4f4d-b962-5a5e0cd6526f.png)

![image](https://user-images.githubusercontent.com/81392570/126232092-b479d7b3-1096-4203-a1eb-674e2a806e5b.png)

[Save218_4793F171_0_49736162656C6C65_BrokenHelmHollow01_010756_20210719215306_11_1.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6844119/Save218_4793F171_0_49736162656C6C65_BrokenHelmHollow01_010756_20210719215306_11_1.zip)

**Comment by ForgottenGlory** [comment]
Will fix when fix is found
