### ISSUE TITLE
left Hand weapon invisible/ Sheathed on Ground

### ISSUE THREAD

**Issue by Marteeen17** [ForgottenGlory/Living-Skyrim-3#423]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
3.3.0

**Describe the bug**
left hand weapon is invisible but can still attack with it, happens when dual wielding aswell

**To Reproduce**
Literally just downloaded the Modlist on 7/20/21 and started the game, happens every time I equip on LH slot

**Expected behavior**
Invisible Weapon/ Weapon appears sheathed on ground

**Screenshots**
https://imgur.com/qUaHtzz
https://imgur.com/WhvEH9J

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**
N/A

**Comment by Exoticusgaming** [comment]
I think the issue is caused by Simple Dual Sheath. It requires XPMSE (https://www.nexusmods.com/skyrimspecialedition/mods/1988), which requires FNIS.esp, but re-generating Nemesis with XPMSE, makes a dummy FNIS.esp, so XPMSE can run, according to this reddit post, https://www.reddit.com/r/skyrimmods/comments/fm35jm/nemesis_and_xpmse/


Edit: That seems to fix the issue:
![The Elder Scrolls V  Skyrim Special Edition Screenshot 2021 07 22 - 20 43 24 38](https://user-images.githubusercontent.com/62580057/126728636-00854de1-c613-4986-8a64-9f1cb6773c1c.jpg)
![The Elder Scrolls V  Skyrim Special Edition Screenshot 2021 07 22 - 20 58 52 26](https://user-images.githubusercontent.com/62580057/126729397-38efebee-3542-47ca-bfca-1743d8403770.jpg)

**Comment by Marteeen17** [comment]
Welp... Should've thought about that. I didn't at first because when I would try to run nemesis it would crash, also I'm a mage build.

I Find it strange that the Mod Author would leave out an essential skeleton mod like that. Thanks friend

**Comment by Marteeen17** [comment]
> 
> 
> I think the issue is caused by Simple Dual Sheath. It requires XPMSE (https://www.nexusmods.com/skyrimspecialedition/mods/1988), which requires FNIS.esp, but re-generating Nemesis with XPMSE, makes a dummy FNIS.esp, so XPMSE can run, according to this reddit post, https://www.reddit.com/r/skyrimmods/comments/fm35jm/nemesis_and_xpmse/
> 
> Edit: That seems to fix the issue:
> ![The Elder Scrolls V Skyrim Special Edition Screenshot 2021 07 22 - 20 43 24 38](https://user-images.githubusercontent.com/62580057/126728636-00854de1-c613-4986-8a64-9f1cb6773c1c.jpg)
> ![The Elder Scrolls V Skyrim Special Edition Screenshot 2021 07 22 - 20 58 52 26](https://user-images.githubusercontent.com/62580057/126729397-38efebee-3542-47ca-bfca-1743d8403770.jpg)

Welp, somehow didn't think about that. Thanks friend.

Weird how a Mod author would leave out such an essential mod like that

**Comment by Exoticusgaming** [comment]
No problem.

**Comment by Marteeen17** [comment]
> 
> 
> No problem.

Welp, it seems that installing XPMSE works only on Males and not Females for some reason... And I can't run Nemesis because it crashes when updating, I guess I'll just live with it until the Mod Author updates

**Comment by ForgottenGlory** [comment]
Fixed 3.3.1
