### ISSUE TITLE
lighting on character bug

### ISSUE THREAD

**Issue by Abdullahalothaim** [ForgottenGlory/Living-Skyrim-3#424]
**LS Version**
3.3

**Describe the bug**
lighting bug on some characters 

**To Reproduce**
put aela near a source of light 

**Screenshots**
https://cdn.discordapp.com/attachments/690616522032545812/867189604468523058/unknown.png

![image](https://user-images.githubusercontent.com/55106678/126410643-259a123e-d60d-48c1-96e9-62445a9a853a.png)

**Save**

[bodsaves.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6851891/bodsaves.zip)

**Comment by ForgottenGlory** [comment]
No idea on this one. Help wanted.
