### ISSUE TITLE
Update The Modlist Spreadsheet

### ISSUE THREAD

**Issue by Swiggo1** [ForgottenGlory/Living-Skyrim-3#425]
There are 2 issues I've found so far. The first one being a mod that's missing. "Gladys the Corgi - A Custom Dog Follower Mod" is included in the game but not in the spreadsheet. A link to that mod can be found here: https://www.nexusmods.com/skyrimspecialedition/mods/50164/. The second issue is the link to the mod "Nykal the master vampire - a standalone follower mod" does not work. Here is the broken link: https://www.nexusmods.com/skyrimspecialedition/mods/10052. P.S. celadoneiron#7183 told me to mention that they told me to report these issues here. Thanks.

**Comment by ForgottenGlory** [comment]
Will be done for 3.3.1
