### ISSUE TITLE
Devotee bonus loss remains on screen.

### ISSUE THREAD

**Issue by LeeDurant** [ForgottenGlory/Living-Skyrim-3#427]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
3.3

**Describe the bug**
Devotee of aedra loss remains on screen after accidental kill and reload of a save.

**To Reproduce**
None found

**Expected behavior**
text disappears after moment.

**Screenshots**

![image](https://user-images.githubusercontent.com/50924770/126848944-a2494700-8823-4319-aeb6-3689784c995a.png)

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**

**Comment by ForgottenGlory** [comment]
I am not aware of any way to consistently replicate or fix this, it seems to happen randomly. The only fix I'm aware of is to reload a save from before it appeared.
