### ISSUE TITLE
Gamepad Controls Bugged

### ISSUE THREAD

**Issue by Deegster** [ForgottenGlory/Living-Skyrim-3#428]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
v3.0

**Describe the bug**
When using a wired controller I have the following issues:

1) I am unable to open the menu to access inventory/spells/map/skills.

2) Trying to sneak causing a bug which makes the charecter freeze, this also causes a drop in stamina as if it is trying to do a roll. To get out of the freeze you can sheath/unsheath a spell. You will be able to move around again but won't be sneaking.

3) Use power/shout, there is also no keybinding for this.

I have used this controlled on numerous playthroughs and tested it on another game and it works fine and as expected.

**To Reproduce**
1) Any attempt to open this menu.

2) Whenever I press L3 to go into sneak. (I checked this is the correct key binding)

3) Whenever I press RB to use a power/shout. (RB should just be the default)
**Expected behavior**
1) The menu to appears so I can access inv/spells/map/skills.
2) To sneak.
3) To activate a power/shout.
**Screenshots**
![image](https://user-images.githubusercontent.com/87906087/126872963-ed45762b-158b-49e4-82f8-3e7c0026adcd.png)

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**
I activated the Gamepad++ mod in mod organiser, trying to play without turning this on causes more issues.

**Comment by TwistedModding** [comment]
read the readme, and read gamepad ++ mod page
