### ISSUE TITLE
Skeleton in Morvunskar with Gleamblossom Hollow key not spawning

### ISSUE THREAD

**Issue by Awooona** [ForgottenGlory/Living-Skyrim-3#429]
**LS Version**
3.0.0

**Describe the bug**
With the mod Gleamblossom Hollow, a key to the house is supposed to spawn on a skeleton in Morvunskar near the gleamblossoms. That skeleton is not spawning.

**To Reproduce**
Go to Morvunskar where said skeleton is supposed to spawn. (The Nexus page for Gleamgall Hollow shows a screenshot of this skeleton. The blood texture is on the ground in the right spot, but no skeleton)

**Expected behavior**
Skeleton to spawn in expected location

**Screenshots**
![BugReport](https://user-images.githubusercontent.com/65203985/126886936-c5792942-6ef6-4c5f-8e80-5e4a3cadc4d4.png)

**Comment by celadoneiron** [comment]
I'm looking into this - have you ever been in Morvunskar's interior before this on this save?

**Comment by Awooona** [comment]
Nope, it was like that on my first visit.

**Comment by celadoneiron** [comment]
I'm unable to replicate this on my end, but my guess is that the skeleton was caught by a spell or attack during your fighting in that area and its parts ended up scattered far away from its intended location.

**Comment by Awooona** [comment]
Ok, that makes sense. With the glitchiness that comes with high framerates
and Bethesda Quality it probably just clipped through the dungeon when it
got moved and fell into the void, which explains why I couldn't find it
elsewhere. Thanks for letting me know.

**Comment by celadoneiron** [comment]
Fix in dev patches channel.

**Comment by ForgottenGlory** [comment]
Fixed 3.5.0
