### ISSUE TITLE
Possible Missing Textures in Helgen after Starting Helgen Reborn

### ISSUE THREAD

**Issue by geo-cjd** [ForgottenGlory/Living-Skyrim-3#431]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
Put the version of the list you are on here.
LS 3.3.0

**Describe the bug**
Missing rock textures adjacent to the front gate of Helgen. This is after following the performance guide - I have not managed to replicate it prior to the performance guide, so am not sure if the issue exists prior (i.e. I was not at Helgen in a save pre performance guide).

**To Reproduce**
Go to Helgen after starting Helgen Reborn, and a rock texture will be missing near the front gate.

**Expected behavior**
Rock textures to load in - unsure of extent and whether this issue persists elsewhere.

**Screenshots**

![20210726113540_1](https://user-images.githubusercontent.com/87976301/126975782-87f29d97-9166-48d4-9a7b-cac52b9de1c0.jpg)

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**

**Comment by ForgottenGlory** [comment]
Testing fix 3.3.1
