### ISSUE TITLE
Nemisis missing files

### ISSUE THREAD

**Issue by TheMrGeeBee** [ForgottenGlory/Living-Skyrim-3#432]
**LS Version**
3.3

**Describe the bug**
Nemisis is missing FNIS.esp that is generated by Nemisis. And running Nemisis just crash. Also because of this´, many animations don't work as intended, and in game all Left Hand items is attached on the ground.

**To Reproduce**
Clean install of the modlist. Run Nemisis. No FNIS.esp. Open game equip a Left Hand weapon or shield and exit fighting mode. (pic 1)
Dodge also makes the character stucked in a pose (pic 2)

**Expected behavior**
FNIS.esp in plugins, Left Hand items should be visibile in the correct slot.

**Screenshots**
![The Elder Scrolls V  Skyrim Special Edition Screenshot 2021 07 26 - 13 40 36 37](https://user-images.githubusercontent.com/43795491/126983971-66bcc0a7-bb81-4b35-bb5a-c2e1926aef9c.png)

![The Elder Scrolls V  Skyrim Special Edition Screenshot 2021 07 26 - 13 41 02 87](https://user-images.githubusercontent.com/43795491/126983985-0007d3a3-c48e-48b5-bdd8-7f382dfe0288.png)

**Comment by ForgottenGlory** [comment]
Why are you trying to run Nemesis

**Comment by TheMrGeeBee** [comment]
Because the animations are all crazed up. Look at pic 2, that is when I try to Dodge

**Comment by ForgottenGlory** [comment]
Rule 11, also the dodge stuff is addressed in the Readme.

**Comment by TheMrGeeBee** [comment]
Same thing, it doesn't change after first dodge.
