### ISSUE TITLE
Laid to Rest Overhaul and Real Names

### ISSUE THREAD

**Issue by thehajo** [ForgottenGlory/Living-Skyrim-3#436]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
3.3.0

**Describe the bug**
Just something minor, due to the changes in the Laid to Rest overhaul, where it changes Laelettes name from "Laelette the Vampire" to just "Vampire", Real Names gives her another name, in this case for me Marguerite. 
**To Reproduce**
Kill "Laelette" in the Laid to Rest quest.

**Expected behavior**
Everybody is talking about Laelette, but you got a dead body called "Marguerite" there. Seems a bit weird to me.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/38141473/127079882-f31eef8a-35c3-4354-91dc-ab5838568d43.png)

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**

**Comment by celadoneiron** [comment]
Test fix shared in dev team patch channel. Thanks for noticing and reporting this. :)

**Comment by ForgottenGlory** [comment]
Fixed 3.3.1
