### ISSUE TITLE
Vokrii "Iron Fist" perk force-unequips Pugilist weapons

### ISSUE THREAD

**Issue by celadoneiron** [ForgottenGlory/Living-Skyrim-3#437]
**LS Version**
LS3.3.0.

**Describe the bug**
Taking the Light Armor perk "Iron Fist" will prevent you from being able to equip the hand-to-hand weapons from Pugilist because it unequips them automatically (in favour of the invisible unarmed weapon from the basegame that's just your bare hands).

**To Reproduce**
1. Get "Iron Fist" perk.
2. Get Pugilist weapons.
3. Equip Pugilist weapons.
4. Suffer.

**Expected behavior**
Equipping weapons should equip weapons.

**Additional context**
Possible fix in dev patch channel.

**Comment by ForgottenGlory** [comment]
Fixed 3.3.1
