### ISSUE TITLE
Unable to download xLODGen.82.7z (MegaDownloader+State|https://mega.nz/file/xdwmmKgA#I_KNynb4Fz0mrQV8bxBNlgw42KUykkk2VhM1RRkn5ts)

### ISSUE THREAD

**Issue by peter-schwier** [ForgottenGlory/Living-Skyrim-3#439]
**LS Version**
7/8/2021 3.3.0

**Describe the bug**
Cannot download a new installation.
Unable to download xLODGen.82.7z (MegaDownloader+State|https://mega.nz/file/xdwmmKgA#I_KNynb4Fz0mrQV8bxBNlgw42KUykkk2VhM1RRkn5ts)

**To Reproduce**
Try to install without any previously downloaded files.

**Expected behavior**
modlist probably needs to be updated to use xLODGen.83.7z

**Screenshots**
None

**Additional context**
None

**Comment by ForgottenGlory** [comment]
Fix in Discord
