### ISSUE TITLE
Activated Werebeast Blood has no texture

### ISSUE THREAD

**Issue by thehajo** [ForgottenGlory/Living-Skyrim-3#440]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
3.3.0
**Describe the bug**
The alchemy ingredient Activated Werebeast Blood has no texture. Neither in your inventory, nor out in the world.

**To Reproduce**
Step 1: Get Activated Werebeast Blood 
Step 2: Look at it
Step 3: You can't

**Expected behavior**
A texture

**Screenshots**
![grafik](https://user-images.githubusercontent.com/38141473/127413944-cfbd0cc1-e71c-47a8-b582-66c9a810b55b.png)
Here is a Screenshot from SSEEdit, not sure if that helps (I would've looked more into it with the Creation Kit, but that thing ain't working for me when started via MO2)
![grafik](https://user-images.githubusercontent.com/38141473/127414054-29c2ba8e-661f-4080-84d6-8b0208c49083.png)

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

Yeah i can't cause when i drop it in the world, it's kinda hard to find.

**Additional context**

**Comment by ForgottenGlory** [comment]
Fixed 3.4.0
