### ISSUE TITLE
Weapon speed fix missing file required for functionality

### ISSUE THREAD

**Issue by celadoneiron** [ForgottenGlory/Living-Skyrim-3#441]
**LS Version**
LS3.3.1.

**Describe the bug**
The weapon speed mult fix for dual flurry doesn't work because the mod it relies on to set weapon speed mult on game start isn't included in the list.

**Expected behavior**
Duel wield should be fixed.

**Additional context**
The fix relies on [this mod](https://www.nexusmods.com/skyrimspecialedition/mods/10741) being installed to set weapon speed mult up properly on game start.

**Comment by AstridCone** [comment]
Just as a reminder, the dual flurry perk still needs to be changed to a value of 0.20 and 0.35 and not 1.20 and 1.35 alongside this. And make sure this happens to the vokrii version of the perk effect and not the vanilla one, really just modify both to be safe, idk

**Comment by ForgottenGlory** [comment]
Fixed 3.4.0
