### ISSUE TITLE
Odd Enemy Spawning in Dawnstar

### ISSUE THREAD

**Issue by CypherAce** [ForgottenGlory/Living-Skyrim-3#442]
**LS Version**
3.3.1

**Describe the bug**
There seem to be Lynx/Snow Leopards and the like spawning in Dawnstar, I even had one enter or Spawn in the Inn itself.

**To Reproduce**
Steps to reproduce the behavior: Just hang around Dawnstar for awhile, go in and out of various buildings.

**Expected behavior**
This probably just shouldn't happen.

**Comment by celadoneiron** [comment]
Take a screenshot with one of the enemies in question selected in the console.

**Comment by CypherAce** [comment]
![Screenshot 2021-07-30 032055](https://user-images.githubusercontent.com/24900970/127624052-b3c407f6-5d68-4bc6-bd90-d53191aacffe.png)
![Screenshot 2021-07-30 032139](https://user-images.githubusercontent.com/24900970/127624060-71b013fd-bcda-4aa4-9b39-0a766aaa3903.png)
An example of some I killed and one that just happened.
