### ISSUE TITLE
Cannot properly acquire ingredient Charred Skeever Meat

### ISSUE THREAD

**Issue by thehajo** [ForgottenGlory/Living-Skyrim-3#444]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
3.3.0 (I know outdated, but i wouldn't be surprised if that bug is still present in 3.3.1)

**Describe the bug**
When buying the ingredient from a merchant (it will be listed under ingredients), it will instead land in your "food" inventory, with no way to use it in a recipe. Also using player.additem to give yourself the Charred Skeever Meat/Hide (CACO changes something there) will in either case result in getting a food item and not an ingredient.

**To Reproduce**
Buy Charred Skeever Meat.

**Expected behavior**
Being able to use it as an ingredient.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/38141473/127717233-4c96aaa9-29d6-41c0-9a5b-c0b8392fa698.png)
You can see in the screenshot that i also spawned in the correct item, but did end up with the food item (on the ground)

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**

**Comment by thehajo** [comment]
Had to reload an old save, so i decided to record a small video of it as well. Very strange.
https://youtu.be/8jrhg9lipS4

**Comment by celadoneiron** [comment]
This is not a bug. It is how CACO works. The one quest that I'm aware of that requires the Charred Skeever Hide item has a patch to make it use the right CACO ingredient, and all vendor inventories should be patched to not sell the Charred Skeever Hide item.

Which merchant had this item available for sale?

**Comment by thehajo** [comment]
![grafik](https://user-images.githubusercontent.com/38141473/127739814-707cebf8-ec25-4701-bdd5-cd8e9a449eb0.png)
I don't understand how CACO turns it into food tho, as you can see in my first screenshot, there is a INGR called Charred Skeever Meat. Oh well, as long as you can't buy it anymore, i guess it's fixed.

**Comment by celadoneiron** [comment]
The ingredient item is swapped for the food item when it enters your inventory.

As far as I can see in 3.3.1, Elgrim has no access to this ingredient (and neither does any other vendor).
