### ISSUE TITLE
Companions radiant quest "trouble in skyrim" can't be completed and points to nowhere.

### ISSUE THREAD

**Issue by WitchGirlTamara** [ForgottenGlory/Living-Skyrim-3#447]
**LS Version**
3.3.1

**Describe the bug**
Companions radiant quest "trouble in skyrim" to kill the leader of the winter war can't be completed and points to the middle of the room in the ship

**To Reproduce**
1. join companions
2. after vilkas/farkas shows you the sleeping quarters he'll give you a quest.
3. go do the quest and it should be impossible to finish

**Expected behavior**
these quests working properly, like bounties you get from jarl stewards.

**Screenshots**

**Additional context**
I tested after the winter war bandit leader didn't show up and the bounty from the jarl's steward worked fine

**Comment by ForgottenGlory** [comment]
I don't see any reason this shouldn't be working, should fixed as part of the fix for #449 though.
