### ISSUE TITLE
Wintersun reading is good compatibility patch broken

### ISSUE THREAD

**Issue by WitchGirlTamara** [ForgottenGlory/Living-Skyrim-3#448]
**LS Version**
3.3.1

**Describe the bug**
When you are a worshipper of xarxes and have read at least one skill book for the skill you're training/leveling your level goes up almost right away to the skill cap (for example my 2 handed skill going to the limit of 35 after only a few swings) this also happened with a pickpocket trainer who trained me to lvl 30+ in one time

**To Reproduce**
1. start as a breton (this lets you worship xarxes at the start of the game)
2. choose a skill with a low level
3. read the skill book for that low level skill
4. use the skill
5. the level is now way way higher

**Expected behavior**
worshipping xarxes should give the correct amount of  extra leveling speed.

**Additional context**
[on the nexus page of the mod it seems like others are having the issue aswell](https://www.nexusmods.com/skyrimspecialedition/mods/48310?tab=posts)
so it might be better to just remove the mod and make xarxes's bonus useless?

**Comment by ForgottenGlory** [comment]
Patch removed 3.4.0 - will look into alternatives in the future.
