### ISSUE TITLE
Guards infinitely rewarding player for captured bandit. 

### ISSUE THREAD

**Issue by Quijiin** [ForgottenGlory/Living-Skyrim-3#449]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
Put the version of the list you are on here.
3.3.1

**Describe the bug**
Capturing a bandit leader results in guards infinitely rewarding the player

**To Reproduce**

1. Capture a bandit leader from any radiant bandit quest
2. Bind him and take him to a guard
3. You will be able to tell the guard that "this is the bandit leader the jarl put a bounty on"
4. The guard will give you 25 gold, the quest will progress, and lead the bandit away
5. You will still be able to tell the guard that "this is the bandit leader the jarl put a bounty on" 
6. The guard will give you 25 gold and again try to lead the bandit away

This works even after you claim the full bounty from the Jarl or the steward

**Expected behavior**

Guards should stop offering rewards once the bandit is removed

**Screenshots**

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**

**Comment by ForgottenGlory** [comment]
Should be fixed 3.4.0
