### ISSUE TITLE
Crashing when saving.

### ISSUE THREAD

**Issue by Deszoke** [ForgottenGlory/Living-Skyrim-3#450]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`
No Crash Report Generated.

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
Put the version of the list you are on here.
LS 3.3.1

**Describe the bug**
Whenever I try to save it crashes without generating any crashlog. Sometimes it crashes when load the game.

**To Reproduce**
Don't really know.

**Expected behavior**
Save correctly.

**Screenshots**

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**

[Save41_64993245_0_507269736F6E6572_SolitudeWinkingSkeever_001002_20210801122259_7_1.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6914911/Save41_64993245_0_507269736F6E6572_SolitudeWinkingSkeever_001002_20210801122259_7_1.zip)

**Comment by celadoneiron** [comment]
I've loaded into the save that you attached, and I can save without crashing, so whatever is causing the issue seems like it isn't baked into the save itself at this point. Do the crashes happen on other saves as well, or is it only after this one?

**Comment by Deszoke** [comment]
They happen only on this one. If you can save maybe the problem is on my end but I don't really know what goes wrong. 2 fresh wabbajack installs and this keeps popping up. It also crashes when I die and sometimes when I load the save from Main Menu.

**Comment by Deszoke** [comment]
I have discovered another hint to why it would crash for me. Windows Event Log:
Log Name:      Application
Source:        Application Error
Date:          8/3/2021 2:56:36 PM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      DESKTOP-QHSI71E
Description:
Faulting application name: SkyrimSE.exe, version: 1.0.0.0, time stamp: 0x5dcae282
Faulting module name: ntdll.dll, version: 10.0.19041.1110, time stamp: 0xe7a22463
Exception code: 0xc00000fd
Fault offset: 0x0000000000051271
Faulting process id: 0x2c80
Faulting application start time: 0x01d7885e466bfc35
Faulting application path: E:\Modding\SSE Living Skyrim\Stock Game\SkyrimSE.exe
Faulting module path: C:\WINDOWS\SYSTEM32\ntdll.dll
Report Id: a7231016-b709-4149-adbe-d638faac363b
Faulting package full name: 
Faulting package-relative application ID:

**Comment by TwistedModding** [comment]
Crash Log
Please upload (drag and drop the file into this channel) the most recent crash log from your [Modlist install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash folder. The Files Generated folder can be found near the bottom of MO2's left pane.
