### ISSUE TITLE
Dark Knight Shield table is blocking the path in the Blue Palace

### ISSUE THREAD

**Issue by Exoticusgaming** [ForgottenGlory/Living-Skyrim-3#451]
**LS Version**
3.3.1

**Describe the bug**
The hall where the Dark Knight Shield is blocked by the table that the shield is on.

**To Reproduce**
Go to the Blue Palace and go right near the door to the Pelagius Wing where the Dark Knight Shield is.

**Expected behavior**
Path should not be blocked.

**Screenshots**
![The Elder Scrolls V  Skyrim Special Edition Screenshot 2021 08 02 - 04 07 01 71](https://user-images.githubusercontent.com/62580057/127908693-2979f210-3be4-4679-ad2a-21d4baee6959.jpg)

![The Elder Scrolls V  Skyrim Special Edition Screenshot 2021 08 02 - 13 55 07 52](https://user-images.githubusercontent.com/62580057/127910023-bafb6665-f258-4152-a091-cca268ad6d29.jpg)

**Comment by ForgottenGlory** [comment]
Fixed 3.4.0
