### ISSUE TITLE
Schneider's Sextant stuck on "Wait 2 hours"

### ISSUE THREAD

**Issue by thehajo** [ForgottenGlory/Living-Skyrim-3#452]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
3.3.0

**Describe the bug**
You can Schneider's Sextant to locate a possible relic within the same cell you are currently in. It will then give you a "Locate the Relic" quest. After doing so, a cooldown of 2 hours will activate. 
However, after using it, picking up the relic, waiting 2 hours, then using it again (in the same cell), picking up the relic and waiting another 2 hours, if you then try to use it, it will still throw the "Wait 2 hours" message at you.

**To Reproduce**
1. Use Schneider's Sextant 
2. Pick up relic
3. Wait 2 hours
4. Repeat steps 1-3
5. You will find yourself unable to activate it again

**Expected behavior**
To able to use it again, instead of being greeted with the 2 hour wait message every time, rendering this item useless.

**Screenshots**

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**
If put in Arkayn's Tool Bag, it will function without a problem (again), but this is due to the bug that you can use it without actually waiting 2 hours when inside the bag.
The save is obviously still in 3.3.0, so not sure if it's actually useful to you guys. At the moment i am in the Ragged Flagon, and there are 2 relics there, both behind the bar. One is the golden fork on the bottom left, the other one is the thieves guild amulet straight ahead in the middle. As soon as you pick up the second relic (having used the Sextant to "locate" it), the Sextant will stop working. The Thieves guild necklace can be picked up easily using the Nocturnal Shadow Power without making everyone aggressive, if you do want to test it.
[Saves_Hajo_Issue_452.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6932737/Saves_Hajo_Issue_452.zip)

**Comment by ForgottenGlory** [comment]
Were you waiting 2 in-game hours or two real hours?

**Comment by thehajo** [comment]
2 in-game hours, using the wait feature. This worked fine previously up until this point. However it seems a bug in the mod itself, and not the list, as i then also found a reddit post from 5 months ago with the same issue. And seeing how there is an easy workaround with Arkayn's Tool Bag, which even buffs it, i think this can be closed
