### ISSUE TITLE
Crashing constantly in Volskygge Passage

### ISSUE THREAD

**Issue by imfreakie** [ForgottenGlory/Living-Skyrim-3#454]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
3.3.1

**Describe the bug**
I have repeated crashes in Volskygg Passage and can't play 1 single minute without crashing altough I had almost no crash until now with 40h of gameplay.

**To Reproduce**
Just moving forward into the dungeon for a very short time.

**Expected behavior**
Finishing this crappy dungeon ? xD

**Screenshots**

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**
I have the impression the first part (the not "Volskygge passage") was stable, it's one time into the Volskygge passage that the game crash every minute.

[Crash_2021_8_7_13-37-18.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6949035/Crash_2021_8_7_13-37-18.txt)
[Save383_00000000_0_426F72686D6972_Volskygge02_010557_20210806183347_17_1.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6949039/Save383_00000000_0_426F72686D6972_Volskygge02_010557_20210806183347_17_1.zip)

I can provide more older saves if needed.

**Comment by ForgottenGlory** [comment]
Fixed 3.4.0
