### ISSUE TITLE
NPC's not attacking / not unsheathing their weapon.

### ISSUE THREAD

**Issue by JohannKnorst** [ForgottenGlory/Living-Skyrim-3#455]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
Living Skyrim 3.

**Describe the bug**
1 in 5 npc's (usually bandits) are not unsheathing their weapons and attacking. They do however agro on the player.

**To Reproduce**
Steps to reproduce the behavior: I just come up to a camp or any other dungeon and some of the NPC's just dont unsheath their weapons.

**Expected behavior**
They should unsheath their weapons and proceed to attack me.

**Screenshots**
I got not screenshots at the time ... but I think the problem is self-explanatory.

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**
I did disable the Ultimate Doge mod. But even after enabling it again, it did not fix the problem.

**Comment by ForgottenGlory** [comment]
Rule 11
