### ISSUE TITLE
SkyrimSE.exe system error when loading game

### ISSUE THREAD

**Issue by PancakeMastr808** [ForgottenGlory/Living-Skyrim-3#457]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

[Save274_44EF5029_0_56696E63656C6D6F204164696F7573_Tamriel_002328_20210802234133_13_1.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6950144/Save274_44EF5029_0_56696E63656C6D6F204164696F7573_Tamriel_002328_20210802234133_13_1.zip)

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
3.3.1

**Describe the bug**
When I try to load a save game I get a system error "A new guard page for the stack cannot be created". The loading screen continues to animate but hangs and acknowledging the error crashes skyrim. 

**To Reproduce**
Load my save file

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/88602475/128619263-a2e7114c-bd8d-476b-894f-150681374977.png)

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**

If I load a save significantly earlier the game loads as normal. I don't know if it matters but this has happened on two save files while doing the LOTD quest where the museum gets robbed.

**Comment by ForgottenGlory** [comment]
This is an out of memory crash. Generally can be fixed by increasing pagefile size. Visit the Discord for more info on how to do that if needed.
