### ISSUE TITLE
Great Village of Old Hroldan issues

### ISSUE THREAD

**Issue by seanpbelcher** [ForgottenGlory/Living-Skyrim-3#46]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
LS3 Beta 1

**Describe the bug**
Great Village of Old Hroldan has the following issues:
1) Interior of the Inn has these black planes appearing when looking in certain directions. Mesh issue?
![enb2021_2_3_03_56_09](https://user-images.githubusercontent.com/67465410/106736349-f5708500-65da-11eb-94c2-830887fe1b4f.png)
![enb2021_2_3_03_56_01](https://user-images.githubusercontent.com/67465410/106736380-fe615680-65da-11eb-983f-d9ce47a89880.png)
![enb2021_2_3_03_55_48](https://user-images.githubusercontent.com/67465410/106736408-06b99180-65db-11eb-9ebf-be8349029b80.png)
2) Floating lanterns outside
![enb2021_2_3_03_58_23](https://user-images.githubusercontent.com/67465410/106736466-1933cb00-65db-11eb-8254-390808873540.png)
![enb2021_2_3_03_58_33](https://user-images.githubusercontent.com/67465410/106736504-25b82380-65db-11eb-9561-7e3cadf49cb9.png)
3) legacy needs a patch
![enb2021_2_3_03_54_02](https://user-images.githubusercontent.com/67465410/106736589-3ff20180-65db-11eb-97cd-bb50ccf0eb8b.png)

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. Additionally, if your report applies to a specific object, make sure it is selected with the console open. Reports without this will be closed.

**Additional context**

**Comment by ForgottenGlory** [comment]
Fixed Beta 2
