### ISSUE TITLE
Missing first floor door to Skalei's Scrap in Helgen

### ISSUE THREAD

**Issue by stoudtlr** [ForgottenGlory/Living-Skyrim-3#461]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
3.4

**Describe the bug**
Skalei's Scrap in Helgen is missing the door on the 1st floor
**To Reproduce**
Go to Helgen and walk around Skalei's Scrap.  There's no door. Skalei's scrap is the two story building next to the watch tower the dragon lands on.
**Expected behavior**
Expect to see a door
**Screenshots**

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**
Skalei's Scrap is added by Alternate Perspective.  I TCL'd to the 2nd floor and entered that way.  Went down to the first floor and there was a door there and I could exit from it.  Only the entrance door from outside is missing.
![The Elder Scrolls V Skyrim_2021 08 11-19 50](https://user-images.githubusercontent.com/36058236/129117990-a14bb4cd-104b-4116-b2c4-9b3f4e3b9447.png)
![The Elder Scrolls V Skyrim_2021 08 11-19 50_1](https://user-images.githubusercontent.com/36058236/129117994-84b821e1-a1b6-419b-995a-847fd247fe8b.png)

**Comment by ChunkeeMunkee** [comment]
I believe this may be the same building I noticed during the Dev release test - if so, it appears there may be two slightly different building meshes in the same location.

stoudtlr - did you notice any flickering textures or geometry on that building? Might be noticeable on the woodwork at the corners of the building? This would also indicate more than one mesh in one spot.

**Comment by stoudtlr** [comment]
yep. you can clearly see the lines where they overlap in this screenshot without console menu up.
![The Elder Scrolls V Skyrim_2021 08 11-19 49_3](https://user-images.githubusercontent.com/36058236/129118447-b6a9613d-97c1-47cb-8c30-af639ffa78f7.png)

**Comment by stoudtlr** [comment]
It's just a load order issue.  Moved Alternate Perspective to bottom of list and the door was there and no overlapping meshes.  Another related thing I noticed is that the Helgen Reborn quest starts immediately on a new game.  There's a patch on AP's mod page so it doesn't start until after Helgen is destroyed.

**Comment by ForgottenGlory** [comment]
Should be fixed by 3.4.0.1
