### ISSUE TITLE
CharGen/Presets Folder Directory not generating on install of 3.4.0.1

### ISSUE THREAD

**Issue by Leonineus** [ForgottenGlory/Living-Skyrim-3#462]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
3.4.0.1

**Describe the bug**
When installing the latest hotfix, the SKSE > Plugins > CharGen > Presets file directory only populates as far as Plugins, which has all the other usual suspects - CampfireData, FISS etc, but no CharGen folder. This wasn't the case back on 3.3.1.

**To Reproduce**
Fresh install of 3.4.0.1 and look in file directory.

**Expected behavior**
I rather expected to be able to just stick my preset in there and get started, I guess.

**Screenshots**

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**
I did manage to fix it by going into the game and saving a preset and that created the folders, but it's a bit of a PITA to start the game, make a preset, close it again to put my own preset in and then finally restart the game again.

**Comment by Dace617** [comment]
Those folders won't be created until you save a preset, if you want to use an existing preset, the correct folder to place them is:
[Your LS3 install location]\mods\LS3 Community Presets\SKSE\Plugins\CharGen\Presets\

**Comment by Leonineus** [comment]
huh. Didn't know that directory was a thing but makes sense. Ta!
