### ISSUE TITLE
Performance patch issue

### ISSUE THREAD

**Issue by Xoveto** [ForgottenGlory/Living-Skyrim-3#463]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
3.4.0.1

**Describe the bug**
When opening texgenx64 it starts to load and says Bleak  Falls Temp has invalid object ID and cannot continue to use texgenx64 for performance guide. 

**To Reproduce**
Same as above. 

**Expected behavior**
Don't understand question. What I expect in regards to how I think it could be resolved? should it be resolved? expected behaviour of error? future consequence of error?

**Screenshots**
![388b3ed70d9044b63c3a487cf715a54e](https://user-images.githubusercontent.com/88824260/129164274-90ee5613-5868-47d2-bef1-14359d8edfe9.png)

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**
Another person had the same issue and we both have freshly installed Living Skyrim mod-list.
Thanks for your time.

**Comment by geo-cjd** [comment]
Adding to this; the same issue also persists when starting DynDOLODx64.

**Comment by geo-cjd** [comment]
Adding some more detail; seems that this is an issue with the Lux mod, author has said he will release a patch shortly.

**Comment by TwistedModding** [comment]
iirc the performance guide lod section isnt needed anymore cause in 3.4.0 glory regenerated lods with those settings

**Comment by TwistedModding** [comment]
nevermind

**Comment by ForgottenGlory** [comment]
Fixed 3.5.0
