### ISSUE TITLE
Not sure its a bug just need some help what to do

### ISSUE THREAD

**Issue by Steben1994** [ForgottenGlory/Living-Skyrim-3#466]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
3.4.0.1
**Describe the bug**
First time installing skyrim se and living skyrim
Does not launch

**Screenshots**
![Naamloos](https://user-images.githubusercontent.com/88855627/129263801-9857cf83-b2fd-49e8-8c44-f8ee4ef38931.png)

**Additional context**
![Naamloos2](https://user-images.githubusercontent.com/88855627/129263821-a305279f-cb70-4a1d-996b-0ce5a7d82435.png)

**Comment by ForgottenGlory** [comment]
What exactly is the issue, a screenshot of MO2 isn’t descriptive enough for me to help you.

**Comment by Steben1994** [comment]
> 
> 
> What exactly is the issue, a screenshot of MO2 isn’t descriptive enough for me to help you.

When i tried to start living skyrim my first time nothing happens sry but thats all i can say and sry for the lack of info

**Comment by Steben1994** [comment]
> 
> 
> > What exactly is the issue, a screenshot of MO2 isn’t descriptive enough for me to help you.
> 
> When i tried to start living skyrim my first time nothing happens sry but thats all i can say and sry for the lack of info

its a kinda mordern pc 

Processor
11th Gen Intel(R) Core(TM) i5-11600KF @ 3.90GHz
Manufacturer
Intel
Speed
4.5 GHz
Number of Cores
12
32g ram
NVIDIA GeForce RTX 3070 8G

**Comment by Steben1994** [comment]
> 
> 
> > > What exactly is the issue, a screenshot of MO2 isn’t descriptive enough for me to help you.
> > 
> > 
> > When i tried to start living skyrim my first time nothing happens sry but thats all i can say and sry for the lack of info
> 
> its a kinda mordern pc
> 
> Processor
> 11th Gen Intel(R) Core(TM) i5-11600KF @ 3.90GHz
> Manufacturer
> Intel
> Speed
> 4.5 GHz
> Number of Cores
> 12
> 32g ram
> NVIDIA GeForce RTX 3070 8G

And i made sure i folowed every step off course to install it

**Comment by Steben1994** [comment]
> 
> 
> > > > What exactly is the issue, a screenshot of MO2 isn’t descriptive enough for me to help you.
> > > 
> > > 
> > > When i tried to start living skyrim my first time nothing happens sry but thats all i can say and sry for the lack of info
> > 
> > 
> > its a kinda mordern pc
> > Processor
> > 11th Gen Intel(R) Core(TM) i5-11600KF @ 3.90GHz
> > Manufacturer
> > Intel
> > Speed
> > 4.5 GHz
> > Number of Cores
> > 12
> > 32g ram
> > NVIDIA GeForce RTX 3070 8G
> 
> And i made sure i folowed every step off course to install it

Update it works i think when i launch from here 
![Naamloos4](https://user-images.githubusercontent.com/88855627/129265158-4c7f3eef-f32a-440d-bf8f-12009b1b76ce.png)
![Naamloos3](https://user-images.githubusercontent.com/88855627/129265171-2f17c7b3-9be2-4126-b8ad-90f85a0d3356.png)

**Comment by ChunkeeMunkee** [comment]
I can see you're already on the Discord - if you're having trouble launching the game after a new install then shout out on the ls3-install-support channel (assign your roles in the roles channel first if you can't see the LS3 channels)

Edit: OK, can see you've launched successfully - shout out in the above channel if you're still having issues.

**Comment by Steben1994** [comment]
> 
> 
> I can see you're already on the Discord - if you're having trouble launching the game after a new install then shout out on the ls3-install-support channel (assign your roles in the roles channel first if you can't see the LS3 channels)
> 
> Edit: OK, can see you've launched successfully - shout out in the above channel if you're still having issues.

Yes thx anyway but thats not normal right if i need to launch it from there?
