### ISSUE TITLE
Falskaar Guards having inconsistent armor

### ISSUE THREAD

**Issue by pizzaman6** [ForgottenGlory/Living-Skyrim-3#467]
The Amber Hold Guards in Falskaar have inconsistent armor because they use vanilla Markarth armor, and a "new item" helmet causing them to have their armor reskinned by the Nordwar replacer mod, and their helmets to have the vanilla guard helmet mesh.

![unknown](https://user-images.githubusercontent.com/88857100/129264414-32ff64e9-1bb5-4581-a3da-a3446f04ae86.png)

There are other soldiers that wear guard armors and helmets in Falskaar, so they might have inconsistencies, too.

**Comment by ForgottenGlory** [comment]
Need full-size screenshot of NPC selected with console open please

**Comment by pizzaman6** [comment]
> Need full-size screenshot of NPC selected with console open please

It's the Falskaar Guards, pretty straightforward.
