### ISSUE TITLE
"Reflect" power giving +30 at start instead of +10

### ISSUE THREAD

**Issue by kevinr1117** [ForgottenGlory/Living-Skyrim-3#468]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
Put the version of the list you are on here.
LS 3.4.0.1
**Describe the bug**
After creating my character and setting up my classes, etc, I used the "Reflect" power. When I select the option for +10 in sneak, it gives me +30 in said skill instead.
**To Reproduce**
Create a new character, use the reflect power, select whichever skill (in my case, sneak), and see that it gives +30.
**Expected behavior**
I expected it to give me +10 rather than +30.
**Screenshots**

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**
User Araqiel in the discord server has also encountered this bug, seeing that it gave him +30 in two-handed when he used the same reflect power.

**Comment by ForgottenGlory** [comment]
This is why the MCM document says to do things in the order they are presented.
