### ISSUE TITLE
Sabre Cats from Animallica in Helgen Tower at start of game

### ISSUE THREAD

**Issue by omgitskae** [ForgottenGlory/Living-Skyrim-3#469]
**LS Version**
3.4.0.1

**Describe the bug**
[saves.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6979328/saves.zip)

Enemies from Animallica that are a variation of sabre cats are in Helgen Tower in the intro part of the game.

**To Reproduce**
Have not tried to reproduce, but here is what I did on the save prior to seeing this:

1. Made a Dunmer, set up ava & elsa, class, mcms.
2. Chose Shipwrecked start
3. Swam to Dawnstar, had some serious water issues and relaunched game at the recommendation of discord, fixed the issue.
4. Talked to a bunch of NPCs in dawnstar, grabbed some whiterun missives and a windhelm one
5. Took carriage to windhelm
6. Talked to some npcs in windhelm, grabbed another whiterun missive
7. Took carriage to riverwood
8. Started claw quest, made Sven hate me with the love triangle quest
9. Ran to Helgen, immediately looked for the inn and rested to start the intro
10. Followed intro as normal, no issues until I ran into a pack of 3 sabre cats that are literally impossible to kill because I'm level 1

**Expected behavior**
There shouldn't have been high level cats there.

**Screenshots**
https://imgur.com/TulmXpl
https://imgur.com/i3R4gNu
[]([](https://imgur.com/AamEtG2))

**Comment by ForgottenGlory** [comment]
Will fix when fix is found
