### ISSUE TITLE
Great Village of Mixwater Mill issues

### ISSUE THREAD

**Issue by seanpbelcher** [ForgottenGlory/Living-Skyrim-3#47]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
LS3 Beta 1

**Describe the bug**
Great Village of Mixwater Mill has some conflicts/navmesh issues, similar to what we saw in Falkreath:
![enb2021_2_3_04_13_46](https://user-images.githubusercontent.com/67465410/106737128-ed651500-65db-11eb-8705-97d2739214fe.png)
![enb2021_2_3_04_13_58](https://user-images.githubusercontent.com/67465410/106737444-4af96180-65dc-11eb-8302-c8fe71b3b6a0.png)
![enb2021_2_3_04_14_25](https://user-images.githubusercontent.com/67465410/106737483-59477d80-65dc-11eb-8900-6f214727dd4e.png)
and our old friend, the floating door...
![enb2021_2_3_04_13_03](https://user-images.githubusercontent.com/67465410/106737588-77ad7900-65dc-11eb-9252-a544db5a239b.png)
![enb2021_2_3_04_13_18](https://user-images.githubusercontent.com/67465410/106737624-8300a480-65dc-11eb-8934-bebf60bc5d01.png)

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. Additionally, if your report applies to a specific object, make sure it is selected with the console open. Reports without this will be closed.

**Additional context**

**Comment by seanpbelcher** [comment]
For what its worth, I didn't see any issues in the Great Town of Shor's Stone or the Great Town of Ivarstead. Still need to check out Karthwasten.

**Comment by ForgottenGlory** [comment]
Fixed Beta 2
