### ISSUE TITLE
Gear and Crafting Consistency Patch changes not winning in Craft & Find Items Merged

### ISSUE THREAD

**Issue by celadoneiron** [ForgottenGlory/Living-Skyrim-3#470]
**LS Version**
3.4.0.1.

**Describe the bug**
Some items don't have the changes from the Gear and Crafting Consistency Patches applied inside Craft & Find Items Merged, making them easily craftable or worth way more than they should be or both.

Edit: Also, some changes from those patches are also being overwritten by LS3 Patches Merged.
LS3_UrsineBipedSlotsPatch.esp is no longer required and can be yeeted from Patches Merged.

**To Reproduce**

1. Go to a forge with leather and leather strips.
2. Craft Ranger Outfit accessories with no book requirement.
3. Sell Ranger Outfit accessories for more money than it costs to buy the materials to craft them.
4. Infinite money.

**Additional context**
I think the load order inside the merge isn't correct now, and the changes from some patches are being ignored because their masters are loading after them? The map and merge jsons show that some plugins are added in _after_ their patches, which means they'd be overriding the patch changes with the originals.

**Comment by ForgottenGlory** [comment]
Fixed 3.5.0
