### ISSUE TITLE
Missing Pugilist-Experience Patch

### ISSUE THREAD

**Issue by celadoneiron** [ForgottenGlory/Living-Skyrim-3#471]
**LS Version**
3.4.0.1.

**Describe the bug**
Pugilist skill levels according to vanilla formula and grants experience towards character level because the patch for Experience is missing.

**To Reproduce**
- punch thing, kill thing, get skill up, progress toward levelup

**Additional context**
The existing Pugilist Experience Patch in the dev channel will still work for the most recent update of Custom Skills - Hand to Hand, just make sure it overwrites the script file.

**Comment by ForgottenGlory** [comment]
Fixed 3.5.0
