### ISSUE TITLE
Update Spell Tutor automation

### ISSUE THREAD

**Issue by celadoneiron** [ForgottenGlory/Living-Skyrim-3#472]
Patch in dev patches channel.

This sets up Spell Tutor's MCM to start with books always being returned when you fail to learn a spell, and also makes it so that spell tomes with a specific exception keyword will always be learned no matter what your skill level or perks are (though you'll still lose maximum magicka and you still won't be able to learn spells while jumping or falling and so on). I've added that keyword to follower summon spell tomes, the teleport-back-to-house spell tomes, and the True Path spell tome from Carved Brink. Users should be able to turn on the chance-to-destroy function if they want, but I've defaulted it to always return the book just in case I've missed some quest-related spell tomes. The notification given when you lose maximum magicka now defaults to telling you that your magicka has been _temporarily_ reduced, so that it doesn't look like reading a spell tome permanently debuffs you.

**Comment by ForgottenGlory** [comment]
Done 3.5.0
