### ISSUE TITLE
Update Hide Quest Items in Container Menu to fix quests

### ISSUE THREAD

**Issue by celadoneiron** [ForgottenGlory/Living-Skyrim-3#473]
The version of the mod used in LS3.4.0.1, v0.3 from June 29, broke the functionality that allows the player to see quest items when the container is also part of a quest (e.g. Thieves Guild shill jobs, returning Viola Giordano's ring). The updated v0.3 from July 6, restores that feature. Don't ask me about version numbering, I don't know.

**Comment by dnocturne** [comment]
Don't know if it's part of it, but for example, taking the misc quest about Klimmek's Supplies, when you finally reach the chest near High Hrothgar, you can't place the supplies in it, the misc. supply item doesn't show up, being stuck in inventory.

Edit:
Setting this in console:
﻿
> set hideQuestItemsDisabled to 1

made Klimmek's Supplies show up in the container properly, and allowed me to place it back.

**Comment by ForgottenGlory** [comment]
Done 3.5.0
