### ISSUE TITLE
Dark Brotherhood Starting Option Not Working

### ISSUE THREAD

**Issue by Crocadillian** [ForgottenGlory/Living-Skyrim-3#474]
Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
Current

**Describe the bug**
After choosing the Dark Brotherhood starting path from the Messenger dragon in the starting inn, I went and did the first 3 generic contracts (Kill Narfi/BeItlid/Ennodius)

Upon returning to the Sanctuary I found that I could not open the door (Nor was there a map marker for it) and it would repeatedly ask me its opening question "What is the music of life?". I did not have the option of "Silence, my brother." and could not open the door or enter the sanctuary.

Upon further investigation I found that Grelod the Kind is still alive, despite being given a letter from the Courier that you normally get after she's dead as well as hearing dialogue from guards about the 'Old lady in Riften being murdered'.

The kid who starts the DBH questline also speaks to me as if 'Innocence Lost' has yet to be started/completed despite appearing as complete in my quest long, as does 'With Friends Like These' and 'Sanctuary'

**To Reproduce**
1. Just start the game and choose the Dark Brotherhood option I suppose?

**Expected behavior**
I should be able to walk into the door and enter the sanctuary without being asked the question. Or at the very least I should have the option to answer it correctly.

**Screenshots**
N.A.

**Additional context**
Completely unrelated but Masked variant of the shrouded cowl does not appear on argonians. I'm assuming that's intentional, though.

**Comment by banyar-shin** [comment]
I have the exact same issue.

**Comment by ForgottenGlory** [comment]
Will fix when fix is found
