### ISSUE TITLE
Crafting books not appearing, formIDs changed in merge

### ISSUE THREAD

**Issue by celadoneiron** [ForgottenGlory/Living-Skyrim-3#475]
**LS Version**
3.4.0.1.

**Describe the bug**
Crafting books will not appear in merchant inventories as the formIDs in Craft and Find Items Merged have changed, and the levelled lists in LS3 Crafting Books Patch are referencing the wrong records.

**Additional context**
I've uploaded a patch to the dev patches channel - it uses the individual gear consistency patches as masters and should be merged in with Craft and Find Items Merged.

**Comment by ForgottenGlory** [comment]
Fixed 3.5.0
