### ISSUE TITLE
Ghorza's Heavy Armor Set [F] Falls Through Mesh, Not Lootable

### ISSUE THREAD

**Issue by Eurafrica** [ForgottenGlory/Living-Skyrim-3#476]
**LS Version**
3.4.0.1

**Describe the bug**
If you try to loot the Ghorza's Heavy Armor set in the Riverwood stables hay pile, you can only loot the boots and chestpiece. The gauntlets and helmet are in the mesh. Can be seen and retrieved with tcl.

**To Reproduce**
Travel to Riverwood, attempt to loot the full set. Tcl console under the mesh to see the rest of the set incorrectly placed.

**Expected behavior**
Loot the full set.

**Screenshots**
![20210814100923_1](https://user-images.githubusercontent.com/79347243/129449107-7ade5630-fc71-4dfb-8d1e-4f4cbc5d3efe.jpg)

**Comment by celadoneiron** [comment]
Patch to appropriately disable these items now in dev patches channel.

**Comment by ForgottenGlory** [comment]
Fixed 3.5.0
