### ISSUE TITLE
Floating urn of overflowing secrets

### ISSUE THREAD

**Issue by SexyThighs** [ForgottenGlory/Living-Skyrim-3#479]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
Put the version of the list you are on here.
3.4.0.1
**Describe the bug**
In Dragonreach, where Farengar's lab is there is a floating urn called Urn of Overflowing Secrets above the alchemy table. Not a hug bug by any means, but nonetheless it seems to be a bug.
**To Reproduce**
Enter Dragon's reach. Go to Farengar's Laboratory. Look above Alchemy table.
**Expected behavior**
No floating Urn unless for some reason it is a magical floating urn.

**Screenshots**
![enb2021_8_14_20_04_47](https://user-images.githubusercontent.com/81831662/129463028-012008ab-6b75-448e-8a33-df2249ecc2e6.png)

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.
![enb2021_8_14_20_05_37](https://user-images.githubusercontent.com/81831662/129463040-34f0404a-9be1-40a3-833e-a34200ffa301.png)

**Additional context**

**Comment by ForgottenGlory** [comment]
Fixed 3.5.0
