### ISSUE TITLE
Misaligned Door at Jacob's Farm in Pre-Destruction Helgen

### ISSUE THREAD

**Issue by Eurafrica** [ForgottenGlory/Living-Skyrim-3#482]
**LS Version**
3.4.0.1

**Describe the bug**
The Jacob's Farm door height is incorrect and has a gap at the bottom of misaligned entry point

**To Reproduce**
Travel to Helgen before starting main quest and walk up to Jacob's Farm

**Expected behavior**
Door should have correct alignment like other houses in pre-Helgen.

**Screenshots**
![20210814180914_1](https://user-images.githubusercontent.com/79347243/129506849-ef50d0ce-7aad-4aaf-8d46-84a0ac057024.jpg)

**Comment by ForgottenGlory** [comment]
Need screenshot with object selected in console
