### ISSUE TITLE
TDM Occasionally Fetching Incorrect Enemy Names

### ISSUE THREAD

**Issue by Eurafrica** [ForgottenGlory/Living-Skyrim-3#483]
**LS Version**
3.4.0.1

**Describe the bug**
Target locking in TDM will occasionally fetch the incorrect enemy/NPC name. In this case, it was a Wolf Fox named "Armsman Thorbjolf"

**To Reproduce**
Difficult to reproduce on command, appears to be related to entering and exiting combat via fleeing a "zone" with different NPC's around. This was a bandit name I left alive from an earlier engagement retreat.

**Expected behavior**
Consistent name behavior from TDM

**Screenshots**
![20210815011528_1](https://user-images.githubusercontent.com/79347243/129507012-c28d4dd8-4eaa-49e2-8d41-7bf005fd0bc9.jpg)

**Comment by ForgottenGlory** [comment]
Will fix when a fix is found
