### ISSUE TITLE
Gold Model Ship Clipped Inside Meade Barrels in Dragonsreach

### ISSUE THREAD

**Issue by Eurafrica** [ForgottenGlory/Living-Skyrim-3#485]
**LS Version**
3.4.0.1

**Describe the bug**
The collectible Gold Model Ship for the gallery is clipped inside the meade barrels in the Dragonsreach kitchen. It can still be looted.

**To Reproduce**
Travel to Dragonsreach kitchen

**Expected behavior**
Shouldn't clip, started happening an update or two ago.

**Screenshots**
![20210815134233_1](https://user-images.githubusercontent.com/79347243/129507376-3a5759bb-28f6-46e3-8dbe-0938ec75e7a2.jpg)

**Comment by ForgottenGlory** [comment]
Need screenshot of objects selected with console open
