### ISSUE TITLE
Misaligned/Floating Deathbell in The Blue Palace

### ISSUE THREAD

**Issue by Eurafrica** [ForgottenGlory/Living-Skyrim-3#486]
**LS Version**
3.4.0.1

**Describe the bug**
Deathbell is floating outside of its planter box in The Blue Palace

**To Reproduce**
Travel to the Blue Palace, bottom floor on the right as you first enter

**Expected behavior**
Should be in planter box

**Screenshots**
![20210815143139_1](https://user-images.githubusercontent.com/79347243/129507516-dec090f6-7d26-442f-85b8-e3efcab9505d.jpg)

**Comment by ForgottenGlory** [comment]
Need screenshot of objects selected with console open
