### ISSUE TITLE
Support Rod Jutting Through 2nd Floor Radiant Raiment

### ISSUE THREAD

**Issue by Eurafrica** [ForgottenGlory/Living-Skyrim-3#488]
**LS Version**
3.4.0.1

**Describe the bug**
Appears to be a support road or some kind of structure from the first floor jutting through to the second, has been in LS for a while.

**To Reproduce**
Travel to Radiant Raiment, go to upstairs bedroom

**Expected behavior**
Doesn't seem like it should be there, could be wrong.

**Screenshots**
![20210815234717_1](https://user-images.githubusercontent.com/79347243/129509330-6a89956f-22b2-4475-a6f8-ae230c5baa48.jpg)
![20210815234720_1](https://user-images.githubusercontent.com/79347243/129509336-84f59535-b008-4c33-937c-cea73070876e.jpg)

**Comment by ForgottenGlory** [comment]
Fixed 3.5.0
