### ISSUE TITLE
Reliable(ish) CTD When Entering Blue Palace

### ISSUE THREAD

**Issue by Eurafrica** [ForgottenGlory/Living-Skyrim-3#489]
**LS Version**
3.4.0.1

**Describe the bug**
In the past several playthroughs across 3.3.0+, I will occasionally CTD when entering the Blue Palace. I have the crash log this time, as this seems to be a ongoing issue. 

**To Reproduce**
Playing the game and entering Blue Palace from Solitude main city main door. Probably had this same CTD 7-8 times across multiple characters.

**Expected behavior**
Not CTD at this specific spot

**Crashlog**
[Crash_2021_8_16_0-28-53.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6989781/Crash_2021_8_16_0-28-53.txt)

**Comment by ForgottenGlory** [comment]
Should be fixed 3.5.0
