### ISSUE TITLE
Potential enhancement: Disable scrolling to switch view (through SSE Engine Fixes)

### ISSUE THREAD

**Issue by celadoneiron** [ForgottenGlory/Living-Skyrim-3#49]
360 Movement Behaviour relies on the keypress to tell when the player has moved from 1st to 3rd person or vice versa, and scrolling will result in it not working at all when going from 1st to 3rd. SSE Engine Fixes contains an option to disable viewchange via scrolling and limit it to the keypress. Since it's pretty easy to scroll accidentally out of 1st person if you fumblefinger (particularly during combat, which is also a time when a sudden change in movement behaviour could distract someone enough for them to die), I think this could be worth implementing as a quality-of-life improvement. It would definitely end up with people asking why they can't switch view by scrolling, but we'd have to tell everyone to only use F to switch anyway when they ask why 360 Movement Behaviour stopped working, so it's a matter of which question is quickest to answer versus how often it'll be asked, alongside the matter of whether it's a significant enough improvement to include. As to whether it makes a real difference in gameplay, I can only say that whenever I've played with 360 Movement Behaviour before, I've always made this change, because the ingrained habit of scrolling to switch meant I was constantly "breaking" it and I got sick of having to swap back and forth again to make it work again.

To lock viewchange to keypress only, open enginefixes.toml and, under the [Patches] section, change:

> ScrollingDoesntSwitchPOV = false

to

> ScrollingDoesntSwitchPOV = true

(I put this as "Reminder" because I mentioned it briefly and because it's not related to an actual bug, since this is just how 360 Movement Behaviour works.)

**Comment by ForgottenGlory** [comment]
Done Beta 2
