### ISSUE TITLE
CTD heading towards Reachwater Rock

### ISSUE THREAD

**Issue by jemaculous** [ForgottenGlory/Living-Skyrim-3#490]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
3.4.0.1

**Describe the bug**
I crash to desktop when heading from Markarth to Reachwater Rock on foot.

**To Reproduce**
Walk as the crow flies towards the quest marker at Reachwater Rock.

**Expected behavior**
I make it there!
[crash log and save.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/6990072/crash.log.and.save.zip)

**Screenshots**

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**

**Comment by ForgottenGlory** [comment]
Known issue with Organic Factions Extension, will fix when mod updates to fix the issue
