### ISSUE TITLE
Hall of the Vigilant Buggy After Dawnguard Start

### ISSUE THREAD

**Issue by Eurafrica** [ForgottenGlory/Living-Skyrim-3#491]
**LS Version**
3.4.0.1

**Describe the bug**
Some kind of mod conflict (perhaps Royal Armory Tweaks?) at the Hall of the Vigilant after level 10 Dawnguard start. Floating furniture, terrain missing, clipping, etc. It's a mess

**To Reproduce**
Hit level 10, head to Hall of the Vigilant

**Expected behavior**
Should be burned down and not look the way it does.

**Screenshots**
![20210817022356_1](https://user-images.githubusercontent.com/79347243/129674630-31ffff90-aab1-4acf-a131-151771d9daa5.jpg)

**Comment by ForgottenGlory** [comment]
Need screenshot of objects selected with console open
