### ISSUE TITLE
Ritual Master (The Man Who Cried Wolf Quest) Often Spawns Naked Due to Hooded Robes

### ISSUE THREAD

**Issue by Eurafrica** [ForgottenGlory/Living-Skyrim-3#492]
**LS Version**
3.4.0.1

**Describe the bug**
The Ritual Master often spawns naked with just the Bloodworm Helm on due to conflicted item assignment on her. She's getting Hooded Robes while guarantee spawning with the unique Bloodworm Helm. Not the biggest deal, but looks goofy when you get to the dungeon boss and she's naked with a silly helm on. Removing hooded robe variants from her will likely fix.

**To Reproduce**
Proceed through the quest, get to her at the end, if she spawns with hooded robes she'll be naked with Bloodworm Helm on

**Expected behavior**
Shouldn't be naked or have hooded robes + helmet.

**Screenshots**
![20210816140249_1](https://user-images.githubusercontent.com/79347243/129675322-10907dd6-550a-4840-939e-2344df333058.jpg)
![20210816140257_1](https://user-images.githubusercontent.com/79347243/129675339-9252eda3-1357-46dc-bc91-0467b2afe974.jpg)

**Comment by ForgottenGlory** [comment]
Will fix when fix is found

**Comment by celadoneiron** [comment]
Fix on trello

**Comment by ForgottenGlory** [comment]
Fixed 3.6.0
