### ISSUE TITLE
ranger armor

### ISSUE THREAD

**Issue by shoyaright** [ForgottenGlory/Living-Skyrim-3#493]
Alvor in Riverwood crafted ranger armor for me, no models showed up for it in the menu. waited, purchased, equipped said armor and my character was invisible, only neck and head showing and bow and quiver were visible.

**Comment by PulsefireEzreal** [comment]
Are you a male character? If so it wont work. Its a female model armor.

**Comment by shoyaright** [comment]
Wow! It's most often the simplest of things. Yes I rolled a male character.
Thank you for your time.

**Comment by celadoneiron** [comment]
Just to let you know, in the next update, all the single-gender outfits I could find should have [F] or [M] appended so that people will know which ones they can wear. You can always give the ones that you can't wear yourself to followers, though. :)

**Comment by shoyaright** [comment]
Awesome, thanks!
