### ISSUE TITLE
Gap in Wall in Fallowstone Cave

### ISSUE THREAD

**Issue by thehajo** [ForgottenGlory/Living-Skyrim-3#496]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
3.3.0 (Dunno if it's fixed already maybe)

**Describe the bug**
Gap in wall

**To Reproduce**
1. Enter Fallowstone Cave
2. Take a few steps forward
3. See gap in wall
4. Stare into the unending void

**Expected behavior**
A smooth surface that prevents the void from leaking into Skyrim

**Screenshots**
![grafik](https://user-images.githubusercontent.com/38141473/129948927-d90267f2-de4f-4d29-a9d8-d85747560af1.png)
![grafik](https://user-images.githubusercontent.com/38141473/129949046-4a5cb844-ed5b-484f-989c-28e1b39af5cb.png)

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**
Gap is literally right upon entiring

**Comment by celadoneiron** [comment]
Patch in dev patches channel.

**Comment by ForgottenGlory** [comment]
Fixed 3.5.0
