### ISSUE TITLE
Forced to kill Paarthurnax in his quest. 

### ISSUE THREAD

**Issue by dnocturne** [ForgottenGlory/Living-Skyrim-3#497]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
3.4.0.1

**Describe the bug**

The game starts the vanilla Paarthurnax quest upon speaking to either Delphine or Esbern, all whilst retaining the modded in dialogue. With the game forcing me to kill Paarthurnax. With modded in dialogue choices doing nothing to change that.

**To Reproduce**

1. Skip or do the "Season Unending" quest.
2. Talk to either Delphine or Esbern to start the Paarthurnax quest.

**Expected behavior**

I expect that upon speaking with Delphine or Esbern and starting Paarthurnax quest, I'll be able to complete the quest without needing to kill Paarthurnax.

**Screenshots**

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**

I've attached the save which is just after completing the "Season Unending" quest. Just wait for Delphine to walk up to you, or go to her instead, and you can start the "Paarthurnax" quest.

If anything else is required, message me.

[dexasz's skyrim saves.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/7014940/dexasz.s.skyrim.saves.zip)

**Comment by ForgottenGlory** [comment]
Fixed 3.5.0
