### ISSUE TITLE
"With Friends Like These" not triggering after completing "Innocence Lost"

### ISSUE THREAD

**Issue by Awooona** [ForgottenGlory/Living-Skyrim-3#498]
**LS Version**
3.4.0.1

**Describe the bug**
After completing the quest "Innocence Lost", the quest "With Friends Like These" is not triggering. Since completing "Innocence Lost," I have received the Mysterious Note, passed several in-game days, leveled up multiple times, and slept in inns in multiple cities, as well as in a number of sleeping bags in other locations, however "With Friends Like These" never triggered. I am currently level 17 as well.

**To Reproduce**
Obtain the Mysterious Note, then try sleeping. I began my save with the Thieves Guild start. Additionally, the Mysterious Note was bundled in with another delivery, so I hadn't realized it was sitting in my inventory for some time.

**Expected behavior**
To wake up in the mysterious shack, kidnapped by Astrid, beginning "With Friends Like These." 

**Additional context**
It seems that this is a bug remedied by USSEP. Perhaps another patch or mod is conflicting? As a temporary fix I was able to begin the quest with
`setstage DB02 10`
and teleport myself to the mysterious shack with 
`player.moveto 0001BDE8`
I was then able to progress the questline as normal.

**Comment by ForgottenGlory** [comment]
Likely related to #474
