### ISSUE TITLE
Helgen Doors from AP still appearing in Helgen and persisting through Helgen Reborn, + extras

### ISSUE THREAD

**Issue by Leonineus** [ForgottenGlory/Living-Skyrim-3#499]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
3.4.0.1.

**Describe the bug**
Some of the doors from AP Helgen are persisting even after the destruction and reconstruction:
- Potent Potables in HR still has Gunnar's House door covering most of its door (you can still access the store by aiming at the small gap between the Gunnar's House door and the lintel)
![image](https://user-images.githubusercontent.com/87247798/130149519-7dd5d836-edfc-4236-9b17-28a8bd53f55e.png)
![image](https://user-images.githubusercontent.com/87247798/130149571-2c08bf18-372d-4299-930d-d859772bff3b.png)
- Abandoned House opposite Gunnar's House (between north and east gates), door is floating halfway below where it should be even before destruction of Helgen, and persists in the doorway of Helgen Wholesale after reconstruction - door is not easily visible at first glance but you'll notice the handle of the old door is close to the porch floor, plus clipping effect is VERY obvious when activating the Helgen Wholesale door
![image](https://user-images.githubusercontent.com/87247798/130149720-d4197f4a-7d44-4178-816a-24ee56e010fc.png)
![image](https://user-images.githubusercontent.com/87247798/130149770-2ce9aebe-c004-424f-b93e-540fa840a2f3.png)

- Cienna's House (between tower you climb during attack and west gate towards Falkreath) still has Vilod's house door showing as activatable depending on where you point at the door.
![image](https://user-images.githubusercontent.com/87247798/130149175-9864518b-8a6e-4021-89af-a3748e041c39.png)
![image](https://user-images.githubusercontent.com/87247798/130149211-5fa9855a-092e-4a94-b2e1-02db7e09df17.png)
- Jacob's Farm (between east gate heading out towards Orphan Rock and the Inn) still has its old door hanging in the middle of the smithy area entrance of the Hammer and Anvil - farm area between it and the inn also clips directly inside the Hammer and Anvil (relevant screenshot taken while using TCL to get inside building)
![image](https://user-images.githubusercontent.com/87247798/130149350-c463cf8a-c935-437f-a7e1-6acca816d403.png)
![image](https://user-images.githubusercontent.com/87247798/130151172-507bf868-b995-4c0a-908f-ea111f73db6e.png)

Extras: 
- I noticed that the Arcane Ambry next door to Potent Potables/Gunnar's House experiences texture flickers when moving around while looking at it - seems like the two mods are trying to overlay two different texture variations onto the same building so far as I can tell, also shown in video is wooden floor on inn-facing side has a direct texture bug (00:05-00:07):
https://1drv.ms/v/s!Au6VNSMLCLmX2S3vCiqKDG4SNnVJ?e=McvEQe
- The doors to Helgen Keep seem to alternate between activating by proximity (like caves) to start with and then later switching to activatable objects later in Helgen Reborn, though I couldn't isolate an exact point for the changeover as only noticed after the fact) - given this doesn't really obstruct anything I figured I'd just point it out more as a "feature report" than a bug report.
- Boulder between Potent Potables/Gunnar's House and north gate is interfering with guard pathfinding through HR and after it
![image](https://user-images.githubusercontent.com/87247798/130150684-ddff5b4d-76d3-4fa9-93c2-7f95898268ca.png)
- Worker rest area during HR questline is buried under rock - only part visible (and only reason I actually realised there was a problem) is the cooking pot itself, plus I remembered where it was from previous builds of LS and occurred to me as I was looking at it.
![image](https://user-images.githubusercontent.com/87247798/130150863-9543adc6-f8ac-4b60-9616-26cc58eb903f.png)

**To Reproduce**
n/a - save attached

**Expected behavior**
That the old purposes of the pre-Alduin Helgen would recede into the vagaries of history as they should, rather than clinging to their former identities in the face of being repurposed by new residents.

**Screenshots**
Screenshots attached against relevant contents

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**
[saves.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/7017964/saves.zip)
Attached save is inside personal tower by bed, relevant problems can be seen just by going outside and walking around

**Comment by stoudtlr** [comment]
Might be related to AP-Helgen Reborn patch.  I saw this issue in my personal non-LS3 list as well a few days ago and found below link about the patch missing a few items when I researched my issues.
[https://forums.nexusmods.com/index.php?/topic/10055153-alternate-perspective/page-34#entry97981573](https://forums.nexusmods.com/index.php?/topic/10055153-alternate-perspective/page-34#entry97981573)

Edit: my list was ONLY AP, Helgen Reborn, AP-Helgen Reborn patch, and my AP extension mod I'm working on so there weren't any other conflicts.

**Comment by ForgottenGlory** [comment]
Seems the Alternate Perspective author is aware of this, will fix when Helgen Reborn patch gets updated to fix it

**Comment by deadmanreaper13** [comment]
While I know its being looked into, I would like to add two more spots that are being effected.

Skalei's Scrap shop (general goods merchant) is inaccessible due to its front door being covered by a wall.
![Screenshot (38)](https://user-images.githubusercontent.com/48200788/133746113-0f2df6e6-c75b-4a6f-864b-229507c20c73.png)

and the Private Tower player home is accessible from the roof of the watchtower as its hatch is already present.
![Screenshot (40)](https://user-images.githubusercontent.com/48200788/133746663-138f2cb3-65cb-4db8-aab6-abf3c1f3db76.png)
