### ISSUE TITLE
Game Folder Files No Longer Located in Steam Game Properties 

### ISSUE THREAD

**Issue by Trent223** [ForgottenGlory/Living-Skyrim-3#5]
**Section**
Section Pre-Installation, subsection Steam & Skyrim Special Edition Setup.

**Description**
The pre-install guide contains the following instruction on locating your Skyrim game folder files:

If there are any files leftover in the Skyrim Special Edition game folder (Right-click > Properties… > Local Files > Browse Local Files…), delete them.

However, as of a recent Steam update, the game folder files can no longer be accessed via the Steam game properties dialog:
![image](https://user-images.githubusercontent.com/30636255/106454787-48baca00-6459-11eb-94bf-95538bc10a0d.png)

See also: https://store.steampowered.com/oldnews/?feed=steam_client patch notes for Dec 21.

Most Skyrim modders will know where their game install is, but I thought this worth mentioning nevertheless.

Edit: The below text (taken from the ENB section) could probably be re-used here:

(Usually located at[install drive]\Steam\steamapps\common\Skyrim Special Edition)

**Comment by ForgottenGlory** [comment]
Updated, thanks for the heads up!
