### ISSUE TITLE
Haafinheim exterior duplicate objects, clipping

### ISSUE THREAD

**Issue by celadoneiron** [ForgottenGlory/Living-Skyrim-3#50]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
1.3.0.

**Describe the bug**
Haafinheim has two piers right next to each other and a nearby campfire is clipping into the ground.

**To Reproduce**
Steps to reproduce the behavior: Go to Haafinheim.

**Expected behavior**
No duplicate pier, campfire fully aboveground.

**Screenshots**
![SkyrimSE 2021-02-04 08-48-18](https://user-images.githubusercontent.com/73095714/106820309-d6e7b800-66c6-11eb-9dc7-05a5ba14ec91.png)
![SkyrimSE 2021-02-04 08-48-32](https://user-images.githubusercontent.com/73095714/106820337-e2d37a00-66c6-11eb-997e-7b33094d5287.png)
![SkyrimSE 2021-02-04 08-48-53](https://user-images.githubusercontent.com/73095714/106820355-e961f180-66c6-11eb-934b-6d4915536f45.png)

**Additional context**
One of the piers is from Morskom and I would expect it's linked to the travel-by-boat system in that mod. The other one is defined in Skyrim and moved by Haafinheim. I don't think Haafinheim has anything attached to that pier, so it might be as simple a fix as just disabling the Haafinheim pier objects and moving them to -10000,-10000,-10000. I ran through the quest to access the house and while the skeleton with the quest item is near the pier, it's close enough to the Morskom pier that I don't think people would have trouble finding it.

**Comment by ForgottenGlory** [comment]
Fixed Beta 2
