### ISSUE TITLE
Incorrect Map Marker Location

### ISSUE THREAD

**Issue by DiodeDiabolus** [ForgottenGlory/Living-Skyrim-3#500]
**LS Version**
3.4.0

**Describe the bug**
With the radiant quest "Ancient Power" it is possible for you to be directed to Staadomaar Temple. In which the map marker will direct you to "Bandit Camp," north of Whiterun. When in actuality, Staadomaar is just north of Lake Illalta.

**To Reproduce**
- Get the radiant quest "Ancient Power" from Feran Sadri and be directed to Staadomaar.

**Expected behavior**
Map Marker is expected to be north of Lake Illalta. Vanilla map screenshot is the expected location of map marker.
![Staadomar_on_map](https://user-images.githubusercontent.com/87377973/130208705-c806f1d0-031e-406e-a8a9-296024e89832.jpg)
![ScreenShot255](https://user-images.githubusercontent.com/87377973/130208728-e677e142-a469-474f-adb5-57e986fb232c.png)

**Additional Information**
It is unknown to me if this is isolated to this quest with this specific location. The location is added with Helgen Reborn according to the following link.
Source: https://legacy-of-the-dragonborn.fandom.com/wiki/Dragon%27s_Fang

**Comment by ForgottenGlory** [comment]
Will fix when fix is found
