### ISSUE TITLE
VioLens Overwriting Blade & Blunt Player Kill Move Immunity

### ISSUE THREAD

**Issue by Eurafrica** [ForgottenGlory/Living-Skyrim-3#501]
**LS Version**
3.4.0.1

**Describe the bug**
Per the Blade & Blunt mod page, player killmoves should be disabled by default:

"With Blade and Blunt installed, the player will be immune to kill moves. While cinematic executions are fun when used on NPCs, allowing them to affect the PC often prevents players from surviving difficult encounters through skill and good play. Additionally, kill moves will only trigger on enemies who are below 50% Health, to account for a bug where enemy armor is not taken into account when the game decides to trigger a kill move. "

VioLens has the Player Killmove Immunity unchecked by default with LS's configuration, which overwrites B&B's. This leaves to frequent instant-deaths of player to attacks they'd otherwise survive. Fixable by checking the Player Killmove Immunity box On in VioLens.

**To Reproduce**
Fight anything in melee early on, get executed.

**Expected behavior**
Not to get executed by health and armor ignoring one shots

**Comment by ForgottenGlory** [comment]
So... turn on Player Killmove immunity in the VioLens MCM?
