### ISSUE TITLE
Glitchy Wall in Dragonborn Gallery Courtyard (Solitude), Can Get Stuck

### ISSUE THREAD

**Issue by Eurafrica** [ForgottenGlory/Living-Skyrim-3#503]
**LS Version**
3.4.0.1

**Describe the bug**
There's a glitchy wall in the courtyard area outside Dragonborn Gallery, in the back near some Dragon's Tongue. If you look at it from different angles or try to crouch/stand inside it to get the herbs, you can clip inside and get stuck. It's been around for many versions.

**To Reproduce**
Go to the small garden area outside the gallery in Solitude

**Expected behavior**
Should be a normal solid wall

**Screenshots**
![20210819055525_1](https://user-images.githubusercontent.com/79347243/130265418-c5efd5e4-06b5-414d-9f2d-b35d30800463.jpg)

**Comment by ForgottenGlory** [comment]
Need screenshot of objects selected with console open
