### ISSUE TITLE
New gnisis corner club.Suspicious laborer leaning against wall inside objects

### ISSUE THREAD

**Issue by WitchGirlTamara** [ForgottenGlory/Living-Skyrim-3#506]
Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
3.4.0.1

**Describe the bug**
In the New Gnisis corner club (inn in the grey quarter in windhelm) a suspicious laborer leans against the wall inside several objects from JK.

**Screenshots**
![image](https://user-images.githubusercontent.com/84421445/130336359-730c1dc6-3fea-4a6f-a66d-1b78f1a276ae.png)

![image](https://user-images.githubusercontent.com/84421445/130336362-1ef0954d-0e41-47ac-add8-4dd2bf386668.png)

**Comment by ForgottenGlory** [comment]
Should be fixed 3.5.0
