### ISSUE TITLE
Broken links for readme page

### ISSUE THREAD

**Issue by dmrickey** [ForgottenGlory/Living-Skyrim-3#507]
The link in the readme.md here and on the wabbajack page both link to a non-existent page.
https://fgsmodlists.com/living-skyrim (nothing lives here)
![image](https://user-images.githubusercontent.com/3664822/130860833-8914cbf1-5a4c-4ad0-b50e-c97cee5e873b.png)

**Comment by ForgottenGlory** [comment]
Fixed 3.5.0
