### ISSUE TITLE
Removing certain pathways in riften that allow you to easily break thieves guild questline.

### ISSUE THREAD

**Issue by PulsefireEzreal** [ForgottenGlory/Living-Skyrim-3#508]
There are some mod-added pathways that allow you to easily get into mercer's house and steal his plans. The unofficial patches patched a way to stop that, but unfortunately the pathways added make it even easier than vanilla.

![image](https://user-images.githubusercontent.com/80222523/130889817-5590835b-8c3a-4368-ab98-f09832785f8f.png)

Cela told me to do this to make sure we get rid of just the ones connecting to his house.

**Comment by PulsefireEzreal** [comment]
this is just to help make sure that the thieves guild questline doesn't get broken

**Comment by ForgottenGlory** [comment]
need screenshots of objects selected in console please

**Comment by celadoneiron** [comment]
Patch in patches channel

**Comment by ForgottenGlory** [comment]
Done 3.5.0
