### ISSUE TITLE
2 bugs 1 report  tudm - crash on save (both fixed)

### ISSUE THREAD

**Issue by TwistedModding** [ForgottenGlory/Living-Skyrim-3#509]
The ultimate dodge mod bug where you're stuck in the air is now fixed thanks to eggy(nem) patch in patch channel: 

Crash on save bug in this cell:  [   1]    TESObjectCELL(Name: Wilderness, FormId: 00008F6F, File: `Occlusion.esp`) should be fixed by regenerating occlusion

**Comment by ForgottenGlory** [comment]
Fixed 3.5.0
