### ISSUE TITLE
Crash to desktop when loading into the library in the mages collage

### ISSUE THREAD

**Issue by GalaxyMonkeyy** [ForgottenGlory/Living-Skyrim-3#510]
**LS Version**
3.4.0.1

**Describe the bug**
When going up the stairs into the loading screen the the library section of the collage after the loading screen sometimes the game crashes, doesnt do it back to back so if you save before going through the load it wont do it again, but i dont think i did that this time

**To Reproduce**
going up the stairs to the right in the collage of winterhold

**Expected behavior**
Soon after the loading screen the game gets kinda framy then crashes to desktop

Crash report
[Crash_2021_8_30_18-18-54.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/7080190/Crash_2021_8_30_18-18-54.txt)

Save
[Most recent save.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/7080197/Most.recent.save.zip)

**Comment by GravenImages** [comment]
Fix shared in developer bug hunting channel.

**Comment by TwistedModding** [comment]
The fix posted fixes all instances of lights attaching to a reference that doesnt exist(yet) such as a npc not loaded in yet. Seems to be fairly common at the college.

**Comment by ForgottenGlory** [comment]
Fixed 3.5.0
