### ISSUE TITLE
Winking Skeever Loft

### ISSUE THREAD

**Issue by D-Lemons** [ForgottenGlory/Living-Skyrim-3#512]
**LS Version**
3.4.0.1

**Describe the bug**
Ladder blocking door to loft. It's still accessible but when you leave you end up underneath Riften.

**To Reproduce**
Enter Winking Skeever Loft and then leave.

**Expected behavior**
I expected regular access to my abode.

**Comment by ChunkeeMunkee** [comment]
Did you mean you end up underneath Solitude - or does this literally yeet you to the opposite corner of the province?

**Comment by D-Lemons** [comment]
I meant Solitude. That would be hilarious

**Comment by ForgottenGlory** [comment]
Need screenshot of the object(s) in question selected in console
