### ISSUE TITLE
Sarethi Farm nirnroot display as free to harvest but count as stealing

### ISSUE THREAD

**Issue by celadoneiron** [ForgottenGlory/Living-Skyrim-3#513]
**LS Version**
3.4.0.1.

**Describe the bug**
The nirnroot plants at the Sarethi Farm show a white "Harvest" activation prompt, but harvesting them will count as theft and give a bounty as they are marked as being owned by Sarethi Farm House Faction.

**To Reproduce**
1. go to Sarethi Farm
2. harvest nirnroot
3. stop right there, criminal scum

**Expected behavior**
Activation prompt reflects ownership

**Screenshots**
![Screen Shot 09-01-21 at 16 50](https://user-images.githubusercontent.com/73095714/131625565-a7603558-7e50-4b5b-b001-e7a76f23c5a8.PNG)
![Screen Shot 09-01-21 at 16 50 001](https://user-images.githubusercontent.com/73095714/131625581-025bb52b-cd50-49d2-93d9-0d161f327b13.PNG)

**Comment by ForgottenGlory** [comment]
Will fix when fix is found

**Comment by celadoneiron** [comment]
Workaround on Trello
