### ISSUE TITLE
Update Lux & include lighting template adjustment addon

### ISSUE THREAD

**Issue by celadoneiron** [ForgottenGlory/Living-Skyrim-3#514]
Main Files: Lux 3.0
Update Files: Missing Light Switch script, Ragged flagon missing cubemap
Optional files: JK's Hag's Cure patch if including that mod, plus Mechanicalpanda's Brighter Templates

As for the specific template to use, I would suggest using 2010 Bright Up as the default (inhabited interiors are two stages brighter, dungeons one stage brighter). It might also be worth adding the other options in under the Configuration Specific separator, so that people can more easily adjust the interior brightness to their liking - since the brightness templates are only affecting Lux-specific lighting templates, it shouldn't be a problem to let people switch between them.

**Comment by ForgottenGlory** [comment]
Done 3.5.0
