### ISSUE TITLE
All daedric armor and black mage hood aren't visible in inventory and unable to pick up daedric weapons

### ISSUE THREAD

**Issue by SaltCannon** [ForgottenGlory/Living-Skyrim-3#516]
**LS Version**
3.4.0.1

**Describe the bug**
After killing the daedra's in Vulhule, when i pick up any of the daedric armor and black mage hoods, they don't appear in my inventory but they affect my carry weight. I'm unable to pick up their daedric weapons at all. My companions who are set to pick up weapons/armor/ammo aren't picking neither the armor or weapons.

**To Reproduce**
1. Pick up daedric boots, gauntlets, armor, helm, or black mage hoods
2. Attempt to press pick up on daedric weapons
3. Check inventory

**Expected behavior**
Be able to see and equip daedric armor aswell as pick up and equip daedric weapons

**Screenshots**
![image](https://user-images.githubusercontent.com/90066712/132062481-4b9c5f17-fb11-49aa-a181-9b9e880528af.png)

**Comment by thehajo** [comment]
Check the second pin in #ls-gameplay-help.

**Comment by SaltCannon** [comment]
The 2nd oldest pin that I see is August 16 2020 and it pertains to the not so fast mod. The 2nd newest pin is talking about quest containers. I don't know how either of those relates to this issue. Unless I'm not seeing the correct pinned messages. Also it seems like the bug is only for gear of daedra's\ghost enemies. I went to another dungeon and encountered the same issue with that bosses gear they dropped.

**Comment by thehajo** [comment]
Hm, i assumed it was due them being hidden as some quest counted them as quest items. I assume you tried the command?
Picking up is only broken for Daedric weapons, picking up daedric armor from the world works?

**Comment by PulsefireEzreal** [comment]
You shouldnt be able to loot armor off of daedra and such last i remember. So that itself needs to be fixed. So whatever is letting you be able to loot their armor isnt supposed to be doing that.

**Comment by PulsefireEzreal** [comment]
Did you loot these armors through quickloot?

**Comment by SaltCannon** [comment]
The first encounter with daedra's, the armor and weapons were on the floor, not on the corpses. The 2nd encounter the armor was looted through quick loot on a corpse

**Comment by PulsefireEzreal** [comment]
Can you attach a save file of right before you attempted to loot them?

**Comment by SaltCannon** [comment]
Unfortunately I'm several hours past that encounter. But I did confirm that it's the companions looting them off corpses and then they drop the items. If I see the corpse first, they're hidden from me.

**Comment by ForgottenGlory** [comment]
One of the many reasons follower looting is left disabled.
