### ISSUE TITLE
Vigilant Dremora hair alpha issue (with fix)

### ISSUE THREAD

**Issue by celadoneiron** [ForgottenGlory/Living-Skyrim-3#517]
**LS Version**
3.4.0.1

**Describe the bug**
Transparency on the hair of male Dremora from Vigilant is borked.

**To Reproduce**
1. Look at Kathutet (during Vigilant quest "Lazy Afternoon").

**Expected behavior**
Hair look like hair.

**Screenshots**
![Screen Shot 09-01-21 at 22 41](https://user-images.githubusercontent.com/73095714/132089930-c3d26017-dce9-46d2-b1d3-bf97d77cdf01.PNG)

**Fix**
Update Vigilant - NPC Overhaul to version 2.2.

**Comment by ForgottenGlory** [comment]
Fixed 3.5.0
