### ISSUE TITLE
Game crashes when saving after visiting labyrinthian or mehrunes dagons shrine

### ISSUE THREAD

**Issue by TheMightySoul** [ForgottenGlory/Living-Skyrim-3#519]
**LS Version**
3.4.0.1

**Describe the bug**
Game crashes after visiting the labyrinthian or shrine of mehrunes dagon. I have tried fast traveling to solitude or dawnstar and then saving but it still crashes. This is what the crash log says:

Possible relevant objects (1)
{
  [   1]    TESObjectCELL(Name: Wilderness, FormId: 00008F6F, File: `Occlusion.esp`)

**To Reproduce**
Save the game in the labyrinthian or shrine of mehrunes dagon

**Expected behavior**
Not fucking crash maybe. 

**Additional context**
[Crash_2021_9_8_15-18-5.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/7130235/Crash_2021_9_8_15-18-5.txt)

**Comment by ForgottenGlory** [comment]
Fixed 3.5.0
