### ISSUE TITLE
ELFXEnhancer.esp changes reverted, mostly by SkyRem - Iris.esp

### ISSUE THREAD

**Issue by celadoneiron** [ForgottenGlory/Living-Skyrim-3#52]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
1.3.0.

**Describe the bug**
The changes that ELFXEnhancer.esp makes to hundreds of cells are being overridden and reverted to default, most of them by SkyRem - Iris.esp. About 300 cells are affected. Some are also overwritten by LS3 Patches Merged.esp.

**To Reproduce**
Steps to reproduce the behavior: Open SSEEdit and "Apply filter to show conflicts (selected files only)" on ELFXEnhancer.esp, to see the list of affected cells.

**Expected behavior**
ELFXEnhancer's changes to lighting should be preserved rather than being reverted to default.

**Screenshots**
If applicable, add screenshots to help explain your problem. Additionally, if your report applies to a specific object, make sure it is selected with the console open. Reports without this will be closed.

**Additional context**

**Comment by ForgottenGlory** [comment]
Fixed Beta 2
