### ISSUE TITLE
Slight mismatch on Arniel Gane's name plate

### ISSUE THREAD

**Issue by thehajo** [ForgottenGlory/Living-Skyrim-3#520]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
3.3.0

**Describe the bug**
Slight mismatch on Arniel Gane's name plate, causing it to appear twice

**To Reproduce**
1. Enter Hall of Atainment
2. Walk to second floor
3. Look at the name plate
4. You will see two

**Expected behavior**
Only one name plate

**Screenshots**
![grafik](https://user-images.githubusercontent.com/38141473/132680730-fe785695-8db6-4625-94fa-78705f26f39e.png)
![grafik](https://user-images.githubusercontent.com/38141473/132681007-20c4c91a-338a-4197-b65b-37f52b8ef894.png)
![grafik](https://user-images.githubusercontent.com/38141473/132681041-40af6426-116d-49da-9e1e-1cf9eecbb232.png)

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**
The lower one should be the correct one, as that one gives me the ability to find him.

**Comment by ForgottenGlory** [comment]
Fixed 3.5.0
