### ISSUE TITLE
I have problem with mod i copied you my logs..

### ISSUE THREAD

**Issue by penteshi** [ForgottenGlory/Living-Skyrim-3#521]
Wabbajack can not find a "skyrim_defauld.ini' i dont know whats going on..
Belowa i copied my logs

0.27 - Wabbajack Build - 2b4227a2f9769cb4f02158b583dcba3f8d92759d
0.27 - Running in C:\Wabbajack\2.5.2.2
0.28 - Detected Windows Version: 10.0.19042.0
0.28 - System settings - (23.9GB RAM) (3.5GB Page), Display: 1920 x 1080 (5.8GB VRAM - VideoMemorySizeMb=10240)
0.29 - Pagefile below recommended! Consider increasing to 20000MB. A suboptimal pagefile can cause crashes and poor in-game performance.
0.31 - Getting new Wabbajack version list
0.31 - Steam: Found no Regex matches in Steam Config at c:/program files (x86)/steam\config\config.vdf
0.32 - Steam: Found no matches in Library Folders file at c:/program files (x86)/steam\steamapps\libraryfolders.vdf
0.32 - Steam: Found game Steamworks Common Redistributables (228980) at "c:/program files (x86)/steam\steamapps\common\Steamworks Shared"
0.32 - Steam: Found game The Elder Scrolls V: Skyrim Special Edition (489830) at "c:/program files (x86)/steam\steamapps\common\Skyrim Special Edition"
0.32 - GOG: Found game Cyberpunk 2077 (1423049311) at "C:\Program Files (x86)\GOG Galaxy\Games\Cyberpunk 2077"
0.32 - BethNet: Unable to open Registry Keys SOFTWARE\WOW6432Node\Bethesda Softworks\Bethesda.net and SOFTWARE\WOW6432Node\Bethesda Softworks\Bethesda.net
0.32 - EGS: Unable to open Registry Key SOFTWARE\Epic Games\EOS
0.33 - Origin: LocalContent directory at C:\ProgramData\Origin\LocalContent does not exist
0.69 - Wabbajack Version: 2.5.2.2
1.15 - Build server is alive
1.15 - File hash check (-42) 0ab32bb778120c30f3124ca1e44cb947212936497b8c718613352da6ab615f20
1.16 - Build server is alive
1.16 - File hash check (-42) 0ab32bb778120c30f3124ca1e44cb947212936497b8c718613352da6ab615f20
1.87 - Loading ModLists from GitHub

**Comment by ChunkeeMunkee** [comment]
This is not a modlist bug - please come through to the Discord server if you need general support (link in the ReadMe)
