### ISSUE TITLE
Children of Gala's Stead suffering from BFB

### ISSUE THREAD

**Issue by ChunkeeMunkee** [ForgottenGlory/Living-Skyrim-3#523]
**LS Version**
3.4.0.1

**Describe the bug**
Both of the children of Gala's Stead (South of Windhelm) have BFB.

**To Reproduce**
N/A - Reported by a couple of users, have found this in my game also.

**Screenshots**
![enb2021_9_11_19_49_43](https://user-images.githubusercontent.com/2692881/132958649-e613eb3a-f8c0-4545-a3ef-782da69b268e.png)
![enb2021_9_11_19_49_55](https://user-images.githubusercontent.com/2692881/132958656-57abe5d7-d4cb-4431-8529-b1c19280cffc.png)
![enb2021_9_11_19_50_02](https://user-images.githubusercontent.com/2692881/132958661-ff722b49-3ab5-48a5-a921-a58dae2e35eb.png)

**Comment by ForgottenGlory** [comment]
Fixed 3.5.0
