### ISSUE TITLE
Crafting equipment in Gala's Stead clipping into ground

### ISSUE THREAD

**Issue by ChunkeeMunkee** [ForgottenGlory/Living-Skyrim-3#524]
**LS Version**
3.4.0.1

**Describe the bug**
Carfting equipment at Gala's Stead (South of Windhelm) are stuck in the ground. Furnace, workbench, wheel, and rack are all inaccessible by the player.

**To Reproduce**
Travel to Gala's Stead, attempt to use the equipment (also locked my view into 3rd person)

**Expected behavior**
Equipment to be usable by the player

**Screenshots**
![enb2021_9_11_19_51_00](https://user-images.githubusercontent.com/2692881/132961312-55bce770-b253-4f01-bd49-d3d0eb75b490.png)
![enb2021_9_11_19_51_08](https://user-images.githubusercontent.com/2692881/132961314-a2fc140b-d2ed-4fb1-b79d-ba3d87dd5635.png)
![enb2021_9_11_19_53_18](https://user-images.githubusercontent.com/2692881/132961316-5d7511a1-c3e6-417e-b0a8-07e86dc2c19d.png)

**Comment by ForgottenGlory** [comment]
Fixed 3.5.0
