### ISSUE TITLE
Thieves Guild Shill Job

### ISSUE THREAD

**Issue by WeirdoWG** [ForgottenGlory/Living-Skyrim-3#525]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
3.4.0.1

**Describe the bug**
I accepted a 'Shill Job' from Vex in the Thieves Guild. I was told to place a 'Stolen Copper and Sapphire Circlet' inside 'Beirund's House' in Solitude. It will not let me place the item in the container, as it is 'QUEST LOCKED'.

**To Reproduce**
- Accept any Shill job from Vex
- Cannot place item in container

**Expected behavior**
To be able to place the item in the container.

**Screenshots**

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**
- I also had this problem with the carrying of Supplies up the 7000 steps to High Hrothgar.

**Comment by thehajo** [comment]
3rd pin from the top in #ls-gameplay-help.

EDIT: I cannot read. I assumed it was not showing up. But thats odd. Only thing i could think of if it was maybe the wrong container, but you said you had it with the supplies as well... hmm..

**Comment by ForgottenGlory** [comment]
Should be fixed 3.6.0
