### ISSUE TITLE
Classic Classes & Birthsigns makes channelled spells (flames, healing, etc) "free"

### ISSUE THREAD

**Issue by AstridCone** [ForgottenGlory/Living-Skyrim-3#526]
**LS Version**
3.5.0, but I think this was actually happening before too

**Describe the bug**
Usually when you have 0 or insufficient magicka, a spell will fail to cast. But if you've got the +20 ModAV to a relevant magic skill via your class from Classic Classes, they will for whatever reason continue to be cast even if you have no magicka to speak of. I have no idea if this is AVA or CC&B's fault, or even how its causing it.

**To Reproduce**
This bug happens if you have set up your attributes, and picked a class with specialization in a relevant magic skill, the birthsign is irrelevant. Now when casting any of channelled spell will cause the described effect of simply ignoring the fact it should be failing.

**Expected behavior**
In a perfect world, Skyrim actor values wouldn't be so fucking strange

**Comment by AstridCone** [comment]
To be fair, it only happens when both are set up, but It might also not happen if you don't try pumping Intelligence and Wisdom to 15 and beyond like I was doing

**Comment by ForgottenGlory** [comment]
Possibly fixed 3.6.0

**Comment by AstridCone** [comment]
The same issue persists in 3.6.0.1, except now it happens no matter if you set up AVA or not, so 100% either a CC&B or general skill modifier bug

**Comment by AstridCone** [comment]
Scratch that, It still happens but I can't pinpoint how. Will update if I ever get an idea of what causes this
