### ISSUE TITLE
Some MCM automation overwritten by Miscellaneous Merged

### ISSUE THREAD

**Issue by celadoneiron** [ForgottenGlory/Living-Skyrim-3#527]
**LS Version**
3.5.0.

**Describe the bug**
Some MCM automation, like A Matter Of Time and Take Notes, doesn't happen.

The relevant scripts from LS3 MCM Automation (takenotesmenu.pex, amotmenuquestscript.pex, and also lfg_customconfigscript.pex) are being overwritten by scripts from Miscellaneous Merged.

**To Reproduce**
Start game.

**Comment by ForgottenGlory** [comment]
Fixed 3.6.0
