### ISSUE TITLE
Font scaling - fonts can run off the bottom of some popups

### ISSUE THREAD

**Issue by ChunkeeMunkee** [ForgottenGlory/Living-Skyrim-3#528]
**LS Version**
3.5.0

**Describe the bug**
Font appears to be a little too large for the UI.

Some users report dialogue options running off the right hand side of the UI - I have only experienced this in the CC&BR dialogue box so far.

I had suspected this may have been something peculiar to Ultrawide aspect ratios, but it appears on my setup for 16:9, 21:9, and 32:9 configurations.

**To Reproduce**
Leave the AP starting cell and move to an outdoor cell to bring up the CC&BR menu, then select a deity.

**Expected behavior**
Font in dialogue boxes and character dialogue choices to be scaled down.

**Screenshots**

16:9@1080p
![enb2021_9_19_00_21_16](https://user-images.githubusercontent.com/2692881/133911185-d56a9607-b5ff-46ba-ada5-a36cef26742a.png)

21:9@1440p
![enb2021_9_19_00_25_04](https://user-images.githubusercontent.com/2692881/133911189-c8e0e79c-3cac-4074-989f-6a3a531fc492.png)

32:9@1440p
![enb2021_9_19_00_29_55](https://user-images.githubusercontent.com/2692881/133911216-b48b0f8f-b309-4d6a-97fe-111f4e9580de.jpg)

**Comment by Dace617** [comment]
This issue also seems to occur with the MCM titles in the setting page. Oddly though if I DO NOT use the ultrawide optional config but leave my resolution at 2560x1080 then the font size is perfectly fine so it seems this occurs if you match your resolution and the nordic ui config

*edit - further info in bug-hunting*

**Comment by ChunkeeMunkee** [comment]
Just tried multiple combinations of 16:9 and 21:9 resolutions, both with the Widescreen Fix and Nordic additional mods enabled and disabled, all still seem to give me the large font size.

**Comment by ForgottenGlory** [comment]
Help wanted

**Comment by ForgottenGlory** [comment]
Fixed 3.7.0
