### ISSUE TITLE
AP start choice dialogue overlaps screen edge at 32:9 aspect ratio

### ISSUE THREAD

**Issue by ChunkeeMunkee** [ForgottenGlory/Living-Skyrim-3#529]
**LS Version**
3.5.0

**Describe the bug**
The Alternate Perspective starting choice dialogue box seems to climb higher on the screen as the aspect ratio increases, so much so that "Default" and "Random" are not accessible at 32:9.

**To Reproduce**
Run the game at a 32:9 aspect ration, talk to AP room dragon.

**Expected behavior**
Dialogue to remain centred.

**Screenshots**

16:9@1080p
![enb2021_9_19_00_18_34](https://user-images.githubusercontent.com/2692881/133911256-1eee25e7-2623-4d30-a182-b91e50146be7.png)

21:9@1440p
![enb2021_9_19_00_24_25](https://user-images.githubusercontent.com/2692881/133911258-b1541dc7-705b-45a9-8471-45aa28d623aa.png)

32:9@1440p
![enb2021_9_19_00_29_12](https://user-images.githubusercontent.com/2692881/133911261-9be1287e-1073-4f3c-980d-c0fa23017c1d.jpg)

**Comment by ForgottenGlory** [comment]
Open to suggestions for this one

**Comment by ForgottenGlory** [comment]
Should be fixed 3.7.0
