### ISSUE TITLE
The smoke from fires looks realistic while the fog in caves/dungeons is very low quality and not fog-like.

### ISSUE THREAD

**Issue by Quietbeat** [ForgottenGlory/Living-Skyrim-3#53]
**LS Version**
3

**Describe the bug**
When viewing the smoke from fire sources, it looks realistic but the fog inside caves is no were near realistic. It looks like globs of something that don't look nor behave like fog.

**To Reproduce**
Go into any cave that has fog.

**Expected behavior**
The fog should look and behave realistically. 

**Screenshots**
![Smoke from fire](https://user-images.githubusercontent.com/57841662/106843458-e7624900-665a-11eb-9a04-544c2e010845.png)
<_working on getting a screenshot from a cave_>

**Additional context**
[saves.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/5923072/saves.zip)

**Comment by Quietbeat** [comment]
After loading a previous save file and not overriding the .ini files from the ENB as mentioned to in the ENB's website , the fog in caves looks much better. Your read.me file says to following the instructions for the ENB so doing so caused problems for me. Thinking you need to clarify your statement.

![ENB](https://user-images.githubusercontent.com/57841662/106843869-e847aa80-665b-11eb-8d2b-c5a323348f6f.png)

**Comment by daffodilian** [comment]
Following the instructions for an ENB preset should be done every time you switch ENB presets.
>After loading a previous save file and not overriding the .ini files from the ENB as mentioned to in the ENB's website

Did you install ENB in the correct order? Meaning that  you extracted the correct files from enbseries_skyrimse_v0452.zip, and then installed Amon's preset, overwriting that?

I'm having trouble seeing how anything in the ENB section of the read me could cause you problems.
