### ISSUE TITLE
Nordic UI hijacks main menu background on Ultrawide settings

### ISSUE THREAD

**Issue by ChunkeeMunkee** [ForgottenGlory/Living-Skyrim-3#530]
**LS Version**
3.5.0

**Describe the bug**
The default Nordic UI background replaces the LS3 custom background at 21:9 and 32:9 aspect ratios.

**To Reproduce**
Activate relevant aspect ratio mods from the Configuration Specific section, and start the game.

**Expected behavior**
LS3 custom main menu.

**Screenshots**

16:9@1080p
![enb2021_9_19_00_17_36](https://user-images.githubusercontent.com/2692881/133911287-2d2edc89-dd95-4f8b-b04b-da049124c3a5.png)

21:9@1440p
![enb2021_9_19_00_23_46](https://user-images.githubusercontent.com/2692881/133911288-008daee8-68bd-4665-bd12-cc9058289ff6.png)

32:9@1440p
![enb2021_9_19_00_28_26](https://user-images.githubusercontent.com/2692881/133911289-d2fcef6b-0ebc-444e-9eab-7acd5e28fc40.png)

**Comment by ForgottenGlory** [comment]
Fixed 3.6.0
