### ISSUE TITLE
Quick Mass Follower Commands overwriting Campfire hotkeys

### ISSUE THREAD

**Issue by Dace617** [ForgottenGlory/Living-Skyrim-3#531]
**LS Version**
3.5.0

**Describe the bug**
The default Hotkey for Quick Mass Follower commands is ' which is also in use by campfire for the instincts power

**To Reproduce**
attempt to use the campfire instincts hotkey, mass follower commands menu activates instead

**Additional context**
The Quick Mass Follower Commands hotkey can be altered by changing the dx scan code in QuickFollowerCommands.json
it should probably replace the keybind we used to use for command followers in NFF.

**Comment by ForgottenGlory** [comment]
Fixed 3.6.0
