### ISSUE TITLE
Brown face bug

### ISSUE THREAD

**Issue by Wotchim** [ForgottenGlory/Living-Skyrim-3#534]
**LS Version**
3.5.0

**Describe the bug**
Brown face bug plus gaps around neck area.

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

![Brownface01png](https://user-images.githubusercontent.com/91005966/133920928-0cef4977-e67c-4865-9a0b-40a837c29518.png)

**Comment by ForgottenGlory** [comment]
Fixed 3.6.0
