### ISSUE TITLE
Embers XD overwriting Animated Forge Water mesh

### ISSUE THREAD

**Issue by celadoneiron** [ForgottenGlory/Living-Skyrim-3#535]
**LS Version**
3.5.0.

**Describe the bug**
Forge water is uggo

**To Reproduce**
look at forge

**Expected behavior**
forge water not uggo

**Screenshots**
![Screen Shot 09-19-21 at 18 42](https://user-images.githubusercontent.com/73095714/133921133-16215568-a69a-4a9f-85c5-bfb8b7d42a91.PNG)

**Comment by ForgottenGlory** [comment]
Fixed 3.6.0
