### ISSUE TITLE
Enemy Health bars not showing up when turning off Target bars from TDM

### ISSUE THREAD

**Issue by roguesins** [ForgottenGlory/Living-Skyrim-3#536]
**LS Version**
3.5

**Describe the bug**
When turning off the floating target bars from True Directional Movement, and activating the applicable settings in MoreHud (or any other MCM), the enemy health bar doesn't show up. Best I've been able to get in the Stamina and Magicka bars and just a number for the health (see screenshot).

**To Reproduce**
Turn off Target Bars in TDM, including "hide Vanilla Target Bar", try to get the vanilla style target bars in the UI from other MCM options (MoreHUD seems to be the only one with these options)

**Expected behavior**
Disable target bars from TDM and have the older "vanilla" style target bars near the compass.

**Screenshots**
![image](https://user-images.githubusercontent.com/81392570/133926997-a394d6f9-37f1-415e-bd13-dd96493cde31.png)

**Comment by ForgottenGlory** [comment]
Almost as if we turned them off for a reason.

**Comment by hiroshi-mcbride** [comment]
I take it there's not going to be a fix of this? It makes for poor compatibility with moreHUD
