### ISSUE TITLE
Cannot claim Bleak Falls Tower

### ISSUE THREAD

**Issue by AbbadontheDespoiled** [ForgottenGlory/Living-Skyrim-3#537]
After clearing Bleak Falls Tower and then, after recommendation, Bleak Falls Barrow, the claim flag for the tower still gives the message "You cannot claim this area until all enemies are killed", another user on the discord has said that after spamming the "kill all" console command around the area this is still persistent.

**Comment by ForgottenGlory** [comment]
Fixed 3.6.0
