### ISSUE TITLE
Falkreath Jarl's Longhouse floor and door bug

### ISSUE THREAD

**Issue by jeffreyxli** [ForgottenGlory/Living-Skyrim-3#538]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
3.5

**Describe the bug**
When you enter the Jarl's Longhouse in Falkreath, the floor of the main room continuously switches between a wooden texture and a stone one. Also, when you walk through into the main room from the entrance, a door is spawned after you pass through that cannot be interacted with. Thus, you cannot leave without using console commands etc. 

**To Reproduce**
1. Enter the Jarl's Longhouse in Falkreath
2. Walk through the first entrance on the left
3. Notice buggy floor as you walk around and spawned door

**Expected behavior**
Assuming the desired texture should just be the wooden one and there is no conflict between the two.

**Screenshots**
![ScreenShot253](https://user-images.githubusercontent.com/90986726/133941125-64922e8d-0d7f-48f9-9da8-02eda1150606.png)
![ScreenShot254](https://user-images.githubusercontent.com/90986726/133941134-526a4b0b-eaeb-4a19-8b71-fba7fadd506a.png)

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**

**Comment by ForgottenGlory** [comment]
Fixed 3.6.0
