### ISSUE TITLE
QuickLootRE no longer ships with retexture

### ISSUE THREAD

**Issue by wswank13** [ForgottenGlory/Living-Skyrim-3#539]
**Section**
Configuration Specific

**Description**
Third paragraph/second config-specific option mentions a retexture for QuickLoot.  This no longer appears in Mod Organizer as of 3.5.0 (downloaded ~1700 MST 9/19/21).

**Comment by ForgottenGlory** [comment]
Fixed 3.6.0 (re-added retexture as optional enable)
