### ISSUE TITLE
CTD every 40 odd minutes. 

### ISSUE THREAD

**Issue by Jacobim-Mugatu** [ForgottenGlory/Living-Skyrim-3#540]
Living Skyrim 3

I am getting constant CTD with no rhyme or reason, after about 5 load screens whether it be a death or entering a building it will crash, always in the loading screen. 
I cannot consistently repeat this. 

[Uploading Crash_2021_9_22_21-18-44.txt…]()

This is my most recent crash, I believe lux is involved but I'm not too sure.

**Comment by ForgottenGlory** [comment]
Please reupload the log, the upload didn't complete.
