### ISSUE TITLE
Crash when going near Reachwind Eyrie

### ISSUE THREAD

**Issue by Naragun** [ForgottenGlory/Living-Skyrim-3#541]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
Put the version of the list you are on here.

3.5

**Describe the bug**

Crash to desktop when going close to the map marker of what I believe is the Reachwind Eyrie

**To Reproduce**

Go to Reachwind Eyrie (possibly with organic faction npc there)

**Expected behavior**

Continue without crashing

**Screenshots**

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**

Seems like it's related to organic faction npcs based on crash logs

[Crash_2021_9_21_18-45-7.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/7212357/Crash_2021_9_21_18-45-7.txt)
[Crash_2021_9_22_9-4-42.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/7212358/Crash_2021_9_22_9-4-42.txt)
[Crash_2021_9_22_9-15-56.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/7212359/Crash_2021_9_22_9-15-56.txt)

**Comment by Naragun** [comment]
Another one a bit further from the area by Mirai's camp
[Crash_2021_9_22_9-31-14.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/7212409/Crash_2021_9_22_9-31-14.txt)

**Comment by chtkwz** [comment]
here is how it looks in my game 
https://www.youtube.com/watch?v=wIauWDpeT6M

**Comment by ForgottenGlory** [comment]
Fixed 3.6.0
