### ISSUE TITLE
Child face bug in darkwater crossing

### ISSUE THREAD

**Issue by Otsdarvatheeverchosen** [ForgottenGlory/Living-Skyrim-3#542]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
3.5

**Describe the bug**
Face bug with children

**To Reproduce**
Go to darkwater crossing and look at child named Geir

**Expected behavior**
Not have face bug

**Screenshots**
![20210922182025_1](https://user-images.githubusercontent.com/90943178/134429739-000b92e5-89d2-46a5-ad21-04fd6ea2975f.jpg)
![20210922180909_1](https://user-images.githubusercontent.com/90943178/134429791-6d39dda2-18bd-45c7-9f9e-a2958acb5db4.jpg)

**Additional context**

**Comment by ForgottenGlory** [comment]
Fixed 3.6.0
