### ISSUE TITLE
Crash to desktop (no log) on death load

### ISSUE THREAD

**Issue by wswank13** [ForgottenGlory/Living-Skyrim-3#543]
**LS Version**
3.5.0, downloaded 9/19/2021.

**Describe the bug**
On player death, the game attempts to quickload the last save, hangs on "Skyrim is not responding", and crashes without generating a crash log.  Attempting to quit to main menu from deathcam causes a similar crash.

**To Reproduce**
Use save files in attached .zip.  Become an hero.  Wait for load screen to hang and note game disappearing shortly thereafter.

[Save47_22452307_0_4C656E6E61_Tamriel_000628_20210923222808_4_1.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/7221530/Save47_22452307_0_4C656E6E61_Tamriel_000628_20210923222808_4_1.zip)

**Expected behavior**
Expected behavior is to quickload without crashing.

**Additional context**
Man who take laxative before bed, wake up in deep shit.

**Comment by ForgottenGlory** [comment]
Unfortunately I'm not really able to do anything about this without a crash log.
