### ISSUE TITLE
Dolls in LOTD safehouse not displaying correctly.

### ISSUE THREAD

**Issue by PulsefireEzreal** [ForgottenGlory/Living-Skyrim-3#544]
The new dolls added in 3.5 are great, however, neither the dolls, nor their replicas can be put into their display cases, the only luck i have found so far was the child's doll, but because that is a vanilla hearthfire item, it might be the reason why. Below are the item Id's of two dolls I have that do not currently get displayed, either manually, or automatically.

![image](https://user-images.githubusercontent.com/80222523/134755605-7a4d2d5e-e1b7-4fb4-884b-0dd6d0084413.png)

![image](https://user-images.githubusercontent.com/80222523/134755615-92b59f26-4de7-48fe-8f6a-9d8e33b3055c.png)

I do not know of the other dolls exactly, but my guess is they might be the same.

**Comment by ForgottenGlory** [comment]
Fixed 3.6.0
