### ISSUE TITLE
CTD while travelling in the Reach.

### ISSUE THREAD

**Issue by Educ4tedGu3ss** [ForgottenGlory/Living-Skyrim-3#546]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

[Crash_2021_9_24_23-41-6.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/7230933/Crash_2021_9_24_23-41-6.txt)
[Crash_2021_9_26_2-1-47.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/7230934/Crash_2021_9_26_2-1-47.txt)
[Crash_2021_9_23_20-42-13.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/7230935/Crash_2021_9_23_20-42-13.txt)

If possible, please also attach a copy of your most recent save before the issue occurred.**

[Most recent save.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/7230947/Most.recent.save.zip)

**LS Version**
3.5

**Describe the bug**
CTD while traveling in the Reach, Particularly near large Forsworn encampments such as The Karthspire and Deepwood Redoubt.
Has also occurred less frequently in random areas such as east of Markarth Stables.

**To Reproduce**
Travel around the reach near the aforementioned locations

**Additional context**
The latest save is just after I cleared a dungeon, if you exit the cave and head towards Markarth you should experience the crash.
The most recent .NET log is from the road next to the Karthspire going towards Markarth after loading the most recent save.

**Comment by chtkwz** [comment]
i was about to make similliar topic


https://youtu.be/wIauWDpeT6M
here is how it looks in my game

**Comment by Educ4tedGu3ss** [comment]
From the video it appears to be the same issue for sure. Considering I've crashed east of Markarth and just down the road from where the video shows, it seems to be that general area next to the Dwemer thing (I think it's from Project AHO, not saying it's related just that area.)

**Comment by MorganRuthless** [comment]
[Crash_2021_10_19_23-3-3.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/7373067/Crash_2021_10_19_23-3-3.txt)

Just chiming in that I am also experiencing this issue, not in those exact locations but along that circular path near Markarth.

**Comment by ribeirojc1** [comment]
Same here

**Comment by TwistedModding** [comment]
Old issue, we know what mod is the cause of it, and the author is trying to fix it.

**Comment by MorganRuthless** [comment]
Just curious @TwistedModding what mod is the cause? Thanks for updating us, appreciate it.

**Comment by ribeirojc1** [comment]
@MorganRuthless 
Organic factions
Seems it's 2 npcs:
TESNPC(Name: `Forsworn Assault Leader`, FormId: 41311EA8, File: `OrganicFactionsExtension.esp`)
TESNPC(Name: `Lost Valley Assault Archer`, FormId: 41311EAE, File: `OrganicFactionsExtension.esp`)

**Comment by Educ4tedGu3ss** [comment]
Seeing as this is a known issue with the mod in question I'm going to go ahead and close this issue. Hopefully the issue is fixed in a future version of OFE. Thanks everyone for your input.
