### ISSUE TITLE
Nordic UI Ultrawide Less Intrusive HUD issues

### ISSUE THREAD

**Issue by Dace617** [ForgottenGlory/Living-Skyrim-3#547]
**LS Version**
3.5.0

**Describe the bug**
Enabling either of the Nordic UI ultraiwde mods makes Less Intrusive Hud's editing overlay invisible and practically unusable as well as ignoring the layout in the preset and even possibly making the bars invisible constantly due to the ultrawide patches overwriting the less intrusive hud nordic UI fix.

**To Reproduce**

**Expected behavior**
The health mana and stamina bars to function correctly and Less Intrusive HUD's editing to be usable.

**Additional context**
Possible solutions would be using the hudmenu.swf file from the Nordic UI less Intrusive HUD fix in both the ultrawide options instead of the current ones used or lowering the nordic ui less intrusive hud fix below configuration specific in the load order.

**Comment by ForgottenGlory** [comment]
Fixed 3.5.1
