### ISSUE TITLE
Missing floors in the Temple of Mara in Riften

### ISSUE THREAD

**Issue by zoeytf** [ForgottenGlory/Living-Skyrim-3#548]
**LS Version**
3.5.0

**Describe the bug**
There are missing floors in the Temple of Mara in Riften. Only in Maramal's quarters, and the room opposite of it on the left. Items/NPC's/Players will fall to the bottom, and be teleported back to the entrance of the Temple.

**To Reproduce**
Enter the Temple of Mara in Riften, and head to either Maramal's room, or go to the left side of the temple.

**Expected behavior**
For there to be no missing floors.

**Screenshots**
https://i.imgur.com/dCX6KuT.jpg - Maramal's room
https://i.imgur.com/qVrqR51.jpg - Adjacent room

**Additional context**

LS Version: 3.5.0

**Comment by ForgottenGlory** [comment]
Fixed 3.6.0
