### ISSUE TITLE
Ranger Outfit Invisible

### ISSUE THREAD

**Issue by idefelipe** [ForgottenGlory/Living-Skyrim-3#55]
**LS Version**
LS3 Beta 1

**Describe the bug**
When forging the Ranger Outfit (all items) it looks invisible. Also, the value looks a bit overpriced

**To Reproduce**
Go to a forge and find the Ranger Outfit.

**Expected behavior**
It should be shown in the forge. 

I have not tested if it is also invisible when you forge and equip it.

**Screenshots**
https://i.imgur.com/FelbF64.png

**Additional context**
I have not tested forging it and equipping, and maybe it also is invisible when it is equipped.
The price is very high, compared with other similar items price.

**Comment by ForgottenGlory** [comment]
Should be fixed Beta 2
