### ISSUE TITLE
Flakreath Jarl's longhouse bug

### ISSUE THREAD

**Issue by Jarendron** [ForgottenGlory/Living-Skyrim-3#550]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
3.5.0

**Describe the bug**
Z-fighting floor texture in Falkreath Jarl's longhouse. Also the Door to enter the main chamber has no activation point to allow you to leave.

**To Reproduce**
Enter the Jarl's longhouse.

**Expected behavior**
For everything to be normal.

**Screenshots**
![enb2021_9_26_21_02_48](https://user-images.githubusercontent.com/83714085/134839648-fd759383-f365-41d8-8cc8-85a5bc6bdef7.jpg)
![enb2021_9_26_21_02_23](https://user-images.githubusercontent.com/83714085/134839652-47218aa9-8a6c-448c-a9c7-5da83d59b379.jpg)

**Additional context**
[Quicksave0_6072F3F0_0_4A27476861737461_Tamriel_000243_20210926025702_4_1.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/7233096/Quicksave0_6072F3F0_0_4A27476861737461_Tamriel_000243_20210926025702_4_1.zip)
.

**Comment by ForgottenGlory** [comment]
Fixed 3.6.0
