### ISSUE TITLE
Reload after crash or death in "Proving Honor", leading to missing companions with all the loot and reset of skills

### ISSUE THREAD

**Issue by MrKeron** [ForgottenGlory/Living-Skyrim-3#551]
**LS Version**
On the latests version.

**Describe the bug**
I was doing the quests "Proving Honor" for the companions, accompanied by Toccata. The first time I died, when the game loaded the latest save, inside the Poving Honor quest, Toccata was missing along with everything she was carrying, a lot of the mods reset their settings, my gear was all unequiped and all my skills were reset.
The second time, I finished the quest, but the game crashed.. Tried reloading a save into one of the last parts of the dungeon and the same thing happened.

**To Reproduce**
Not sure, but it did happen on the same quest.. It broke my last 3 saves both times. I had to go back to my save in Jorrvaskr, before I started the quest.

**Expected behavior**
The mods to not reset, and loose all that progress, including skills, mod settings and everything Tocatta was carrying, and a lot of the things I was carrying myself.

**Comment by ForgottenGlory** [comment]
This is caused by exceeding the plugin limit for SSE. Remove the mods you've added by re-installing the list using Wabbajack and start a new save.
