### ISSUE TITLE
Floating window at 2rd floor of lotdsafehouse

### ISSUE THREAD

**Issue by kakapapalala** [ForgottenGlory/Living-Skyrim-3#552]
![Snipaste_2021-09-28_10-34-50](https://user-images.githubusercontent.com/32580028/135014836-1b0778e8-829f-49b0-b880-0588ef22453f.png)
Game version ls 3.5.1

**Comment by TwistedModding** [comment]
fixed

**Comment by ForgottenGlory** [comment]
Fixed 3.6.0
