### ISSUE TITLE
Blank screen after loading Nurndural - Sickness Ward in Clockwork

### ISSUE THREAD

**Issue by sovietclarinet** [ForgottenGlory/Living-Skyrim-3#553]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
3.5.1

**Describe the bug**
When trying to enter Nurndural - Sickness Ward, loading screen finishes and screen turns black with music still playing. Does not CTD, but otherwise completely locks up game. Cannot progress in quest without going in this cell.

**To Reproduce**
Steps to reproduce the behavior: Enter Sickness Ward from save.

**Expected behavior**
Area loads.

**Screenshots**

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**
Save: [save.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/7249120/save.zip)

**Comment by Dace617** [comment]
Try installing/updating the most recent x64 Visual C++ Runtimes and restart your PC, we've had a couple successes with people doing this that stops the blackscreens

you can download them [here](https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0)

**Comment by sovietclarinet** [comment]
That fixed it thank you!
