### ISSUE TITLE
Carved Brink CACO compatability

### ISSUE THREAD

**Issue by Dace617** [ForgottenGlory/Living-Skyrim-3#554]
**LS Version**
3.5.0/3.5.1

**Describe the bug**
Carved Brink adds lootable powders that mimic existing potions in the game that don't play nice with Complete Alchemy and Cooking Overhaul: Poisonous Powder and Refined Poisonous Powder both don't function with CACO's changes as they are listed as a 0 duration for the effects so the poison applies to the weapon but does nothing to an enemy. The Powders that restore health/magicka/stamina similarly don't have a duration but still function, they're just instant effects.

**To Reproduce**
attempt to use these powders

**Additional context**
patch fix in patch sharing

**Comment by ForgottenGlory** [comment]
Fixed 3.6.0
