### ISSUE TITLE
Falmer drops not aligning to anatomy

### ISSUE THREAD

**Issue by Dace617** [ForgottenGlory/Living-Skyrim-3#555]
**LS Version**
3.5.1

**Describe the bug**
Higher Level Falmer are dropping 4 ears 

**To Reproduce**
Level high enough for Falmer Skulkers, Falmer mages or Gloomlurkers to appear, Kill one, loot.

**Expected behavior**
Falmer to be anatomically correct in death, and not have ears in their limited pocketses

**Additional context**
something in LS3 Patches Merged  is overwriting the LS3_CACO_Patch in the merge and adding an extra 2 ears to the DeathFalmerItems leveled item aside from the ones CACO places on them

**Comment by Dace617** [comment]
Fix shared

**Comment by ForgottenGlory** [comment]
Fixed 3.6.0
