### ISSUE TITLE
CTD in Windhelm/Possibly related to fire effects (ENB disabled)

### ISSUE THREAD

**Issue by fyreglider** [ForgottenGlory/Living-Skyrim-3#556]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**
Unable due to file type
Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
Put the version of the list you are on here.
3.5.1
**Describe the bug**
Stuttering when viewing fire effects, CTD upon entering Palace of Kings in Windhelm, as well as a CTD on the second floor of Candlehearth Hall, facing fireplace.
**To Reproduce**
Unsure, possible that it could be hardware limitations.
**Expected behavior**
Did not expect fire and flame effects to cause stutter and CTD
**Screenshots**

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional cont

Add any other context about the problem here
[Crash_2021_9_30_18-6-24.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/7263238/Crash_2021_9_30_18-6-24.txt)
[Crash_2021_9_30_19-4-25.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/7263239/Crash_2021_9_30_19-4-25.txt)

**Comment by fyreglider** [comment]
User update: CTDs have gotten more manageable after resolving some hardware driver issues, though stuttering persists and seems to nearly crash near windhelm. Other users have reported similar issues within dragonsreach, which is also where my first unmentioned crash took place. Theory: Mesh Conflicts between Inferno and Embers are causing stuttering and possible CTDs in interiors with bonfire and campfire objects. Attached are the mesh files that the two mods have in common. It seems that the conflict is derived from the clutter and effects folders within the mesh folders. I'm not an expert at troubleshooting, so this is a best guess
![MeshConflicts2excludeSovngarde](https://user-images.githubusercontent.com/91706458/135666765-9e44921e-a309-4ad5-b8a7-4ba6115e0595.PNG)
![MeshConflicts](https://user-images.githubusercontent.com/91706458/135666758-69cd2b31-062e-4c9a-bccf-59847778f253.PNG)
.

**Comment by MorganRuthless** [comment]
Hey, I'm also having the same issue but running with an ENB. Our error logs have the same relevant objects
[Crash_2021_10_11_0-17-7.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/7317512/Crash_2021_10_11_0-17-7.txt)
.

**Comment by ForgottenGlory** [comment]
Should be fixed 3.6.0
