### ISSUE TITLE
Odd Texture Overlaps near Pale Pass and in the Pale Pass Extended zone

### ISSUE THREAD

**Issue by FatalityMilk** [ForgottenGlory/Living-Skyrim-3#557]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
3.5.1

**Describe the bug**
Seems to be textures overlapping on top of one another, with these textures issues popping up in the camp area where you first talk to the smuggler who tells you about Serpent Trail and within the Pale Pass Extended zone that connects Skyrim and Cyrodill. Skyrim, LOTD Pale Pass Extended, and Bruma all might be conflicting.

**To Reproduce**
Head over to the border and cross through Pale Pass into the "Pale Pass Extended" zone which is included in the pack. From here you will see the roads odd, with floating textures at Knee level, then head to the Old Pale Fort and you will see numerous texture issues including those that are shown in the screenshots

**Expected behavior**
I expected the textures to be formatted on the land properly, while it does not impact gameplay it is god ugly.

**Screenshots**
![LS3 Pale Pass bug 1](https://user-images.githubusercontent.com/91711451/135559539-4d64d5a2-bcf3-451a-b5b3-014382241532.jpg)
![LS3 Pale Pass bug 2](https://user-images.githubusercontent.com/91711451/135559541-5a1cb5e3-4416-47db-9cdf-c4614abdda6f.jpg)
![LS3 Pale Pass bug 3](https://user-images.githubusercontent.com/91711451/135559543-313e2767-de80-4e24-be0d-4e9de4541855.jpg)
![LS3 Pale Pass bug 4](https://user-images.githubusercontent.com/91711451/135559546-866723c0-6408-45f7-ae5c-56225550883a.jpg)
![Screenshot (2)](https://user-images.githubusercontent.com/91711451/135559548-a416dce9-501a-45da-9af1-42e9a0edff22.png)

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

- The console would not select the terrain that is causing the issue near the smuggler.

**Additional context**

**Comment by ForgottenGlory** [comment]
Looks like a DynDOLOD issue that can happen sometimes. A game restart can fix it, or leaving the area for a while and coming back can fix it as well.
