### ISSUE TITLE
Winter is Coming mod is not active

### ISSUE THREAD

**Issue by idefelipe** [ForgottenGlory/Living-Skyrim-3#558]
**LS Version**
LS 3.5.1

**Describe the bug**
The cloaks, backpacks, hoods and other recipes from Winter is Coming mod are not shown in the tanning rack when the requirement is fullfiled. 

This requirement is, as shown in the mod nexus web, to have the Fur Crafting Kit in the inventory.

**To Reproduce**

1. build a fur craft kit / purchase a fur craft kit in a trader
2. go to a tanning rack
3. Find the fur hoods, cloaks and things related to WiC mod (the recipes should appear automatically when you have the fur craft kit in your inventory)

**Expected behavior**
The recipes should appear and should be able to be crafted.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by PulsefireEzreal** [comment]
Could be possible recipe book requirement. Just to note.

**Comment by celadoneiron** [comment]
They're available at the forge. I can change that if it's too confusing/doesn't feel natural.
