### ISSUE TITLE
A knight (NPC) is all the time on horse in the same place - Riften

### ISSUE THREAD

**Issue by idefelipe** [ForgottenGlory/Living-Skyrim-3#56]
**LS Version**
LS3 Beta 1

**Describe the bug**
There is a NPC Knight staying all the time in the same place in the city of Riften. He does not move nor do anything else.

**To Reproduce**
Go to riften and will find him in the bridge near the inn.

**Expected behavior**
He should dismount, or move out of the city, or something.

**Screenshots**
![ScreenShot189](https://user-images.githubusercontent.com/78406797/106867635-21b8fe00-66ce-11eb-8045-1fa02ef8ad3c.png)

**Additional context**
I think I found another one in the low levels in Riften (near the water channel).

**Comment by TwistedModding** [comment]
select the npc and horse in the console and post a screenshot

**Comment by ForgottenGlory** [comment]
Might have just been a quirk particular to that save, I'm not able to replicate this.
