### ISSUE TITLE
Falkreath Long House Bug

### ISSUE THREAD

**Issue by FruchtgummiMania** [ForgottenGlory/Living-Skyrim-3#560]
- You can enter the Jarl's longhouse but there are wooden floor board and stone tiles textures flickering on the entire ground floor.

- You can NOT leave the longhouse since the unmodded version of the house still seems to exist on top of the modded one. That means the vanilla entrance door exists but is not useable, effectively imprisoning the player in the house since he can not enter the newly added entrance hall (The one with the animal statues

![ScreenShot245](https://user-images.githubusercontent.com/91563725/135714941-82a8dde3-2994-4eb4-a668-fe9e6e022352.png)

![ScreenShot247](https://user-images.githubusercontent.com/91563725/135714945-fb7bad0a-9142-4038-85b2-a91afd9b6ba4.png)

**Comment by ForgottenGlory** [comment]
Fixed 3.6.0
