### ISSUE TITLE
Diety Favor

### ISSUE THREAD

**Issue by Elvenman24** [ForgottenGlory/Living-Skyrim-3#563]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
3.5.1

**Describe the bug**
Favor is either not being gained from menial tasks. Or if it is, it is not popping up with a notification.

**To Reproduce**

**Expected behavior**

[**Screenshots**]
![enb2021_10_8_13_06_47](https://user-images.githubusercontent.com/51525788/136602956-ddace520-1554-4ba9-88fd-7c31e30d8062.jpg)
![enb2021_10_8_13_06_37](https://user-images.githubusercontent.com/51525788/136602951-540d897c-5368-4db0-a47f-d1a8826c30d3.jpg)
![enb2021_10_8_13_07_01](https://user-images.githubusercontent.com/51525788/136602966-d7780931-1057-4bcd-ade7-fe53381d008d.jpg)

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**
Problem started shortly after Updating list from 3.5.0 to 3.5.1. Favor is no longer gained when doing menial tasks, if it is gained it doesn't pop up with a notification, the notification for "You haven't prayed in a while" also does not pop up anymore

[Save628_8C80163F_0_41727961_Tamriel_042205_20211008180100_30_1.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/7313418/Save628_8C80163F_0_41727961_Tamriel_042205_20211008180100_30_1.zip)
notification, the notification for "You haven't prayed in a while" also does not pop up anymore

**Comment by ForgottenGlory** [comment]
Fixed 3.6.0
