### ISSUE TITLE
Quest book fail to trigger quest

### ISSUE THREAD

**Issue by Elvenman24** [ForgottenGlory/Living-Skyrim-3#564]
**LS Version**
3.5.1
**Describe the bug**
The quest book Aetherium Wars does not trigger Lost to the Ages quest. 
**To Reproduce**

**Expected behavior**
Reading the book starts the Questline.

**Screenshots**

**Additional context**
Quest not triggering was true both on first read of the book, and on second read after finding an Aetherium Shard gave miscellaneous quest (Identify the Crystal Shard) to find the book and start the quest. Had to Find Arkngthamz myself and activate Katria's body to start the quest Lost to the Ages

**Comment by Elvenman24** [comment]
![enb2021_10_8_19_30_23](https://user-images.githubusercontent.com/51525788/136637323-fdeafd99-fb2f-4751-9714-1d980dd1fd8a.jpg)

**Comment by Elvenman24** [comment]
![enb2021_10_8_19_33_49](https://user-images.githubusercontent.com/51525788/136637426-76b2d1e5-89d4-4e9a-95df-91e3f52f73fd.jpg)

**Comment by ForgottenGlory** [comment]
I'm not seeing any reason this wouldn't work. Will fix when fix is found.
