### ISSUE TITLE
Follower Mirai

### ISSUE THREAD

**Issue by Elvenman24** [ForgottenGlory/Living-Skyrim-3#565]
**LS Version**
3.5.1

**Describe the bug**
Mirai's elemental shouts hurt the PC, and her Frost Atronarch aggro's other followers if they get too close to it

**To Reproduce**
stand in front of Mirai when she shouts. have a follower get too close to the Frost Atronarch

**Expected behavior**
Doesn't deal damage to PC or other followers

**Screenshots**

**Additional context**
Frost Atronarch close aoe Slow aura affects followers and causes them to aggro and fight it

**Comment by Elvenman24** [comment]
Mirai
![enb2021_10_8_19_35_18](https://user-images.githubusercontent.com/51525788/136637461-edbb3d95-54d8-4434-9e9e-37f487292a4f.jpg
Mirai's Atronach
![enb2021_10_8_20_33_56](https://user-images.githubusercontent.com/51525788/136639248-16c128d4-148d-430f-a23e-8fdf959b7b6d.jpg)
)

**Comment by ForgottenGlory** [comment]
Help wanted
