### ISSUE TITLE
Hitbox Frost Atronarch/Atronarch Matron

### ISSUE THREAD

**Issue by Elvenman24** [ForgottenGlory/Living-Skyrim-3#566]
**LS Version**
3.5.1
**Describe the bug**
Frost Atronarch and any larger versions of Frost atronarch Hitbox's are skewed

**To Reproduce**
Target lock any frost atronarch and fire arrows at it

**Expected behavior**
Arrow hits and deals damage

**Screenshots**

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**
Frost atronarchs hit box is only it's legs and inbetween the legs, when using Aim lock, and firing a ranged projectile at it, the Arrow harmlessly flies through the atronarch, have to manually aim and hit its legs or in between the legs. Will add screenshots later with Unit ID and possibly the target lock/aiming

**Comment by Elvenman24** [comment]
Screenshot of Crosshair large dot means it will hit it, small dot is it going through atronach and hitting something in the distance First picture is about as high as it will actually hit the Atronach, and Target lock tries to hit it mid chest.
![enb2021_10_8_20_37_00](https://user-images.githubusercontent.com/51525788/136639315-26868256-622a-4ac4-8e15-bc4f4dcb6c39.jpg)
![enb2021_10_8_20_37_02](https://user-images.githubusercontent.com/51525788/136639316-09779d08-2751-4ada-994f-bce3fc05010e.jpg)
![enb2021_10_8_20_37_03](https://user-images.githubusercontent.com/51525788/136639317-7aa190b4-d874-4c91-a0df-b09f53f0e6ca.jpg)
![enb2021_10_8_20_37_09](https://user-images.githubusercontent.com/51525788/136639318-bad67d59-931c-4914-a087-5b1d9b085f47.jpg)
![enb2021_10_8_20_37_16](https://user-images.githubusercontent.com/51525788/136639319-6a494518-b856-491c-baef-888572cb1da7.jpg)
![enb2021_10_8_20_37_19](https://user-images.githubusercontent.com/51525788/136639320-90b658d1-73d1-4379-9eef-20506483edf8.jpg)

**Comment by ForgottenGlory** [comment]
Need a screenshot of the atronach selected with the console open please.
