### ISSUE TITLE
Jaxonz MCM Kicker resets certain MCM settings on every game load

### ISSUE THREAD

**Issue by celadoneiron** [ForgottenGlory/Living-Skyrim-3#568]
**LS Version**
3.5.1.

**Describe the bug**
MCM settings for some mods are reset to default on every game load.

**To Reproduce**
1. Start a new game.
2. Look at the items in the wardrobe and observe that displayable items have the LOTD symbols on their inventory cards.
2. Open the MCM for The Curator's Companion, go to the "Advanced" settings tab, and set the moreHUD icons to "Hide All".
3. Look at the items in the wardrobe and observe that the LOTD symbols are no longer there.
4. Save the game.
5. Reload that save.
6. Look at the items in the wardrobe and observe that the LOTD symbols are back.
7. Look at the TCC MCM and observe that the settings still say "Hide All", but just don't hide all.
8. Cry.

**Expected behavior**
Adjusting settings in MCM should persist throughout save.

**Additional context**
There's one mention on the MCM Kicker mod page of another mod doing this, though not a mod we use in the list. TCC is the only one I can currently confirm, but I suspect it might also be contributing to a desync-on-load issue I'm experiencing with the compass toggle and the AMOT clock widget toggle.

I don't think there's a way around this other than to remove MCM Kicker.

**Comment by ForgottenGlory** [comment]
Fixed 3.6.0
