### ISSUE TITLE
Area not loading.  Walking from College to Windhelm

### ISSUE THREAD

**Issue by ggnvz** [ForgottenGlory/Living-Skyrim-3#57]
![Screenshot 2021-02-04 133038](https://user-images.githubusercontent.com/78560707/106938627-3bb60900-66ed-11eb-86eb-1c1dd1e0be64.png)

After starting a new game I try walking from College of Winterhold to Windhelm.  I end up getting meshes that won't load and textures that look unloaded.  This was an issue in Living Skyrim 1.  I found a solution to it in Living Skyrim 1 but I forget what it was. 

EDIT:  My apologies,

Specs are here:
Intel i5 8600K @ 4.3gHz
RTX 2070 Super
32GB DDR4 RAM
Game loaded on Samsung EVO 860 1TB SSD

Second Edit: reloaded the game and pushed the game to it's limit. Walked to Windhelm in the air using TCL. Area loaded fine. Not sure what the culprit is.

**Comment by TwistedModding** [comment]
Looks fine on my end

**Comment by ggnvz** [comment]
Could be VRAM running out. I noticed a guy streaming Living Skyrim 3 on Twitch and he walked up to Whiterun and all of the textured/meshes looked muddy like the picture above. He said he just enters a new cell/building and it fixed itself. He showed me on stream and said the list is very VRAM hungry and walking long distances can cause this. Is there any option in DYNDOLOD that could fix this or help?

**Comment by ForgottenGlory** [comment]
If it truly was VRAM running out we'd be seeing it all over the place, not just Windhelm. I'm not able to replicate this on my end.
