### ISSUE TITLE
"Hide Quest Items in Container Menu" mod is preventing Climb the Steps quest progression

### ISSUE THREAD

**Issue by mdurec21** [ForgottenGlory/Living-Skyrim-3#570]
**LS Version**
3.4.0.1

**Describe the bug**
"Hide Quest Items in Container Menu" mod enabled does make Klimmek's supplies item removed from container menu, thus preventing placing them in the quest chest during Climb the Steps quest.

**Expected behavior**
Klimmek's supplies item is visible in container menu, to be able to put it into quest chest.

**Additional context**
temporary workaround: disable "Hide Quest Items in Container Menu" mod

**Comment by celadoneiron** [comment]
This is a duplicate of #473 , and is about a bug that was fixed multiple versions ago.
