### ISSUE TITLE
TUDM - The Ultimate Dodge Mod v4 Google Drive DL has gone private

### ISSUE THREAD

**Issue by lordendgame** [ForgottenGlory/Living-Skyrim-3#572]
**LS Version**
Current version: 3.5.1

**Describe the bug**
The Google Drive Download link for TUDM - The Ultimate Dodge Mod v4 has gone private and requires permission to access. This makes the mod whole modpack unavailable for download from Wabbajack.

**To Reproduce**
Downloading the Mod Pack

**Expected behavior**
Unable to download the mod pack

**Screenshots**
https://imgur.com/a/MLk4CEb

**Additional context**
N/A

**Comment by gjcampesi63** [comment]
@lordendgame how did you get the file. Were you eventually granted permission to the google drive link? I am having the same issue and wondering how you closed it.

**Comment by thehajo** [comment]
Check the pins in #ls-install-support.

**Comment by gjcampesi63** [comment]
I found a working link in the pinned messages of that channel and manually installed it. Everything is working fine now. Thank you for your help!
