### ISSUE TITLE
Falkreath Jarl's Longhouse magic door 

### ISSUE THREAD

**Issue by Razgriz35** [ForgottenGlory/Living-Skyrim-3#573]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
Living Skyrim 3 (up to date)

**Describe the bug**
When I'm entering the Jarl's Longhouse of Falkreach to finish my quest (speak to the jarl of Falkreach), there is an entrance making me go left, then in the main hall. When I want to go back outside, a door appears and it can't be opened. 

Ps : NPC walk though like if there wasn't any door. 

**To Reproduce**
Go to the Longhouse I suppose. 

**Expected behavior**
It shouldn't be a door here. 

**Screenshots**
The entrance : on the right side, we can walk to the main hall and to the jarl. 
![20211020_153337](https://user-images.githubusercontent.com/92867631/138103403-15195c3f-bd7b-4df8-8435-80d3313c46e8.jpg)

On the way out : 
A freaking door appears ( not the main door): 
![20211020_153405](https://user-images.githubusercontent.com/92867631/138103613-91d11c82-e885-43f8-bb1f-728598065cb2.jpg)

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**

**Comment by PulsefireEzreal** [comment]
Known bug. Fixed in 3.6. Open console, select it in console, then use command disable to remove it. Please make sure to check the github before posting to avoid multiple of the same report.
