### ISSUE TITLE
Vissual Effect fix for Mace Amulet of Molag Bal

### ISSUE THREAD

**Issue by sicarface** [ForgottenGlory/Living-Skyrim-3#574]
Its not an bug but an anoying visual
when ever your in contact with an enemy the DB will be shrouded in an soulcloak which is pretty anoying in first person.
i found a possible solution in the offical mod page (Amulets of Skyrim SSE), which i did not try but could help you removing this visual:

1) Open AmuletsSkyrim.esp in SSEEdit
2) Expand the Magic Effect section, look for the one called Soul Trap Cloak
3) Find the section somewhat near the top that says Flags (sorted)
4) Right-click it, Edit, remove the flag 'FX Persist'
5) Copy-paste the following (without the quotes): "NULL - Null Reference [00000000]"
6) Right-click the line that says Hit Shader, click Edit, ctrl+v that line
7) ctrl+s to save changes, close SSEEdit

If you also use Legacy of the Dragonborn:
8) Re-open SSEEdit, open both AmuletsSkyrim.esp and DBM_AmuletsofSkyrim_Patch.esp this time
9) Go to Soul Trap Cloak under Magic Effect in AmuletsSkyrim again, there should now be two columns
10) Right-click each of the two sections you just changed in the right column, Edit, make the same changes there, you don't need to touch the Magic Item Description part

**Comment by ForgottenGlory** [comment]
Fixed 3.6.0
