### ISSUE TITLE
CTD: Game crashes when Saving

### ISSUE THREAD

**Issue by the12thscorpion** [ForgottenGlory/Living-Skyrim-3#575]
**LS Version**
LS 3.4.0.1

**Describe the bug**
Game won't Save. Everytime i'm trying to save the game it crashes to desktop; No matter where I am on the map. This started happening once I exited ''Dimhollow Crypt'' 
- Also, (Don't know if this is revelant)  this happened earlier in the game too at the same location, I tried to go back a few levels, Delete every save that had the early stages of the Dawnguard DLC and tried again a few levels higher, but no luck.

**To Reproduce**
I have no Idea

**Expected behavior**
A new save.

[Crash_2021_10_21_19-58-14.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/7392274/Crash_2021_10_21_19-58-14.txt)

**Comment by celadoneiron** [comment]
This is a known issue fixed in 3.5. To fix it for your current save, you can disable Occlusion.esp in the right-hand pane of MO2 (likely at some performance cost) or regenerate occlusion using the steps in the Performance Guide (although if you follow all of the steps the game won't look as good).
