### ISSUE TITLE
CTD when walking in Kynesgrove

### ISSUE THREAD

**Issue by Thortug** [ForgottenGlory/Living-Skyrim-3#576]
Hey!

So this is my first time here and I hope I'm doing this right, if not please forgive me ahah. 

**LS Version**
3.5.0

**Describe the bug**
When I enter Kynesgrove (just after discovering it) the game CTDs after some seconds walking. Happened 3 times in a row, in both werewolf and human form. I tried restarting my PC, and I already did the pagefile thing, nothing seems to fix this bug.

**To Reproduce**
Discovering Kynesgrove. Walking into Kynesgrove.

**Expected behavior**
Walking in Kynesgrove without CTD I guess ^^

Here are my 3 crashlogs:

[Crash_2021_10_23_3-35-18.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/7402799/Crash_2021_10_23_3-35-18.txt)
[Crash_2021_10_23_3-29-17.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/7402800/Crash_2021_10_23_3-29-17.txt)
[Crash_2021_10_23_12-44-0.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/7402801/Crash_2021_10_23_12-44-0.txt)

**Comment by Thortug** [comment]
Issue has been fixed by waiting several hours (in game) just outside Kynesgrove, and then discovering and entering it! I had no crashes since then in this place.

**Comment by ForgottenGlory** [comment]
Should be fixed 3.6.0
