### ISSUE TITLE
Crash running from Markath toward Mirai's fishing hut

### ISSUE THREAD

**Issue by Gerdofal** [ForgottenGlory/Living-Skyrim-3#577]
Running at night from Markath down the path toward Mirai's fishing cottage on her first quest.  Crash happens just past the second lamp from the save.

**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

[Crash_2021_10_25_5-20-2.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/7410396/Crash_2021_10_25_5-20-2.txt)
[Crash_2021_10_25_5-25-5.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/7410404/Crash_2021_10_25_5-25-5.txt)
[Crash_2021_10_25_5-29-29.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/7410407/Crash_2021_10_25_5-29-29.txt)

If possible, please also attach a copy of your most recent save before the issue occurred.**

[Save160.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/7410412/Save160.zip)

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
3.5.1

**Describe the bug**
Momentary freeze while running then crash to desktop. Crashlog generated.

**To Reproduce**
Continue running down the path in the direction of the quest. Crash happens just after passing the second lamp along the path.

**Comment by Gerdofal** [comment]
Definitely related to:

SSE Organic Factions Extension
(and maybe Organic Factions Extension - Patch Collection... I can't tell)

I deactivated those and the crash went away.

Most likely related to the Siege of Markath and/or Forsworn, but the result is to make this area pretty much unplayable unless you want to save way more often than is good.

**Comment by PulsefireEzreal** [comment]
Its a known crash, best way to solve it for now until 3.6 is to wait a few days, and save up to right before you get there. Also please re-run wabba as disabling mods are not supported so no further support will be given, also this is a duplicate ticket so please close it.

**Comment by Gerdofal** [comment]
Yep, I know, re-running it now.
