### ISSUE TITLE
Smart Cast issue

### ISSUE THREAD

**Issue by Quietbeat** [ForgottenGlory/Living-Skyrim-3#58]
**LS Version**
3

**Describe the bug**
When I try to assign known spells using Smart Cast, only Call Horse and Pray are available. I have several spells as favorites. I looked at two Smart Cast videos and they all say that you simply pick the spell you want to use.

**To Reproduce**
Have one or more spells and try to assign them in Smart Cast.

**Expected behavior**
All of my spells are available.

**Screenshots**
![Favorite spells](https://user-images.githubusercontent.com/57841662/106952954-aadc2f00-66e6-11eb-9af7-63ce38ff4640.png)
![Restoration spells](https://user-images.githubusercontent.com/57841662/106952956-ab74c580-66e6-11eb-9663-475979c288b0.png)
![Smart Cast - Config](https://user-images.githubusercontent.com/57841662/106952958-ab74c580-66e6-11eb-81ee-a8f9562cc905.png)
![Smart Cast - Spells](https://user-images.githubusercontent.com/57841662/106952961-ac0d5c00-66e6-11eb-8cd3-e0d1dc5544d1.png)

**Additional context**
[saves.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/5928396/saves.zip)

**Comment by ForgottenGlory** [comment]
You have to equip the spells before they will show up in the SmartCast menu, because it looks for spells that have been recently equipped.
