### ISSUE TITLE
Swapping the location of the hearthfiredolls patch so its below the actual mod itself.

### ISSUE THREAD

**Issue by PulsefireEzreal** [ForgottenGlory/Living-Skyrim-3#581]
Reason why the hearthfire dolls are not going into the display is because the patch is loaded BEFORE the mod itself. Hajo already tested it and found this.
![image](https://user-images.githubusercontent.com/80222523/139537016-28b960f0-8861-4b96-b92a-f2243bc9091c.png)

**Comment by ForgottenGlory** [comment]
Fixed 3.6.0
