### ISSUE TITLE
Activating an arcane enchanter or riding a horse seems to count as praying 

### ISSUE THREAD

**Issue by Beege808** [ForgottenGlory/Living-Skyrim-3#586]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
3.6.0.1

**Describe the bug**
Mounting a horse and using an Arcane Enchanter both put the player in a state of Prayer. If the player is following Mehrunes Dagon, this is fatal, as his prayer mechanic is timed and spending too long in a prayer state kills the player. 

**To Reproduce**
Follow Mehrunes Dagon, then activate an Arcane Enchanter. 

**Expected behavior**
Prayer and object activation shouldn't be related. 

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**
It might be the case for any faith, but it's the most obvious with Mehrunes Dagon because you get a visual effect on your character when you're praying, and you die after a few seconds.

**Comment by ForgottenGlory** [comment]
Can you please provide a copy of your save file so we can try to reproduce this?

**Comment by Beege808** [comment]
[Save320_CA06C4DC_0_5472697374726978_WinterholdCollegeHallofTheElements_010032_20211109153020_17_1.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/7507152/Save320_CA06C4DC_0_5472697374726978_WinterholdCollegeHallofTheElements_010032_20211109153020_17_1.zip)

No idea what I did to trigger this one but I haven't been able to do it since. Let me know if there's anything I can do to help, it might be a tricky one to track down or it could've just been a one-off thing.
