### ISSUE TITLE
(REUPLOAD since I forgot to link the save file) Ring of Jurgen Windcaller won't reforge into the ancient version.

### ISSUE THREAD

**Issue by BigChungusFungus** [ForgottenGlory/Living-Skyrim-3#589]
LS Version
Living Skyrim 3.6.0.2

Describe the bug
The Ring of Jurgen Windcaller (Located in the Ustevgrav Depths) won't reforge into in the ancient version. (Link: https://legacy-of-the-dragonborn.fandom.com/wiki/Ring_of_Jurgen_Windcaller)

To Reproduce
There were no clear things I did that led to this bug.

Expected behavior
Described in the "Describe the bug" section.

Screenshots
Non-Applicable.

Additional context
[$R32ZX0C.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/7509954/R32ZX0C.zip)

**Comment by thehajo** [comment]
As commented on the other report, after checking your save, you did not meet one of the requirements. You still had the Summon Inigo spell equipped. I unequipped it (and took the ring back from your follower) and:
![grafik](https://user-images.githubusercontent.com/38141473/141391989-53887de7-469b-403c-8228-cad727e52fa2.png)

**Comment by TwistedModding** [comment]
reopen if issue persists
