### ISSUE TITLE
CTD When trying to fast travel by horse and carriage from Falkreath to Riften

### ISSUE THREAD

**Issue by ggnvz** [ForgottenGlory/Living-Skyrim-3#59]
[Crash_2021_2_5_0-57-4.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/5930526/Crash_2021_2_5_0-57-4.txt)

After playing for about 30 minutes or so I try to fast travel to Riften by horse from Falkreath. Immediate CTD

**Comment by TwistedModding** [comment]
Can you replicate this?

**Comment by ggnvz** [comment]
I tried last night and I could not replicate. I fast traveled to all major cities by horse with no crash
