### ISSUE TITLE
Alternate Perspective "Dragonborn" start doesn't work

### ISSUE THREAD

**Issue by Gerdofal** [ForgottenGlory/Living-Skyrim-3#590]
**LS Version**
3.6.0.1

**Describe the bug**
If you choose Dragonborn start and try to go out the door, the script seems to stall at some point. Unbound is completed and a few others, Bleak Falls is started... then everything stops.

Screen stays black, you can run though and end up back in the start room.

**To Reproduce**

1. Choose "Dragonborn - I went with Rolof"
2. Exit the room

**Expected behavior**
I imagine should be teleported somewhere. Alternately, if it just won't work with LS3, maybe it could be hidden from the menu?

**Additional context**
Sometime during the processing player is prompted to choose a god, not sure if this is related or not. I tried not choosing, but the existence of the dialog seems to pause the scripting.

**Comment by Gerdofal** [comment]
[saves.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/7514489/saves.zip)

**Comment by ForgottenGlory** [comment]
Should be fixed 3.7.0
