### ISSUE TITLE
No longer able to install on fresh Skyrim install due to Anniversary update

### ISSUE THREAD

**Issue by Gerdofal** [ForgottenGlory/Living-Skyrim-3#593]
I did a fresh Skyrim install today and the modlist will no longer install.  Looks like the attempt to copy to the stock game folder fails.

> 198.97 - Unable to download binkw64.dll (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|binkw64.dll)
198.97 - Unable to download Skyrim.ccc (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|skyrim.ccc)
198.97 - Unable to download SkyrimSE.exe (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|skyrimse.exe)
198.97 - Unable to download Data_Dawnguard.esm (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\dawnguard.esm)
198.97 - Unable to download Data_Dragonborn.esm (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\dragonborn.esm)
198.97 - Unable to download Data_HearthFires.esm (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\hearthfires.esm)
198.97 - Unable to download Data_Skyrim.esm (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\skyrim.esm)
198.97 - Unable to download Data_Update.esm (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\update.esm)
198.97 - Unable to download Data_Skyrim - Animations.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\skyrim - animations.bsa)
198.97 - Unable to download Data_Skyrim - Interface.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\skyrim - interface.bsa)
198.98 - Unable to download Data_Skyrim - Meshes0.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\skyrim - meshes0.bsa)
198.98 - Unable to download Data_Skyrim - Meshes1.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\skyrim - meshes1.bsa)
198.98 - Unable to download Data_Skyrim - Misc.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\skyrim - misc.bsa)
198.98 - Unable to download Data_Skyrim - Patch.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\skyrim - patch.bsa)
198.98 - Unable to download Data_Skyrim - Shaders.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\skyrim - shaders.bsa)
198.98 - Unable to download Data_Skyrim - Sounds.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\skyrim - sounds.bsa)
198.98 - Unable to download Data_Skyrim - Textures0.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\skyrim - textures0.bsa)
198.98 - Unable to download Data_Skyrim - Textures1.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\skyrim - textures1.bsa)
198.98 - Unable to download Data_Skyrim - Textures2.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\skyrim - textures2.bsa)
198.98 - Unable to download Data_Skyrim - Textures3.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\skyrim - textures3.bsa)
198.98 - Unable to download Data_Skyrim - Textures4.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\skyrim - textures4.bsa)
198.98 - Unable to download Data_Skyrim - Textures5.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\skyrim - textures5.bsa)
198.98 - Unable to download Data_Skyrim - Textures6.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\skyrim - textures6.bsa)
198.98 - Unable to download Data_Skyrim - Textures7.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\skyrim - textures7.bsa)
198.98 - Unable to download Data_Skyrim - Textures8.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\skyrim - textures8.bsa)

**Comment by Gerdofal** [comment]
Sorry, didn't notice the server announcement

**Comment by perc3ptr0n** [comment]
> Sorry, didn't notice the server announcement

I am a new one in this modding stuff, which announcement? Have the same problem =(

**Comment by thehajo** [comment]
The one from yesterday, in #server-announcements.
