### ISSUE TITLE
Lux placing a window in the LotD Safehouse (patch load order issue)

### ISSUE THREAD

**Issue by Dace617** [ForgottenGlory/Living-Skyrim-3#594]
**LS Version**
3.6.0.1

**Describe the bug**
The extra window placed by Lux (details in issue #552) is still present 

**To Reproduce**
check the second floor of the safehouse

**Expected behavior**
no window

**Screenshots**
see original issue #552

**Additional context**
there is a patch fixing this already in the list but it needs to be placed after the lux patch causing the issue (ls3_lotd_window_fix.esp needs to be placed after Lux - Legacy of the Dragonborn Patch.esp)

**Comment by ForgottenGlory** [comment]
Fixed 3.7.0
