### ISSUE TITLE
Heathfire dolls still not getting placed

### ISSUE THREAD

**Issue by thehajo** [ForgottenGlory/Living-Skyrim-3#595]
**LS Version**
3.6.0.2

**Describe the bug**
Same as #544 , Dolls are not getting placed down

**To Reproduce**
Try to place dolls in Safehouse

**Expected behavior**
Dolls getting placed

**Screenshots**
See #544 

**Additional context**
Need to put AdditionalHearthfireDolls.esp anywhere above DBM_AdditionalHFDolls.esp

**Comment by ForgottenGlory** [comment]
Fixed 3.7.0
