### ISSUE TITLE
TUDM and xLODGen .meta files might be broken

### ISSUE THREAD

**Issue by thehajo** [ForgottenGlory/Living-Skyrim-3#596]
**LS Version**
3.6.0.2

**Describe the bug**
Seems like the .meta files for TUDM and xLODGen have links that are no longer available, thus causing the problem that the download fails on those.

![grafik](https://user-images.githubusercontent.com/38141473/141391322-2696902e-5e76-4019-8a8f-9ddd1eea66af.png)
![grafik](https://user-images.githubusercontent.com/38141473/141391401-92919143-efa2-412d-a450-d8d08c4d6976.png)

**Comment by mitchiehier19** [comment]
i got the failed download TUDM ErroR AS WEL as google drive Acces???? just on the exact last download haha, to im already dowloading for 3 a 4 days. please save our appreciation for this master piece as i still believe it can be 👍

**Comment by thehajo** [comment]
Please check #ls-install-support for further assistance with downloading and installing the list

**Comment by ForgottenGlory** [comment]
Fixed 3.7.0
