### ISSUE TITLE
TUDM forcing player out of sneak when weapon is drawn.

### ISSUE THREAD

**Issue by VinDogPD** [ForgottenGlory/Living-Skyrim-3#597]
**LS Version**
3.6.1 (Latest. Downloaded 11/11/2021)

**Describe the bug**
When sneaking with a weapon drawn, TUDM's dodge will trigger, sending the player character out of stealth mode.

**To Reproduce**
In this instance, on a new save, I selected a dagger from the starting room chest. I then chose the wanted criminal in Whiterun start. Upon entering the world, I began sneaking on the path, back and forth between the watch tower and the fort. Everything appears to work fine, but when I draw the dagger, eventually the TUDM dodge triggers on its own and forces the player out of stealth.

This bug was successfully reproduced by an admin in the Discord server.  See the ls-discussion server, timestamp 12:00am 11/12/2021.

Another user shortly thereafter reproduced the bug with a hunting bow and iron arrow equipped.

**Expected behavior**
TUDM not triggering automatically in stealth mode and taking the player out of stealth.

**Comment by ForgottenGlory** [comment]
Fixed 3.7.0
