### ISSUE TITLE
Improper Flesh Alteration Values

### ISSUE THREAD

**Issue by ghost** [ForgottenGlory/Living-Skyrim-3#599]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**
[Save224_68BC4F9B_0_417068726F64696574652773204469736369706C65_Mzulft01_011045_20211115233540_27_1.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/7542257/Save224_68BC4F9B_0_417068726F64696574652773204469736369706C65_Mzulft01_011045_20211115233540_27_1.zip)

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
Put the version of the list you are on here.
3.6.0.1
**Describe the bug**
- Flesh spells while being buffed by the alteration tree using Mage Armor are not giving correct armor values. For instance, I have no armor equipped and Ebony Flesh is only giving me 86AP whereas with the buffs and the base value alone it should be giving me 250AP (100 from the spell itself and then the 150% multiplier from Mage Armor 2). 

**To Reproduce**
-Simply attempt to cast ebony flesh with the attached save file. I am also using Breton which I have heard may be the cause of the issue. 

**Expected behavior**
- As described above the buffs should be placed properly giving me an armor value of at least 250. 
**Screenshots**

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**

**Comment by ForgottenGlory** [comment]
Should be fixed 3.7.0
