### ISSUE TITLE
UI components are clunky with ultrawide monitor

### ISSUE THREAD

**Issue by Quietbeat** [ForgottenGlory/Living-Skyrim-3#60]
**LS Version**
3

**Describe the bug**
I reinstalled the game and started a new character.
When I play the game without the 'Complete widescreen Fix..." the font size of the MCM mod menus (left pane) looks good but with the mod enabled, they're larger and overlap the border.  I've tried adjusting the font size in SkyUI to no avail.

**To Reproduce**
- Play the game on an ultrawide monitor without the mod
- Play the game on an ultrawide monitor with the mod

ASUS ROG Swift PG348Q:
	- Panel Size : Ultra-wide screen 34” 21:9
	- True Resolution : 3440x1440

**Expected behavior**
The font size of the mod menu selection is fits within the left pane.

**Screenshots**
![MCM when not using widescreen fix](https://user-images.githubusercontent.com/57841662/107001149-01c12300-673e-11eb-8f34-41ab4b8dc306.png)
![MCM when using widescreen fix](https://user-images.githubusercontent.com/57841662/107001155-05ed4080-673e-11eb-8334-4305b24363c5.png)

**Additional context**
When Googling if others had this issue, I came across the following Issue that was logged for v2 and that issue and mine seem related.
https://github.com/ForgottenGlory/Living-Skyrim-2/issues/75

[saves.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/5930959/saves.zip)

**Comment by ForgottenGlory** [comment]
The widescreen fix mod overwrites a lot of the HUD elements to make them look more reasonable on ultrawide monitors. Unfortunately it's not perfect, but it helps in most cases. This is, unfortunately, not one of them.
