### ISSUE TITLE
Tactical Valheim - Shield of Valheim CTD

### ISSUE THREAD

**Issue by sayso9** [ForgottenGlory/Living-Skyrim-3#601]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
Living Skyrim 3.6.0.2

**Describe the bug**
Consistent crashing every 5-10 minutes at seemingly random intervals. Later I found it was caused by Lucien holding the Shield of Valtheim

**To Reproduce**
Steps to reproduce the behavior: Give Lucien (or possibly any follower) the Shield of Valtheim from Tactical Valtheim. 

**Expected behavior**
The game will randomly crash every couple of minutes

**Screenshots**
Not able to really get any screenshots

**Additional context**
I found bug reports for this issue in the TacVal bug reports section
[Crash_2021_11_25_21-0-14.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/7606648/Crash_2021_11_25_21-0-14.txt)
[Crash_2021_11_25_20-45-58.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/7606649/Crash_2021_11_25_20-45-58.txt)
[Crash_2021_11_25_20-9-47.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/7606650/Crash_2021_11_25_20-9-47.txt)
[Crash_2021_11_25_23-37-11.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/7606651/Crash_2021_11_25_23-37-11.txt)
[Crash_2021_11_25_23-13-41.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/7606652/Crash_2021_11_25_23-13-41.txt)
[Crash_2021_11_25_23-10-36.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/7606653/Crash_2021_11_25_23-10-36.txt)
[Crash_2021_11_25_22-16-59.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/7606654/Crash_2021_11_25_22-16-59.txt)
[Crash_2021_11_25_22-7-20.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/7606655/Crash_2021_11_25_22-7-20.txt)
[Crash_2021_11_25_21-29-42.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/7606656/Crash_2021_11_25_21-29-42.txt)
[Crash_2021_11_25_21-20-40.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/7606657/Crash_2021_11_25_21-20-40.txt)
.

**Comment by TwistedModding** [comment]
Looks like a npc is checking to see if the player is aggresive towards the it and crashing after that. Maybe something to do with the AI package?
