### ISSUE TITLE
Female Breton's magic magnitude reduction bites both ways

### ISSUE THREAD

**Issue by AstridCone** [ForgottenGlory/Living-Skyrim-3#602]
**LS Version**
LS 3.6+

**Describe the bug**
The spell damage reduction perk applied to female Breton by GABI was created with some unforeseen consequences. Instead of touching something sensible like magic resistance, it instead would reduce incoming spell magnitude by 0.5% each level. The consequence of this is that all spell effects would be lessened in magnitude, mainly buff spells and enchanted equipment. So yeah, that's no good, all your enchants lessened by 25% at level 50 is pretty stinky.

**To Reproduce**
Create a female Breton, this issue can be identified by simply spawning a novice hood fresh out the character creation pre-mcm.

**Additional context**
Please lets just get rid of it, the balance is all over the place, and barely anyone is out here actually picking the sex of their character based on the associated bonuses

**Comment by Binturong3205** [comment]
Not sure if it helps, but GABI has been updated and no longer contains level-scaled bonuses. It's been completely revamped to flat, one-time effects. An update would likely resolve this one.

**Comment by AstridCone** [comment]
We're aware, and it has made away with the effect that was causing this. On the other hand, GABI is now completely pointless to its purpose, as its just an extended race overhaul with ironically very indistinct differences between the sexes

**Comment by ForgottenGlory** [comment]
Fixed 3.7.0
