### ISSUE TITLE
CTD at College of Winterhold

### ISSUE THREAD

**Issue by HillyBilly48** [ForgottenGlory/Living-Skyrim-3#603]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
3.6.0.1

**Describe the bug**
Constant crashing when entering the hall of attunement and the stairs leading up to the arcanuem. Crash logs attached below (first one is for the hall of attunement and the second one is for arcanuem.

**To Reproduce**
Steps to reproduce the behavior: enter the hall of attunement/stairs to arcanuem.

**Expected behavior**
Not crashing when entering these rooms

**Screenshots**

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**

[Crash_2021_11_30_13-45-38.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/7628182/Crash_2021_11_30_13-45-38.txt)
[Crash_2021_11_30_14-5-49.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/7628184/Crash_2021_11_30_14-5-49.txt)

[College Crash.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/7628200/College.Crash.zip)

**Comment by AELIENUS** [comment]
I also have this problem.

**Comment by Binturong3205** [comment]
Constant crashing at the college for me as well, same locations. Disabling Quick Light and turning off ENB didn't help, per Discord support.

**Comment by mannzzaa** [comment]
I'm having the same issue
[Crash_2022_2_13_21-25-48.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/8065755/Crash_2022_2_13_21-25-48.txt)
[CTD College of winterhold save ess and skse.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/8065808/CTD.College.of.winterhold.save.ess.and.skse.zip)
