### ISSUE TITLE
Wabbajack Website Gallery links

### ISSUE THREAD

**Issue by Dace617** [ForgottenGlory/Living-Skyrim-3#604]
When you click 'View' on the Wabbajack website Gallery on Living Skyrim and it takes you to the living skyrim machineurl page. the Living Skyrim Modlist link takes you to "https://www.fgsmodlists.com/living-skyrim" which returns a 404 error on the website. needs either a redirect to the correct page or changing the link

**Comment by ForgottenGlory** [comment]
Fixed
