### ISSUE TITLE
Mogo's Mead Case not visible/interactable

### ISSUE THREAD

**Issue by schererererer** [ForgottenGlory/Living-Skyrim-3#605]
**LS Version**
3.6.0.1

**Describe the bug**
Mogo's Mead Case is invisible/intangible or not present where it should be in the Black-Briar Meadery basement for the Mogo's Mead quest from Interesting NPCs, preventing the player from picking it up to continue the quest. The quest marker points to where it should be, and using prid 1015a1c2 to select it, moveto it, etc, function as expected. Additem was used as a successful workaround. There is also no visible model of the Mogo's Mead Case or the matching quest item Beatrice's Mogo's Mead Case in the inventory. 

**To Reproduce**
Follow the Mogo's Mead quest until you must take the Mogo's Mead Case in the Black-Briar Meadery, then note the quest objective marker points to empty space. 

**Expected behavior**
The item should be visible and able to be picked up. 

**Screenshots**
![enb2021_12_5_08_11_31](https://user-images.githubusercontent.com/8533789/145490627-8e6ee0f2-4df3-4a7b-9d48-a8ceeef7c485.png)

**Comment by celadoneiron** [comment]
Potential fix on trello.
