### ISSUE TITLE
Falkreath Flickering Objects / Misplaced Objects

### ISSUE THREAD

**Issue by Viatos** [ForgottenGlory/Living-Skyrim-3#608]
**LS Version**
3.6.0.2

**Describe the bug**
Several locations in Falkreath, exterior and interior, have flickering/vanishing objects and bad placement, notably the Hall of the Dead, but some exterior locations as well.

**To Reproduce**
Go to Falkreath, find an outside overhanging roof where looking through the side-posts supporting it changes what things are visible depending on where you step. There is a location somewhere in town I was able to stand that caused most of the town to vanish at a certain angle.

Then, go to to the Hall of the Dead. The floor flickers constantly between two different textures and the beds for Runil and Kust are embedded in a stone wall. 

**Expected behavior**
Things would look like a lovely fantasy world with stable physical reality.

**Screenshots**
![image](https://user-images.githubusercontent.com/24367836/145634935-b8b42d1b-6cd1-48ad-9e56-0db520093a82.png)

**Comment by ForgottenGlory** [comment]
Should be fixed 3.7.0
