### ISSUE TITLE
Second constructed LOTD field station (Branching Out... Again) has a tree embedded in the stairs.

### ISSUE THREAD

**Issue by schererererer** [ForgottenGlory/Living-Skyrim-3#609]
**LS Version**
3.6.0.1

**Describe the bug**
A tree partially blocks access to the second LOTD field station, constructed in the quest 'Branching Out... Again'. 

**To Reproduce**
Follow the LOTD quest line(s) to where you build the second field station, and observe the tree that sticks around after construction.

**Expected behavior**
Tree should either be removed after construction or not exist to begin with. 

**Screenshots**
![enb2021_12_6_18_13_24](https://user-images.githubusercontent.com/8533789/145635639-999905d4-500a-49f4-a0c4-dfaa80fc8030.png)

**Comment by ForgottenGlory** [comment]
Fixed 3.7.0
