### ISSUE TITLE
Add comments on how to configure The Ultimate Dodge mod

### ISSUE THREAD

**Issue by Quietbeat** [ForgottenGlory/Living-Skyrim-3#61]
**LS Version**
3

**Describe the bug**
This is a Quality of Life request in that every time I've installed or updated the game, I have to reconfigure the mod and I always forget how. I took a note this time but for the future and others, I'd be helpful if you could do one or both things:
- Pre-configure this mod so that L-ALT is the Dodge key and Sneak is L-CTRL.
- Provide instructions on how to set this up.

**To Reproduce**
Pull your hair out as you try to figure out how to configure this mod.

**Expected behavior**
It just works.

**Screenshots**
n/a

**Additional context**
n/a

**Comment by TwistedModding** [comment]
It says in the mcm menu how to configure it, if you can't follow those simple instructions, I don't think anything else could help. 

Whatever your sneak key is in controls, is your dodge key, then you look at the mcm menu to figure out which key is your sneak key
