### ISSUE TITLE
Cant serve jail time. 

### ISSUE THREAD

**Issue by mojucy** [ForgottenGlory/Living-Skyrim-3#611]
**LS Version**
3.6.0.1

**Describe the bug**
when attempting to either sleep of jail time, or mine to enact the same effect in when forced to mine, i get a sleep option but not the normal menu which says you are about to serve jail time. Regardless of time spent, jail is never served. 

**To Reproduce**
get arrested, attempt to serve jail time

**Expected behavior**
jail time to be served, and removed from jail

**Additional context**
moderator, GravenImages was able to replicate this as well as my friend, who originally informed me of the bug.

**Comment by GravenImages** [comment]
A workaround is unlocking the cell door, punching the guard, and getting arrested again. This will allow you to serve the sentence as expected.

**Comment by ForgottenGlory** [comment]
Fixed 3.7.0
