### ISSUE TITLE
Unable to download LS3 3.6.0.2 modlist

### ISSUE THREAD

**Issue by zachjreed1993** [ForgottenGlory/Living-Skyrim-3#617]
**LS Version**
v3.6.0.2

**Describe the bug**
Unable to download Living Skyrim 3 Modlist. Receive "Error downloading modlist. Check logs and/or restart Wabbajack to try again" error. Have tried multiple time and receive same error each time. Any help would be greatly appreciated! 

**To Reproduce**
Press download button on Wabbajack. Failure occurs towards ends of download.

**Screenshots**
Wabbajack Log: 
[Wabbajack.current.log](https://github.com/ForgottenGlory/Living-Skyrim-3/files/7721921/Wabbajack.current.log)

![Capture](https://user-images.githubusercontent.com/96200516/146245633-cdaf5ef1-dfd8-4c83-a53e-397e1ee5db24.PNG)

Modlist shows up in "downloaded_mod_lists" folder but is corrupted when I try to open.
![Capture1](https://user-images.githubusercontent.com/96200516/146247024-9e1198c2-537c-4c1b-a584-716a9ab265b5.PNG)

**Additional context**
Followed procedure exactly. Uninstalled and reinstalled Skyrim SE. Used AE downgrade patcher afterwards. Tool said downgrade was successful.

**Comment by GravenImages** [comment]
Please drop the Wabbajack log in the #ls-install-support channel in the support Discord channel. Invite link, if you need it: https://discord.gg/fgsmodlists
