### ISSUE TITLE
Papyrus bloated, maybe by quest _M_QuestHjaalmarchGatherIngrMed

### ISSUE THREAD

**Issue by Marvozz** [ForgottenGlory/Living-Skyrim-3#618]
**Describe the bug**
Im 24 lv, and game is mostly unplayable because of script lag. 10 minute papyrus log gives around 30k calls of quest _M_QuestHjaalmarchGatherIngrMed, so my uneducated guess lies here. I don't recall that quest completely, and have no idea how to pinpoint it to exact mod. 

Most frequent occurences:

Dumping stack 12806781:
	Frame count: 0 (Page count: 0)
	State: Waiting on other stack for call (Freeze state: Freezing)
	Type: Normal
	Return register: None
	Has stack callback: No
	Stack trace:
		[alias Player on quest _M_QuestHjaalmarchGatherIngrMed (8C0133C6)]._M_AliasPlayerGather.OnItemAdded() - (requested call)
			[param 0]: [MiscObject < (FE20880D)>]
			[param 1]: 1
			[param 2]: None
			[param 3]: None

Dumping stack 11618952:
	Frame count: 0 (Page count: 0)
	State: Waiting on other stack for call (Freeze state: Freezing)
	Type: Normal
	Return register: None
	Has stack callback: No
	Stack trace:
		[alias Player on quest _M_QuestHjaalmarchGatherIngrMed (8C0133C6)]._M_AliasPlayerGather.OnItemRemoved() - (requested call)
			[param 0]: [MiscObject < (FE20880D)>]
			[param 1]: 1
			[param 2]: None
			[param 3]: None

**Comment by celadoneiron** [comment]
We can't do anything if you don't use the bug report template and attach the entire papyrus log file.
