### ISSUE TITLE
Sacrosanct issues

### ISSUE THREAD

**Issue by Amiral1212** [ForgottenGlory/Living-Skyrim-3#62]
**LS Version**
LS 3 beta 1.

**Describe the bug**
In LS2 final release, as a vampire, i had some powers depending on thirst, like vampire's command. With ls3 beta, i don't have these powers, and i can't get them by leveling. I specify that I tried to have them while being sated or while being hungry. I just don't have them. It also seems that the blue blood quest does not start after feeding on Delphine.

**Expected behavior**
have the powers based on our character's thirst, and launch the blue blood quest after feeding on a character concerned by this quest.

**Comment by TwistedModding** [comment]
sacrosanct isnt in living skyrim 3

**Comment by Amiral1212** [comment]
Oh ! my bad, 
will it be replaced by a similar mod?

**Comment by TwistedModding** [comment]
was replaced by this: https://www.nexusmods.com/skyrimspecialedition/mods/42408

**Comment by Amiral1212** [comment]
thanks :)
