### ISSUE TITLE
Pine Trees Low Res LOD

### ISSUE THREAD

**Issue by DonKinadon** [ForgottenGlory/Living-Skyrim-3#622]
**LS Version**
3.6.0.2

**Describe the bug**
Pine trees low res LOD only update when I'm fairly close to it. Then it renders whilst the LOD is still in place of a second or 2.

**To Reproduce**
I have an unchanged wabbajack install. Reinstalled it twice to be sure. Spawned at either at the Riverwood or Rorikstead inn and the the LOD's are hard to miss.

**Expected behavior**
Pine trees to render like the others. They're very hard to miss as they only render when I'm fairly close.

**Screenshots**

![Bentpine](https://user-images.githubusercontent.com/96259306/146665706-9bb877d3-e215-498e-8b4e-9211352aa41b.PNG)

![benptine_console](https://user-images.githubusercontent.com/96259306/146665676-66218a9a-2734-4d0c-bd4c-12f8a73d9829.PNG)

There's quite a few trees not transitioning from their LOD state properly but these huge bent pine trees are were the ones that made this issue obvious. There are other ones doing the same thing, only rendering when I'm fairly close. I'm aware that LODs are not meant to be high resolution but they are also not meant to "pop" like that at such a close distance. The screenshot is taken a bit far away to point out multiple of the same bent pine tree in one shot. 

The other ones I spotted were from Treeswinedave.esp and Graphics Merger.esp . I tried Disabling them but it is useless as their low res LOD will pop up at a short distance even without the tree.

Great work with the list though, I've never been so close to finally playing Skyrim after hundreds of lost hours trying to mod it 10 years go! If you could point me in the right direction with this or fix it if it's a bug, I would greatly appreciate it.

**Comment by ForgottenGlory** [comment]
Should be fixed 3.7.0
