### ISSUE TITLE
Occlusion causing bug at Silent Moons camp. (AGAIN)

### ISSUE THREAD

**Issue by PulsefireEzreal** [ForgottenGlory/Living-Skyrim-3#623]
Hey, just making a bug report about Occlusion like Twisted asked. Here's the latest log file someone had about it.
[Crash_2021_12_25_23-40-32 (1).txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/7776604/Crash_2021_12_25_23-40-32.1.txt)

**Comment by ForgottenGlory** [comment]
Should be fixed 3.7.0
