### ISSUE TITLE
Camera and movement keys stuck after game loads

### ISSUE THREAD

**Issue by DRYN07** [ForgottenGlory/Living-Skyrim-3#624]
**LS Version**
3.6.0.2

**Describe the bug**
After starting a game (new game or saved), the camera and most of the keyboard are not working. I can't use the mouse or the WASD, TAB, ESC, SPACE... Although some keys like campfire, journal etc opens the window. I can't even exit the game because the ESC key also not working.

**To Reproduce**
Steps to reproduce the behavior: I did nothing, just start the game. after it loads, the movement things are stucked

**Expected behavior**
I think it is obvious :)

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**
After this anomaly happens, I need to restart my PC or skyrim won't start again. If I try to alt tab, after a whle my whole screen goes black and can't do anything, however I am hearing skyrim's sounds and music. If I try to run the task manager, I see it is running if I press alt tab, but I cant change skyrim's black window

**Comment by WietseDeKoninckPXL** [comment]
Opening inventory and re-equipping items fixes this for me. Can you still access that?

**Comment by DRYN07** [comment]
> Opening inventory and re-equipping items fixes this for me. Can you still access that?

I think that is the only thing I did not try. Thanks for the idea, if this happens again I am going to check this.
