### ISSUE TITLE
Falskaar "Strength and Wisdom" and "Lost Knowledge" bug

### ISSUE THREAD

**Issue by Helm12** [ForgottenGlory/Living-Skyrim-3#625]
**LS Version**
LS3

**Describe the bug**
I was playing through Falskaar ,and during the Strength and Wisdom quest ,i encountered a progress breaking bug.Once you get to the end of "Strength and Wisdom" the next quest "Lost Knowledge" never starts ,you get the xp for completing "Strength and Wisdom" but "Lost Knowledge never starts"

**To Reproduce**
Start the quest "Strength and Wisdom" ,chose to go with either of the two keys (both have the same issue).And once you get to the last part of the quest ,the bug occurs .

**Expected behavior**
Once the "Strength and Wisdom" quest ends ,the next one should automatically start ,as is the case with the other quests.

**Additional context**
I have tried to set the quest stage to different stages ,to no avail.I have tried to also fast travel back ,pass time ,again ,same result.
Npcs involved in the quest : Jarl Agnar ,Ulgar ,Svegard and Brother Thorlogh.

**Comment by ForgottenGlory** [comment]
So I don't forget: https://www.nexusmods.com/skyrimspecialedition/mods/61445
