### ISSUE TITLE
Default Start seems to be broken, essentially

### ISSUE THREAD

**Issue by Day7-J** [ForgottenGlory/Living-Skyrim-3#628]
**LS Version**
3.7

**Describe the bug**
intro lock

**To Reproduce**
start game
do mcms
talk to dragon
choose default start
buy room (start intro)
try to move after "standing up" from sleeping to start the intro

**Expected behavior**
the ability to move after "standing up" from sleeping to start the intro

**Comment by LunaDarkfyre** [comment]
just encountered the same issue and used the fix mentioned on the  disccusion section  on the modpage for alternate perspectives heres link to it https://www.nexusmods.com/skyrimspecialedition/mods/50307?tab=posts  to sort this out was wondering if it was something on my end for while there lol

**Comment by Day7-J** [comment]
That just links to the posts tab, not the post, just so you know.

**Comment by LunaDarkfyre** [comment]
my bad thought that it did  and what i was attempting to link to was a post that  comes after all the pinned red posts its the 2nd post down from the last red pinned post and apologies again

**Comment by ForgottenGlory** [comment]
Fixed 3.7.1
