### ISSUE TITLE
Floating Door Above Whiterun Giant Camp

### ISSUE THREAD

**Issue by seanpbelcher** [ForgottenGlory/Living-Skyrim-3#63]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
LS3 Beta 1

**Describe the bug**
A door is floating above the giant camp in Whiterun hold. 

**To Reproduce**
N/A

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. Additionally, if your report applies to a specific object, make sure it is selected with the console open. Reports without this will be closed.
![enb2021_2_5_13_47_54](https://user-images.githubusercontent.com/67465410/107082771-4db1ad80-67ba-11eb-8771-13ce10c10f04.png)
![enb2021_2_5_13_47_30](https://user-images.githubusercontent.com/67465410/107082819-5b673300-67ba-11eb-90fc-b46fb5ff8b74.png)

**Additional context**

**Comment by TwistedModding** [comment]
Fixed - patch in discord

**Comment by ForgottenGlory** [comment]
Fixed Beta 3
