### ISSUE TITLE
Dark Brotherhood Armor SE being overwritten by vanilla model

### ISSUE THREAD

**Issue by Dace617** [ForgottenGlory/Living-Skyrim-3#631]
Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
3.7

**Describe the bug**
the model for Dark Brotherhood Armor SE is being overwritten by the vanilla model, it shows the alternate design in the inventory menu but it shows vanilla when equipped on a character

**To Reproduce**
obtain dark brotherhood armor, equip it. note model difference.

**Expected behavior**
the correct model to be displayed on your character

**Additional context**
Should be fixed by either redoing bodyslide so the correct armour is winning all conflicts

**Comment by ForgottenGlory** [comment]
Fixed 3.7.1
