### ISSUE TITLE
Crash to desktop when reloading (manually or automatically) after dying

### ISSUE THREAD

**Issue by Zamachi** [ForgottenGlory/Living-Skyrim-3#632]
`**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in [LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash**`
No crash files were generated(my folder is empty).

``If possible, please also attach a copy of your most recent save before the issue occurred.**``
Save file:
[Save484_59BA691E_0_42617473636861_Tamriel_021147_20220109000303_13_1.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/7842781/Save484_59BA691E_0_42617473636861_Tamriel_021147_20220109000303_13_1.zip)

**LS Version**
3.6

``**Describe the bug**
**To Reproduce**
**Screenshots**``
https://youtu.be/jNg4hrYkWuo <- best shown by a video

**Expected behavior**
I should be able to reload the game from anywhere without crashing. 

**Additional context**
I don't know if this can be tied to an area (The Reach), or the save count(which is 400+, not really sure if that can cause instabilities). But I've noticed these types of crashes when I got into areas near Riften...

Also, another log, dunno if it can be useful, the last sentence is a warning as it appears(it always appears last when the file is updated/regenerated). 
[usvfs-2022-01-10_23-49-54.log](https://github.com/ForgottenGlory/Living-Skyrim-3/files/7842783/usvfs-2022-01-10_23-49-54.log)
Also, another thing I used to do is do a quicksave, and make a regular save to overwrite that one, am not really sure if that can cause crashes either.

**Comment by Zamachi** [comment]
Just a small update, nothing too special, it could be related to the "Quicksave" functionality, namely, I've used to quicksave->regular save overwrite over that quicksave, and then reload afterwards... Or straight up reload a quicksave. I don't know if this can cause a crash, but it was something I was doing(and will try to avoid doing in the future).
Also, it could be area-related, I was around Riften, crashes like these specifically started occuring near Black Briar Lodge.

**Comment by celadoneiron** [comment]
_Possible_ fix: update [SSE Engine Fixes](https://www.nexusmods.com/skyrimspecialedition/mods/17230) to 5.8.3 for SE 1.5.97 in next list release and set MaxStdio = 8192 in config .toml file.

**Comment by Zamachi** [comment]
I've updated to 3.7.1 version of the modlist, so far no such crashes appear, I can reload after dying, but there's no guarantee it won't happen again, I won't try the fix _unless_ it becomes really necessary again. Thanks
