### ISSUE TITLE
my Living Skyrim keeps failing installation 

### ISSUE THREAD

**Issue by dreday846** [ForgottenGlory/Living-Skyrim-3#636]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
Put the version of the list you are on here.
living skyrim 3
**Describe the bug**
it was saying it was unable to download certain mods as in high poly head v1.4, Gleam Blossom Hollow ,and Voices EN
**To Reproduce**

**Expected behavior**
It to download with no problems 
**Screenshots**
If appliclble
```, add screenshots to help explain your problem.
![Screenshot 2022-01-18 131723](https://user-images.githubusercontent.com/97983700/150004020-6c623218-ec84-4bfa-b786-3e5ad4c2ecd7.png)

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**
Add any other context about the problem here.

**Comment by celadoneiron** [comment]
installation issue to do with WJ and/or VectorPlexus. for future reference: download files manually and save in chosen download folder before restarting WJ and rerunning installer
