### ISSUE TITLE
Game crashes on startup

### ISSUE THREAD

**Issue by DennisWitzel90** [ForgottenGlory/Living-Skyrim-3#638]
**NET Script Framework crash log is attached**

**LS Version**
Living Skyrim 3

**Describe the bug**
I have a clean install of Skyrim and installed Living Skyrim 3. When I start the game through ModOrganizer it opens the game to a black screen with some ENB info in the top left corner and then it just closes the game

[Crash_2022_1_23_18-37-51.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/7921036/Crash_2022_1_23_18-37-51.txt)
[Crash_2022_1_23_18-42-24.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/7921037/Crash_2022_1_23_18-42-24.txt)
[Crash_2022_1_23_18-51-7.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/7921038/Crash_2022_1_23_18-51-7.txt)

**Comment by Dace617** [comment]
This looks like your Antivirus interfering. 
If you are using an Antivirus program other than Windows Defender:

Try making exceptions for your Living Skyrim folder if possible, Disabling the antivirus, or you may need to uninstall the antivirus program completely.
