### ISSUE TITLE
Mona Alta landscape conflict

### ISSUE THREAD

**Issue by Fungusface** [ForgottenGlory/Living-Skyrim-3#639]
**LS Version**
3.7.1

**Describe the bug**
The Mona Alta player home is melded into the mountain it sits on. The building is inaccessible. There's another landmark very nearby called the Path of Faith (?) which is probably what it's conflicting with.

**To Reproduce**
Go to the Mona Alta location, north of Falkreath, and try to reach the building. You'll find it's impossible.

**Expected behavior**
Expect to be able to explore the Mona Alta location, but can't due to landscape.

**Screenshots**
![image](https://user-images.githubusercontent.com/25883197/150692512-1f47927f-fc5e-43e1-8a1d-d843f2948697.png)

**Additional context**
The Path of Faith landmark nearby also appears to be broken. There are stone stairs that lead to nowhere.

**Comment by celadoneiron** [comment]
Not a bug. The Path of Faith is the path to the house. You walk up the stairs to nowhere, and when you look towards the house from the high point, a bridge of light will appear that you can use to cross over to it.
