### ISSUE TITLE
Old Hroldan inn shadow issues and weird out of place stools. 

### ISSUE THREAD

**Issue by crustycreampietv** [ForgottenGlory/Living-Skyrim-3#64]
old hroldan inn has shadow issues and stools that are out of place. Living skyrim 3 of course :) 

pictures: 
![20210205200739_1](https://user-images.githubusercontent.com/78619253/107083204-963a8c80-67f5-11eb-8bd5-4b79c1d5ec80.jpg)
![20210205200744_1](https://user-images.githubusercontent.com/78619253/107083221-9cc90400-67f5-11eb-8e76-86756c4e39ff.jpg)
![20210205200749_1](https://user-images.githubusercontent.com/78619253/107083232-a05c8b00-67f5-11eb-9f37-5d71f1300794.jpg)

**Comment by Trent223** [comment]
Nothing to add other than I can reproduce this on Beta 2 as well.

**Comment by ForgottenGlory** [comment]
Fixed Beta 3
