### ISSUE TITLE
Hall of vigilant disappearing 

### ISSUE THREAD

**Issue by Ashensakar** [ForgottenGlory/Living-Skyrim-3#640]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
3.7.1

**Describe the bug**
Hall of the vigilants hall is gone, teleporting still works but the actual outside is gone, with just a few floorings.

**To Reproduce**
teleport to hall of the vigilants with new char

**Expected behavior**
Hall to be here.
**Screenshots**
https://imgur.com/a/kTG7DL6

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**
i've uploaded my saves to the ls-community-additions discord as i cant seem to upload them here

**Comment by Ashensakar** [comment]
[ls3 saves.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/7921297/ls3.saves.zip)

**Comment by zj-92** [comment]
Adding my saves, as I'm having the same issue. Had the orc for Dawnguard spawn and tell me about the Vigilants getting wiped out, but other than that I've done nothing for the Dawnguard story.

**Comment by zwoodcock** [comment]
[Save_LS3.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/8056730/Save_LS3.zip)

**Comment by zj-92** [comment]
[LS3_Save.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/8056806/LS3_Save.zip)
