### ISSUE TITLE
Missing Firiniel's End

### ISSUE THREAD

**Issue by TehOnlyPeanut** [ForgottenGlory/Living-Skyrim-3#642]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
Put the version of the list you are on here.
3.7.1
**Describe the bug**
Firiniel's Bow is not appearing during nor after the relevant Dark Brotherhood quest. When giving the item via console, it is invisible in hand and in inventory the model is of whatever item was previously shown/hovered.
**To Reproduce**
unknown? Item is missing. No mods added. Wabbajack install was a success.

**Expected behavior**
Firiniel's End to be on the ledge during the DB quest "Bound Until Death" or afterwards. After giving self item via console, I expected it to appear normal.
**Screenshots**
![image](https://user-images.githubusercontent.com/98442004/151100987-f9efd4c3-4977-463c-8837-52aa14242ea1.png)
![image](https://user-images.githubusercontent.com/98442004/151101021-51a2ddb4-5644-43c3-86a2-69c0c9bb6ea2.png)
![image](https://user-images.githubusercontent.com/98442004/151101045-c4be8afe-ae9f-4f48-a67a-2319d8ea11c5.png)

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**
Trying to drop the item to select it in console makes it despawn(?) item isn't visible nor are there any indicators to pick it up

**Comment by celadoneiron** [comment]
The Awesome Artifacts + ArteFakes patch included in the list is for a newer version of ArteFakes than we have, so ArteFakes needs to be updated (and Awesome Artifacts and its patch should be checked for updates as well just in case).
