### ISSUE TITLE
Vagrant Armor causes gloves to be disembodied in 1st person

### ISSUE THREAD

**Issue by ReallyRilee** [ForgottenGlory/Living-Skyrim-3#643]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
3.7.0

**Describe the bug**
The Vagrant Armor (chest piece) causes your gloves to look disembodied in 1st person. Your arms become invisible. 

**To Reproduce**
I removed all armor and tested each piece 1 by 1 to see which was causing the issue. 

**Expected behavior**
Your arms become invisible when you have a weapon/spell equipped in first person.

**Screenshots**
First 2 show the invisible arms in 1st person. Last shows the armor in 3rd person working as intended.
![20220126115708_1](https://user-images.githubusercontent.com/72872325/151211922-35deabd9-1887-47b7-aeb9-a1ef2e5167c8.jpg)

![20220126120550_1](https://user-images.githubusercontent.com/72872325/151211948-d35332aa-2d3a-44cc-ad05-0a8d012afe29.jpg)

![20220126121208_1](https://user-images.githubusercontent.com/72872325/151212504-0e09765d-92c9-485b-a3d2-a6c4d09256d5.jpg)

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**
The Vagrant armor set is obtained when killing Taranis during the Act 1 Vigilant quest line. My FoV is set to 95.

**Comment by celadoneiron** [comment]
Updating [Vigilant CBBE Patch](https://www.nexusmods.com/skyrimspecialedition/mods/43676) in the next version of LS3 should fix this. (v1.5.3 is the latest as of this comment.)
