### ISSUE TITLE
Boethiah's Proving quest book does not initate quest

### ISSUE THREAD

**Issue by fractalsauce** [ForgottenGlory/Living-Skyrim-3#645]
**Copy of your most recent save before the issue occurred**
[Save677_CAE61B15_0_5676617276656E_WhiterunWorld_050948_20220127230855_30_1.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/7954773/Save677_CAE61B15_0_5676617276656E_WhiterunWorld_050948_20220127230855_30_1.zip)

**LS Version**
3.7.0

**Describe the bug**
I killed and looted the corpse of Arns Falas, a Boethiah Cultist I found after fast traveling to The Atronach Stone. He had the book (Quest) Boethiah's Proving on his person. I had never read the book before and expected a journal entry to the quest. No such journal entry or quest started.

**To Reproduce**
Steps to reproduce the behavior: Find the book (Quest) Boethiah's Proving and read it to see if the quest pops. It won't.

**Expected behavior**
For a quest related to the book to start since the book has "(Quest)" appended to the beginning of its name.

**Screenshots**

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.
![enb2022_1_27_19_40_28](https://user-images.githubusercontent.com/54872574/151467933-39393bfc-8c17-4e50-8d54-34e284a66a0d.png)
![enb2022_1_27_19_40_59](https://user-images.githubusercontent.com/54872574/151467944-36721029-e903-445e-ad73-66d7fc4dbbc1.png)

**Additional context**
I decided to reload the save right before I got the book and give myself the book with the console and try again. There was still no quest that popped, but I did notice a notification popped in the upper left hand corner saying "Map Updated." I checked my map and it added a new ? symbol on it called Sacellum of Boethiah. I looked on the [Elder Scrolls Wiki](https://elderscrolls.fandom.com/wiki/Boethiah%27s_Calling) for the quest and it states "Boethiah's Calling is a quest available in The Elder Scrolls V: Skyrim. Upon reaching level 30, the book Boethiah's Proving will begin spawning in various locations. Once read, the quest will start."

**Comment by celadoneiron** [comment]
Not a bug, it's part of The Choice Is Yours.

> Reading the book "Boethiah's Proving" or encountering a cultist will not start the quest (it will, however, still give you the map marker to the shrine). You can find the shrine and speak to the Priestess, without automatically triggering the quest. The quest will not begin until you have agreed to complete the task she gives you. If you refuse the task and kill the cultists, you will be given 4 new options when speaking to Boethiah: Accept the quest (this begins the quest); Refuse the quest (nothing happens...the quest does not start, and you can return to complete the quest later if you change your mind), and up to two options to reject Boethiah completely (which will lead to alternate routes to complete the quest...you will not receive the Ebony Mail and can never return to finish the task for Boethiah. One of the rejection options is only available if you've completed Molag Bal's quest).

**Comment by fractalsauce** [comment]
Ah ok cool thanks for the info!
