### ISSUE TITLE
Greenhouse plants yield different from plantings

### ISSUE THREAD

**Issue by Chaps-Fantastic** [ForgottenGlory/Living-Skyrim-3#646]
**LS Version**
3.7.1

**Describe the bug**
In the Greenhouse of the player-built home (Hearthfire, Lakeview Manor), I planted the following plants which yielded different results:
PoisonBloom yielded Trama Root
Gleamblossom yielded Spiky Grass (edit)
Marshmerrow yielded Scrib Cabbage
[Something non-Vanilla] yielded Hanging Moss (edit)

I planted Scathecraw outside in the garden and the yield was Scathecraw, so it does seem to grow some non-vanilla plants (at least Outside)

**To Reproduce**
I will replant and update. I will also plant other non-vanilla plants inside the Greenhouse as well as outside in the garden to see if it makes a difference

**Comment by Chaps-Fantastic** [comment]
2nd Run in Greenhouse
PoisonBloom still yields Trama Root
Gleamblossom still yields Spiky Grass
I do not have any more Marshmarrow so I have not been able to confirm that
I cannot remember what I planted to yield Hanging Moss
I tried planting Scathecraw inside the greenhouse and it yields Crimson Nirnroot in the Greenhouse, but continues to yield Scathecraw outside in the garden.

**Comment by Chaps-Fantastic** [comment]
3rd Run (Garden)
PoisonBloom still yields Trama Root
Gleamblossom still yields Spiky Grass

**Comment by ForgottenGlory** [comment]
I get it. You don't have to comment every time the bug occurs.

**Comment by Chaps-Fantastic** [comment]
Sorry, I was just testing it under different circumstances and seeing if that affected the results.
