### ISSUE TITLE
LoTD missing Texture on building

### ISSUE THREAD

**Issue by Ashensakar** [ForgottenGlory/Living-Skyrim-3#647]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
3.7.1

**Describe the bug**
Lotd building as a missing building texture on a few of the buildings in the area during the quest

**To Reproduce**
On the LoTD quest Shattered Legacy, in the outside area Sancre Tor

**Expected behavior**

**Screenshots**
![enb2022_1_30_11_11_01](https://user-images.githubusercontent.com/68168803/151697317-729eee46-f864-4f4e-bf82-b74057dc392b.png)
![enb2022_1_30_11_16_09](https://user-images.githubusercontent.com/68168803/151697318-f05964de-74b6-43bf-96d1-1dbc694f254e.png)
![enb2022_1_30_11_08_30](https://user-images.githubusercontent.com/68168803/151697322-4735bc44-2eff-4f4e-b569-74bee2258e35.png)
![enb2022_1_30_11_08_48](https://user-images.githubusercontent.com/68168803/151697323-f8f096f7-17cc-4171-b1b3-8963749ac894.png)
![enb2022_1_30_11_08_51](https://user-images.githubusercontent.com/68168803/151697325-01802301-926b-46ef-a0c5-f3977111e901.png)
![enb2022_1_30_11_09_02](https://user-images.githubusercontent.com/68168803/151697327-b49beae7-5b3f-43dd-aabd-abeaa7d89771.png)
![enb2022_1_30_11_09_04](https://user-images.githubusercontent.com/68168803/151697329-257ab218-9f1d-44a0-b4be-27a6cc389312.png)
![enb2022_1_30_11_09_06](https://user-images.githubusercontent.com/68168803/151697332-ac659a03-244e-4ecb-be76-20851421cb9c.png)

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**

**Comment by celadoneiron** [comment]
Potential fix on trello.
