### ISSUE TITLE
Markarth area = roads and phantom low -ress bridge 

### ISSUE THREAD

**Issue by crustycreampietv** [ForgottenGlory/Living-Skyrim-3#65]
the markarth roads seem to be floating and the phantom low-ress bridge. 

pictures: 
![20210205201831_1](https://user-images.githubusercontent.com/78619253/107083534-13fe9800-67f6-11eb-80b7-69fe6b43ec5f.jpg)
![20210205201725_1](https://user-images.githubusercontent.com/78619253/107083551-19f47900-67f6-11eb-964d-8d595c16fc82.jpg)

**Comment by ForgottenGlory** [comment]
Should be fixed Beta 3
