### ISSUE TITLE
can u send the files that it didnt download

### ISSUE THREAD

**Issue by alexprentice1** [ForgottenGlory/Living-Skyrim-3#654]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
Put the version of the list you are on here.
?
**Describe the bug**
dosnt download
**To Reproduce**

**Expected behavior**
down the files and it didnt.
**Screenshots**
https://gyazo.com/03e717a79158cc6238b04507dd151423
https://gyazo.com/cc53e51a98631098f535a8d252c2c00c
If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**

**Comment by ForgottenGlory** [comment]
no
