### ISSUE TITLE
Rorikstead's general store Low-ress

### ISSUE THREAD

**Issue by crustycreampietv** [ForgottenGlory/Living-Skyrim-3#66]
Rorikstead's general store seems to be quite low resolution 

people in my stream commented on it didn't bother me too much 

picture: 
![20210205193611_1](https://user-images.githubusercontent.com/78619253/107083828-7eafd380-67f6-11eb-8219-93ef2bf8f814.jpg)

**Comment by ForgottenGlory** [comment]
Should be fixed Beta 3
