### ISSUE TITLE
Improper Scroll ID

### ISSUE THREAD

**Issue by Barachiel2285** [ForgottenGlory/Living-Skyrim-3#660]
**LS Version**
3.7.1

**Describe the bug**
During the quest "The Way To a Big Oaf's Heart" you're required to fetch several ingredients.  You're told one is a "scroll of repel undead or bane of undead"  however, this item does not complete the quest.  

According to the wiki, the item ID code for "Scroll of Repel Undead" is "000A44C5".  However if you use that item code, you get a Scroll of Toxic Cloud.  This item counts for quest completion as opposed to what's asked for in dialogue.

**To Reproduce**
Try to complete the quest with the requested scroll, and nothing happens.  Complete it with a scroll of Toxic Cloud, and it completes.  

**Expected behavior**
Use a scroll of repel undead to complete the quest, as the journal and in-game dialogue states.

**Comment by thehajo** [comment]
Fix for switching Repel to Turn Undead Scrolls on Trello
