### ISSUE TITLE
CTD around Auris Pod

### ISSUE THREAD

**Issue by Ellothil** [ForgottenGlory/Living-Skyrim-3#667]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
Put the version of the list you are on here.
3.7.1

**Describe the bug**
[Crash_2022_2_28_20-32-6.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/8156533/Crash_2022_2_28_20-32-6.txt)
Freeze with CTD

**To Reproduce**
Steps to reproduce the behavior: walking around at auris pod

**Expected behavior**

**Screenshots**

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**

**Comment by celadoneiron** [comment]
I've been unable to replicate this. Does it happen consistently on your save? If so, go to [Your LS3 install folder]\profiles\Living Skyrim 3\saves\ and find the matching .ess and .skse files for a save where you can trigger it repeatedly. Bundle those two files into a zip archive and upload the archive here so we can test it. If it's only happened once and hasn't re-occurred, let me know in a comment and I'll close the issue.

**Comment by Ellothil** [comment]
It happened constantly on a specific save but I tried just traveling to another place and everything worked fine and when I came back anytime there was no problem :)
