### ISSUE TITLE
cheat item in new game

### ISSUE THREAD

**Issue by Ashensakar** [ForgottenGlory/Living-Skyrim-3#67]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
LS3 Beta 2

**Describe the bug**
cheat item in inventory when starting new game
**To Reproduce**
create new character and look in bag
**Expected behavior**
no easy way to cheat
![Screenshot 2021-02-05 214535](https://user-images.githubusercontent.com/68168803/107092592-cc7b0a80-67fb-11eb-9729-f21a19091829.png)

**Screenshots**
If applicable, add screenshots to help explain your problem. Additionally, if your report applies to a specific object, make sure it is selected with the console open. Reports without this will be closed.

**Additional context**

**Comment by ForgottenGlory** [comment]
This is a temporary inclusion in the list to make bug testing and fixing easier when it comes to specific items, it will be removed for the final release.
