### ISSUE TITLE
missing 1 archive

### ISSUE THREAD

**Issue by DrRSolarios** [ForgottenGlory/Living-Skyrim-3#672]
Version: LS3

Wabbajack is unable to douwnload xLODGen.85.7z

I would like a link to dl this archive

[Wabbajack.current.log](https://github.com/ForgottenGlory/Living-Skyrim-3/files/8256070/Wabbajack.current.log)

**Comment by vyralove** [comment]
You can find a mirror on our discord. Our discord can be found on our website. 
Website link is broken. Use this: https://discord.gg/pU5szuqE

**Comment by DrRSolarios** [comment]
thx
