### ISSUE TITLE
CTD while in Racemenu and selecting Face Part 5 (HighPolyHead -female-)

### ISSUE THREAD

**Issue by mordang7** [ForgottenGlory/Living-Skyrim-3#68]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`
[Crash.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/5936082/Crash.zip)

If possible, please also attach a copy of your most recent save before the issue occurred.**

There is no save as this is a brand new installation of the Beta 2 and the bug occurred while creating a new character for a new game.

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
Living Skyrim 3 Beta 2

**Describe the bug**
After starting a new game, while in Racemenu creating my female character in the HEAD section and selecting Face Part 5 my game crashes to desktop. (it is a High Poly Head part but the CTD is too fast for me to read the whole name, probably in the Crash reports).

**To Reproduce**

Start a new game and in Racemenu HEAD section select Face Part 5 (I don't know if I can reproduce in game as the game crashes before the first save is created).

**Expected behavior**

The expected behavior would be to select the Face Part of my liking and continue my character creation undisturbed.

**Screenshots**
If applicable, add screenshots to help explain your problem. Additionally, if your report applies to a specific object, make sure it is selected with the console open. Reports without this will be closed.

**Additional context**

**Comment by TwistedModding** [comment]
Looks like the crash could be related to engine fixes.

[EngineFixes.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/5939775/EngineFixes.zip)

extract this file into this file path: D:\(modlist location)\mods\SSE Engine Fixes (skse64 plugin)\SKSE\Plugins

See if this fixes it, if not post another crash log.

**Comment by mordang7** [comment]
@TwistedModding Thank you so much for the solution. TL;DR It works like a charm.

Applied Methodology: For reproduction and testing, first I started a new game and confirmed that selecting that specific Head Part 5 would crash the game (which it did every time). I then proceeded to loading my current savegame and launched the Racemenu through the console by typing "showracemenu". When selecting Head Part 5 the game crashed again as expected. After copying the new EngineFixes file provided the crashing has stopped in all cases.

Again thanks for your support and quick solution! "Insert  Virtual High Five Clap Here" :P

**Comment by ForgottenGlory** [comment]
Fixed Beta 3

**Comment by daggerbyte** [comment]
I'm experiencing this exact same problem as described, I have the latest version of SSE Engine Fixes installed, and I unzipped the file suggested above into my install successfully, but it did not stop the crashing when I attempt to choose Face Part 5 in RaceMenu. Are there are other suggestions? How can I create a crash log like the one given at the start of this thread?

**Comment by ForgottenGlory** [comment]
Wait for Beta 3

**Comment by daggerbyte** [comment]
What is beta 3?

**Comment by daggerbyte** [comment]
> What is beta 3?

I'm sorry--I just realized I may be in the wrong area of the internet. I don't know what Living Skyrim is. Sorry for bothering you guys! Take care.
