### ISSUE TITLE
Bow Of Shadow action speed

### ISSUE THREAD

**Issue by ForgottenGlory** [ForgottenGlory/Living-Skyrim-3#686]
Is bug?: Confirm

Read the readme?: Confirm

List Version: LS 3.8.4

Reproducable?: Yes

Discord Username: thorkellthetall#5431

Rule 11?: No

Type: Gameplay (objects which cannot be activated or other gameplay related bugs)

Summary: Bow Of Shadow action speed

Details: The draw speed on the Bow of Shadows is unusually slow compared to other bows either standing or in stealth.

Steps to reproduce: Draw the bow normally 

Crash log: 

Screenshots:

**Comment by thehajo** [comment]
As far as i can see, thats intended by the mod author. The speed is not modified by any patches
