### ISSUE TITLE
Miner's House in Soljund's Sinkhole has extra floating door

### ISSUE THREAD

**Issue by Trent223** [ForgottenGlory/Living-Skyrim-3#69]
**LS Version**
Beta 2

**Describe the bug**
In Soljund's sinkhold, the building called Miner's House has a second door to the left of the main one, floating slightly off the ground. 

**To Reproduce**
I imagine traveling here by any means would reproduce, but I did the following:
1. Start new game
2. Choose Redguard as race
3. Choose Alik'r alternate start option. This spawned me very close to the location
4. Walk into Soljund's Sinkhole and look for door

**Expected behavior**
Only 1 door for building

**Screenshots**
https://imgur.com/a/foA704r

**Comment by ForgottenGlory** [comment]
Select the object with console open and post that screenshot please

**Comment by Trent223** [comment]
@ForgottenGlory right, my bad. See below.

https://imgur.com/a/jAtJKZQ

**Comment by ForgottenGlory** [comment]
Fixed Beta 3
