### ISSUE TITLE
Racemenu Bodypaint CTD

### ISSUE THREAD

**Issue by weronika0805** [ForgottenGlory/Living-Skyrim-3#7]
**LS Version**
2/1/2021 3.0.0.1 Beta 1

**Describe the bug**
When creating a female Breton character in Racemenu there is a CTD whenever I change to a body paint named CO61.

**To Reproduce**
Open Racemenu with a female character, change to bodypaint CO61,

**Expected behavior**
No CTD, the body paint shows up on character.

**Screenshots**
n/a

**Additional context**

Netscriptframework crash log - https://pastebin.pl/view/00d5b0c8

**Comment by ForgottenGlory** [comment]
Also so I don't forget, Auri headpart is causing crash in Racemenu as well. Will be fixed as part of this

**Comment by weronika0805** [comment]
This issue is documented on Nexus - https://forums.nexusmods.com/index.php?showtopic=8652293/#entry86063673

**Comment by TwistedModding** [comment]
https://www.nexusmods.com/Core/Libs/Common/Widgets/DownloadPopUp?id=137645&nmm=1&game_id=1704 - downloading and merging this with the original mod fixes the issue.

**Comment by ForgottenGlory** [comment]
Fixed Beta 2
