### ISSUE TITLE
Infinite loading screen while loading save

### ISSUE THREAD

**Issue by ForgottenGlory** [ForgottenGlory/Living-Skyrim-3#725]
Is bug?: Confirm

Read the readme?: Confirm

List Version: 3.8.4

Reproducable?: Yes

Discord Username: WeKnewBetter2318#3420

Rule 11?: No

Type: Save will not load

Summary: Infinite loading screen while loading save

Details: Saves appear to work prior to becoming a werewolf through the companions questline. After, it's very hit and miss on whether or not the save will load.

Steps to reproduce: Make a save prior to entering underforge, confirm proper load. Make multiple saves in multiple locations after becoming werewolf and attempt to load.

Crash log: 

Screenshots:

**Comment by GravenImages** [comment]
https://cdn.discordapp.com/attachments/690613668836016178/992249207295594557/After_Werewolf.zip
https://cdn.discordapp.com/attachments/690613668836016178/992249369829064704/Prior_To_Werewolf.zip
Saves for this report

**Comment by GravenImages** [comment]
User updated:
"Following up on this...just if it helps...But using a "cure beastblood potion" or whatever it was called immediately after becoming a werewolf resolved all issues with loading my saves"
