### ISSUE TITLE
Crosshair conflicts: archery, SmoothCam, Less Intrusive HUD

### ISSUE THREAD

**Issue by celadoneiron** [ForgottenGlory/Living-Skyrim-3#73]
**LS Version**
LS3 Beta 2.

**Describe the bug**
When drawing the bow, two crosshairs are visible - the normal, central crosshair (and sneak meter, if sneaking) and the SmoothCam predictive crosshair. Attempting to change the position of the sneak meter using Less Intrusive HUD will appear to work, but will reset as soon as you draw, sheathe, or aim the bow again.

**To Reproduce**
Equip and draw a bow.

**Expected behavior**
There should be only one crosshair.

**Screenshots**
![SkyrimSE 2021-02-06 21-03-54](https://user-images.githubusercontent.com/73095714/107116557-cf3f3380-68bf-11eb-916d-bbf21e587779.png)
![SkyrimSE 2021-02-06 21-04-00](https://user-images.githubusercontent.com/73095714/107116565-dd8d4f80-68bf-11eb-95ce-c721a74b83a1.png)
(The SmoothCam crosshair is the thin white line in the first image pointing to the place where the arrow hit in the second image, if it's hard to see.)

**Additional context**
The second, central crosshair can be removed when not sneaking by disabling "Crosshair Activation: When wielding ranged weapon" in Immersive HUD. However, this removes it in first person as well, which is less than ideal.
![SkyrimSE 2021-02-06 21-08-17](https://user-images.githubusercontent.com/73095714/107116594-1cbba080-68c0-11eb-9c77-85b33dae097f.png)

Using the Less Intrusive HUD alternative sneak crosshair and meter will remove the dual crosshair issue, but the placement of the sneak meter still resets after using the bow in any way, which leaves an ironically *very* intrusive bar right across the middle of the screen even if you used the LIHUD position edit mode to move it away.

Also, the recommended SmoothCam preset does not enable Archery Gameplay Overhaul compatibility. I didn't notice a difference with *this* issue in my testing between having it enabled or not, but that doesn't mean there may not be other problems.

**Comment by ForgottenGlory** [comment]
I'll admit to being uncertain how to elegantly fix this, I'm open to suggestions

**Comment by Darkangel13** [comment]
As far as I know you can't. Not even the authour could fix it, that is why he/she added the simulated trajectory.
![image](https://user-images.githubusercontent.com/26364611/107387911-912b5500-6af5-11eb-97bd-fc60dc5717ae.png)

**Comment by TwistedModding** [comment]
This isnt a bug. Smoothcam has a raycasted crosshair/air path to where the arrow ACTUALLY goes. The vanilla crosshair is horrible for third person thus why this crosshair is even a thing. Smoothcam isnt suppose to remove the vanilla crosshair either, and the way ihud works, it either removes the crosshair entirely or not at all (third or first person doesnt matter). This is normal mod behavior and if it really bothers you, just disable the crosshair entirely in ihud.

**Comment by ForgottenGlory** [comment]
Actually, after playing around with it a bit more, this can be 100% fixed by leaving the ranged crosshair enabled in Immersive HUD and disabling the Worldspace Crosshair option in Smoothcam's MCM.

**Comment by ForgottenGlory** [comment]
I've updated the SmoothCam preset to have the correct setup to work with Immersive HUD and such. Fixed Beta 3
