### ISSUE TITLE
CTD when changing Combat Style MCM setting for Sofia Follower

### ISSUE THREAD

**Issue by Trent223** [ForgottenGlory/Living-Skyrim-3#74]
**LS Version**
LS3 Beta 2

**To Reproduce**
1. Open MCM for Sofia Follower
2. Under Sofia Settings, change Combat Style to anything else
3. Acknowledge the popup, exit the MCM
CTD, see attached crash log
[Crash_2021_2_6_6-57-47.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/5936773/Crash_2021_2_6_6-57-47.txt)

**Comment by ForgottenGlory** [comment]
A temporary workaround while I work on a more permanent fix is to tell her to wait outside somewhere, go into a building (shop, inn, whatever) and change it there. For some reason it crashes if she's visible while making that change, unsure of cause.

**Comment by ForgottenGlory** [comment]
`[F3] BD UUNP Armor and cloth replacer.esp`

Rule 11
