### ISSUE TITLE
CTD when approaching Forsworn Camp 

### ISSUE THREAD

**Issue by Trent223** [ForgottenGlory/Living-Skyrim-3#75]
**LS Version**
LS3 Beta 2

**Describe the bug**
A CTD occurs when approaching the Forsworn camp near Markarth. This is the camp you are sent to early in the LOTD questline to retrieve the Jade Statue. The crash log indicates (to me) an issue with Organic Factions, so it could be the case that the issue is reproduceable almost anywhere in the Reach.

**To Reproduce**
1. Leave Markarth and head east towards the Forsworn Camp

[Crash_2021_2_6_9-51-54.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/5937031/Crash_2021_2_6_9-51-54.txt)

**Comment by ForgottenGlory** [comment]
` [F3] BD UUNP Armor and cloth replacer.esp`

Rule 11
