### ISSUE TITLE
Ranger Outfit Invisible

### ISSUE THREAD

**Issue by Deth24** [ForgottenGlory/Living-Skyrim-3#77]
**LS Version**
LS3 Beta2

**Describe the bug**
Crafting the Ranger Outfit Assassin (I assume others as well) creates an invisible piece of armor when equipped

**To Reproduce**
Craft Ranger Outfit armor at the forge

**Expected behavior**
Visible armor

**Screenshots**
If applicable, add screenshots to help explain your problem. Additionally, if your report applies to a specific object, make sure it is selected with the console open. Reports without this will be closed.

**Additional context**
I noticed this same issue was posted and closed 2 days ago. I just confirmed it is still a bug

**Comment by TwistedModding** [comment]
Is it invisible on your body or in the crafting menu?

**Comment by Trent223** [comment]
It shows up alright for me both in inventory and on character https://imgur.com/a/LEnVJzv

**Comment by Deth24** [comment]
Invisible in the craft menu and when equipped it made that body part invisible. I specifically made the Ranger assassin gloves/bracers and they made my forearms and hands invisible

**Comment by ForgottenGlory** [comment]
Unable to replicate, looks fixed for Beta 3
