### ISSUE TITLE
Mistwatch/Darkwater landscape/object issues

### ISSUE THREAD

**Issue by seanpbelcher** [ForgottenGlory/Living-Skyrim-3#79]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
LS3 Beta 2.

**Describe the bug**
The area around the hot springs/Mistwatch keep is broken. Mistwatch fort itself doesn't physically exist - it's just low res LODs. Several large rocks/landscape features are also non-existent, but their low res LODs are present. Several trees are not loading their proper textures either. 

**To Reproduce**
If you head east just past Darkwater Crossing, towards the hot springs, you can't miss it. Several LODs are obviously low res and do not load when you get close, and you can clip through several objects as you move through the area. Unfortunately, because these objects don't physically exist in the world anymore, I can't select them in console. 

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. Additionally, if your report applies to a specific object, make sure it is selected with the console open. Reports without this will be closed.
![enb2021_2_7_06_04_42](https://user-images.githubusercontent.com/67465410/107146387-84e4a380-690d-11eb-9e7f-c3e5707597cd.png)
![enb2021_2_7_06_05_05](https://user-images.githubusercontent.com/67465410/107146396-929a2900-690d-11eb-9b78-a1f12e4eed77.png)
![enb2021_2_7_06_06_09](https://user-images.githubusercontent.com/67465410/107146402-99c13700-690d-11eb-8537-4680acdd15e2.png)
![enb2021_2_7_06_06_27](https://user-images.githubusercontent.com/67465410/107146411-a776bc80-690d-11eb-9623-ff28816178fd.png)
![enb2021_2_7_06_06_52](https://user-images.githubusercontent.com/67465410/107146418-af366100-690d-11eb-8aaf-c8a1c9c240c7.png)
![enb2021_2_7_06_07_32](https://user-images.githubusercontent.com/67465410/107146423-bc535000-690d-11eb-8a7a-8600b58fd45b.png)
![enb2021_2_7_06_07_39](https://user-images.githubusercontent.com/67465410/107146428-c9703f00-690d-11eb-8002-b55c4e46fb75.png)
![enb2021_2_7_06_08_19](https://user-images.githubusercontent.com/67465410/107146431-d42ad400-690d-11eb-9cd6-9020911b23f1.png)
![enb2021_2_7_06_08_40](https://user-images.githubusercontent.com/67465410/107146437-dee56900-690d-11eb-860a-8ff03a7cde1a.png)
![enb2021_2_7_06_09_06](https://user-images.githubusercontent.com/67465410/107146446-eb69c180-690d-11eb-9933-f9e46e2e5675.png)
![enb2021_2_7_06_09_38](https://user-images.githubusercontent.com/67465410/107146451-f6bced00-690d-11eb-9ebd-95c3b63447e4.png)
![enb2021_2_7_06_10_42](https://user-images.githubusercontent.com/67465410/107146455-02101880-690e-11eb-9af4-a630e64f78ed.png)
![enb2021_2_7_06_10_57](https://user-images.githubusercontent.com/67465410/107146459-0dfbda80-690e-11eb-88ca-3c3c653edd9a.png)

**Additional context**

**Comment by seanpbelcher** [comment]
UPDATE: OK, so it seems this was just a problem loading up correctly because on that same save this morning that area is loading fine other than the purple tree texture you know about - bandits are back in Mistwatch and the fort and surrounding area are solid again. I'm going to chalk this up as an anomaly on my end unless someone else has that issue. 
![enb2021_2_8_03_46_44](https://user-images.githubusercontent.com/67465410/107203304-e0239e00-69c0-11eb-8aba-5200125a0cab.png)

**Comment by ForgottenGlory** [comment]
Should be fixed Beta 3
