### ISSUE TITLE
Mystic Condenser - Missing hand and stirring is outside the bowl

### ISSUE THREAD

**Issue by Quietbeat** [ForgottenGlory/Living-Skyrim-3#80]
**LS Version**
3

**Describe the bug**
When using the Mystic Condenser in Dragon's Reach, my left hand is invisible and the item I use to stir will appear outside of the bowl when stirring.

**To Reproduce**
Use the Mystic Condenser in Dragon's Reach

**Expected behavior**
- My hand is visible
- The stirring is always inside the bowl

**Screenshots**
![Mystic Condensor - Missing hand](https://user-images.githubusercontent.com/57841662/107153602-3d691200-6923-11eb-9263-5ad9f23b1532.jpg)

**Additional context**
[saves.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/5939465/saves.zip)

**Comment by Quietbeat** [comment]
I just figured out that my hands are missing all of the time.

**Comment by ForgottenGlory** [comment]
Unable to replicate, works for me
