### ISSUE TITLE
Quest Missing in Action - Companion always running

### ISSUE THREAD

**Issue by Quietbeat** [ForgottenGlory/Living-Skyrim-3#81]
**LS Version**
3

**Describe the bug**
When I entered House Gray-Mane for the quest Missing in Action, one of my companions started running all the time inside and outside. Only after fast traveling does he stop running.

**To Reproduce**
- Get the companion Hjoromor
- Get the quest Missing in Action
- Enter house Gray-Mane 

**Expected behavior**
Companions shouldn't run around

**Screenshots**
![Hjoromor running after entering House Gray-Mane for quest Missing in action](https://user-images.githubusercontent.com/57841662/107153864-9dac8380-6924-11eb-95c4-170c612e37a3.png)

**Additional context**
[saves.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/5939483/saves.zip)

**Comment by TwistedModding** [comment]
This is probably something to do with his ai and can simply be fixed by either leaving the cell and coming back in or using the resetai command on him in the console.
