### ISSUE TITLE
Game crashes upon loading a save, usually after death

### ISSUE THREAD

**Issue by ZaryGodMan** [ForgottenGlory/Living-Skyrim-3#82]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`\

Empty, no log located

If possible, please also attach a copy of your most recent save before the issue occurred.**

Attached

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**Describe the bug**

There is a chance when I load a save I CTD during the loading screen.

**To Reproduce**

I load a save. Sometimes while playing.

**Expected behavior**

No crash

[Save9.zip](https://github.com/ForgottenGlory/Living-Skyrim-3/files/5939698/Save9.zip)

**Screenshots**
If applicable, add screenshots to help explain your problem. Additionally, if your report applies to a specific object, make sure it is selected with the console open. Reports without this will be closed.

**Additional context**
[Crash_2021_2_7_12-0-47.txt](https://github.com/ForgottenGlory/Living-Skyrim-3/files/5939702/Crash_2021_2_7_12-0-47.txt)
Edit: My most recent attempt generated a crash log.

**Comment by ZaryGodMan** [comment]
If it helps, I'm also using the High Poly Head.

Maybe same issue as (HighPolyHead -female-) #68 user.

**Comment by ForgottenGlory** [comment]
I'm unable to replicate this, possibly fixed Beta 3
