### ISSUE TITLE
Invisible npc's

### ISSUE THREAD

**Issue by ghost** [ForgottenGlory/Living-Skyrim-3#83]
**LS Version**
LS3 Beta 2

**Describe the bug**
invisible npcs

**To Reproduce**

https://www.youtube.com/watch?v=7Qz-UXUPvD0&feature=youtu.be
**Expected behavior**

**Screenshots**

![enb2021_2_7_18_59_32](https://user-images.githubusercontent.com/44908095/107155667-5228c280-6982-11eb-8bb5-5beeb6b2cfcc.png)

![enb2021_2_7_15_36_59 (1)](https://user-images.githubusercontent.com/44908095/107155679-666cbf80-6982-11eb-86fd-e8d808165236.png)

**Additional context**

**Comment by ForgottenGlory** [comment]
Unable to replicate, looks fixed Beta 3
