### ISSUE TITLE
persitent text on screen 

### ISSUE THREAD

**Issue by vMichaelMyersv** [ForgottenGlory/Living-Skyrim-3#85]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
Latest

**Describe the bug**
persistent text on screen unable to make this go away even on re load or a new character or death or travel to new region ect even though not a vampire 

**To Reproduce**
unsure 

**Expected behavior**
text to fade away/ not be present
 since not a vampire 

**Screenshots**

![screenshot](https://user-images.githubusercontent.com/78704848/107159675-894ea200-6989-11eb-88be-5b5f83460d21.png)

**Additional context**

**Comment by JaxomofRuatha** [comment]
Trying to narrow down the cause, which deity did you select to worship if any?

And if you could potentially attach a save, that would be helpful also.

**Comment by vMichaelMyersv** [comment]
seems to have sorted it self i started um my pc this morning and started a new character seems to have cleared it i had selected the smithing one think its zennith?

**Comment by Darkangel13** [comment]
hmmmm ussually a message from the same type will fix this issue.
I.E. if you get a follower chat stuck on screen, a quick chat with any other npc will fix that.
I got a message about the blessing stuck once on LS2 second blessing fixxed that.
In your case any other message related to your vampire status should fix that.
I am not sure but me thinks this is actually a original Skyrim bug. 
Then again I have never played vanila Skyrim :D
