### ISSUE TITLE
Reading is Good bugged

### ISSUE THREAD

**Issue by jomoroon** [ForgottenGlory/Living-Skyrim-3#86]
LS3 Version Beta 2 that was released 5/2/21.

Skill books do not grant any levelling bonus via *Reading is Good*.
I note that there was a prior entry regarding this in LS3 Beta 1 that was marked as fixed in beta 2 (current build) however it is still prevalent in this build.

To reproduce read a skill book and notice the lack of notification + lack of skill registration in the mod's MCM menu.

Many thanks,
Jom

edit: I dont know how to edit the labels, I am new to github. I'm so sorry!

**Comment by jomoroon** [comment]
UPDATE: 

Interestingly if you configure SSE gameplay fix to enable learning bonus from SKILL books only, it too does not register them. It does however register normal books.
Could this mean that the problem is not Reading is Good but another mod that affects the skill books? Something is causing them to not be recognized as skill books.

**Comment by jomoroon** [comment]
UPDATE 2:

Ok I found the problem: 
1) SSEEdit 
2) LS3patches merged
3) All skill books have had their award skill point trigger disabled. I enabled it on all of them to test the content (I know we are not supposed to alter the mod list but I did it for science!) and all the functions of SSE gameplay and Reading is Good now work including appropriate book glow and learning skill speed.

I think we can count this as solved. I know there is a very strict rule on opening up files but I hope you guys can forgive me! This is my favourite modlist and I'm very keen to bug exterminate and get this thing out of beta so more people can experience it!

Please let me know if you guys would rather I report future bugs and just leave it at that or if I have your permission to dig into these bugs to try solve them, easing the load on the dev team.

**Comment by ForgottenGlory** [comment]
If you are working to fix bugs and you know what you're doing, I couldn't care less if you mess with the list. The less work I have to do to fix bugs, the better! :) I'll incorporate the fix in the next update.

**Comment by ForgottenGlory** [comment]
Fixed Beta 3
