### ISSUE TITLE
Purple tree LODs

### ISSUE THREAD

**Issue by ForgottenGlory** [ForgottenGlory/Living-Skyrim-3#9]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in MO2's Overwrite folder.

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
Beta 1

**Describe the bug**
One particular tree type from Trees Addon has purple missing texture bark LODs for whatever reason.

**To Reproduce**
None

**Expected behavior**
No disco trees

**Screenshots**
When you see it, you can't miss it

**Additional context**
N/A

**Comment by xelphos** [comment]
Not sure if this is what he means, but here is a similar issue: https://i.imgur.com/H9ttRe6.png

Tree in question with console: https://i.imgur.com/zy12GAC.png

**Comment by TwistedModding** [comment]
When generating dyndolod, it probably mentions missing textures while generating, keep the log and look at it once its done and it might help

**Comment by ForgottenGlory** [comment]
Possibly fixed Beta 3

**Comment by ForgottenGlory** [comment]
Still an issue Beta 3

**Comment by ForgottenGlory** [comment]
Fixed for 3.0.0 Release
