### ISSUE TITLE
Archery skill won't level

### ISSUE THREAD

**Issue by shiraisenpai** [ForgottenGlory/Living-Skyrim-3#91]
**LS Version**
Beta 2

**Describe the bug**
Not gaining Archery experience when shooting enemies. Archery not leveling up.

**To Reproduce**
Start as an Imperial, let the scripts finish, default LS MCM stuff, warrior birthsign, anyclass, any points. 

**Expected behavior**
Gain exp.

**Comment by ForgottenGlory** [comment]
I'm unable to replicate this, it's working for me.
