### ISSUE TITLE
Halldir's Cairn missing floor

### ISSUE THREAD

**Issue by Orc12x** [ForgottenGlory/Living-Skyrim-3#94]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
Latest release

**Describe the bug**
A part in the dungeon has floor pieces missing

**To Reproduce**
Go to the dungeon o.o

**Expected behavior**
Floor shouldn't have any missing pieces.

**Screenshots**
https://ibb.co/d2fb8B2 + https://ibb.co/VJGShcz

**Additional context**
LS3 is awesome! 🗡️

**Comment by ForgottenGlory** [comment]
I don't see anything modifying/removing ground tiles, going to have to dig deeper on this one
