### ISSUE TITLE
Windyridge incompatible with JK's Skyrim

### ISSUE THREAD

**Issue by weronika0805** [ForgottenGlory/Living-Skyrim-3#95]
**LS Version**
LS3 beta 2

**Describe the bug**
The Windyridge player house is slightly incompatible with JK's Skyrim - there's a huge wall going through the main entrance of the house, and the purchase sign is obscured by a brazier added by JK's.

**To Reproduce**
Look for Windyridge in Winterhold.

**Expected behavior**
No wall going through the house, purchase sign easy to see.

**Screenshots**
![enb2021_2_8_22_44_46](https://user-images.githubusercontent.com/78365583/107285973-3f84bb00-6a60-11eb-8013-2869d144f54a.png)
![enb2021_2_8_22_45_02](https://user-images.githubusercontent.com/78365583/107285981-427fab80-6a60-11eb-817e-d98ba241de5f.png)
![enb2021_2_8_22_49_08](https://user-images.githubusercontent.com/78365583/107285996-46133280-6a60-11eb-8a41-0ff2771204c9.png)

**Comment by ForgottenGlory** [comment]
Removed Windyridge beta 3
