### ISSUE TITLE
Falkreath Mysterious Floating Lantern

### ISSUE THREAD

**Issue by Orc12x** [ForgottenGlory/Living-Skyrim-3#96]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[LS Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**LS Version**
Latest release

**Describe the bug**
Lantern out in the open floating, not attached to anything.

**To Reproduce**
Go to Falkreath and look for the lantern

**Expected behavior**
Unless this lantern is enchanted; no lantern should float.

**Screenshots**
https://ibb.co/6ygZpmy

**Additional context**

**Comment by TwistedModding** [comment]
fixed - esp in patch channel

**Comment by ForgottenGlory** [comment]
Fixed Beta 3
