### ISSUE TITLE
Remove link to LS2 Install Tutorial video

### ISSUE THREAD

**Issue by celadoneiron** [ForgottenGlory/Living-Skyrim-3#97]
**Section**
Important Links

**Description**
The link to the install tutorial goes to a video about installing LS2. Since it's very different to the LS3 beta install process (e.g. directing people to find the list via the Browse Modlists option on Wabbajack) it might be better to just remove the link until there's a new video that's made for the full release.

**Comment by ForgottenGlory** [comment]
Done
